### ISSUE TITLE
.Net full framework sample apps

### ISSUE THREAD

**Issue by envergokmen** [elastic/apm-agent-dotnet#1013]
I followed instructions for .net full framework but couldn't get any transaction logs.  I don't know whether is an bug or not. That would be great if we have asp.net full framework working samples.

**Comment by gregkalapos** [comment]
We have one [here](https://github.com/elastic/apm-agent-dotnet/tree/master/sample/AspNetFullFrameworkSampleApp).

There is also a [troubleshooting section in the docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/troubleshooting.html).
