### ISSUE TITLE
.NET 5 produces warning in logs

### ISSUE THREAD

**Issue by ffMathy** [elastic/apm-agent-dotnet#1024]
> {"Service"} Failed to detect whether the current .NET runtime is .NET Full Framework, Mono or .NET Core - `"N/A"' will be used as the current .NET runtime name

**Comment by gregkalapos** [comment]
This was fixed in https://github.com/elastic/apm-agent-dotnet/pull/964 and it's already merged - but we haven't released it yet.

@ffMathy if this is `1.6.1` or an earlier version then it should be fixed and will be included in the next release.

**Comment by ffMathy** [comment]
Is there an ETA on release?

**Comment by gregkalapos** [comment]
We don't communicate specific dates, but we are working on it and it should be soon.

**Comment by russcam** [comment]
[1.7.0 is now released to nuget](https://www.nuget.org/packages/Elastic.Apm/1.7.0), which includes #964 

@ffMathy please can you try with 1.7.0 and see if this resolves the issue?

**Comment by ffMathy** [comment]
It worked!
