### ISSUE TITLE
No SQL tracing when using dapper in .Net 5 

### ISSUE THREAD

**Issue by poserdonut** [elastic/apm-agent-dotnet#1025]
Initially I created this as a question here: https://discuss.elastic.co/t/no-sql-tracing-when-using-dapper-in-net-5/255032

But I realized it should probably go as an issue here on github. 

APM Agent language and version:
C# 1.6.1

<PackageReference Include="Elastic.Apm.AspNetCore" Version="1.6.1" />
<PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.6.1" />
<PackageReference Include="Elastic.Apm.SqlClient" Version="1.6.1" />
Original install method (e.g. download page, yum, deb, from source, etc.) and version:
Nuget

Hi!

We have a Web API which uses Dapper for data access. However we get no tracing for the SQL call. We are running .Net 5.0

In the Configure method in Startup.cs

    app.UseElasticApm(Configuration, new SqlClientDiagnosticSubscriber(), new HttpDiagnosticsSubscriber());
The code which calls the database looks like this

    using IDbConnection db =  new SqlConnection(_configuration.InsuranceConnection());

    const string getAllaArbetsgivareIdnProcName = "[dbo].[Stored_Procedure]";

    var allaArbetsgivareId = await db.QueryAsync<Guid>(getAllaArbetsgivareIdnProcName, null, commandType: CommandType.StoredProcedure);
And it's using

using Microsoft.Data.SqlClient;
Logs from the application
https://pastebin.ubuntu.com/p/wxWzQpRwWb/

Ubuntu Pastebin
How it looks in Kibana

![image](https://user-images.githubusercontent.com/61051475/98806582-aff84d80-2419-11eb-9f39-a72d0e8967be.png)

We have antoher Web API running .net core 3.1 where it seems to be working.

**Comment by poserdonut** [comment]
I tried with the 1.7 release today and still no SQL tracing.

**Comment by russcam** [comment]
Thanks @poserdonut, I've opened https://github.com/elastic/apm-agent-dotnet/pull/1042 to address
