### ISSUE TITLE
[META 319] Add sanitize_field_name option to Kibana

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1034]
According to [this PR](https://github.com/elastic/apm/pull/334) the `sanitize_field_names` option needs to be added to [Kibana's configuration options](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/general_settings.ts) for the .NET agent.

**Comment by gregkalapos** [comment]
Turns out this setting is not yet live changeable. I opened https://github.com/elastic/apm-agent-dotnet/pull/1082 to change this. Once PR https://github.com/elastic/apm-agent-dotnet/pull/1082 is done, I'll also update the Kibana config.

**Comment by gregkalapos** [comment]
Talked to @AlexanderWert, I opened the Kibana PR now, just to make sure this setting gets into Kibana also for .NET before `7.11` feature freeze.  https://github.com/elastic/apm-agent-dotnet/pull/1082 is ready to review and we still have enough time to make sure it's merged before `7.11` is out.
