### ISSUE TITLE
Do you have an opentracing bridge for .net agent?

### ISSUE THREAD

**Issue by SRA-123** [elastic/apm-agent-dotnet#1038]
We have microservices instrumented with opentracing.Currently we use Jaeger implementation but would like to use the elastic .net agent without changing the instrumentation.We use elastic RUM agent with opentracing bridge for our webapplications.

**Comment by russcam** [comment]
Hi @SRA-123,

There's no [OpenTracing bridge](https://www.elastic.co/guide/en/apm/get-started/current/opentracing.html) for the .NET agent currently. 

[There is an OpenTelemetry integration](https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html) that extends the Open Telemetry collector to translate OpenTelemetry trace data to Elastic APM's protocol, and then exports it to Elastic APM server.

**Comment by gregkalapos** [comment]
We had a discussion about this. The latest version of the [.NET OpenTracing library](https://github.com/opentracing/opentracing-csharp) is version `0.12.1` and it's from more than a year ago. Given that OpenTracing is discontinued in favor of OpenTelemetry, we'd rather invest into OpenTelemetry. Supporting a `v 0.12.1` library which will likely never reach version `1.0` doesn't sound good to us.

Having said that, if someone wants to contribute and open a PR with the OpenTracing bridge, I'm more than happy to help out. But for now, we won't work on OpenTracing for .NET.
