### ISSUE TITLE
Elastic.Apm.Agent.AddFilter doesn't work in Global.asax's Application_Start()

### ISSUE THREAD

**Issue by Pepo-BG** [elastic/apm-agent-dotnet#1045]
**Describe the bug**
In my MVC project, I wanted to add some global filters. To do that, I've added my code in the `Global.asax` `Application_Start()` method. Here is my code:

```
protected void Application_Start()
{
  //my other code
  Utils.ElasticUtilities.AddAPMGlobalFilter();
}
```

```
public class ElasticUtilities
    {
        public static void AddAPMGlobalFilter()
        {
            AgentDependencies.Logger = new ApmLoggerBridge();

            try
            {
                bool filterAdded = Elastic.Apm.Agent.AddFilter((Elastic.Apm.Api.ITransaction transaction) =>
                {
                    try
                    {
                        LogMessage("APM Transaction filter" + transaction.Id);
                        transaction.Labels.Add("UserID", MyCustomCode.UserID.ToString());
                        transaction.Labels.Add("EmailAddress", MyCustomCode.EmailAddress);
                    }
                    catch (Exception exc)
                    {
                        transaction.CaptureException(exc);
                        LogException(exc);
                    }
                    return transaction;
                });
                LogMessage("Filter added:" + filterAdded.ToString());
            }
            catch (Exception ex)
            {
                LogException(ex);
            }
        }

        internal class ApmLoggerBridge : IApmLogger
        {
            public bool IsEnabled(LogLevel level)
            {
                return true;
            }

            public void Log<TState>(LogLevel level, TState state, Exception e, Func<TState, Exception, string> formatter)
            {
                string message = formatter(state, e);
                if (e == null)
                {
                    LogMessage(message);
                }
                else
                {
                    LogException(e);
                }
            }
        }

    }
```

But transactions aren't sent to the APM... The only exceptions that I received are:
```
Exception type:
System.UnauthorizedAccessException

Message:
Access to the registry key 'Global' is denied.
```

and

```
Source:
Microsoft.Diagnostics.Tracing.TraceEvent

Exception type:
System.UnauthorizedAccessException

Message:
Error Starting ETW:  Access Denied (Administrator rights required to start ETW)
```

The configuration is valid because the code above everything is logged to the APM correctly.
If I move my code from `Application_Start()` to `Session_Start()` it works, but I don't want to add a filter for each session.

Thank you!

**Comment by russcam** [comment]
Hi @Pepo-BG, I've put together a sample application:

https://github.com/russcam/ApmFullFrameworkAddFilterExample

I can see that the global filter is applied, looking at the console output:

> Starting IIS Express ...
Successfully registered URL "http://localhost:5000/" for site "ApmFullFrameworkAddFilterExample" application "/"
Registration completed for site "ApmFullFrameworkAddFilterExample"
IIS Express is running.
Enter 'Q' to stop IIS Express
**Filter added:True**
{AbstractConfigurationReader (FullFrameworkConfigReader)} The agent was started without a service name. The service name will be automatically discovered.

and later, when a transaction is filtered

> Request started: "GET" http://localhost:5000/
> Response sent: http://localhost:5000/ with HTTP status 200.0
> **APM Transaction filterd3ea9eb317387a6c**

So it looks like adding the transaction filter is working correctly.

The logged exceptions look like they relate to starting ETW. I wouldn't _expect_ a failure to start ETW to cause transactions not to be sent to APM server. Are you running the application in IIS, and if so, what identity are you running the application pool with? One thing to try is adding the application pool to the `Performance Monitor Users` and `Performance Log Users` groups. For example, from cmd

```cmd
net localgroup "Performance Monitor Users" "IIS APPPOOL\<app pool name>" /add
net localgroup "Performance Log Users" "IIS APPPOOL\<app pool name>" /add
```

where `<app pool name>` is the name of the application pool that the application is using.
