### ISSUE TITLE
Automate creating of ElasticApmAgent_[version].zip file

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1051]
For the zero code change (startup hook based) agent injection we distribute a `.zip` file with all the agent components. In the future we may use other ways to distribute this.

Regardless of how we distribute it we should:
- Generate a file or folder with all the agent components. By setting `DOTNET_STARTUP_HOOKS` the agent should be injected from the generates file/folder .
- Zip the content of this for now which we can publish here on GitHub.
- Run this whole thing in CI.
- Add a test stage with a sample app, so all commits are tested with this type of setup.

**Comment by russcam** [comment]
I've opened #1062 to address building the zip file. I think it might make sense to split this issue into two, one to create zip, one to test zip, as the testing requires some work to ensure startup hooks work with different major versions of System.Diagnostics.DiagnosticSource.
