### ISSUE TITLE
Oracle , apm 

### ISSUE THREAD

**Issue by mjnk9xw** [elastic/apm-agent-dotnet#1064]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions.
I wonder if it has monitor for oracle using Oracle.ManagedDataAccess.Client command, thanks

**Comment by russcam** [comment]
Hi @mjnk9xw, the APM .NET agent does not currently support auto instrumentation of Oracle.ManagedDataAccess.Client. Please fill out this survey to help us prioritize framework support: https://goo.gl/forms/FHHbhptcDx8eDNx92

For now, you would be able to manually instrument calls using [the tracer API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-tracer-api)

**Comment by russcam** [comment]
Support for Oracle.ManagedDataAccess has been implemented as part of #1534. This will be released as beta in the next release, 1.12.
