### ISSUE TITLE
Breaking binary backwards compatibility

### ISSUE THREAD

**Issue by adamcloutex** [elastic/apm-agent-dotnet#1067]
**Describe the bug**
 Version 1.7.0 introduces breaking binary backwards compatibility changes in the `IExecutionSegment.CaptureException` method by adding a new optional parameter.

**To Reproduce**

1. Create a NuGet package that depends on version < 1.7.0
2. Have an application depend on v1.7.0 AND the library
3. Deploy service and have the library call `IExecutionSegment.CaptureException`
4. See error `Method not found: 'Void Elastic.Apm.Api.IExecutionSegment.CaptureException(System.Exception, System.String, Boolean, System.String)' recorded in Elastic APM

**Expected behavior**
Backwards incompatible changes to not be introduced through optional parameters, or at a minimum calling these breaking changes out in release notes.

**Comment by gregkalapos** [comment]
Thanks for letting us know. We already discuss to compare the public API surface of our changes to previous versions, that'll help us prevent this later.

I added this to the [release notes](https://github.com/elastic/apm-agent-dotnet/releases/tag/1.7.0).

**Comment by adamcloutex** [comment]
Great, glad to hear it's on your backlog. Thanks for updating release notes
