### ISSUE TITLE
APM Server secret token

### ISSUE THREAD

**Issue by CraigKennedy** [elastic/apm-agent-dotnet#107]
**Is your feature request related to a problem? Please describe.**
APM Server hosted in ElasticCloud.  Seems to need `APM Server secret token`, but unclear on how to set that token.

**Describe the solution you'd like**
Add support or understand how to insert this token

**Describe alternatives you've considered**
Not use for now.

**Additional context**

**Comment by gregkalapos** [comment]
Thx for reporting this @CraigKennedy! 

It's definetly a planned feature, and we don't want to have the "Not use for now" for too long with cloud! :)

cc @russcam

**Comment by CraigKennedy** [comment]
Is there a way to "fake" this in manually for now? Do you have any docs that I could look at to see how this needs to be passed in and I'll fork and create a PR if that would be helpful?

**Comment by gregkalapos** [comment]
I don't think there is a way to fake it...especially in ElasticCloud. Currently the only option is to run the apm-server on-premise and not use the token. 

But I think we can solve this very quickly. 

This is the java PR: https://github.com/elastic/apm-agent-java/commit/06c6cc17e636b0bc8e82c009a31a7ef509e951f1 

I think @russcam already has it locally... maybe he'll already have a PR ready - let's see what he says.

**Comment by russcam** [comment]
I've added #108 to address

**Comment by gregkalapos** [comment]
(Assign myself to not overlook this in our planning, all credit goes to @russcam)
