### ISSUE TITLE
ELASTIC_APM_ENABLED environment variable does not have the same behavior as "Enabled" setting in appsettings.json file

### ISSUE THREAD

**Issue by jpinedanu** [elastic/apm-agent-dotnet#1077]
**Bug**
When using appsettings.json to configure Elastic APM, if the option "Enabled" is set as false, the initial fetch to read the configuration from APM Server is ignored and no connection is attempted. This is the expected behavior. However, when the code reaches any explicit call when using the Elastic APM agent a connection to the APM server will be attempted even though ElasticApm:Enabled is set as false. 
When setting the environment variable ELASTIC_APM_ENABLED as false, instead of using appsettings.json, all connections were ignored and no attempt was made to connect against the APM server. I believe disabling Elastic APM by using appsettings.json should have the same behavior as setting the  environment variable which is to disable all connections to the APM server

**To Reproduce**
1. Set Enabled to false in appsettings.json config
```
{
  "ElasticApm": {
    "Enabled": false
  }
}
```
2. Then call Elastic.Apm.Agent.Tracer.CaptureTransaction and see an attempt is made to reach the APM server. 
3. Remove "Enabled" configuration from appsettings.json file and set environment variable "ELASTIC_APM_ENABLED" to false.
4. Run the same code calling CaptureTransaction from the Elastic APM agent and view that no connection is attempted.

**Expected behavior**
Disabling Elastic APM by using appsettings.json to set ElasticApm:Enabled to false should have the same behavior as setting the ELASTIC_APM_ENABLED environment variable to false by having them both avoid reaching out to the APM server and disabling all behavior of the agent.

**Comment by gregkalapos** [comment]
Thanks for reporting this. Indeed, this is a bug. I opened https://github.com/elastic/apm-agent-dotnet/pull/1078 to fix this.

**Comment by gregkalapos** [comment]
Fixed in #1078.
