### ISSUE TITLE
Transaction.Custom is null if Apm is disabled

### ISSUE THREAD

**Issue by tbutler-qontigo** [elastic/apm-agent-dotnet#1080]
**Describe the bug**
Version 1.7.1

When Enabled = false you get a NoopTransaction when you call StartTransaction.
The Custom dictionary is null so any attempt to add to that will throw a NullReferenceException

**To Reproduce**
1. Ensure Apm is disabled (Enabled = false)
2. Then call `var transaction = Agent.Tracer.StartTransaction(...)` and note that you get a NoopTransaction
3. Then do `transaction.Custom.Add(....)`
4. Observe that you will get a `NullReferenceException` because Custom is null

**Expected behavior**
1transaction.Custom.Add1 should not fail whether Apm is enabled or not.

**Comment by gregkalapos** [comment]
Thanks for reporting @tbutler-qontigo.

I opened https://github.com/elastic/apm-agent-dotnet/pull/1081 to fix it.

**Comment by tbutler-qontigo** [comment]
BTW just discovered this is also a problem with `OutgoingDistributedTracingData` - we call SerializeToString on that and again that is null for a `NoopTransaction`

**Comment by gregkalapos** [comment]
> BTW just discovered this is also a problem with `OutgoingDistributedTracingData` - we call SerializeToString on that and again that is null for a `NoopTransaction`

That one is known to me and I think it's best to not fake that one. If the agent is disabled, you won't get `OutgoingDistributedTracingData` out of the agent. If we'd fake it, we'd either need to generate all the ids (`traceid`, `transactionid`, and `spanid`) which would mean the agent still does a lot of things, or return something fake, but that'd mean we give you invalid data.

**Comment by gregkalapos** [comment]
On the other hand, I think we should warn people about this. I'll add some docs to make this clear.

**Comment by tbutler-qontigo** [comment]
Hi - I think the problem (or "a" problem) is that to the developer, they don't know that they are getting a `NoopTransaction` rather than a real one and so don't know to check the properties have values.
Also it does mean that 1.7.x should really be 2.x (if you follow semver?) because it is essentially a breaking change - code that used to always work now doesn't if Apm is not enabled because properties which were always non null before are now potentially null in some circumstances.

Putting foo?.bar?.baz everywhere is a bit of a smell tbh...but if that's what we have to do then that's what we have to do....
If there are more props that might be null on the NoopTransaction can you add them to the docs too please?

Sidenote:  It is very hard to write automated tests that ones code is resilient to Apm being enabled or not enabled because the only thing we can check is the `Enabled` property...which can only ever be set once...so you can either have unit tests that test the Apm enabled path OR tests that test the Apm disabled path, but you cannot test both in the same Test project.

**Comment by gregkalapos** [comment]
I opened https://github.com/elastic/apm-agent-dotnet/pull/1179 to improve the docs on this.
