### ISSUE TITLE
Additional User properties

### ISSUE THREAD

**Issue by mdschweda** [elastic/apm-agent-dotnet#1084]
`Elastic.Apm.Api.Context` exposes a property `User`. That property corresponds to the `user.*` fields of the `apm-*` index. Unfortunately, `User` only contains `Id`, `UserName` and `Email` whereas APM Server creates the following fields:

```
user.domain
user.email
user.full_name
user.full_name.text
user.group.domain
user.group.id
user.group.name
user.hash
user.id
user.name
```

Would you consider extending that model to support all available APM / [ECS](https://www.elastic.co/guide/en/ecs/master/ecs-user.html) fields. I'm be especially interested in `user.domain` since I'd like to filter entries by tenant in a multi-tenant application. Mapping could be done with a DI service, options delegate or in a manual fashion:

```csharp
public class ApmTransactionFilter : IActionFilter {

    public void OnActionExecuting(ActionExecutingContext context) {
        if (Elastic.Apm.Agent.Tracer.CurrentTransaction?.Context is { } transactionContext)
            if (context.HttpContext.User is { Identity: { Name: { Length: > 0 } name } })
                transactionContext.User = new User {
                    // ...
                    Domain = LookupTenant(name)
                };
    }

}
```

**Comment by gregkalapos** [comment]
@mdschweda  those fields are not available on the intake API of the APM server. The intake API is where the agent sends data to. 

These fields are inherited from beats via ecs definitions.

One workaround could be that you put this data into a [label](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-transaction-set-label) and use an [ingest pipeline](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html) to move them into the corresponding fields.

There are no plans at this point to make these fields available through the intake API for APM Agents.

**Comment by mdschweda** [comment]
Bummer. I was able to accomplish what you suggested by defining the following pipeline:

```json
PUT _ingest/pipeline/apm_user_domain
{
  "processors": [
    {
      "dot_expander": {
        "field": "transaction.custom.tenant",
        "ignore_failure": true
      }
    },
    {
      "rename": {
        "field": "transaction.custom.tenant",
        "target_field": "user.domain",
        "ignore_failure": true
      }
    }
  ]
}
```

... and adding a processor to the default pipeline (`apm`):

```jsonc
[
  // ...
  {
    "pipeline": {
      "name": "apm_user_domain"
    }
  }
]
```

**Comment by gregkalapos** [comment]
Perfect - happy to hear that.

Closing, since likely that's the best option for this right now.
