### ISSUE TITLE
No HTTP transaction are captured in worker service

### ISSUE THREAD

**Issue by poserdonut** [elastic/apm-agent-dotnet#1085]
**Describe the bug**
Hi!

We have a .Net 5 worker service which is doing HTTP calls on a schedule and we are using 1.7.1 of the agent. However no transaction are being captured. 

We are adding APM by using
` .UseElasticApm(new AspNetCoreDiagnosticSubscriber(), new HttpDiagnosticsSubscriber());`

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseWindowsService()
                .ConfigureServices((hostContext, services) =>
                {
                    var configuration = hostContext.Configuration;

                    services.AddKpaLogging();

                    services.AddQuartz(q =>
                    {
                        q.UseMicrosoftDependencyInjectionJobFactory(options =>
                        {
                            options.CreateScope = false;
                        });

                        q.AddJobAndTrigger<NyanmälPersonerTillKisJob>(configuration);
                    });

                    services.AddQuartzHostedService(options =>
                    {
                        // when shutting down we want jobs to complete gracefully
                        options.WaitForJobsToComplete = true;
                    });

                    services.AddHttpClient<IPersonServiceClient, PersonServiceClient>();
                })
                .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                    logging.AddKpaLogger();
                    logging.AddConsole();
                    logging.AddDebug();
                })
                .UseElasticApm(new AspNetCoreDiagnosticSubscriber(), new HttpDiagnosticsSubscriber());
```

And using an injected HTTPClient to make the HTTP requests.

However it's totally empty in the APM GUI
![image](https://user-images.githubusercontent.com/61051475/101765720-01abfa80-3ae2-11eb-8ef4-42a3233d6693.png)

The service that is called is getting an APM transaction but with no trace connected to the calling service.

**Comment by gregkalapos** [comment]
@poserdonut in case of a worker service you need to start the transaction manually.

You can inject an `ITracer` instance into your service (the `UseElasticApm` method adds that) and use that, like this:

```
public class QuartzHostedService : IHostedService //I'm guessing here, but probably you have something similar to this
{
	private readonly ITracer _tracer;
	public QuartzHostedService(ITracer tracer) => _tracer = tracer;
	public async Task StartAsync(CancellationToken cancellationToken)
	{
                //Here we start the transaction
		var transaction = _tracer.CaptureTransaction("foo", "BackgroundService", () =>
		{
			//The `HttpDiagnosticsSubscriber` you passed to `UseElasticApm` will automatically capture the HTTP calls on the transaction
			//Do HTTP call, and all other logic...
		});
	
	}
}
```

Alternatively you can use the [`StartTransaction`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-start-transaction) method (and call `.End()` manually) if you can't pack everything into a lambda.

The HTTP calls are spans and the agent will only create spans if there is an active transaction. Unlike in ASP.NET Core, in a worker service the agent won't automatically create the transaction for you. The reason for this is that it's not really possible to know what exactly a transaction is in case of a worker service (in case of ASP.NET Core it's clear - it's an incoming HTTP request). Therefore in this use case you'll need to manually define what a transaction is (with the `_tracer.CaptureTransaction` or `StartTransaction` method), once that's done the agent will capture HTTP (and other things you register with `DiagnosticsSubscriber`s) automatically on the created transaction.

**Comment by poserdonut** [comment]
@gregkalapos Thank you for a great explanation!
