### ISSUE TITLE
Ensure transaction_ignore_urls is centrally configurable

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1086]
Meta issue https://github.com/elastic/apm/issues/144 has been implemented in https://github.com/elastic/apm-agent-dotnet/issues/688.

Configuration option has been added in Kibana for the .NET agent: https://github.com/elastic/kibana/pull/85734

**The purpose of this issue is to make sure that agent supports central configuration for this option.**

**Comment by gregkalapos** [comment]
Looked into this; this setting wasn't central config-ready. Opened https://github.com/elastic/apm-agent-dotnet/pull/1087 which makes it central config compatible.

**Comment by gregkalapos** [comment]
https://github.com/elastic/apm-agent-dotnet/pull/1087 merged.
