### ISSUE TITLE
Tags are missing from errors

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#109]
**Describe the bug**
Tags are missing from the error object

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new transaction
2. Add a tag example : apmTransaction.Tags.Add("response", JsonConvert.SerializeObject(result, JsonDefaults.JsonSerializerSettings));
3. Capture exception using CaptureException. example apmTransaction?.CaptureException(result.Exception
4. Check error in kibana (tags tab) is empty http://joxi.net/v296V1U385bqAG.png

**Expected behaviour**
Tags should not be empty

**Comment by gregkalapos** [comment]
Thanks for reporting, and fixing this! I added a comment [here](https://github.com/elastic/apm-agent-dotnet/pull/111#discussion_r257651371). #111 will fix it. 

👍
