### ISSUE TITLE
AspNetFullFramework - Implicit initialization inconsistent IConfigurationReader

### ISSUE THREAD

**Issue by Daluur** [elastic/apm-agent-dotnet#1098]
When using AspNetFullFramework and accessing Agent before it has been initialized via a request, (e.g. by accessing Agent.AddFilter()), the Agent will be initialized with a EnvironmentConfigurationReader instead of a FullFrameworkConfigReader.
This means that accessing Agent.something before it has been initialized, initializes the Agent incorrectly.
It is also not possible to manually call Agent.Setup and have it use the FullFrameworkConfigReader.

I would expect the same result when calling Agent.CaptureTransaction before the first request and after the first request

Our current solution is to always check Agent.IsConfigured before doing anything, but that means we are dropping som manually captured transactions, and not able to set up our filters beforehand.
A secondary solution would be to duplicate our config values, having the same values in both web.config and Envirionemt, so both configReaders read the same values.

I would like if accessing Agent before it has been setup gives the same result as after, or giving a way of manually setting it up to read from web.config, without having to write a custom ConfigReader, that does the same as FullFrameworkConfigReader

**Comment by russcam** [comment]
Thanks for opening @Daluur. 

My initial thought is that filters should not instantiate the agent if not already instantiated, and should be added to the agent once instantiated.

**Comment by Daluur** [comment]
My main issue is that it is not possible to define that the agent should use the FullFrameworkConfigReader in any other way than recieving a request, and having it be initialized at the point.
It defaults to EnvironmentConfigurationReader, I think it would be nice to be able to either explicitly initialize it using FullFrameworkConfigReader, or being able to define it as a setting.

**Comment by russcam** [comment]
@Daluur The agent is initialized in the ElasticApmModule Init method: https://github.com/elastic/apm-agent-dotnet/blob/8875c8a2fdd514d3ece3151742d03816daa9fa08/src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs#L35-L49


So you'd be able to add filters **after** the agent is initialized _and_ **on** the first request by adding them in `Application_BeginRequest`. For example

```c#
using System;
using System.Diagnostics;
using System.Web.Mvc;
using System.Web.Optimization;
using System.Web.Routing;
using Elastic.Apm;
using Elastic.Apm.Api;

namespace ApmFullFrameworkExample
{
    public class MvcApplication : System.Web.HttpApplication
    {
        private bool _addFilters;
        private readonly object _lock = new object();
        
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            // plus any other methods to run on application start
        }
        
        protected void Application_BeginRequest(object sender, EventArgs e)
        {
            // add filters when the first request is received
            if (!_addFilters)
            {
                lock (_lock)
                {
                    if (!_addFilters)
                    {
                        _addFilters = true;

                        // example filter that always adds a custom label
                        var addFilter = Agent.AddFilter((ITransaction transaction) =>
                        {
                            transaction.SetLabel("CustomLabel", "Always set");
                            return transaction;
                        });
                        
                        if (!addFilter)
                        {
                            // log that the filter couldn't be added
                            Trace.WriteLine("Could not add custom filter");
                        }
                    }
                }
            }
        }
    }
}
```

I do think that in the future though, agent configuration like adding filters and subscribing diagnostic listeners should not instantiate the agent. I don't think we'd be able to change this behaviour in 1.x at this point, so would need to look at this for the next major version.

**Comment by Daluur** [comment]
This is exactly what we have done. The issue is that it is not possible to capture a transaction before the first request.

We have some background jobs running in our service that we would like to capture, but it is not possible to setup the Agent before the first request, which means that everything that happens from Application_Start until the first request will not have an Agent.

It would be nice to be able to specify that the Agent should use the FullFrameworkConfigReader instead of defaulting to EnvironmentConfigurationReader if no requests has happened yet.

I believe the issues is with this line, as it always defaults to EnvironmentConfigurationReader, even when using FullFramework.
https://github.com/elastic/apm-agent-dotnet/blob/8875c8a2fdd514d3ece3151742d03816daa9fa08/src/Elastic.Apm/AgentComponents.cs#L36

Agent.Tracer.CaptureTransaction() Will use FullFrameworkConfigReader if called _after_ the first request, but will use EnvironmentConfigurationReader if called _before_ the first request and in the process set up the agent incorrectly, making the Agent useless until the application has been recycled.

We have a wrapper to capture a transaction and for now we have added (not actual code):
```
if (!Agent.IsConfigured)
{
	Log("Agent not configured, cannot capture transaction yet");
	return;
}
```

**Comment by russcam** [comment]
Thanks for the additional detail, super helpful!

What might be a way forward in this major version is to expose `BuildAgentComponents()` on `ElasticApmModule` as public, which would allow agent components specific to ASP.NET Full Framework to be constructed and used to setup and initialize the agent, allowing the agent to be used to capture transactions and spans early in application startup. The `ElasticApmModule` does try to take ownership of agent construction in `SafeAgentSetup()`:

https://github.com/elastic/apm-agent-dotnet/blob/7c8fa40299fcd4ca61d1ce3007bef35aec0dac37/src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs#L446-L467

and logs an exception if the agent has already been created, but we may be able to workaround this and not log if we know that the agent has been initialized with components from `BuildAgentComponents()`.

**Comment by Daluur** [comment]
Being able to call BuildAgentComponents during app startup would solve all our issues, and make it very transparent what is happening, while being optional. I think that it seems to be a good solution :) 
By the way, thanks for responding and looking into the issue :)

**Comment by russcam** [comment]
@Daluur I've opened https://github.com/elastic/apm-agent-dotnet/pull/1122 as a potential solution
