### ISSUE TITLE
Line number is missing

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#110]
**Describe the bug**
Line number is missing from exception stack trace

**Expected behavior**
Line numbers should be included in stack trace

**Comment by gregkalapos** [comment]
Thx @skynet2! [elastic#110](https://github.com/elastic/apm-agent-dotnet/issues/110) will solve it...

**Comment by pavel-agarkov** [comment]
When `segment.CaptureException` is used there are no line numbers.
The result looks something like this all the time:
```json
{
  "stacktrace": [
    {
      "exclude_from_grouping": false,
      "filename": "MyCompany.Tracing.TracingTranBatch+<CaptureSpan>d__15",
      "line": {
        "number": 0
      },
      "module": "MyCompany.Tracing, Version=1.0.0, Culture=neutral, PublicKeyToken=***",
      "function": "CaptureSpan"
    },
    {
      "...": "..."
    }
```

**Comment by gregkalapos** [comment]
@pavel-agarkov this is an optional field and we don't always get the line number from the runtime - so it could be that it's a known scenario and there is not much we can do about it.

We capture the linenumber [here](https://github.com/elastic/apm-agent-dotnet/blob/a951cbd9cc0c26e2d8154f54890ee5f10e90ba09/src/Elastic.Apm/Helpers/StacktraceHelper.cs#L64). - I think all `CaptureException` calls end up there.

But if you have a reproducer, or you see a bug there, feel free to open an issue.
