### ISSUE TITLE
Memory leak in GrpcClientDiagnosticListener

### ISSUE THREAD

**Issue by rickardp** [elastic/apm-agent-dotnet#1116]
**Describe the bug**
We are experiencing memory leaks where gRPC objects are held by the APM (according to the profiler). It looks like the _processingRequests dictionary is never removed from, only added to. Should line 60 read TryRemove instead of TryGetValue?

**To Reproduce**
In profiler:
Use the gRPC + APM
Do a number of requests
Observe how the objects are never collected.

**Expected behavior**
Objects (responses) are collected

**Comment by gregkalapos** [comment]
Thanks for reporting! 

> Should line 60 read TryRemove instead of TryGetValue?

Indeed, that's the fix. 

I opened https://github.com/elastic/apm-agent-dotnet/pull/1118 to fix this.
