### ISSUE TITLE
Support Average Duration by Span Type

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1128]
Currently, the UI for .NET applications doesn't show the breakdown of average response times by span type due to missing information:

![image](https://user-images.githubusercontent.com/866830/104557778-17ad5d80-5642-11eb-924c-3ea0eacce578.png)

**Comment by gregkalapos** [comment]
This is a dupl. of https://github.com/elastic/apm-agent-dotnet/issues/227 - since that issue has more info, I moved that into the milestone and close this.
