### ISSUE TITLE
[META 373] Support replacement of plain-text formatters with ECS formatters

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1129]
Evaluate and if applicable implement https://github.com/elastic/apm/issues/373

**Comment by russcam** [comment]
This feature would require:

- the interception of logging library setup methods, which would require a profiler to readily achieve
- Either the application to be referencing the relevant ECS .NET packages for the logging library, or to be referencing an APM agent meta-package that references the APM agent and ECS .NET packages.

At this stage, I think it would be prudent to close this issue as currently unfeasible.
