### ISSUE TITLE
Trace transaction start/end automatically for ASP.NET applications (Full .NET Framework, IIS hosted)

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#113]
Find a way to trace transaction start/end automatically - the current approach requires manually wrapping each controller method with “CaptureTransaction”.

**Comment by markdemich** [comment]
Have you made any progress on this?

**Comment by SergeyKleyman** [comment]
> Have you made any progress on this?

Yes, we are actively working on it and there will be a PR in the very near future.
