### ISSUE TITLE
Investigate how to monitor ADO.NET calls with “library-only” approach

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#114]
Among data access layer technologies currently we only support Entity Framework (EF) Core which less popular in classic ASP.NET applications. ADO.NET is much more popular for classic ASP.NET applications - either direct ADO.NET calls or usage of classic Entity Framework which in turn is implemented on top of ADO.NET. So we would like to investigate:

- If  it's possible to monitor ADO.NET calls with “library-only” approach (i.e., without resorting to Profiling API, etc.) 
- How much details we can get employing “library-only” approach

**Comment by gregkalapos** [comment]
I think it's worth looking at the corefx repo and see what we can do with DiagnosticSource.

E.g. MSSQL related objects already emit DiagnosticSource events:
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlCommand.cs#L31 

I'm not sure that the layer below (the pure ADO interfaces) emit similar events - it'd be really good if they'd do. 

The other question is the version where those events were introduced. If it's only in a super new Full Framework version then the usefulness of those DiagnosticSource events is questionable. But if it's there since let's say 4.6.1 then it's good.

**Comment by vhatsura** [comment]
@gregkalapos, I looked into it and have some news about it.
> I'm not sure that the layer below (the pure ADO interfaces) emit similar events - it'd be really good if they'd do.

ADO interface doesn't emit any events.

> The other question is the version where those events were introduced.

Events were introduced only in .Net Core and unavailable in .Net Framework (checked all versions from 4.6.1 to 4.8).

In addition, right now `SqlClient` implemented in two independent packages: `System.Data.SqlClient` and [`Microsoft.Data.SqlClient`](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/).  `Microsoft.Data.SqlClient` also emits events only in .Net Core ([`listener`](https://github.com/dotnet/SqlClient/blob/d6f2e29cda769e711988c64d3cb57eb5010a3e9c/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs#L70) exists only in .net core partial part).

However, instrumentation for both of these packages can be used by many developers with .Net Core. Also, instrumentation can be made in generic way (we don't need to divide listener pipelines).
So, my question is: Are you interesting to have such instrumentation in Elastic.Apm?

**Comment by SergeyKleyman** [comment]
@vhatsura If I understand you correctly you are proposing to add support for ADO.NET automatic instrumentation but only for .NET Core. At least at this stage only for .NET Core - it shouldn't prevent us from adding support for Full .NET Framework in the future and of course it's better than not having support for ADO.NET at all, Did I understand you correctly? If so I think it's a good idea and your PR will be welcome.

**Comment by vhatsura** [comment]
> @vhatsura If I understand you correctly you are proposing to add support for ADO.NET automatic instrumentation but only for .NET Core. At least at this stage only for .NET Core - it shouldn't prevent us from adding support for Full .NET Framework in the future and of course it's better than not having support for ADO.NET at all, Did I understand you correctly? If so I think it's a good idea and your PR will be welcome.

@SergeyKleyman, I returned to your comment and, unfortunately, I didn't mean support for ADO.NET automatic instrumentation, I mean support for SqlClient automatic instrumentation. So, it means my changes will cover only `System.Data.SqlClient` and `Microsoft.Data.SqlClient`.

Is it still ok?

**Comment by SergeyKleyman** [comment]
> Is it still ok?

@vhatsura It's definitely is.

To tell you the truth I don't have that much experience with ADO.NET so I'm not even sure which use cases would still not be covered by SqlClient automatic instrumentation that you propose. Could you please give a simple example? It's just for my education - regardless of whether there are important use cases that still won't be covered I still think that you proposal has significant value.

**Comment by vhatsura** [comment]
> > Is it still ok?
> 
> @vhatsura It's definitely is.
> 
> To tell you the truth I don't have that much experience with ADO.NET so I'm not even sure which use cases would still not be covered by SqlClient automatic instrumentation that you propose. Could you please give a simple example? It's just for my education - regardless of whether there are important use cases that still won't be covered I still think that you proposal has significant value.

ok, I will try. From my understanding, ADO.NET is only a set of interfaces and abstract classes. I know only 3 implementations of ADO.NET:
1. System.Data.SqlClient
2. [System.Data.SQLite](https://www.nuget.org/packages/System.Data.SQLite/). Also, Microsoft.Data.SQLite
3. [System.Data.OracleClient](https://docs.microsoft.com/en-us/dotnet/api/system.data.oracleclient) - deprecated
