### ISSUE TITLE
Allow Stack Trace configuration for Errors / Exceptions individually of Spans

### ISSUE THREAD

**Issue by dasMulli** [elastic/apm-agent-dotnet#1145]
Currently it is possible to disable stack trace capture for spans by setting `StackTraceLimit` to `0`.
This helped us a lot before recent perf improvements in demystifying. However we still decided to leave it off b/c we trace with a high sample rate and capture lots of spans (mostly DB transactions but also custom ones).

This has the unfortunate effect that exceptions also no longer contain stack traces and investigating errors is a bit harder (still possibly by correlating logs with APM but more cumbersome).

It would be great if I could disable span stack trace collection independent of error / exception stack trace collection.

**Comment by gregkalapos** [comment]
Hey @dasMulli,

there is also another setting called [SpanFramesMinDuration](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-stacktrace.html#config-span-frames-min-duration). If you set that to `0`  then that will only apply to spans and with `0` you'll disable stack trace capturing for every span. With that you should still have stack traces on errors.

Does that help?

**Comment by gregkalapos** [comment]
I close this for now - I think we have a fairly ok workaround here. If not feel free to reopen and we can continue the discussion.

**Comment by dasMulli** [comment]
Argh forgot to close it - working great in production for weeks
