### ISSUE TITLE
Add capture-body-content-types setting to Kibana

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1146]
[Docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-capture-body-content-types) already indicate that this is dynamic, but does not show up for .NET now. From https://github.com/elastic/apm-agent-dotnet/issues/1144

**Comment by russcam** [comment]
Related: https://github.com/elastic/apm/issues/395.

I suggest we remove the `dynamic` label from the docs for now.

**Comment by stevejgordon** [comment]
Closing as outdated.
