### ISSUE TITLE
Instrumentation for MongoDB

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1158]
Include MongoDB instrumentation in the agent distribution.

Community package: https://github.com/vhatsura/elastic-apm-mongo 

Another package which generates diagnostic source events on top of its own diagnostic: https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources

**Comment by russcam** [comment]
@vhatsura, would you be open to contributing https://github.com/vhatsura/elastic-apm-mongo for instrumenting MongoDB?

**Comment by RascoApps** [comment]
We have this need as well. a generic DiagnosticSource listener by Name would be fantastic!
