### ISSUE TITLE
Add support for Custom fields

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#116]
Add support for Custom user fields

**Comment by gregkalapos** [comment]
As discussed on the [PR](https://github.com/elastic/apm-agent-dotnet/pull/118#pullrequestreview-206362197) unfortunately we won't do this now. 

Reason: https://github.com/elastic/apm/issues/7 is about to potentially deprecating `Custom` and the java agent doesn't have this either. If we would add it now maybe we'd need to remove it very soon, which would be a breaking change.

**Comment by skynet2** [comment]
Hi @gregkalapos , 
I think we can reopen that issue, there is a final decision under https://github.com/elastic/apm/issues/7 to keep "custom" in the schema as i understand 

Thanks,
Stas
