### ISSUE TITLE
Additional headers

### ISSUE THREAD

**Issue by kodigo35** [elastic/apm-agent-dotnet#1164]
Hello,

i am using apmserver throught api gateway which requires apikey header to be sent.

is there a way to add additionnal headers to requests sent via payloadsender ?

regards

**Comment by gregkalapos** [comment]
Hi @kodigo35,

we have an [ApiKey](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-api-key) config, which adds a header (code [here](https://github.com/elastic/apm-agent-dotnet/blob/79f886a51501fa0c5cbee42709a42733dbab8e91/src/Elastic.Apm/BackendComm/BackendCommUtils.cs#L153)).

But I'm not sure this config would help you. That setting is designed for another use case - at least that's my impression based on your issue description.

> is there a way to add additionnal headers to requests sent via payloadsender ?

No, at this point we don't expose anything where you could do this - I think the only way to do this now is to fully replace the payloadsender, but that sounds like an overkill.

**Comment by kodigo35** [comment]
hi @gregkalapos 

Thanks for your answser.

Your example with apikey is good, need the same thing except  that the header name is not the same.

In production environment, apmserver is rarely directly reachable by backend applications. 

For the moment, i'm dealing with a custom appsetting for adding extra headers.

May be some kind of preSend events to override or subscribe could do the trick

**Comment by stevejgordon** [comment]
@kodigo35 I presume this issue may be outdated. Is it something that still affects you?

**Comment by stevejgordon** [comment]
Closing as outdated
