### ISSUE TITLE
Add support for request_body field

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#117]
Add support for request_body field

**Comment by gregkalapos** [comment]
Done in https://github.com/elastic/apm-agent-dotnet/pull/134.

**Comment by xitaocrazy** [comment]
Hi @gregkalapos, 

About this issue,
When I post data in the request body (by Rest or GraphQL), my service in dotnet receive this information, but this data is not shown in ElasticAPM, I don't know if the Agent is sending the data in body. Can you help me with this information? I have no problems with the request headers data.
![NoBodyData_LI](https://user-images.githubusercontent.com/2092215/56690529-0ffe9600-66b4-11e9-821e-46a4c0ea0573.jpg)

**Comment by gregkalapos** [comment]
Thanks for pinging me @xitaocrazy! This issue and #134 only added the `Request.Body` field to our agent API, but our ASP.NET Core instrumentation does not use it - which is definitely not our intention long term.

So currently unfortunately the only way to do this is that you capture the body manually with the [Public Agent API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html).

Additionally I just opened #213 to address this. Similarly to other agents the default will be off (from performance reasons), but once #213 is done you'll be able to capture the request body just by turning on the corresponding setting.

**Comment by xitaocrazy** [comment]
@gregkalapos thanks for help me with this issue.
