### ISSUE TITLE
After updating APM nuget packages from 1.6.1 to 1.8.0 all transactions in Kibana are broken

### ISSUE THREAD

**Issue by insanity13** [elastic/apm-agent-dotnet#1187]
### APM Agent version

Elastic.Apm: 1.8.0
Elastic.Apm.AspNetFullFramework: 1.8.0
Elastic.Apm.EntityFramework6: 1.8.0

Elastic Cloud: v 7.10.2
### Environment

**.NET Framework/Core name and version**
.net net472 ASP.MVC

### Describe the bug
After updating APM nuget packages from 1.6.1 to 1.8.0 all transactions in Kibana are broken

#### Expected behavior
As it was on 1.6.1 version
![image](https://user-images.githubusercontent.com/1174911/108373273-2676c980-7219-11eb-9c89-9b3107f92f8e.png)

#### Actual behavior
As it now on 1.8.0 version
![image](https://user-images.githubusercontent.com/1174911/108373175-047d4700-7219-11eb-81ae-8363527198bd.png)

**Comment by russcam** [comment]
Hi @insanity13, I'll take a look at this with our sample ASP.NET FF application. 

Would you be able to explain in more detail what the problem you're seeing in Kibana is please? It's not clear to me what difference in the screenshot I should be looking at.

**Comment by insanity13** [comment]
1. I've got ASP.MVC application with angularjs as frontend.
2. Registered rotes map
![image](https://user-images.githubusercontent.com/1174911/108462734-91b2b100-7296-11eb-9747-9d4405a85993.png)
3. And a ton of API-Controllers like
![image](https://user-images.githubusercontent.com/1174911/108462802-aee77f80-7296-11eb-9e5b-558063cac70b.png)

Previously in "APM/Services/MyApp" a see separate requests like
api/counties/1234/agents

![image](https://user-images.githubusercontent.com/1174911/108463175-5d8bc000-7297-11eb-8380-dfff3737a559.png)


But now I see only strange "PUT Home/Index {url}" (**I've no such controller**)
![image](https://user-images.githubusercontent.com/1174911/108463220-6d0b0900-7297-11eb-8763-7f242649ce32.png)

And All PUT requests inside it. See below:
![image](https://user-images.githubusercontent.com/1174911/108463026-14d40700-7297-11eb-9449-63fb4bdab2fb.png)
![image](https://user-images.githubusercontent.com/1174911/108463048-1ef60580-7297-11eb-8575-f766efdea7d0.png)
![image](https://user-images.githubusercontent.com/1174911/108463084-2cab8b00-7297-11eb-9945-877752a4bb96.png)

**Comment by russcam** [comment]
Thank you for the additional detail @insanity13. Can you confirm if you see the same issue with 1.7.1 packages, or **only** 1.8.0 packages?

**Comment by insanity13** [comment]
@russcam Maybe. I've skipped 1.7 version. So, I'll check that next week.

**Comment by insanity13** [comment]
@russcam yes, in 1.7.1 I've got the same issue.

**Comment by russcam** [comment]
Thanks for confirming @insanity13.

I've run the [AspNetFullFrameworkSampleApp](https://github.com/elastic/apm-agent-dotnet/tree/master/sample/AspNetFullFrameworkSampleApp) in conjunction with 7.10.2 Elastic stack components started with [apm-integration-testing](https://github.com/elastic/apm-integration-testing). I'm not seeing an issue in the sample application; all transactions that I'm seeing appear as expected. 

I'm wondering if there's something that we're not currently testing that might be resulting in the behaviour you're seeing. Would you be able to put together the _simplest possible_ application that reproduces the issue, and share a link to it _(a GitHub repository would be fine)_?

**Comment by insanity13** [comment]
@russcam  I found the reason. I apologize for not checking this point right away.

1. We register API-routes dynamically:
![image](https://user-images.githubusercontent.com/1174911/108686045-515d6800-750e-11eb-8835-590bee1884e8.png)
2. Then we registering routes for the pages (We should accept all request and handle them by Angular)
![image](https://user-images.githubusercontent.com/1174911/108686141-73ef8100-750e-11eb-8cb6-01b9432428ac.png)

ASP.NET processes the request according to the registration order (API-routes goes first). But you got the different Route Map.

**Comment by insanity13** [comment]
I've added a constraint to the "Catch-All Route" to exclude API calls, and it works as before.
![image](https://user-images.githubusercontent.com/1174911/108801937-773b4900-75b0-11eb-945b-b5ee10519b7c.png)

But it'll be great to aggregate by Route Attribute
![image](https://user-images.githubusercontent.com/1174911/108802065-d00ae180-75b0-11eb-836a-68820dcba83d.png)

![image](https://user-images.githubusercontent.com/1174911/108802079-d6995900-75b0-11eb-828e-c87ba93727a3.png)

**Comment by russcam** [comment]
Happy you got it sorted @insanity13 👍 

Aggregating by the `RouteAttribute` is in #1189, which we're looking to introduce in 1.9.0.

**Comment by insanity13** [comment]
@russcam  great! Thanks a lot for your help!
