### ISSUE TITLE
[docs] Link to self-signed certs documentation

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-dotnet#1188]
After the `1.9.0` release, APM Server documentation will need to be updated to link to the new self-signed certs docs added in https://github.com/elastic/apm-agent-dotnet/pull/1180. These are the pages that require updates:

* [Server cert auth](https://www.elastic.co/guide/en/apm/server/current/ssl-setup.html#ssl-server-authentication)
* [HTTPS comms in agents](https://www.elastic.co/guide/en/apm/server/current/secret-token.html#https-in-agents)

**Comment by russcam** [comment]
@bmorelli25 v1.9.0 has been released so docs are good to be updated 🙏
