### ISSUE TITLE
Detected pacakge downgrade on blank ASP.NET Core WebApi NET5.0

### ISSUE THREAD

**Issue by stefannikolei** [elastic/apm-agent-dotnet#1194]
I created a fresh WebApi project in VS2019 targeting .NET5.0.

When trying to install the package Elastic.Apm.NetCoreAll 1.8.0 version i get following Nuget error:

```
Detected package downgrade Microsoft.Extensions.Logging.Abstractions from 5.0.0 to 3.0.0
Detected package downgrade Microsoft.Extensions.Hosting.Abstractions from 5.0.0 to 3.0.0
```

**Comment by gregkalapos** [comment]
Thanks for reporting this. Opened https://github.com/elastic/apm-agent-dotnet/pull/1198 to fix it.
