### ISSUE TITLE
Metrics did not send until the first transaction

### ISSUE THREAD

**Issue by insanity13** [elastic/apm-agent-dotnet#1200]
## APM Agent version
- Elastic.Apm: 1.8.0
- Elastic.Apm.EntityFramework6: 1.8.0

## Environment
- Operating system and version:  Windows Server 2012 R2
- .NET Framework 4.7.2

## Describe the bug
I've added APM to Windows Service app. 
In app.config file added appSettings: ServerUrls, SecretToken, ServiceName, Environment, ServiceVersion.
Service starts automatically (always on), and listen to MSMQ Queue.
When the message received I've adding APM transaction
`
var transaction = Elastic.Apm.Agent.Tracer.StartTransaction("Calculate Pricing", ApiConstants.TypeRequest); 
/// etc
`

Service worked several hours, and then the MSMQ message was received and the transaction was sent to Elastic.
- Until this time I cant see my service in APM Dashboard
- Until the first transaction was sent Metrics also does not sends

After restarting the service the same picture.

## Expected behavior
Metrics send on service start.

## To Reproduce
- Create a new APM service
- Start it
- Do not send any transaction several hours
- Then sent something
- You will see that the metric will start being sent only after the first transaction leaves (Lazy initialization?)

For example:
![image](https://user-images.githubusercontent.com/1174911/108670901-1997f580-74f9-11eb-840a-99fca14a1e36.png)
Point 1 - Service Restarted
Point 2 - Transaction Sent.

**Comment by russcam** [comment]
@insanity13 please can you add the following details:

### APM Agent version
The version of the `Elastic.Apm` nuget package used

### Environment

**Operating system and version:**

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):

### Describe the bug
A clear and concise description of what the bug is.

### To Reproduce

Steps to reproduce the behavior:

1. Use this config '...'
2. Then call '....'
3. Then do '....'
4. See error

#### Expected behavior
A clear and concise description of what you expected to happen.

#### Actual behavior

**Comment by insanity13** [comment]
@russcam I've updated my post. But I'm totally sure that initial information was enough. This is not a bug report, this is asking for advice.

It looks like the agent has lazy initialization, and until I call "Elastic.Apm.Agent.Tracer.StartTransaction" it stays uninitialized.
![image](https://user-images.githubusercontent.com/1174911/108723284-8339f300-753d-11eb-83ed-952c85442e53.png)

What is the best way to initialize it on service start? I didn't call Setup or Subscribe methods. Tracer Transactions are enough for me.

**Comment by insanity13** [comment]
If I'm not mistaken the same picture with IIS services can have long periods of inactivity (with autostart and always running).

**Comment by gregkalapos** [comment]
@insanity13 with that setup, you'll need to call `Agent.Setup(new AgentComponents());`. 

The thing is that something has to initialize the agent. If there is no agent code running, the metrics collector won't be initialized either. If you only use the public API (with `Agent.X`), the agent initializes itself before the first call for you in case it's not initialized. `Agent.Setup(new AgentComponents());` basically does the same manually.

Btw. don't you have an `IHostBuilder`? You could also turn on the agent on that one, and that'll also immediately initialize the agent. Something like [this](https://github.com/elastic/apm-agent-dotnet/tree/master/sample/SampleConsoleNetCoreApp) - this is not a Windows service, but I can imagine you could have something similar.

**Comment by insanity13** [comment]
@gregkalapos thanks for your response!

/*Agent.Setup(new AgentComponents());.
Great, I'll try it, thanks!

/*don't you have an IHostBuilder
If I understand you correctly, that is for .net Core and later, we have .NET Framework 4.7.2 project.
IHostedService will be helpful, but, unfortunately, we cannot use it in this project.
