### ISSUE TITLE
Performance issue : allowing to capture stacktrace on exception even if it's disabled for regular process

### ISSUE THREAD

**Issue by NicolasReyDotNet** [elastic/apm-agent-dotnet#1204]
**Is your feature request related to a problem? Please describe.**
I have an API route with a lot of business logic (with serveral Elasticsearch calls) that is monitored by APM and which is supposed to reply in 200ms or less (acceptance criteria).

With APM disabled (`"TransactionSampleRate" : 0`), my mean response time (based on 50 calls) is approx **100ms**
As soon as I monitor with APM (`"TransactionSampleRate" : 1`) with all parameters as default, the mean response time jumps to **430ms** (with exactly the same data)
I tried many parameters combinations accordind to the performance tagged settings : [All options settings](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-all-options-summary.html)

What I concluded, is, as I already read it in another thread, that the "problem" is linked to captured stacktraces.
Indeed I achieved the best performances disabling it (`"StackTraceLimit" : 0`) which is anyway useless for me for a regular call that process with no error.
![image](https://user-images.githubusercontent.com/37657851/109029955-a7274100-76c3-11eb-8095-2b278e8e1c79.png)
Now my mean response time is **180ms,** almost twice than without APM, but in accordance criteria. Great!

**BUT** this parameter seems also responsible for capturing stacktrace of uncaught throw exceptions, so when it occurs, I don't get the stacktrace either.
![image](https://user-images.githubusercontent.com/37657851/109029652-5879a700-76c3-11eb-96fa-49df7fb6c835.png)

**Describe the solution you'd like**
1) The solution I expect is using a dedicated parameters for capturing stacktraces of normal process and another one for uncaught exceptions (or the same one with all possibilities as enum do the job as well)

2) Or increase overall performance / speed so that I don't have to loose functionnalities because I need response time performance in my own application

**Describe alternatives you've considered**
1) I considered sampling request, but this has been rejected because of the loss of information + for the sampled transactions, the response time is beyond the limits (> 200ms as response time)

2) I also considered disabling stacktrace (`"StackTraceLimit" : 0`) but for uncaught exception it's a real problem

**Additional context**
Versions of Lib :
```
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.8.0" />
    <PackageReference Include="NEST" Version="7.11.1" />
```

.net 5 / Docker / local Docker-compose Elk stack (https://github.com/NicolasReyDotNet/APMSpanErrorRepro/blob/master/infrastructure/docker-compose.yml)

**appsettings.json**
```
  "ElasticApm": {
    "ServerUrls": "http://apm:8200",
    "TransactionSampleRate": 1,
    "CaptureBody": "all",
    "CaptureHeaders": true,
    "StackTraceLimit": 0, // find a compromise here
    "CloudProvider": "none"
  }
```

**Comment by gregkalapos** [comment]
This looks very similar to [this one](https://github.com/elastic/apm-agent-dotnet/issues/1145) - does the solution from that issue help you?

I just quickly went through the description, if it doesn't help I'll look deeper into this.

**Comment by NicolasReyDotNet** [comment]
@gregkalapos yes it does the trick thank you very much 👍 
Maybe the doc should contain something about that ? (it's a bit tricky)

One last question : is it the expected extra amount of time that activation APM this way :
 ```
 "ElasticApm": {
    "ServerUrls": "http://apm:8200",
    "TransactionSampleRate": 1,
    "CaptureBody": "all",
    "CaptureHeaders": true,
    "SpanFramesMinDuration": 0, // no stacktrace except for exception
    "CloudProvider": "none"
  },
```

We add approx **80ms** to a "APM free" transaction ? 
**100ms** without APM (mean time on 50 calls)
**180ms** with APM (mean time on 50 calls)

Many thanks for your reactivity

**Comment by gregkalapos** [comment]
I opened [a PR](https://github.com/elastic/apm-agent-dotnet/pull/1205) to explain this better in the docs.

> One last question : is it the expected extra amount of time that activation APM this way 

Going from 80 ms to 180ms sounds a bit too much, but this heavily depends on what the app does and the amount of things the agent captures.

I don't fully get the `100ms without APM` part. Does it mean you have an active agent (like it captures metric) but you don't start a transaction?

If this is still too much we still have some other performance related settings [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-all-options-summary.html).

**Comment by NicolasReyDotNet** [comment]
@gregkalapos 

Yes I saw the the PR yesterday, it's perfect.

### For my second question, sorry it was not very clear:

I have a controller with an action that basically use a service which use 4 singletons (1 per elk collection), to get data, apply business rules, then produce a response.
The transaction is then implicit, I don't have to create manually it.

The singletons are typed by T objects, they extend an abstract repository, example :
https://github.com/NicolasReyDotNet/APMSpanErrorRepro/blob/master/ElasticSearchRepository.cs
https://github.com/NicolasReyDotNet/APMSpanErrorRepro/blob/master/TestEntityElkRepository.cs
https://github.com/NicolasReyDotNet/APMSpanErrorRepro/blob/7ed4cc4a184b352f277e25ad3df6acb75cba4bd4/Startup.cs#L32

Here are the default spans created by the whole process (we see the  calls)
![image](https://user-images.githubusercontent.com/37657851/109126065-201eab00-774d-11eb-8bcb-6c1ee1ef21ed.png)


- When I "disable" APM, on 50 calls of this API (local docker-compose env), I got a mean response time of **100ms** 

 ```
 "ElasticApm": {
    "ServerUrls": "http://apm:8200",
    "TransactionSampleRate": 0, // "disabling" APM transaction tracing
    "CaptureBody": "all",
    "CaptureHeaders": true,
    "SpanFramesMinDuration": 0, // no stacktrace except for exception
    "CloudProvider": "none"
  },
```

- When I "enable" APM, on 50 calls of this API (local docker-compose env), I got a mean response time of **180ms** , so it add approx **80ms** on the mean response time.
 ```
 "ElasticApm": {
    "ServerUrls": "http://apm:8200",
    "TransactionSampleRate": 1, // "enabling" APM transaction tracing
    "CaptureBody": "all",
    "CaptureHeaders": true,
    "SpanFramesMinDuration": 0, // no stacktrace except for exception
    "CloudProvider": "none"
  },
```
I tried to change several "performance related" parameters, and here are the results
![image](https://user-images.githubusercontent.com/37657851/109126273-5a884800-774d-11eb-915a-729f8821d511.png)

The stacktrace appears to be the most significant one.

Thank you for your help

**Comment by gregkalapos** [comment]
I see - yeah, I can't really give more advice here. If I'd have guessed, I'd have said less than 80ms overhead for this situation, but overall it does not sound super dramatic to me. We have some benchmarks, simply creating spans and transactions is well above 1ms, but in this case just receiving callbacks for the given calls also adds some overhead.

nit: btw we also have specific settings to disable the agent. See [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-enabled) and [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-recording).

**Comment by NicolasREY69330** [comment]
@gregkalapos 
Thank you, I'll use the correct parameter to disable APM.
Yes the overall is not that much, 80ms is close to nothing, and surely we can't have an instrumentation that sophisticated  for no additional time

By the way, is there a way to not instrument ElasticSearch calls ?

**Comment by gregkalapos** [comment]
> By the way, is there a way to not instrument ElasticSearch calls ?

Yes, that's possible, for that you'll need to change the call [here](https://github.com/NicolasReyDotNet/APMSpanErrorRepro/blob/7ed4cc4a184b352f277e25ad3df6acb75cba4bd4/Helpers/ElasticSearchExtensions.cs#L32) to call `UseElasticApm`. That'll only capture incoming ASP.NET Calls and you can then enable further diagnostic manually. You can see the list of default diagnostic subscribers we use [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.NetCoreAll/ApmMiddlewareExtension.cs#L34) when you call `UseAllElasticApm`. The `UseElasticApm` won't add any of those, but you can pass the ones you need manually into the `UseElasticApm` method. 

One thing to keep in mind is that even if you drop `ElasticsearchDiagnosticsSubscriber`, the `HttpDiagnosticsSubscriber` will still capture the pure HTTP calls going to elasticsearch.

More on it [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-asp-net-core.html#_quick_start_2).

**Comment by NicolasREY69330** [comment]
Great I'll have a check on monday, I keep you informed on my benchmarks

**Comment by NicolasReyDotNet** [comment]
@gregkalapos 

I tested both : 
1) disabling APM with the dedicated setting
```
  "ElasticApm": {
    "ServerUrls": "http://apm:8200",
    "Enabled": false, //<== disabled
    "TransactionSampleRate": 1,
    "CaptureBody": "all",
    "CaptureHeaders": true,
    "SpanFramesMinDuration": 0, // no stacktrace except for exception
    "CloudProvider": "none"
  }
```
The mean response time is pretty closed to the one having `"TransactionSampleRate": 0` (**100ms**), which seems normal.

2) removing Elasticsearch diagnostic subscriber
```
                app.UseElasticApm
                (
                    config
                    , new HttpDiagnosticsSubscriber()
                    , new AspNetCoreDiagnosticSubscriber()
                    , new EfCoreDiagnosticsSubscriber()
                    , new SqlClientDiagnosticSubscriber()
                // , new ElasticsearchDiagnosticsSubscriber() 
                );
```
The mean response time is here pretty closed to the one obtained when enabling APM with the trick you gave to me `"SpanFramesMinDuration": 0` (**150 to 180ms**).

Maybee I could use more than 50 calls to compute my mean response time, anyway we'll have performance tests within our K8S cluster, in conditions closer to reality than my local docker stack.

I guess it's hardly linked to the type of operation captured (Sql operations, Http calls, Elk calls etc ...)
I close the ticket, but **if you can give me your point of view about these results**, it would be great.

Anyway awesome lib, great job!
