### ISSUE TITLE
FlushInterval doesn't work

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1210]
_Originally posted by @wast in https://github.com/elastic/apm-agent-dotnet/issues/141#issuecomment-786767998_

Well I got here while looking for FlushInterval and performance issues. I'm having a problem with rare Flushes.

![image](https://user-images.githubusercontent.com/9076227/109330159-ab866200-785b-11eb-9948-9c25a0152d74.png)

My single transaction is quite big, it has 10 spans and I'm running it at localhost currently. When I turn on small load test like 100 RPM, APM server doesn't get data from my app.

Look at "newEventQueueCounts" and timing of "{PayloadSenderV2} Sent items to server".

![image](https://user-images.githubusercontent.com/9076227/109330596-1fc10580-785c-11eb-9107-6b685d299faa.png)

Current config:
    "TransactionSampleRate": 0.2,
    "StackTraceLimit": 10,
    "FlushInterval": "5s", //doesn't work
    "MaxQueueEventCount": 5000,
    "SpanFramesMinDuration": "100ms", //this doesn't seem work, all spans including smaller than 100ms are recorded
    "CaptureHeaders": true,
    "CentralConfig": false,
    "CloudProvider": "none"

**Comment by wast** [comment]
To describe it more precisely, I start the application, it opens the default page which generates APM entry. It does get sent to the APM server and seen there. After that I keep refreshing the page in the browser and I see in the debug log that actions are behing queued:

![image](https://user-images.githubusercontent.com/9076227/109332731-d2926300-785e-11eb-9cd1-a43494df653a.png)

then I stop and I see after 20 seconds that a batch of 10 queued items are sent to the server. After 21 seconds another batch of 10 are being set to the server.

![image](https://user-images.githubusercontent.com/9076227/109332849-f81f6c80-785e-11eb-921d-9b9c09edad3a.png)

**Comment by gregkalapos** [comment]
> Look at "newEventQueueCounts" and timing of "{PayloadSenderV2} Sent items to server".

I see, yeah, that's strange. @wast is this a trimmed log I see there or a full one? Could you maybe attach a full log on debug level?

Also on debug fairly early you should see a line on debug level starting with `Using the following configuration options` - that prints the flush interval the agent uses. How does that line look int your setup.

It should be something like this:

```
dbug: Elastic.Apm[0]
      {PayloadSenderV2} Using the following configuration options: Events intake API absolute URL: http://localhost:8200/intake/v2/events, FlushInterval: 10s, MaxBatchEventCount: 10, MaxQueueEventCount: 1000
```

> "SpanFramesMinDuration": "100ms", //this doesn't seem work, all spans including smaller than 100ms are recorded

That setting is about stack trace capturing, not about the capturing of the span itself. I admit, the name is confusing. Docs on it can be found [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-stacktrace.html#config-span-frames-min-duration).

**Comment by wast** [comment]
Here's the full log
[dotnet-apm.log](https://github.com/elastic/apm-agent-dotnet/files/6051348/dotnet-apm.log)

**Comment by wast** [comment]
Also, this was the same on both versions 1.7.1 and latest 1.8.1.

**Comment by gregkalapos** [comment]
Could you set the log level to trace and regenerate the logs? We have more info around this on trace level.

**Comment by wast** [comment]
Here is verbose log [dotnet-apm.log](https://github.com/elastic/apm-agent-dotnet/files/6051635/dotnet-apm.log)

**Comment by gregkalapos** [comment]
Hmm. The only theory I can come up with is that sending data to APM server takes fairly long and that's why the agent keeps the events in the queue. Once the agent started sending 1 batch of data, it won't try sending another one as long as the previous one is not finished. That's the only explanation I can think of based on the logs.

To support this, here is one span with id `1f452cbe2fe34e80`:

```
[19:08:07 VRB] {PayloadSenderV2} Serialized item to send: Span{Id: 1f452cbe2fe34e80,
```

Serialization happens right before the agent sends the data and the timestamp for that is `19:08:07`. Right after this action the agent will send the serialized data to the APM Server - well, to be precise, it serializes all items and then sends the data. So 2 thins happen: the serialization and sending the data.

And here is when we see the next info about the same span - the agent prints this right after it gots response from the APM Server (in this case a OK) about the data sent.

[19:09:12 DBG] {PayloadSenderV2} Sent items to server:
    Span{Id: 1f452cbe2fe34e80, TransactionId: 

The timespan here is `19:09:12` - much later than the serialization. Basically the only thing that happens between the 2 lines is the HTTP call to the APM Server.

What was the problem with the default settings? Also, is this a real production problem or just a demo app locally and the only issue is that you see the data a little bit delayed?

**Comment by wast** [comment]
Yes, it was a production issue. When load-testing we didn't get data to APM. It never came there, not just delayed. Then I went to try it locally and saw that local queue is getting filled quickly. Also tried other performance tweaks from the documentation.

What you suggest is there are some APM server or network issues then?

**Comment by gregkalapos** [comment]
> Yes, it was a production issue. When load-testing we didn't get data to APM. It never came there, not just delayed.

In this case I think you should not lower the `FlushInterval`, that won't really help, especially not if my theory is true (which is that this is a connection issue between the APM server and the agent, or an issue with the server). I don't know the details of your load testing, but lowering `FlushInterval` would mean that in a high load situation the agent will try to do even more HTTP calls. 
 
Setting the `MaxBatchEventCount ` is definitely a good idea and I'd also try to set `MaxBatchEventCount` to something higher.

You can calculate how much requests you'd like to capture: e.g. if you sample everything, let the `FlushInterval` on default (`10s`) and set `MaxBatchEventCount` to 5000, then the agent will be able to capture up to 5000 events (transactions+spans+metrics) per 10 sec - if you lower the sample rate, the number goes up.

Also I'd like to mention that the goal of the agent is definitely not to capture everything at every price. If you hit queue limits, the agent will drop data. With the above example you can calculate the number of transactions per time frame the agent will capture. Do not try to aim for an infinite number, it's just not possible - in a super high load situation the agent will give up, that's normal - in exchange the app still has a chance to keep up with the requests.

Based on the logs it seems the 10sec `FlushInterval` is even too optimistic (I have never seen that being an issue, but I'd focus on that here, since that's what logs point to) - I'd try to set it to something higher - in my example from the logs in my previous comment  it took even 1 minute to finish the request (again, I have never seen something like that, so it's definitely not normal).

> What you suggest is there are some APM server or network issues then?

I think so, at least that's what I'd look into based on the logs. Of course I could be wrong, and you have better overview about the situation - but fact is, sending the events and getting a response from the APM server took super long.

**Comment by wast** [comment]
Let me investigate a little.

**Comment by gregkalapos** [comment]
I close this now for inactivity - feel free to reopen any time if you have more findings.
