### ISSUE TITLE
Add support for messaging

### ISSUE THREAD

**Issue by glucaci** [elastic/apm-agent-dotnet#1211]
The APM Server already has support for message context https://github.com/elastic/apm-server/issues/2697.

**Comment by glucaci** [comment]
I found the spec also https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-messaging.md.

Do you have this on the pipeline?

**Comment by RascoApps** [comment]
We also would love to MassTransit DiagnosticSource wired up. How about support to add any DiagnosticSource like ApplicationInsights? I tried to add myself but didn't want to Fork the repo.

**Comment by glucaci** [comment]
Seams that the agent don't need and special support for messaging.
We have created a basic package for the MassTransit https://github.com/swisslife-oss/elastic-apm-extensions#readme

**Comment by RascoApps** [comment]
Thank you very much. I’m glad I reached out. 😁

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
