### ISSUE TITLE
Add ENABLED, RECORDING settings

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#122]
Currently changing the app`s code is the only way to enable/disable automatic creation of transactions/spans.

Other agents have settings for this and the .NET agent should also have these settings.

The two settings:
- active
- instrument

Definition of instrument: https://github.com/elastic/apm/issues/49

**Comment by SergeyKleyman** [comment]
We should consider if setting `ACTIVE` to false should disable everything agent does including connecting to APM Server (in particular that would mean that having `ACTIVE` in configuration received from APM Server AKA remote configuration would be problematic). See discussion of `ACTIVE` at https://github.com/elastic/apm/issues/76

**Comment by freeranger** [comment]
> We should consider if setting `ACTIVE` to false should disable everything agent does 
Can I suggest that this would indeed be the case - per #865, in some cases consumers of our libraries simply have no interest in APM and therefore won't have a server to connect to; in other cases it may simply be that we want to disable it completely when looking at performance issues.

And locally as developers of libraries, it means we don't have to spin up an APM server just to avoid being spammed in the logs ;)

thanks

**Comment by basepi** [comment]
FYI, https://github.com/elastic/apm/issues/49 was closed, so perhaps this can be closed? Or at least amended to only include `enabled` and `recording`.

**Comment by gregkalapos** [comment]
I looked at other agents' docs and also asked about this in Slack. So far none of the configs mentioned here is implemented. According to current alignments across agents we'll add these 2:

- `enabled` : if `false`, the agent is totally turned off (doesn't even instrument, no background threads started, basically the agent does not do anything). This can't be changed, if the agent starts with `enabled=false` then only chance to turn on the agent is to set it to true AND restart the app.
- `recording` : This is live changeable, and even if it's `false`, the agent still listens to central config changes. If it's false  then nothing is collected (no transactions, no errors, not metrics, nothing) - but instrumentation is still in place - it's just not collecting data.

**Comment by gregkalapos** [comment]
Implemented in #997.

**Comment by billhong-just** [comment]
@gregkalapos  

Hi, gregkalapos  
I found [src/Elastic.Apm.AspNetFullFramework/ElasticApmModule.cs](https://github.com/elastic/apm-agent-dotnet/pull/997/files?file-filters%5B%5D=.cs#diff-8a14c77d217cb6c399e7d35f5db17042daec52b67a41d416fb23455bae6e6f2bR67) only use [`Enabled`](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/configuration.asciidoc#enabled-added170) without using [`Recording` ](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/configuration.asciidoc#recording-added170).  
In this case, is it still applicable to dynamically disable Elastic APM at runtime?
