### ISSUE TITLE
RabbitMQ support for .NET 

### ISSUE THREAD

**Issue by danielvoilaLEGO** [elastic/apm-agent-dotnet#1223]
Hello,

Is RabbitMQ support for .NET planned to be available in the near future?

Thank you!

**Comment by gregkalapos** [comment]
Hi @danielvoilaLEGO ,

we are currently working on [Azure ServiceBus](https://github.com/elastic/apm-agent-dotnet/issues/1157) - that'll add the  basis for messaging and from that point likely we can easily offer an API to also capture messaging related things manually.

Specifically for RabbitMQ we are watching https://github.com/rabbitmq/rabbitmq-dotnet-client/issues/776. If that happens we can add auto instrumentation fairly easily, if it doesn't happen we'll need to come up with something else which'll be more work.
