### ISSUE TITLE
Kibana observability overview section

### ISSUE THREAD

**Issue by domagojmedo** [elastic/apm-agent-dotnet#1226]
**Is your feature request related to a problem? Please describe.**
When sending APM data to elastic, package also sends some metrics data (https://www.elastic.co/guide/en/apm/agent/dotnet/current/metrics.html). Why is that data not compatible with metrics and overview part of observability in kibana? 
I can see the requests to the app on both servers, but I can't see any data in metrics and observability 
![image](https://user-images.githubusercontent.com/12157224/111290270-45b11d00-8646-11eb-86f1-53b93fc4ed54.png)

Why is that? Can the library also send data to metrics-* index? I added apm-* to metrics index but there is no data as you can see in the screenshot. I created custom dashboards but was hoping that library would do this by default. 

Metrics part recognizes 2 hosts from apm-* index but default view is really lacking. It would be great if data passed in would show up in the default view
![image](https://user-images.githubusercontent.com/12157224/111291080-1818a380-8647-11eb-882c-eef8eb902a72.png)

**Describe the solution you'd like**
Library should send metrics data in format that kibana metrics dashboard knows how to read and use by default.

**Describe alternatives you've considered**
We built custom dashboard for data that we want to see but I would be nice for it to be integrated in the default overview section

**Additional context**
Great library BTW 👍

**Comment by gregkalapos** [comment]
Hi @domagojmedo  

The metrics tab is mainly built for data coming from [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/7.11/index.html). We continuously work on better integrating all the observability parts.

> Why is that? Can the library also send data to metrics-* index?

Not really, all data from the APM agent goes to the APM Server which uses the apm-* indices.

Unfortunately that's all I can say now, I'm not super up-to-date what we plan on the UI side, but I can definitely say we are working on better integrating these things.

In terms on how to proceed on this: if this happens then this likely won't change anything in the .NET APM Agent (so in this library). The part that would do this work is likely the [APM Server](https://github.com/elastic/apm-server/).

**Comment by domagojmedo** [comment]
Is metrics tab meant to monitor apps or servers? 
One thing that is confusing to me is if I go to APM part and choose an app and then go to metrics tab, CPU usage is for the app and memory usage graph is for the server. Shouldn't they both be for the app since it's in APM part?

**Comment by gregkalapos** [comment]
> Is metrics tab meant to monitor apps or servers?

By default the starting point is the server (or host, or the container, or something some other "virtual" equivalent of the server), but then you can ingest all sorts of metrics which then can be also on the application level.

> One thing that is confusing to me is if I go to APM part and choose an app and then go to metrics tab, CPU usage is for the app and memory usage graph is for the server. Shouldn't they both be for the app since it's in APM part?

Both should be both for the server and for the app as well. [Here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/metrics.html#metrics-system) are the metrics that the .NET agent collects. We have both system and process data for both memory and CPU. Could you maybe check if some of those are missing? If so, it's worth [looking at agent logs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/troubleshooting.html#collect-agent-logs) after startup - if the agent is unable to read any of those, it prints it with some more info.

**Comment by gregkalapos** [comment]
I close this now, I think within this library we can't really progress more on this issue.
