### ISSUE TITLE
.NET Core Linux not logging Entity Framework Core transactions

### ISSUE THREAD

**Issue by mterwoord** [elastic/apm-agent-dotnet#123]
I published my app using:

```dotnet publish -r linux-x64 -f netcoreapp2.2 --self-contained -c Release```

The app works, requests end up in APM server, but no entity framework transactions.
Running the app from Rider on Windows works just fine. Is this a known thing with self-contained releases?

**Comment by gregkalapos** [comment]
Thanks for reporting this.

No, this is not a known thing, so we'll need to look into this. 

Unfortunately we don't have debug logs in the EF Core code.. 😕 

How did you install the agent? If I add some debug output on master, can you redeploy a new version of the agent by building it yourself? - we'd need some debug logs in the EF Core code anyway.

In case you can attach a debugger then one thing to look at would be to debug the `EfCoreDiagnosticListener` class.

**Comment by mterwoord** [comment]
Building and using a custom version should work.
This weekend I should have time to do some tests myself..

**Comment by skynet2** [comment]
On our prod machines, we are using pretty the same configuration, except netcoreapp, in our case is 2.1 

"C:\Program Files\dotnet\dotnet.exe" publish xxx.csproj --configuration Release --runtime linux-x64

And it works without issues, @mterwoord  can you try to use netcore 2.1 just as an experiment?

**Comment by mterwoord** [comment]
I just did a clean experiment with .net core 2.2, and there it works. Must be something in my product then. Will dig further, most likely tomorrow. Will keep you posted.

**Comment by gregkalapos** [comment]
> I just did a clean experiment with .net core 2.2, and there it works. Must be something in my product then. Will dig further, most likely tomorrow. Will keep you posted.

Thanks for letting us know! It's interesting. 

I think it's worth to see whether `EfCoreDiagnosticsSubscriber.Subscribe` runs or not in the case where it does not work.

Maybe another thing that comes to my mind: in the scenario where it did not work: does your app talk to a real database? What kind of database is it? The `DiagnosticSource` events are not fired when EF Core uses [in-memory database](https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/in-memory). Is this maybe something related? 

Let me know if I can help with more info.

**Comment by mterwoord** [comment]
The app runs inside docker, on a Ubuntu 18.04 server. It connects to a MS SQL Server 2017 instance, also running on that docker container. 
Maybe it has to do with docker?

**Comment by gregkalapos** [comment]
> The app runs inside docker, on a Ubuntu 18.04 server. It connects to a MS SQL Server 2017 instance, also running on that docker container.
> Maybe it has to do with docker?

Docker should not matter here... the agent subscribes to the DiagnosticSource events that EF Core sends, and it should not matter where the app runs. Of course this is just speculation... We should repro this. Is it possible that I get access to the docker image (or some modified version of it), so I can debug it? That'd make it easier...

**Comment by mterwoord** [comment]
I'm working on a repro project, but cannot really find anything yet.
Next week, I'll try to work on trimming down my product to a version that's OK to share, and still shows the issue..

**Comment by gregkalapos** [comment]
@mterwoord Is there any further help needed here? If not I'd close it soon (you can of course reopen it any time).

**Comment by mterwoord** [comment]
It's ok to close. I dont have time soon to work on it, sadly..

**Comment by gregkalapos** [comment]
Ok, closing now, feel free to reopen when you have time for this.
