### ISSUE TITLE
Support OpenTelemetry .NET

### ISSUE THREAD

**Issue by RascoApps** [elastic/apm-agent-dotnet#1234]
We would love to use an Elastic APM Exporter for the newly release .NET API.
https://devblogs.microsoft.com/dotnet/opentelemetry-net-reaches-v1-0/

Would this be possible?

**Comment by gregkalapos** [comment]
Yes, the OpenTelemetry Collector already has an exporter to our APM Server - so you'll need to use that. More on that setup [here](https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html).

We also have [another issue in this repo](https://github.com/elastic/apm-agent-dotnet/issues/303) to consider further integration.

**Comment by AlexanderWert** [comment]
[#1521 ](https://github.com/elastic/apm-agent-dotnet/issues/1521) implements an OpenTelemetry bridge
