### ISSUE TITLE
How to use APM in Console Applications in 4.7?

### ISSUE THREAD

**Issue by gabrieldocarmosantana** [elastic/apm-agent-dotnet#1238]
301 / 5000
Resultados de tradução
Hello, at the company where I work we use APM.
And I would like to know how to use it independently, so that we can monitor batch routines and console applications in Net Framework 4.7.
I tried this, but I was not successful, could you help me to use the solution in this case? 
```

public class CustomLogger : IApmLogger
	{
		public static CustomLogger Instance { get; } = new CustomLogger();

		public LogLevel Level => LogLevel.Debug;

		public bool IsEnabled(LogLevel level)
		{
			return true;
		}

		public void Log<TState>(LogLevel level, TState state, Exception e, Func<TState, Exception, string> formatter)
		{
			var message = formatter(state, e);
			Console.WriteLine(string.Format("[{0}] {1}", level.ToString(), message));
		}
	}

	public class CustomConfigurationReader : AbstractConfigurationReader, IConfigurationReader
	{
		public CustomConfigurationReader(IApmLogger logger = null) : base(logger,null)
		{

		}

		public LogLevel LogLevel => LogLevel.Debug;

		public IReadOnlyList<Uri> ServerUrls => new List<Uri>() { new Uri("MY-URL") };

		public string ServiceName => "BaixaDePedidos";

		public string SecretToken => "MYSECRETKEY";

		public bool CaptureHeaders => false;

		public double TransactionSampleRate => 1;

		public double MetricsIntervalInMillisecond => ConfigConsts.DefaultValues.MetricsIntervalInMilliseconds;

		public string ApiKey => null;

		public IReadOnlyCollection<string> ApplicationNamespaces => new List<string>();

		public string CaptureBody => ConfigConsts.DefaultValues.CaptureBody;

		public List<string> CaptureBodyContentTypes =>  new List<string>();

		public bool CentralConfig => false;

		public string CloudProvider => "";

		public IReadOnlyList<WildcardMatcher> DisableMetrics => null;

		public bool Enabled => true;

		public string Environment => "Staging";

		public IReadOnlyCollection<string> ExcludedNamespaces => null;

		public TimeSpan FlushInterval => new TimeSpan(ConfigConsts.DefaultValues.FlushIntervalInMilliseconds);

		public IReadOnlyDictionary<string, string> GlobalLabels => null;

		public string HostName => "IBM";

		public int MaxBatchEventCount => ConfigConsts.DefaultValues.MaxBatchEventCount;

		public int MaxQueueEventCount => ConfigConsts.DefaultValues.MaxQueueEventCount;

		public double MetricsIntervalInMilliseconds => ConfigConsts.DefaultValues.MetricsIntervalInMilliseconds;

		public bool Recording => false;

		public IReadOnlyList<WildcardMatcher> SanitizeFieldNames => null;

		public Uri ServerUrl => new Uri("http://10.141.0.118");

		public string ServiceNodeName => "ECOM";

		public string ServiceVersion => "1.0";

		public double SpanFramesMinDurationInMilliseconds => ConfigConsts.DefaultValues.SpanFramesMinDurationInMilliseconds;

		public int StackTraceLimit => ConfigConsts.DefaultValues.StackTraceLimit;

		public IReadOnlyList<WildcardMatcher> TransactionIgnoreUrls => ConfigConsts.DefaultValues.TransactionIgnoreUrls;

		public int TransactionMaxSpans => ConfigConsts.DefaultValues.TransactionMaxSpans;

		public bool UseElasticTraceparentHeader => false;

		public bool VerifyServerCert => false;
	}
```

And finaly:

Using as:    
```
var configReader = new CustomConfigurationReader(new CustomLogger());
var config = new AgentComponents(configurationReader: configReader  );
Agent.Setup(config);
```

My Regards!

**Comment by gregkalapos** [comment]
Hi @gabrieldocarmosantana,

you don't really need a config reader implementation, unless you want to configure the agent in code. By default the agent will read config values from environment variables.

If it's a console application, then likely you'll need to use the [public API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html) to start transactions manually.

Calling `Agent.Setup(new AgentComponents())` is enough to initialize the agent - from that point you can just use the environment variables we list [int the docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-all-options-summary.html).

We have a console app sample [here](https://github.com/elastic/apm-agent-dotnet/blob/master/sample/ApiSamples/Program.cs) - it's .NET Core, but the code basically looks the same in .NET Framework 4.7.

**Comment by gabrieldocarmosantana** [comment]
I don't know why, my agent didn't read my settings, so I activated it by code and set up a manual for him to access appsetings. I know it is not the ideal solution, but in this case my project is depreciated and we are moving to a project in asp net core that the apm works correctly. Thanks for listening. Below is my example of implementation, in case someone goes through the same problem.

`
 {


	public class CustomLogger : IApmLogger
	{
		public static CustomLogger Instance { get; } = new CustomLogger();

		public LogLevel Level => LogLevel.Debug;

		public bool IsEnabled(LogLevel level)
		{
			return true;
		}

		public void Log<TState>(LogLevel level, TState state, Exception e, Func<TState, Exception, string> formatter)
		{
			var message = formatter(state, e);
			Console.WriteLine(string.Format("[{0}] {1}", level.ToString(), message));
		}
	}

	public class CustomConfigurationReader : AbstractConfigurationReader, IConfigurationReader
	{
		public CustomConfigurationReader(IApmLogger logger = null) : base(logger, null)
		{

		}

		public LogLevel LogLevel => LogLevel.Debug;

		public IReadOnlyList<Uri> ServerUrls => new List<Uri>() { new 
 Uri(ConfigurationManager.AppSettings.Get("ServerUrls").ToString()) };

		public string ServiceName => ConfigurationManager.AppSettings.Get("ServiceName").ToString();

		public string SecretToken => ConfigurationManager.AppSettings.Get("SecretToken").ToString();

		public bool CaptureHeaders => false;

		public double TransactionSampleRate => 1;

		public double MetricsIntervalInMillisecond => ConfigConsts.DefaultValues.MetricsIntervalInMilliseconds;

		public string ApiKey => null;

		public IReadOnlyCollection<string> ApplicationNamespaces => new List<string>();

		public string CaptureBody => ConfigConsts.DefaultValues.CaptureBody;

		public List<string> CaptureBodyContentTypes => new List<string>();

		public bool CentralConfig => true;

		public string CloudProvider => "";

		public IReadOnlyList<WildcardMatcher> DisableMetrics => new List<WildcardMatcher>();

		public bool Enabled => true;

		public string Environment => ConfigurationManager.AppSettings.Get("Environment").ToString();

		public IReadOnlyCollection<string> ExcludedNamespaces => new List<string>();

		public TimeSpan FlushInterval => new TimeSpan(ConfigConsts.DefaultValues.FlushIntervalInMilliseconds);

		public IReadOnlyDictionary<string, string> GlobalLabels => new Dictionary<string, string>();

		public string HostName => "IBM";

		public int MaxBatchEventCount => ConfigConsts.DefaultValues.MaxBatchEventCount;

		public int MaxQueueEventCount => ConfigConsts.DefaultValues.MaxQueueEventCount;

		public double MetricsIntervalInMilliseconds => ConfigConsts.DefaultValues.MetricsIntervalInMilliseconds;

		public bool Recording => true;

		public IReadOnlyList<WildcardMatcher> SanitizeFieldNames => new List<WildcardMatcher>();

		public Uri ServerUrl => new Uri(ConfigurationManager.AppSettings.Get("ServerUrls").ToString());

		public string ServiceNodeName => "ECOM";

		public string ServiceVersion => null;

		public double SpanFramesMinDurationInMilliseconds => 
 ConfigConsts.DefaultValues.SpanFramesMinDurationInMilliseconds;

		public int StackTraceLimit => ConfigConsts.DefaultValues.StackTraceLimit;

		public IReadOnlyList<WildcardMatcher> TransactionIgnoreUrls => 
 ConfigConsts.DefaultValues.TransactionIgnoreUrls;

		public int TransactionMaxSpans => ConfigConsts.DefaultValues.TransactionMaxSpans;

		public bool UseElasticTraceparentHeader => false;

		public bool VerifyServerCert => false;
	}

  }
`

And call in main program 
`       var config = new AgentComponents(configurationReader: configReader, logger: configLogger);`
`           Agent.Setup(config);`


And add a basic configuration in App.config 
`    <add key="Environment" value="Staging"/>`
`      <add key="SecretToken" value="X54z4wMy2tuyQCSrEs"/>`
`      <add key="ServiceName" value="GPA_ORDER_INTEGRATION"/>`
`      <add key="ServerUrls" value="https://api.gtw.prd.e-store.gpa.digital:443/apm"/>`
