### ISSUE TITLE
Expose configuration snapshot on IApmAgent

### ISSUE THREAD

**Issue by russcam** [elastic/apm-agent-dotnet#1244]
`IApmAgent` exposes the starting configuration of the agent through `IConfigurationReader`:

https://github.com/elastic/apm-agent-dotnet/blob/c6b7cb5f974f07301153ccf64389c30003511f00/src/Elastic.Apm/Agent.cs#L17

The agent's configuration can be updated dynamically through central configuration, with updated configuration captured in `IConfigSnapshot` in `IConfigStore` on the concrete `ApmAgent` implementation:

https://github.com/elastic/apm-agent-dotnet/blob/c6b7cb5f974f07301153ccf64389c30003511f00/src/Elastic.Apm/Agent.cs#L37

The configuration snapshot is not however exposed on `IApmAgent`, which would be useful to have, for checking configuration values at runtime where the agent is referenced through the interface.

**Comment by glucaci** [comment]
I will propose to:
1. Mark `ConfigurationReader` as `Obsolate` for 1.x and remove it in 2.x
```csharp
public interface IApmAgent
{
    [Obsolete("Use IApmAgent.ConfigurationSnapshot, this will be removed in 2.x")]
    IConfigurationReader ConfigurationReader { get; }
}
```
2. Expose `IConfigSnapshotProvider`
```csharp
public interface IApmAgent
{
    IConfigSnapshotProvider Configuration { get; }
}
```

**Comment by pbalwall** [comment]
Thanks @russcam  and @glucaci  . Do we any idea when this feature could make it into a dotnet release?

**Comment by glucaci** [comment]
@russcam do you have another proposal on this?

**Comment by russcam** [comment]
@glucaci I haven't put further thought into this yet. At the moment, we're focused on finishing Azure Storage, Service Bus, CosmosDB, and MongoDB integrations for the next release. I'm hoping that we'll have some time to look at this afterwards.

I think configuration could be made easier to work with, though we may be limited in terms of binary compatibility in what we can do in 1.x; the end result might simply end up exposing `IConfigStore` in 1.x, but I think it'd be good to evaluate what the options are.

**Comment by gregkalapos** [comment]
Done in https://github.com/elastic/apm-agent-dotnet/pull/1323
