### ISSUE TITLE
Create a "kitchen sink" sample application

### ISSUE THREAD

**Issue by russcam** [elastic/apm-agent-dotnet#1246]
Relates: https://github.com/elastic/apm-agent-dotnet/pull/1197

We have several sample applications within the `/sample` directory that can be used to demonstrate different APM agent integrations, but we don't currently have a sample that demonstrates _many_ integrations in the one application. The closest to this is probably the `SampleAspNetCoreApp`, which is also used for ASP.NET Core integrations.

It would be useful to have a "kitchen sink" sample application that demonstrates  _many_ integrations in the one application.

**Comment by stevejgordon** [comment]
Closing as we have a wider plan for examples that also includes using the OTel distro
