### ISSUE TITLE
set "ElasticApm:Recording" to "false" still captures HTTP requests

### ISSUE THREAD

**Issue by billhong-just** [elastic/apm-agent-dotnet#1250]
### APM Agent version

**Elastic.Apm.AspNetFullFramework** v1.9.0

### Environment

**Operating system and version:** 

Windows 10 Enterprise 1909 18363.1440

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):

.NET 4.6.1

### Describe the bug

Still captures when **`ElasticApm:Recording`** set to **`false`**

### To Reproduce

1. Install **Elastic.Apm.AspNetFullFramework** v1.9.0
2. Set **`ElasticApm:Recording`** to **`false`** in web.config
3. Still seeing captured transactions on kibana UI

#### Expected behavior

not to capture anything when **`ElasticApm:Recording`** set to **`false`**

#### Actual behavior

still captures when **`ElasticApm:Recording`** set to **`false`**

#### Possible fix

https://github.com/elastic/apm-agent-dotnet/pull/997#discussion_r606744259

**Comment by davidnmbond** [comment]
In case anyone else finds this issue and is in the position we were in...

If you have background services etc. you will need to set **transaction_sample_rate=0**, as setting **recording=false** does not, in fact, stop all recording(!)
