### ISSUE TITLE
Apply custom limits to stack trace entries

### ISSUE THREAD

**Issue by marcoregueira** [elastic/apm-agent-dotnet#1253]
**Is your feature request related to a problem? Please describe.**

Currently, Apm sends a lot of data when **StackTraceLimit** is not set. Most of it is unneeded or unwanted.

The problem is that setting a limit affects all categories. **Exception records will also honor the same limits** and will not provide useful information if trimmed. Furthermore, if you set a low number, for instance 5, chances are that you will not get any useful info since it includes a lot of lines coming from infrastructure and only a few from my application. 

[Check this file for reference](https://pastebin.com/raw/Gv2YepNa); **It is a database span captured from the SampleAspNetCoreApp application in your repository.** It depicts quite well the problem.  

For instance, if there is a transaction that makes 250 calls to the database there will be 250 records including all of that stack information. The thing is I usually won't need the stack trace for database calls, especially if it comes at that cost. Usually they will be enclosed in some other spans. 

Other places excessively verbose are spans whose _outcome_ is **unsuccessful** or **unknown**. Those spans include the stack, even when there is an associated error trace that also includes it. If you review the traces generated with the same sample project you can see that "external" transactions have the same problem, there is also a "csvRead" transaction that has the entire stack.

Aside of that, it would be great to be able to limit the stack trace entries to those that **have a line number greater than zero**. In my sample file, there are around 47 entries for libraries and only 3 that are from the application code. In 99 percent of cases those library lines are only noise. Entries that have a line number _are my code_ and I care about them. The others could be useful, but mostly they aren't.

**Describe the solution you'd like**

I think a couple of changes would be useful:

- It would be great to use different settings to limit the stack trace limits for each category/transaction type. To not affect existing projects the current setting StackTraceLimit could be global and the ability to override it for the different trace kinds, if the new setting is informed. Being naive it could be StackTraceLimitForErrors or something more elaborated like separated settings for each transaction span, DB, request, external, etc... As an alternative a hook to discard entries could do the job that would provide more fine grained control to deal with the different _outcomes_.

- Another useful setting would limit the stack entries to those that have a **line number different from 0**.  If the previous setting is not feasible, this could be easier and very handy.

- Adding the new settings to the central configuration too would a win.

**Describe alternatives you've considered**

Well, sometimes I use a modified APM agent. That is the only alternative I figured out. I would like to get rid of it.

I think these additions would make the information already provided more useful, less verbose and more efficient for communications and storage.

**Comment by gregkalapos** [comment]
Hi @marcoregueira,

Some quick thoughts on this:

> As an alternative a hook to discard entries could do the job that would provide more fine grained control to deal with the different outcomes.

You should be able to do that with the [Filter API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#filter-api) - that gives you access to events (including spans with their stack traces) and you can modify or trim them before they go out to the APM server.

And maybe this issue will be also useful: https://github.com/elastic/apm-agent-dotnet/issues/1145 It shows how to disable span capturing for spans but keep it for errors.

**Comment by marcoregueira** [comment]
Hi @gregkalapos. Thank you for your answer. You're completely right.

Funny thing is I have used the filter api before, and completely forgot about it. 

Thank you for your patience.
