### ISSUE TITLE
dotnet Agent with AspNet Core Hooks feature doesn't report events to apm-server

### ISSUE THREAD

**Issue by ienjreny** [elastic/apm-agent-dotnet#1255]
APM Agent version: 1.8.1

Environment:
OS: Windows 10
.NET Core 5 and .NET Core 3.1

I am using the way described in the following link to monitor ASP.NET Core
https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-dotnet-net-core.html#zero-code-change-setup

The environment variables are set as following image:
![env](https://user-images.githubusercontent.com/19180819/114198379-ee0f8400-995b-11eb-843c-6bf2b8ec36e2.png)

To Reproduce the issue please 
1 - Create ASP.NET Core application
2 - Publish it under IIS
3 - Nothing is reported to APM UI and even apm-server log doesn't show any events

**Comment by russcam** [comment]
@ienjreny thanks for opening. Can you 

1. set the environment variable `ELASTIC_APM_STARTUP_HOOKS_LOGGING` to `true` 
2. Run the application again
3. Share the contents startup hooks log file written to `D:\apm\ElasticApmAgentStartupHook.log` ?

This might be related to https://github.com/elastic/apm-agent-dotnet/issues/1233 or https://github.com/elastic/apm-agent-dotnet/issues/1232, but will know more with the startup hooks log file.

**Comment by ienjreny** [comment]
Thanks @russcam for your reply, after a lot of try and error I found the issue, it is related to Environment variable cache, based on the following hint from Microsoft:

> When hosting an app in IIS and adding or changing the ASPNETCORE_ENVIRONMENT environment variable, use any one of the following approaches to have the new value picked up by apps:
> 
> Execute net stop was /y followed by net start w3svc from a command prompt.
> Restart the server.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-5.0#windows

Based on that, I followed the first approach (restart the IIS server from command line) and everything is working fine

Any way, the log file is attached FYR
[ElasticApmAgentStartupHook.log](https://github.com/elastic/apm-agent-dotnet/files/6294002/ElasticApmAgentStartupHook.log)

Thanks and we can consider this point is closed

**Comment by russcam** [comment]
great to hear @ienjreny 👍
