### ISSUE TITLE
Incorrect transaction duration shown on Kibana

### ISSUE THREAD

**Issue by arindamdat** [elastic/apm-agent-dotnet#1264]
### APM Agent version
Elastic.Apm dotnet agent 1.6.1

### Environment
**.NET Framework/Core name and version** core 3.1 :

### Describe the bug
The duration of the transactions shown on Kibana are not correct in some cases. For example, in the following screenshot, it says Avg. duration: 498 ms and 95th Percentile: 4183 ms. Whereas, none of the Trace samples inside took more than 160ms.
![image](https://user-images.githubusercontent.com/7764767/114827460-59d37000-9de6-11eb-9847-fb4e7e8a64ef.png)
![image](https://user-images.githubusercontent.com/7764767/114827753-b59df900-9de6-11eb-8e3e-2a733ca20980.png)

**Comment by russcam** [comment]
@elastic/apm-ui are the average and 95th percentile calculated based on **all** transactions of a given grouping (e.g. by transaction name)?

**Comment by sqren** [comment]
> are the average and 95th percentile calculated based on all transactions of a given grouping (e.g. by transaction name)?

The average and 95th in the table are per transaction group (unless we have a bug). So it sounds odd that it shows 4183ms if there're no transactions with durations higher than this. 

I'd like to see a screenshot of the latency distribution histogram for `GET /connect/userinfo` (displayed on the transactions details page when clicking on the item in the table)

**Comment by russcam** [comment]
> I'd like to see a screenshot of the latency distribution histogram for GET /connect/userinfo (displayed on the transactions details page when clicking on the item in the table)

@arindamdat are you able to share a screenshot of the latency distribution histogram for GET /connect/userinfo?

**Comment by russcam** [comment]
@arindamdat Noticed also that you're using .NET agent version 1.6.1; I'd recommend updating the agent to the latest (1.9.0) too

**Comment by arindamdat** [comment]
Hi @russcam , thanks for your response. When I looked at the **Transaction duration distribution** chart, I saw one small bar with longer duration and by default ElasticAPM shows traces for only the first one unless I explicitly select the other bar. This caused the confusion. I think you can close this Issue as it was a confusion from my side. Plz refer to the screenshot:
![image](https://user-images.githubusercontent.com/7764767/115426504-31040e00-a21e-11eb-8306-5b4f13c4a831.png)

**Comment by russcam** [comment]
Thank you for getting back, @arindamdat. This makes sense. Take a look at the [APM UI documentation on transactions](https://www.elastic.co/guide/en/kibana/current/transactions.html#transaction-duration-distribution) for more details.
