### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by benberg86** [elastic/apm-agent-dotnet#1285]
### APM Agent version
1.3.0

### Environment
The docs

### Describe the bug
Small typo in documentation

### To Reproduce

1. Visit https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-use-elastic-apm-traceparent-header

#### Expected behavior
ElasticApm:UseElasticTraceparentHeader

#### Actual behavior
ElasticApm:UseElasticTraceparentHeder

**Comment by russcam** [comment]
Thanks @benberg86 - would you like to submit a PR for the change? If not, I can do so 👍
