### ISSUE TITLE
Truncate strings 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#129]
Mostly triggered by https://github.com/elastic/apm-agent-dotnet/pull/118 

The initial suggestion was to do the truncation in the setters. 

We discussed this with @Mpdreamz and @SergeyKleyman and we found more advantages to do the truncation during serialization. 

- If it's serialization time we can most likely write a more generic way to trim/clean up these props while the dto's can stay simple getter/setters.
- If we do it in the setters we'd do it on a user-thread. By doing it during serialization we'd move this work to a non-user thread.
- In case we add new classes/string properties it's easy to forget if this is done in each setter

So the current agreement is to do this work during serialiazation.

FYI: @skynet2

**Comment by skynet2** [comment]
HI @gregkalapos ,

My first intention was also to do that during serialization, but as I remember you had an idea to remove json.net serializer or am I missing something?

Thanks,
Stas

**Comment by gregkalapos** [comment]
Hi @skynet2 , 

Do you mean [this comment](https://github.com/elastic/apm-agent-dotnet/pull/120#discussion_r259005099)?

By "change" I meant changing the number 1024. Whether we change json.net, I don't know... we talked about utf8json, but we don't really have a final decision. But I'd expect to have the option to do this during serialization with all major json serializers. 

Anyway, I think everyone is convinced already that it's better to move this to serliazation time. 

Btw. the [java agent also](https://github.com/elastic/apm-agent-java/blob/master/apm-agent-core/src/main/java/co/elastic/apm/agent/report/serialize/DslJsonSerializer.java#L927) does it that way.

**Comment by skynet2** [comment]
Hi @gregkalapos ,
Nope i`m talking about https://github.com/elastic/apm-agent-dotnet/issues/106  - Json.NET (the elasticsearch client already solves this, we should reuse this solution)

**Comment by gregkalapos** [comment]
> Hi @gregkalapos ,
> Nope i`m talking about #106 - Json.NET (the elasticsearch client already solves this, we should reuse this solution)

I see, yes, that's what I referred to in my previous comment "we talked about utf8json, but we don't really have a final decision". 

But that should not change the concept regarding truncation.

Do we have any remaining objection against moving truncation to serialization time? If there is nothing I'd say we'll progress with this soon.

**Comment by gregkalapos** [comment]
PR: https://github.com/elastic/apm-agent-dotnet/pull/135

**Comment by gregkalapos** [comment]
PR #135 merged. Fixed.
