### ISSUE TITLE
Ability to add SanitizeFieldNames, without having to copy the current values

### ISSUE THREAD

**Issue by bertvan** [elastic/apm-agent-dotnet#1294]
**Is your feature request related to a problem? Please describe.**

We would like to add additional fieldnames to sanitize, more specifically: `*secret*`, so with wildcards.
The only way to do this, is by copying the current default values and overriding them.

**Describe the solution you'd like**

An option to add an additional list of fieldnames.

**Describe alternatives you've considered**

The only way to do this, is by copying the current default values and overriding them.

**Comment by gregkalapos** [comment]
Thanks for bringing this up @bertvan.

The challenge here is that all other Elastic APM Agents implement this feature and all work this way. [Here](https://github.com/elastic/apm/blob/master/specs/agents/sanitization.md) is the spec for it, if we were to change it, we'd need to change the spec first and that'd mean all other agents would need to adapt this as well.

I understand the issue and I see how this can be challenging - on the other hand right now all our settings work the same way: if there is a default value and you change a setting, then the default value gets removed. So at least in this sense settings are consistent.

**Comment by bertvan** [comment]
Hi @gregkalapos thanks for answering. 
Ok, I'll see if there's a way to read out the config value and append additional fieldnames instead then.

**Comment by gregkalapos** [comment]
I'll close this for now.
