### ISSUE TITLE
[FEATURE] Add ability to create DistributedTracingData instance from Trace Context

### ISSUE THREAD

**Issue by russcam** [elastic/apm-agent-dotnet#1296]
In its current form, `DistributedTracingData` only exposes traceparent and **not** tracestate, and provides a method to create `DistributedTracingData` only from traceparent. 

The Elastic APM agents may be used with other systems that require manual propagation of traceparent and tracestate. `DistributedTracingData` should provide a way to both set and get tracestate.

**Comment by stevejgordon** [comment]
Outdated and as far as I can see, no longer the case.
