### ISSUE TITLE
NullReferenceException ApmErrorLogger/GenerateApmStackTrace

### ISSUE THREAD

**Issue by aheubusch** [elastic/apm-agent-dotnet#1309]
### APM Agent version

Elastic.Apm 1.9.0
Elastic.Apm.Extensions.Hosting 1.9.0
Elastic.Apm.Extensions.Logging 1.9.0

### Environment

.NET Core 3.1

### Describe the bug

`ApmErrorLogger` passes a null logger to `StacktraceHelper.GenerateApmStackTrace` (second arg)
https://github.com/elastic/apm-agent-dotnet/blob/4591f02a53de6104c80fd3c56bce640e14c80602/src/Elastic.Apm.Extensions.Logging/ApmErrorLogger.cs#L45-L46
which then causes a NullReferenceException. Several try/catch keep the exception from reaching user code though.
https://github.com/elastic/apm-agent-dotnet/blob/4591f02a53de6104c80fd3c56bce640e14c80602/src/Elastic.Apm/Helpers/StacktraceHelper.cs#L51

### To Reproduce
```csharp
public static void Main()
{
    var host = Host
        .CreateDefaultBuilder()
        .ConfigureLogging(logging => logging.ClearProviders())
        .UseElasticApm()
        .Build();

    var logger = (ILogger)host.Services.GetService(typeof(ILogger<object>));
    logger.LogError(new Exception(), "error log with exception");
}
```

**Comment by gregkalapos** [comment]
😱 

Thanks for reporting it - super useful summary 👍 

Opened https://github.com/elastic/apm-agent-dotnet/pull/1311 to fix it.
