### ISSUE TITLE
Typo in setup.asciidoc mongodb auto instrumentation

### ISSUE THREAD

**Issue by sidinwillis** [elastic/apm-agent-dotnet#1317]
### APM Agent version
1.10.0

Hi!
Just a simple typo in the documentation (setup.asciidoc) in the "Quick start" prerequisite to the mongodb auto instrumentation:

MongoEventSubscriber

```csharp
settings.ClusterConfigurator = builder => builder.Subscribe (new MongoEventSubscriber ());
```
 instead of MongoDbEventSubscriber 

```csharp
settings.ClusterConfigurator = builder => builder.Subscribe (new MongoDbEventSubscriber ());
```

Thank you

**Comment by gregkalapos** [comment]
Thanks for reporting @sidinwillis 

I opened https://github.com/elastic/apm-agent-dotnet/pull/1318 to fix it. Btw for such things we are super happy to take PRs as well.

**Comment by sidinwillis** [comment]
Ok thanks @gregkalapos.

Sorry, next time I will ;)
