### ISSUE TITLE
Elastic APM - GC related memory leaks

### ISSUE THREAD

**Issue by andrewharry** [elastic/apm-agent-dotnet#1346]
### APM Agent version
Elastic.Apm 1.10.0

### Environment
Windows 10
.NET 4.8

### Describe the bug
I identified that we are having a slow memory leak in production.  Local testing with the server running idle showed that memory was being allocated continually

![image](https://user-images.githubusercontent.com/1200776/122503275-4f786100-d037-11eb-8de0-f29570f200a2.png)

Attached is a screen shot taken from my local dev machine (Windows 10 64)
running a self hosted WebAPI on .NET 4.8 (owin self hosted)

### To Reproduce

1. Add Elastic.Apm to a standard .NET framework Web Api Project
2. Run the API service
3. Observe memory increase over time

I was able to fix this issue by rolling back to version 1.8.1.  Version 1.9 also had the same memory leak occurring

#### Expected behavior
I expect an idle web api services to not increase in memory usage over time

#### Actual behavior
There is a slow memory leak while the server is even idle which all seems to be related to Elastic APM's GC metric collection

**Comment by russcam** [comment]
Thanks for opening @andrewharry, we'll need to investigate. Are you able to share a memory dump, which might help expedite investigation? Can be shared by email if necessary.

**Comment by jdupont** [comment]
We've also seen memory leaks when running APM on a self-hosted ASP.NET Core API service on .NET Framework 4.8, with similar retained objects as shown in the dotMemory screenshot from the original issue. We were on version 1.11.0 so we're going to try downgrading to 1.8.1 as suggested by @andrewharry.

**Comment by andrewharry** [comment]
I couldn't see anything obvious either when reviewing the delta between version 1.8.1. Version 1.9
But this was the threshold where the issue went away

**Comment by russcam** [comment]
It looks like the dictionary of `Dictionary<ProcessIndex, TraceLoadedDotNetRuntimeExtensions.DotNetRuntime>` that is used to track loaded .NET runtimes can grow unbounded, when `.NeedLoadedDotNetRuntimes()` is called. I'm going to continue looking at this, but this looks like it may be the cause.

Each `DotNetRuntime` tracks GC in a `TraceGarbageCollector` in a collection of `List<TraceGC>`, where each `TraceGC` holds a `List<GCPerHeapHistory>`, each containing a `GCPerHeapHistoryGenData[]`. This correlates with the screenshot you provided, @andrewharry - thank you for this!

**Comment by russcam** [comment]
After further investigation, I've opened https://github.com/elastic/apm-agent-dotnet/pull/1538 to address. This applies a filter to the TraceEventSession to filter to the current process only, resulting in only one `DotNetRuntime` tracked by the TraceEventSession. This does mean that GC metrics will not collected for less than Windows 8.1 / Windows Server 2012 R2, as earlier versions do not support filtering.
