### ISSUE TITLE
Unable to Setup Elastic APM for .NET Framework 4.7.5

### ISSUE THREAD

**Issue by kartheek91** [elastic/apm-agent-dotnet#1351]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions.
Hi, I tried setting up Elastic APM in c# web API .Net Framework 4.7.5 but I'm facing challenges. Please help in this regard.

**Comment by gregkalapos** [comment]
Hi @kartheek91 ,


could you please use our [discuss forum](https://discuss.elastic.co/c/apm). [Here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-asp-dot-net.html) is the documentation on how you can set up the agent in that environment.

If that doesn't work, please also include more details in the discuss forum (what error you see, maybe show logs, include your config files if relevent, etc.). 

We also have a [troubleshooting section](https://www.elastic.co/guide/en/apm/agent/dotnet/current/troubleshooting.html) in our documentation which may help.
