### ISSUE TITLE
Elastic.Apm.AspNetFullFramework and Cloudflare client IP

### ISSUE THREAD

**Issue by aboyaniv** [elastic/apm-agent-dotnet#1355]
hello.

We are using Cloudflare  as WAF , and it send the client IP in a header named "CF-Connecting-IP".
How to I make that the CurrentTransaction  will use this header for client IP ?
Can I overwrite the Client IP?

**Comment by russcam** [comment]
Hi @aboyaniv,

We try to reserve GitHub for bugs and feature requests, so please [use the discuss forums to ask questions](https://discuss.elastic.co/c/apm) in future.

I'm assuming that you'd like to set the `Request.Socket.RemoteAddress` to the value from the `CF-Connecting-IP` header. If that's the case, it should be [possible to do this with a filter](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#filter-api) **when** [also capturing headers](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-capture-headers). Something like the following should work:

In `Application_Start` in global.asax.cs, setup the agent with a filter

```c#
public class WhateverYourDerivedApplicationTypeIsCalled : System.Web.HttpApplication
{
    protected void Application_Start()
    {
        var components = ElasticApmModule.CreateAgentComponents();
        Agent.Setup(components);
        var filterAdded = Agent.AddFilter((ITransaction transaction) =>
        {
            if (transaction.Context?.Request?.Socket != null)
            {
                string value = null;
                // pull the value out of the headers
                if (transaction.Context.Request.Headers?.TryGetValue("CF-Connecting-IP", out value) ?? false)
                {
                    transaction.Context.Request.Socket.RemoteAddress = value;
                }
            }
            
            return transaction;
        });

        if (!filterAdded) 
            // log that the filter wasn't successfully added

        // other application start code...
    }
}

```

**Comment by aboyaniv** [comment]
Hi

Thanks! It works!


Best Regards,
Yaniv abo
Cardcom Inc.
http://www.cardcom.co.il<http://www.cardcom.co.il/>
***@***.******@***.***>
Mobile: +972-54-7257217
Office: +972-3-9436100
Direct: +972-3-9436112

**Comment by russcam** [comment]
Glad to hear it's working for you! I'm going to close this issue.
