### ISSUE TITLE
[FEATURE] Registering query parameters for 'StackExchange.Redis' spans

### ISSUE THREAD

**Issue by grietine** [elastic/apm-agent-dotnet#1364]
**Example of other packages:**
SqlClient span.db.statement:
`SELECT Id, Name FROM Users WHERE Id = "MyId"`

MongoDb span.db.statement:
`{ "find" : { "Id" : "MyId" }, "$db" : "MyDb" }`

**Current:**
Redis span.db.statement:
`GET`

**Expected:**
Redis span.db.statement:
`GET MyId`

**Context:**
Other packages like MongoDb, SqlClient are registering actual queries in span.db.statement field.
Redis package only registers plain commands without the actual parameters. In this case I would like to see a key used for GET or SET a cache value.

**Comment by russcam** [comment]
Thanks for opening @grietine. 

The data available to construct Redis spans is somewhat limited, based on what is publicly [exposed by StackExchange.Redis' profiling APIs](https://stackexchange.github.io/StackExchange.Redis/Profiling_v2.html). Most notably, the `Message` field is private, which contains information about the keys used. We may be able to do something with reflection here, to get more information, if available.

**Comment by russcam** [comment]
I've opened https://github.com/elastic/apm-agent-dotnet/pull/1374

**Comment by grietine** [comment]
Writing this as a regression, previously you've added this part and now it's gone again. Why it was removed?
