### ISSUE TITLE
TransactionIgnoreUrls ignored, recording all traffic regardless of my overrides

### ISSUE THREAD

**Issue by christamlyn-bridge** [elastic/apm-agent-dotnet#1371]
### APM Agent version
1.11.0

### Environment

Dotnet Core 3.1 Docker

### Describe the bug
I've tried to setup my appsettings to include TransactionIgnoreUrls, excluding two paths

- /swagger*
- */status*

By adding the following to appsettings.json
`  "ElasticApm": {
    "Enabled": true,
    "ServerUrls": "https://.....",
    "SecretToken": ".....",
    "CaptureHeaders": false,
    "ServiceName": "Service Name",
    "Environment": "Development",
    "TransactionSampleRate": 1.0,
    "TransactionIgnoreUrls": [ "/status*", "/swagger*" ]
  },`

When running my application, I still see the transactions being recorded and sent to APM

e.g.
`{"metadata":{"service":{"agent":{"name":"dotnet","version":"1.11.0+a4eb5008af64ca52fe6973c18810c0c8c7a99554"},"environment":"Development","framework":{"name":"ASP.NET Core","version":"3.1.16.0"},"language":{"name":"C#"},"name":"Service Name","node":{},"runtime":{"name":".NET Core","version":"3.1.16"},"version":"1.0.0"},"system":{"detected_hostname":"DESKTOP-I13197M","hostname":"DESKTOP-I13197M"}}}
{"transaction":{"context":{"request":{"body":"[REDACTED]","http_version":"1.1","method":"GET","socket":{"encrypted":false,"remote_address":"::1"},"url":{"full":"http://localhost:5430/swagger/index.html","hostname":"localhost","pathname":"/swagger/index.html","protocol":"HTTP","raw":"http://localhost:5430/swagger/index.html","search":""}},"response":{"finished":true,"status_code":200}},"duration":471.265,"id":"318f21645e14aa41","sampled":true,"name":"GET /swagger/index.html","outcome":"success","result":"HTTP 2xx","sample_rate":1.0,"span_count":{"dropped":0,"started":0},"timestamp":1628069014884261,"trace_id":"1e30a5092eb3a64ebed64f88c15362a6","type":"request"}}
{"transaction":{"context":{"request":{"body":"[REDACTED]","http_version":"1.1","method":"GET","socket":{"encrypted":false,"remote_address":"::1"},"url":{"full":"http://localhost:5430/swagger/ui/swagger.json","hostname":"localhost","pathname":"/swagger/ui/swagger.json","protocol":"HTTP","raw":"http://localhost:5430/swagger/ui/swagger.json","search":""}},"response":{"finished":true,"status_code":200}},"duration":931.386,"id":"87d2ed00d3008c4b","sampled":true,"name":"GET /swagger/ui/swagger.json","outcome":"success","result":"HTTP 2xx","sample_rate":1.0,"span_count":{"dropped":0,"started":0},"timestamp":1628069016022184,"trace_id":"fe8561882ee9004a9da7e7683c633f86","type":"request"}}`

#### Expected behaviour
From what I understand about this property, overriding the defaults should exclude these transactions from being recorded.  We get a high number of health checks on /status and there is little value in sending these to APM.

I've tried various other patterns, moving the wildcard around but it always seems to record all traffic.  Not sure If I am misunderstanding the purpose of this property.

**Comment by russcam** [comment]
@christamlyn-bridge

 I'd expect `/swagger*` to ignore requests to swagger endpoints like `http://localhost:5430/swagger/ui/swagger.json`.

A couple of things to check:

1. Set the [agent log level to `Trace`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-supportability.html#config-log-level) and assert that `TransactionIgnoreUrls` is being set with the values expected from configuration, by [checking the agent logs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/troubleshooting.html#collect-agent-logs). Can also check the `Agent.Config.TransactionIgnoreUrls` after the client has been instantiated, to see the original values set when the agent was first instantiated.
2. Since `TransactionIgnoreUrls` is a setting that can be dynamically updated by Kibana central configuration, make sure that the original setting value is not being overridden by a centrally configured value.

If this yields no further insights, can you provide more detail or an example of how the agent is configured in your application?

**Comment by christamlyn-bridge** [comment]
[Full logs here](https://gist.github.com/christamlyn-bridge/041270845e071d5b3186121483e4fa35).

I can see TransactionIgnoreUrls being mentioned:

`{"Timestamp":"2021-08-16T13:45:53.6388151+01:00","Level":"Debug","MessageTemplate":"{{{Scope}}} Request ignored based on TransactionIgnoreUrls, url: {urlPath}","RenderedMessage":"{\"ApmMiddleware\"} Request ignored based on TransactionIgnoreUrls, url: \"/swagger/swagger-ui-bundle.js\"","Properties":{"Scope":"ApmMiddleware","urlPath":"/swagger/swagger-ui-bundle.js","SourceContext":"Elastic.Apm","RequestId":"0HMB0MF3P3SKS:00000001","RequestPath":"/swagger/swagger-ui-bundle.js","SpanId":"|8f7962ec-429184fa751b08c6.","TraceId":"8f7962ec-429184fa751b08c6","ParentId":"","ConnectionId":"0HMB0MF3P3SKS","EnvironmentUserName":"DESKTOP-I13197M\\Chris","MachineName":"DESKTOP-I13197M","ProcessId":2712,"ThreadId":8,"Format":"json","Environment":"Development","Country":"Global","Source":"Bridge Report Books API","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"}}
{"Timestamp":"2021-08-16T13:45:53.6388088+01:00","Level":"Debug","MessageTemplate":"{{{Scope}}} Request ignored based on TransactionIgnoreUrls, url: {urlPath}","RenderedMessage":"{\"ApmMiddleware\"} Request ignored based on TransactionIgnoreUrls, url: \"/swagger/swagger-ui-standalone-preset.js\"","Properties":{"Scope":"ApmMiddleware","urlPath":"/swagger/swagger-ui-standalone-preset.js","SourceContext":"Elastic.Apm","RequestId":"0HMB0MF3P3SKU:00000001","RequestPath":"/swagger/swagger-ui-standalone-preset.js","SpanId":"|8f7962ed-429184fa751b08c6.","TraceId":"8f7962ed-429184fa751b08c6","ParentId":"","ConnectionId":"0HMB0MF3P3SKU","EnvironmentUserName":"DESKTOP-I13197M\\Chris","MachineName":"DESKTOP-I13197M","ProcessId":2712,"ThreadId":9,"Format":"json","Environment":"Development","Country":"Global","Source":"Bridge Report Books API","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"}}
`

Which looks good, suggesting its going to ignore the Requests like /swagger*.  But then later in the logs

`{"Timestamp":"2021-08-16T13:45:54.2896146+01:00","Level":"Debug","MessageTemplate":"{{{Scope}}} Incoming request. Starting Trace.","RenderedMessage":"{\"ApmMiddleware\"} Incoming request. Starting Trace.","Properties":{"Scope":"ApmMiddleware","SourceContext":"Elastic.Apm","RequestId":"0HMB0MF3P3SKS:00000002","RequestPath":"/swagger/ui/swagger.json","SpanId":"|8f7962ee-429184fa751b08c6.","TraceId":"8f7962ee-429184fa751b08c6","ParentId":"","ConnectionId":"0HMB0MF3P3SKS","EnvironmentUserName":"DESKTOP-I13197M\\Chris","MachineName":"DESKTOP-I13197M","ProcessId":2712,"ThreadId":4,"Format":"json","Environment":"Development","Country":"Global","Source":"Bridge Report Books API","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"}}`

Which now recording requests even though (as far as I can tell) it also matches the pattern so should be ignored.

**Comment by russcam** [comment]
@christamlyn-bridge Thank you for the logs. I removed the link to the gist as it contains sensitive information. **IMPORTANT: Please generate a new secret token to access APM server.**

Looking at the logs, some of the requests to swagger endpoints are ignored, and some start a span:

- Starts a trace
  - /swagger/index.html
  - /swagger/ui/swagger.json
- Ignored
  - /swagger/swagger-ui-bundle.js
  - /swagger/swagger-ui-standalone-preset.js

I'd expect the wildcard `/swagger*` to match all these paths and ignore them, which the following tests confirms

```c#
[Fact]
public void TestMatch()
{
	var matcher = new List<WildcardMatcher>() { WildcardMatcher.ValueOf("/swagger*") };

	WildcardMatcher.IsAnyMatch(matcher, "/swagger/swagger-ui-bundle.js").Should().BeTrue();
	WildcardMatcher.IsAnyMatch(matcher, "/swagger/ui/swagger.json").Should().BeTrue();
	WildcardMatcher.IsAnyMatch(matcher, "/swagger/index.html").Should().BeTrue();
}
```

I don't see the trace log line with message

```
"Try parsing TransactionIgnoreUrls, values: {TransactionIgnoreUrlsValues}"
```
which is written when `TransactionIgnoreUrls` is constructed from the configuration value, which indicates that the agent is not configured with at least `TransactionIgnoreUrls` from your settings.

The default value for `TransactionIgnoreUrls` will ignore `*.js` but not `*.json` or `*.html`, which makes me believe that the agent is running with the default configuration, given the above. Can you show how the agent is instantiated/set up?

**Comment by christamlyn-bridge** [comment]
Sorry I didn't have time to try and create a sample app but here is how I am registering APM:

In appsettings.json:

`  "ElasticApm": {
    "Enabled": true,
    "ServerUrls": "https://blah",
    "SecretToken": "blah",
    "CaptureHeaders": false,
    "ServiceName": "Service Name",
    "Environment": "Development",
    "TransactionSampleRate": 1.0
  },`

Which is mapped to a Settings Class:
` public class ElasticApmSettings
    {
        [Required]
        public bool Enabled { get; set; }

        [Required]
        public string Environment { get; set; }

        public double TransactionSampleRate { get; set; } = 1.0;

        public List<string> TransactionIgnoreUrls { get; set; } = new List<string> { "/status*", "/swagger*" };
    }`

Then registering in Startup Configure like

 `   public virtual void Configure(IApplicationBuilder application) =>
            application
                .UseIf(this.elasticApmSettings.Enabled, x => x.UseAllElasticApm(this.configuration))`

I also tried removing the defaults from the class and explicitly specifying in the json like

`"TransactionIgnoreUrls":  ["/swagger*", "/status*"]`

But I couldn't see any difference in behaviour.  I even wondered if it was my specifying `TransactionSampleRate` but again, I removed and saw no difference in behaviour.

**Comment by russcam** [comment]
I see a few problems, if I've understood it correctly:

> ```cs
> public virtual void Configure(IApplicationBuilder application) =>
>             application
>                 .UseIf(this.elasticApmSettings.Enabled, x => x.UseAllElasticApm(this.configuration))
> ```

What is `this.configuration`? If it's the `Microsoft.Extensions.Configuration.IConfiguration` that is passed to the `Startup` constructor, I'm not sure how the values assigned to `ElasticApmSettings.TransactionIgnoreUrls` are assigned to the `IConfiguration` instance. It looks like they're set on the `ElasticApmSettings` instance, but won't be set on the `IConfiguration` instance.

With the [`Enabled`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-enabled) setting, the agent will be either completely enabled (`true`, the default) or disabled (`false`), which can't be changed for the lifetime of the application. It's intended to be used as a way to easily disable the agent without needing to make code changes - the middleware is still registered and an agent instance instantiated. If you really wanted to use the property to determine whether to add the middleware at all, something like

```c#
var enabled = Configuration["ElasticApm:Enabled"];
if (string.IsNullOrEmpty(enabled) || bool.TryParse(enabled, out var b) && b)
	app.UseAllElasticApm(Configuration);
```

would work. I wouldn't really recommend this approach however- if the agent public API is used to manually create transactions/spans anywhere, the agent instance will be instantiated at this point, and there might be other gotchas to consider too.

----

For

> ```cs
> public List<string> TransactionIgnoreUrls { get; set; } = new List<string> { "/status*", "/swagger*" };
> ```

and

> "TransactionIgnoreUrls":  ["/swagger*", "/status*"]

[`TransactionIgnoreUrls`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-transaction-ignore-urls) should be specified as a comma separated string of patterns to ignore. Something like the following in appsettings.json

```json
"TransactionIgnoreUrls":  "/swagger*, /status*"
```

The documentation is unclear and misleading, so I can see how this can happen. Apologies, I'll make sure this is updated to better clarify.

I'd recommend running with the [log level turned to "Trace"](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-supportability.html#config-log-level) for the agent, to see the verbose logs of how the agent gets configured on startup. It'll provide insight into what is happening and what might need to be changed to get this working for you.

**Comment by christamlyn-bridge** [comment]
thanks @russcam.  This is the magic that works for me.

`"TransactionIgnoreUrls":  "/swagger*, /status*"`

Using the trace logs I can see that my attempts to use defaults in the strongly typed settings class won't work due to the way we register APM.

Thanks for the support
