### ISSUE TITLE
[BUG]  CentralConfigFetcher logs SecretToken and ApiKey from request headers

### ISSUE THREAD

**Issue by rfatkullin** [elastic/apm-agent-dotnet#1376]
### APM Agent version
Version: v1.10.0

### Environment
OS: Windows 10
Net Framework version: NET Core 3.1.100

### Describe the bug
When server url is corrupted CentralConfigFetcher can't reach apm server and logs error with serialized request,
which contains sensitive data such apikey or authorization token.

### To Reproduce
1) Set to config "ServerUrls" corrupted address, set "ApiKey" or "SecretToken" configs.
2) Start app.
3) Open logs.
4) We can see ApiKey and SecretToken in logs.

#### Expected behavior
Apm sanitize sensitive data in request's headers before log and we can't see sensitive data.

#### Actual behavior
We can see sensitive data:

> +-> Request:
>     Method: GET, RequestUri: 'http://unavailable_address:8200/config/v1/agents?service.name=service_name&service.environment=Development', Version: 1.1, Content: <null>, Headers:
>     {
>       User-Agent: elasticapm-dotnet/1.10.0+ecfe0d02ee33d22706236b4cb31126d15a02507f
>       User-Agent: System.Net.Http/5.0.721.25508
>       User-Agent: .NET_5/5.0.7
>       Authorization: ApiKey SecretApiKey
>       traceparent: 00-edc8c158612d944da8c3a3b8e3a22322-c490329b63c0ac4a-00
>     }
> +-> Response: N/A
> +-> Response body [length: N/A]: N/A
> System.Net.Http.HttpRequestException: No such host is known. (unavailable_address:8200)

**Comment by russcam** [comment]
Thanks for reporting @rfatkullin. We'll look to investigate and fix for the next release

**Comment by russcam** [comment]
I've opened https://github.com/elastic/apm-agent-dotnet/pull/1471 to address
