### ISSUE TITLE
Add distributed tracing support

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#14]
As a test we can implement #42.

**Comment by gregkalapos** [comment]
This can be relevant: https://github.com/dotnet/corefx/issues/30331

**Comment by xitaocrazy** [comment]
Hi @gregkalapos,
There is some prevision to support distributed tracing? 
Thanks for attention.

**Comment by gregkalapos** [comment]
Hi @xitaocrazy, 

I'm currently working on this, so this is on the top of my list. 

If nothing unexpected comes along there should be a PR for this soon.

**Comment by xitaocrazy** [comment]
@gregkalapos thank for attention, please tell me if I could help with something.

**Comment by gregkalapos** [comment]
PR: https://github.com/elastic/apm-agent-dotnet/pull/168

**Comment by gregkalapos** [comment]
PR #168 landed, we have this. 🚀 

Some caveats (like header name) should be considered.

With this we have traces between multiple agents:
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/1091853/55791429-c2343c00-5abe-11e9-93a0-0d4a18ee91a9.png">
