### ISSUE TITLE
Act on server responses and implement back-off

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#141]
Currently the agent tries to send each event once, and if it fails, it just logs. 

We should implement a retry logic and listen to responses from the server and act on those responses. 

From: https://github.com/elastic/apm-agent-dotnet/pull/136#discussion_r264652202

**Comment by alvarolobato** [comment]
Related: 
https://github.com/elastic/apm-agent-java/pull/181
https://github.com/elastic/apm-agent-java/pull/210

**Comment by SergeyKleyman** [comment]
See https://github.com/elastic/apm/blob/master/docs/agent-development.md#transport-errors

**Comment by SergeyKleyman** [comment]
When agent receives unsuccessful HTTP status code from APM Server we should log not just the body of the response but HTTP status code itself as well.
For example in #433 - we logged 

> {PayloadSenderV2} Failed sending event. queue is full

and logging HTTP status code as well would have made it easier to find what condition among the ones listed at https://www.elastic.co/guide/en/apm/server/7.3/common-problems.html triggered the response.

**Comment by wast** [comment]
https://github.com/elastic/apm/blob/master/docs/agent-development.md#batchingstreaming-data is 404, is there any other update on this? FlushInterval is not working for me. It flushes randomly and really slow.

**Comment by gregkalapos** [comment]
That part of the doc got moved [here](https://github.com/elastic/apm/blob/master/specs/agents/transport.md#batchingstreaming-data).

No update on implementing back-off. We haven't done that.


What's exactly your issue @wast?

**Comment by wast** [comment]
Well I got here while looking for FlushInterval and performance issues. I'm having a problem with rare Flushes.

![image](https://user-images.githubusercontent.com/9076227/109330159-ab866200-785b-11eb-9948-9c25a0152d74.png)

My single transaction is quite big, it has 10 spans and I'm running it at localhost currently. When I turn on small load test like 100 RPM, APM server doesn't get data from my app.

Look at "newEventQueueCounts" and timing of "{PayloadSenderV2} Sent items to server".

![image](https://user-images.githubusercontent.com/9076227/109330596-1fc10580-785c-11eb-9107-6b685d299faa.png)

**Comment by gregkalapos** [comment]
Let me move this to a separate issue - it seems to be unrelated to this one. I opened https://github.com/elastic/apm-agent-dotnet/issues/1210 and I'll try to help there.

**Comment by stevejgordon** [comment]
Closing as we currently have no plans to implement this.
