### ISSUE TITLE
Extract common part from ISpan and ITransaction to a shared base interface

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#143]
There are a few parts in ISpan and ITransaction interfaces that have the same meaning (for example CaptureError, Start-time, Duration. etc.) so it might be beneficial to extract those common parts to a shared base interface (something like IExecutionSegment).

**Comment by alvarolobato** [comment]
Beware that this would be an implementation detail, in the model (ie server API) there is no such relation and this might change in the future, which could cause some refactor here if we do this change.

**Comment by gregkalapos** [comment]
In #179 we introduced a smaller common interface encapsulating methods related to capturing exceptions and errors and starting a sub span. It also has some basic common properties `Name`,  `Duration`.

There is still no direct inheritance between span and transaction. A span is not a transaction, a transaction is not a span - and both can evolve independently.
