### ISSUE TITLE
Choose better default for error's `culprint` property

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#145]
It seems that it's better to set some default culprint - I assume that taking the name of the method from the top  stack frame (i.e., the method that actually threw the exception) seems the most fitting option to me but it definitely can be done in a separate PR.

_Originally posted by @SergeyKleyman in https://github.com/elastic/apm-agent-dotnet/pull/136#discussion_r264831192

**Comment by gregkalapos** [comment]
Maybe this can help: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.callermembernameattribute?view=netframework-4.7.2

**Comment by SergeyKleyman** [comment]
I'm not sure. `System.Runtime.CompilerServices.CallerMemberName` will capture method that called `CaptureException` but that is usually the method that caught the exception while in `culprint` you probably would prefer the method that thrown the exception.

**Comment by alvarolobato** [comment]
The approach followed in the Java agent is obtaining the first in-app frame of the deepest nested exception. See for reference: https://github.com/elastic/apm-agent-java/issues/192 and https://github.com/elastic/apm-agent-java/pull/206

**Comment by kanadaj** [comment]
@gregkalapos is there any event/hook to attach to to set the culprint during an exception?

Also, Sentry already has a way to find the right culprint; maybe that'd be worth investigating, considering?

**Comment by kanadaj** [comment]
Relevant parts of code:
https://github.com/getsentry/sentry-dotnet/blob/9affdb5d8e6a38ead535770e64c0356d7a8a3f02/src/Sentry/Extensibility/SentryStackTraceFactory.cs#L140

And the default `InAppExclude` list:
https://github.com/getsentry/sentry-dotnet/blob/9affdb5d8e6a38ead535770e64c0356d7a8a3f02/src/Sentry/SentryOptions.cs#L388

**Comment by gregkalapos** [comment]
Done in #740.
