### ISSUE TITLE
[BUG] Elastic.Apm "fail:" logs when up/downloading Streams to/from Blob storage.

### ISSUE THREAD

**Issue by gcstarr** [elastic/apm-agent-dotnet#1479]
### APM Agent version and Azure Blob storage
```xml
<PackageReference Include="Azure.Storage.Blobs" Version="12.8.4" />
<PackageReference Include="Elastic.Apm" Version="1.11.0" />
<PackageReference Include="Elastic.Apm.Azure.Storage" Version="1.11.0" />
```

### Environment

Windows 10

**.NET Framework/Core name and version**:
.NET SDK v5.0.300

**Application Target Framework(s)**:
```xml
<TargetFramework>net5.0</TargetFramework>
<LangVersion>9.0</LangVersion>
```

### Describe the bug
I originally thought I had the same issue described in elastic/apm-agent-dotnet#1352 however after downgrading Azure.Storage.Blobs to `v12.8.4` the issue continued, namely getting the `Failed capturing DiagnosticSource event` warning from Elastic.Apm on blob operations when using `AzureBlobStorageDiagnosticsSubscriber`.

This happens on UploadAsync when the Stream being uploaded is a Stream type that has `CanSeek` set to `false`, such as `HttpRequestStream`. This also happens to me when downloading to a Stream, regardless of `CanSeek` setting.

Error:
```
fail: Elastic.Apm[0]
      {AzureBlobStorageDiagnosticListener} Failed capturing DiagnosticSource event
      System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
         at System.Uri..ctor(String uriString)
         at Elastic.Apm.Azure.Storage.BlobUrl..ctor(String url)
         at Elastic.Apm.Azure.Storage.AzureBlobStorageDiagnosticListener.OnStart(KeyValuePair`2 kv, String action)
         at Elastic.Apm.Azure.Storage.AzureBlobStorageDiagnosticListener.HandleOnNext(KeyValuePair`2 kv)
         at Elastic.Apm.DiagnosticListeners.DiagnosticListenerBase.OnNext(KeyValuePair`2 kv)
```

The blob successfully uploads. And the span is created, however the above warning displays in the logs, and I assume the span will be missing some information.

### To Reproduce

I made a repo that reproduces this here: https://github.com/gcstarr/ElasticApmAzureBlobBug

Relevant portions:
1. `.UseElasticApm(new AzureBlobStorageDiagnosticsSubscriber());`
2. Use an "un-seekable" Stream type (as HttpRequestStream is) to upload from. I made a simple sub-class of MemoryStream like this:
```cs
public class UnSeekableStream : MemoryStream
{
    public UnSeekableStream()
    {
    }
    public UnSeekableStream(byte[] buffer) : base(buffer)
    {
    }
    
    public override bool CanSeek => false;
}
```
3. Attempt to upload the stream. My function is:
```cs
public async Task StartAsync(CancellationToken cancellationToken)
{
    const string containerName = "data-storage";
    var client = new BlockBlobClient(_connectionString, containerName, "test1/test2/test3/testblob");
    var testBytes = Encoding.UTF8.GetBytes("{\"test\": \"test\"}");

    var transaction = _tracer.StartTransaction("Blob Tests", "Sample");
    
    var seekableStream = new MemoryStream(testBytes);
    var seekableSpan = transaction.StartSpan("Seekable Test Blob Upload", "Sample");
    await client.UploadAsync(seekableStream, new BlobUploadOptions());
    // No errors logged ^
    seekableSpan.End();
    
    var unSeekableStream = new UnSeekableStream(testBytes);
    var unSeekableSpan = transaction.StartSpan("Un-seekable Test Blob Upload", "Sample");
    await client.UploadAsync(unSeekableStream, new BlobUploadOptions());
    // Fail error logged ^
    unSeekableSpan.End();

    var seekableDownloadStream = new MemoryStream();
    var seekableDownloadSpan = transaction.StartSpan("Seekable Test Blob Download", "Sample");
    await client.DownloadToAsync(seekableDownloadStream);
    // Fail error logged ^
    seekableDownloadSpan.End();
    
    var unSeekableDownloadStream = new UnSeekableStream();
    var unSeekableDownloadSpan = transaction.StartSpan("Un-seekable Test Blob Download", "Sample");
    await client.DownloadToAsync(unSeekableDownloadStream);
    // Fail error logged ^
    unSeekableDownloadSpan.End();

    transaction.End();
}
```
4. Note a `fail:` logged at each of the 3 places noted above by comment.

#### Expected behavior
Uploading an CanSeek=false Stream type, such as HttpRequestStream, should work as other streams. Downloading to a stream should not throw warnings.

#### Actual behavior
Uploading with a CanSeek=false Stream type, or downloading to any Stream type, causes Elastic.Apm to throw warnings.

**Comment by russcam** [comment]
Thanks for reporting @gcstarr.

We're looking at a general fix for #1352, for the next release, which I think would also address this issue. Thank you for the reproduction; I'll add a test in the fix branch based on your repro, to assert this will also be addressed.
