### ISSUE TITLE
[Feature] Method level tracing similar to trace_methods in the Java Agent

### ISSUE THREAD

**Issue by bvader** [elastic/apm-agent-dotnet#1482]
As a developer and DevOps engineer I would like the ability to enable method level tracing with the .Net agent so that I can more easily pinpoint troublesome methods in my application.

**Is your feature request related to a problem? Please describe.**
Without the method level tracing it is very difficult to diagjosis 
We see this level of tracing 

**Describe the solution you'd like**
Method Level tracing similar to trace_methods in the Java Agent

**Describe alternatives you've considered**
Extensive Manual Transactions which is not effective

**Comment by stevejgordon** [comment]
Closing as unplanned at this time
