### ISSUE TITLE
Elastic Apm cannot perform link tracking, and the program initialization reports an exception 

### ISSUE THREAD

**Issue by zqlovejyc** [elastic/apm-agent-dotnet#1485]
### APM Agent version
The version of the `Elastic.Apm` nuget package used 1.11.0

### Environment

NET Core 5.0

### Describe the bug
`The singleton APM agent has already been instantiated and can no longer be configured. Reusing existing instance `

**Comment by russcam** [comment]
@zqlovejyc thanks for opening. We'll need more detail to be able to help-

1. what kind of application are you instrumenting?
2. how are you instrumenting it?
3. What do you expect to happen? What actually happens?

> The singleton APM agent has already been instantiated and can no longer be configured. Reusing existing instance

This agent log line is indicates that the APM agent singleton instance has already been instantiated when an attempt to configure and instantiate it has been made. It's not an exception, but an agent log to help diagnose agent operation. This log line may likely be related to the issue you're seeing. If you're to provide more details, we'll be able to help further.

**Comment by zqlovejyc** [comment]
> @zqlovejyc thanks for opening. We'll need more detail to be able to help-
> 
> 1. what kind of application are you instrumenting?
> 2. how are you instrumenting it?
> 3. What do you expect to happen? What actually happens?
> 
> > The singleton APM agent has already been instantiated and can no longer be configured. Reusing existing instance
> 
> This agent log line is indicates that the APM agent singleton instance has already been instantiated when an attempt to configure and instantiate it has been made. It's not an exception, but an agent log to help diagnose agent operation. This log line may likely be related to the issue you're seeing. If you're to provide more details, we'll be able to help further.

The problem has been solved. The mysql used before the problem was in cluster mode. After changing to single mode, Elastic Apm can collect data normally.
