### ISSUE TITLE
Implement sampling

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#15]
### Main requirement for sampling feature
"Non-sampled" means that spans and detailed transaction context aren't reported. So for each downstream service, we will still report a transaction with minimal context (for now -- may change to metrics later)

### Additional requirements for integration between distributed tracing and sampling features

1.  `recorded` flag is used to signal sampling decision which means that the agent that starts the trace should decide whether to sample and set `recorded` flag in outgoing calls accordingly. If an agent sees that it's a downstream agent for the current trace then it should sample current transaction based on the incoming `recorded` flag.
2. In order to enforce the same sampling decision for the whole trace agents should inject distributed tracing header even if the current trace is nonsampled. The difference in in the way distributed tracing should behave for nonsampled transactions is that for transaction ID should used for inject header value instead of span ID (see https://github.com/elastic/apm/issues/16).
3. Optionally consider covering requirements in elastic/apm-agent-dotnet#44 (Add `transaction.sampled` to Errors) by this implementation.

**Comment by gregkalapos** [comment]
#30 can be relevant.

**Comment by gregkalapos** [comment]
https://github.com/elastic/apm/issues/16

**Comment by SergeyKleyman** [comment]
Implemented by #188
