### ISSUE TITLE
Do not log certain 404s as "Unknown route"

### ISSUE THREAD

**Issue by skuc-fp** [elastic/apm-agent-dotnet#1533]
When an endpoint returns 404, the transaction name in APM is logged as "<METHOD> Unknown route". 
In some cases this is desired behavior, however it doesn't really play well with REST.
If, for example, the endpoint `/api/customers/{id}` returns 404 because the route exists but the customer with that id doesn't, then we'd like to see this logged under endpoint name in APM instead of "Unknown route".

**Is your feature request related to a problem? Please describe.**
I guess this is related to: https://github.com/elastic/apm-agent-dotnet/pull/953/files

**Describe the solution you'd like**
We'd like to be able to mark some endpoints in any way, so that their 404 response logs with correct transaction name

**Comment by kbalys** [comment]
Hi, is there a plan to fix this issue in the nearest future?

**Comment by gregkalapos** [comment]
I opened https://github.com/elastic/apm-agent-dotnet/pull/1715 which addresses this issue.
