### ISSUE TITLE
Implement metrics

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#154]
Currently the .NET Agent does not send metrics. We don't take advantage of this feature at all.

Metrics are also shown on the UI and in case of the .NET Agent those charts are empty, so we should catch up on this feature. 

Java Agent PR for ideas: https://github.com/elastic/apm-agent-java/pull/360

**Comment by gregkalapos** [comment]
Similarly to Java in step 1 (or step 0) we should make sure we fill the charts on Kibana - for this we need to send `cpu` and `memory` metrics.

Then we can also include agent specific metrics (e.g. gc metrics could be interesting). This can of course happen in 1 PR.

**Comment by francisminu** [comment]
Is this being developed at present? If so, is there a date by when this would be available? @gregkalapos  @alvarolobato

**Comment by alvarolobato** [comment]
No is not, but we plan to work on it very soon, probably in a few weeks.

**Comment by francisminu** [comment]
@alvarolobato 
Will this include the ability to push custom metrics or just the system level and agent level metrics?

**Comment by gregkalapos** [comment]
Hey @francisminu,

we don't have a 100% ready to implement plan on this one yet. Nevertheless, probably we will have system and some CLR metrics in the first iteration. I haven't looked at the details yet. Once we come up with a plan on what to implement in what stage I'll give a more detailed answer here.

**Comment by francisminu** [comment]
Thank you @gregkalapos 
Looking forward to an update soon :)

**Comment by gregkalapos** [comment]
A short update/summary on this issue.

Opened #248.

With that PR the agent will send some basic metrics to fill the Kibana charts under APM - my plan  is to definitely make sure those lend with this PR. So basic memory and CPU metrics are covered. 

The PR also contains new APIs as part of the Public Agent API to manually send custom metrics. This is public, so every user will have access to that API. The Go agent has something similar, other agents according to my current knowledge don't expose this API - nevertheless I think it's useful for .NET and adding it in the PR is very little additional work - so I think it'd make sense to also add that.

This is the plan for the Beta release. We'll have another iteration on this topic for adding more .NET specific metrics (like GC, etc..) Feedback on what would be useful is very appreciated.

**Comment by gregkalapos** [comment]
#248 merged.

There won't be a public API now to send metrics manually, that'll come in another iteration. See the description of #248 for details about what metrics we send now.
