### ISSUE TITLE
Consider renaming Elastic.Apm.NetCoreAll

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1562]
Since this would be a fairly big major change: This is not a final decision, we may not do it! Even if we do this, it'll be only in a major version.

`Elastic.Apm.NetCoreAll` was introduced in the .NET Core 2.x/3.x time frame and the package pulls in all the diagnostic source based instrumentations and turns those on. It's a super convenient way to turn on the agent. Currently it has 3mio+ downloads.

With .NET5 and .NET6, the package still works since those are basically just the next evolution of .NET Core. On the other hand, the package name with `NetCoreAll` could be now a bit misleading and it'd be nice to maybe better align with the naming from Microsoft here.

Questions:
- Do we want to do this?
- If so, what would be a good name?

**Comment by stevejgordon** [comment]
Closing as unplanned
