### ISSUE TITLE
[META 531] Add transaction.name to errors

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1574]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F531)](https://github.com/elastic/apm/issues/531)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F553)](https://github.com/elastic/apm/issues/553)

Implement https://github.com/elastic/apm/issues/531.

**Comment by gregkalapos** [comment]
Done in #1589
