### ISSUE TITLE
ElasticApm:ServiceName doesn't work

### ISSUE THREAD

**Issue by cysnet** [elastic/apm-agent-dotnet#1577]
My Project is .Net Framwork and name is WebApplication3. Use the nuget package Elastic.Apm.AspNetFullFramework

![image](https://user-images.githubusercontent.com/35944271/143157418-de117085-4338-467c-a115-4e5b2414eb14.png)

I set the ServiceName as TestFromworkSite as below
```
	<add key="ElasticApm:ServiceName" value="TestFromworkSite" />
	<add key="ElasticApm:Environment" value="Dev" />
```

but there is no data is TestFromworkSite and all data in WebApplication3
![image](https://user-images.githubusercontent.com/35944271/143157260-ae0d1338-e853-4114-90b2-adaf7581139a.png)

I hope that data should be in Service TestFromworkSite

**Comment by haroldrandom** [comment]
+1. The output in ECS doesn't include the `service.name` section at all.

ASP.NET Core and .Net 5

**Comment by z1c0** [comment]
I tried to reproduce the problem with the latest version (`1.19.0`) of `Elastic.Apm.AspNetFullFramework` but to no avail.
Hence, I am closing this issue. Should it persist, feel free to reopen and please provide a reproducer.
