### ISSUE TITLE
Allow tracing of external http requests/responses

### ISSUE THREAD

**Issue by slacksach** [elastic/apm-agent-dotnet#1578]
It would be highly beneficial to be able to track nested **external** http requests/responses using the APM
We utilise several 3rd party providers and not being able to track the request/response without utilising multiple sources makes it difficult to get to the root cause of issues.

Love the Elastic APM and this feature would be hugely appreciated :)

**Describe the solution you'd like**
1. Add a new appsetting + environment variable **ELASTIC_APM_CAPTURE_BODY_EXTERNAL** which follows the same rules for size limitations etc as the **ELASTIC_APM_CAPTURE_BODY**
2. Allow the Diagnostic Listener implementations to be extended so that teams can add additional tracing data without injecting Tracer instances.

**Describe alternatives you've considered**
- Extending the HttpDiagnosticListener implementations but these are marked internal so no flexibility to extend :(
- Manually injecting the Tracer and using that to append custom labels and data

**Comment by gregkalapos** [comment]
I'm not sure I fully understand this scenario. Could you please give a more specific example @slacksach?

We have 1 internal thing in the agent which we may consider making it public - and that may help you.

All I write about here is internal, so you won't be able to use it at this point - first I'd like to know if that'd help you.

There is an [`IHttpSpanTracer` interface](https://github.com/elastic/apm-agent-dotnet/blob/5412f5d1e74516df72c6768878dd434fd17a2d26/src/Elastic.Apm/DiagnosticListeners/IHttpSpanTracer.cs).

You can implement this interface and add your implementation to the agent like this:

```
Agent.HttpTraceConfiguration.AddTracer(new MyHttpSpanTracer());
```

What this will do is that for each outgoing HTTP call via `HttpClient`, it's going to call the `IsMatch` on the interface where you can check if you want to capture a span for a given HTTP call. If your `IsMatch` implementation returns true then the `StartSpan` on the interface is going to be called with all the HTTP info and you have the chance to create a span for the call yourself.

We use this internally in the agent for multiple HTTP based libraries - e.g. for Azure CosmosDB and Blob Storage. 

Would that be helpful for you? Your use case sounds similar, but I'm not totally sure it covers what you need.

**Comment by gregkalapos** [comment]
We discussed this in one of our meetings and we aren't really sure we should open up this API.

What you can do alternatively is that you just implement a custom diagnostic listener. 

Here are the steps you can do:

First create an initializer which will subscribe your listener
```
public class DiagnosticInitializer : IObserver<DiagnosticListener>
{
	public void OnCompleted() { }
	public void OnError(Exception error) { }
	public void OnNext(DiagnosticListener value)
	{
		if (value.Name == "HttpHandlerDiagnosticListener")
			// CustomHttpListener will contain the logic
			value.Subscribe(new CustomHttpListener());
	}
}
```

Then implement the listener with the logic to capture the HTTP request:

```
public class CustomHttpListener : IObserver<KeyValuePair<string, object>>
{
	public void OnCompleted() { }
	public void OnError(Exception error) {}
	public void OnNext(KeyValuePair<string, object> kv)
	{
		if (kv.Key == "System.Net.Http.HttpRequestOut.Stop")
		{
			if (Agent.IsConfigured && Agent.Tracer.CurrentSpan != null)
			{
				var requestObject = kv.Value.GetType().GetTypeInfo().GetDeclaredProperty("Request")?.GetValue(kv.Value);
				if (requestObject is HttpRequestMessage request)
				{
					// request contains the request object with the full content
					// Agent.Tracer.CurrentSpan contains the current HTTP span and with Agent.Tracer you can create a new span if you need that
					// Read the HTTP content here and set it accordingly
					// Regarding constant Agent.Tracer: Alternatively you can use DI with the UseAllElasticApm extension method.
				}
			}
		}
	}
}
```

Then finally subscribe:

```
DiagnosticListener
	.AllListeners
	.Subscribe(new DiagnosticInitializer());
```

In order to make sure the order of the listener matches, make sure you execute the above code after the agent registration.

I hope this helps - with this I believe you'll be able to achieve the functionality you need.

I'd be nice to use a simple `ActivityListener` for this, unfortunately that won't give you access to the HTTP request object - so that's why we need a Diagnostic Listener here.

I'm closing this now - if there is a question ping here and feel free to reopen.
