### ISSUE TITLE
[CI] Master branch failing

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-dotnet#1587]
It appears that the master branch is failing since December in some tests

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/master/640/pipeline/299

* `Windows .NET Framework / IIS Tests / ErrorsTests.Elastic.Apm.AspNetFullFramework.Tests.ErrorsTests.HttpCallWithResponseForbidden – Elastic.Apm.AspNetFullFramework.Tests.ErrorsTests`
15s
* `Linux / Test / MicrosoftAzureBlobStorageTracerTests.Elastic.Apm.Azure.Storage.Tests.MicrosoftAzureBlobStorageTracerTests.Capture_Span_When_Copy_From_Uri – Elastic.Apm.Azure.Storage.Tests.MicrosoftAzureBlobStorageTracerTests`

**Comment by v1v** [comment]
Unfortunately this is related to the flakiness in the slaves allocation, they get destroyed immediately after the worker has been provisioned.

**Comment by cachedout** [comment]
@v1v Interesting. Is there any GH issue filed that tracks this behavior? I don't think I've come across one before.

**Comment by cachedout** [comment]
@v1v Do I understand correctly that this is a generic problem which can affect any pipeline and is not just limited to the .NET Agent? If so, I feel like we should get an issue filed on it and start a discussion between stakeholders on how we might mitigate it.

**Comment by v1v** [comment]
> @v1v Do I understand correctly that this is a generic problem which can affect any pipeline and is not just limited to the .NET Agent? If so, I feel like we should get an issue filed on it and start a discussion between stakeholders on how we might mitigate it.

I forgot to mention, as we discussed this offline. this is a generic problem that can affect any pipeline. Already reported to the system owners

**Comment by gregkalapos** [comment]
There were a few failing tests, I fixed those, now it seems to be green. I think we can close this. Any objection?

**Comment by gregkalapos** [comment]
Closing now - these issues are solved.
