### ISSUE TITLE
[BUG] Missing Elastic.Apm.OpenTelemetry project

### ISSUE THREAD

**Issue by glucaci** [elastic/apm-agent-dotnet#1595]
On the master branch `Elastic.Apm.AspNetCore` has a reference to `Elastic.Apm.OpenTelemetry` but in the source control there is no project/files under `.src\Elastic.Apm.OpenTelemetry`

**Comment by glucaci** [comment]
If the intention was to have a separate project but in the end was developed under `.src\Elastic.Apm\OpenTelemetry\ElasticActivityListener.cs` than it's only a leftover.

**Comment by gregkalapos** [comment]
Ahh - thanks for reporting. Yes, you are right. 

I opened https://github.com/elastic/apm-agent-dotnet/pull/1597 to remove the reference.
