### ISSUE TITLE
Support Npgsql 6

### ISSUE THREAD

**Issue by ajuch** [elastic/apm-agent-dotnet#1602]
We started using Elastic Cloud recently and were quite happy with APM. But since upgrading Npgsql to 6.0.1, the Postgres spans disappeared. https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-auto-instrumentation.html states that NpgsqlCommand is only instrumented for Npgsql up to 5.*, so I suspect this is the reason.

**Describe the solution you'd like**
We'd like to see our database queries in Elastic Cloud even when we use Npgsql 6.*, so we hope that a newer version of the APM agent will bring this functionality back.

**Describe alternatives you've considered**
Maybe it's possible to use a DB independent way of monitoring SQL queries?

**Comment by gregkalapos** [comment]
Thanks for reporting!

There wasn't any specific reason to not support Npgsql v6 - it's just that it was new and we haven't had tests for it. https://github.com/elastic/apm-agent-dotnet/pull/1609 introduces support for `6.*`, and also adds test covering it. This will be in the next release.

**Comment by ajuch** [comment]
Great, thank you for your work!
