### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by CraigKennedy** [elastic/apm-agent-dotnet#161]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Possible to add info to all transactions? (i.e. Environment, CloudRegion, etc)
Also unclear how to get user info into request.  Authenticated user not showing up. Bug/My Bad Code/Incomplete Feature?

**Describe alternatives you've considered**

**Additional context**

**Comment by gregkalapos** [comment]
Hi @CraigKennedy, 

Regarding user info and authenticated user: that is unfortunately a missing feature. I opened an issue, I don't expect this to be very complicated. You can track the progress here: https://github.com/elastic/apm-agent-dotnet/issues/163

Regarding adding info to all transactions: would `Tags` help? You have to code a little bit for this, but I think it covers your use cases.

[Here is the documentation](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-transaction-tags) for that. With `Elastic.Apm.Agent.Tracer.CurrentTransaction` you get access to the current transaction and then as the documentation describes you can simply add strings to the transaction. 

Hope this helps.

**Comment by CraigKennedy** [comment]
@gregkalapos - Thanks for the reply.  Thanks for the user link for the user info.

RE: transaction tags, that is exactly what I'm looking for.  Is there a way to have the agent always include these without having to always set it on the current transaction?

**Comment by gregkalapos** [comment]
> Is there a way to have the agent always include these without having to always set it on the current transaction?

Currently unfortunately there isn't, but we are discussing this feature within the team: https://github.com/elastic/apm/issues/48 
The implementation on the server side is already in progress, no promises here, but I think very soon we can start adding this also to the .NET Agent.

**Comment by gregkalapos** [comment]
@CraigKennedy do you have any other question? If not I'd close this. You can track the progress on those features on the linked issues.
