### ISSUE TITLE
[BUG] Failed reading APM server info

### ISSUE THREAD

**Issue by SergeyKotyushkin** [elastic/apm-agent-dotnet#1624]
### APM Agent version
1.13.0 (the problem starts with 1.7.0)

### Environment

**Operating system and version:**
Windows 10

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
.NET 6

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
.NET 6

### Describe the bug
I installed the Elastic.Apm.AspNetCore package version 1.13.0. Added `app.UseElasticApm(configuration)` to the Startup class.
When I run application I see the exception in console logs:
```csharp
02/10/2022 10:39:50 [WRN]  Elastic.Apm - {PayloadSenderV2} Failed reading APM server info
Elastic.Apm.Libraries.Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: b. Path '', line 0, position 0.
   at Elastic.Apm.Libraries.Newtonsoft.Json.JsonTextReader.ParseValue()
   at Elastic.Apm.Libraries.Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Elastic.Apm.Libraries.Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Elastic.Apm.Libraries.Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Elastic.Apm.Libraries.Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Elastic.Apm.Libraries.Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Elastic.Apm.Libraries.Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Elastic.Apm.ServerInfo.ApmServerInfoProvider.FillApmServerInfo(IApmServerInfo apmServerInfo, IApmLogger logger, IConfiguration configuration, HttpClient httpClient)
```

I tried to investigate problem and checked the `Elastic.Apm.ServerInfo.ApmServerInfoProvider.FillApmServerInfo` method.
It sends request to Kibana by the ServerUrl. Then it tries to deserialize response and expects that the response is json. But it is not.
I captured request:
```http
GET http://kibana.foo:8200/ HTTP/1.1
Host: kibana.foo:8200
Metadata: true
User-Agent: apm-agent-dotnet/1.13.0+4b4c5d961bc37c0b9ff68bd3d5a3bbc337afdd97 (MyService develop) System.Net.Http/6.0.121.56705 .NET_6/6.0.1
```
and got response:
```http
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Date: Thu, 10 Feb 2022 07:39:50 GMT
Content-Length: 103

build_date:"2019-04-05T21:50:06Z"
build_sha:"1f7ad059a0bbf0174b90e07c80c0274d152f1155"
version:"7.0.0"
```

I think that the problem connects with the `Content-Type: text/plain` header. I wonder why a request sends without any `Content-Type` header.

Thanks in advance!

### To Reproduce

See the `Describe the bug` section.

#### Expected behavior
No exception on application start.

#### Actual behavior
Exception on application start.

**Comment by russcam** [comment]
Based on the captured request 

> GET http://kibana.mlg.ru:8200/ HTTP/1.1
> Host: kibana.mlg.ru:8200

and 

> It sends request to Kibana by the ServerUrl.

It sounds like the APM server URL is set to the Kibana endpoint, which is incorrect. [It should be set to the APM Server endpoint](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-server-url).

**Comment by SergeyKotyushkin** [comment]
@russcam, thanks for the reply

I think I was not accurate in my question. Excuse me. But I don't think that I use incorrect endpoint because when MyService app works I can see its data in APM. The problem is only on APM server info load. It finishes with error but then all APM functionality works well.

p.s. could you please edit your answer and replace both places with host name to `kibana.foo:8200` and after that delete your first comment revision?🙂 It was my mistake that I didn't obfuscare it.. I've noticed it only today and edited my original question text already too. Thanks

**Comment by SergeyKotyushkin** [comment]
@russcam,

I've done some research :)

I've set up the ApmServer locally and tried to retry this problem. The local ApmServer works without problems.
It shows that there are differences in the settings of the servers that provide the ApmServer.

In my first message we can see that the http request is sent without the Accept header. The Accept header tells to server in what format a client expects to get a response.
It is obvious that the servers can have different settings. It is not mandatory that every server is set to return "Content-Type: application/json" on a http request without Accept header. But [in the code](https://github.com/elastic/apm-agent-dotnet/blob/3d2674f1f88dd3c27ef863c8e2c5433015b5918a/src/Elastic.Apm/ServerInfo/ApmServerInfoProvider.cs#L31) we see that the response is mandatory be in json format, because json deserialization is used.

So, there is a requirement for a server to handle requests without the Accept header in one way. But it is not correct as I think.

Can I suggest to send "Accept: application/json" header with the http request that loads the ApmServerInfo? In this way the sending http request and handling response code will be agreed.

**Comment by russcam** [comment]
Thanks for following up @SergeyKotyushkin. [According to the APM server docs](https://www.elastic.co/guide/en/apm/guide/current/api-info.html#api-info), an Accept header should not be needed. There would be no harm in including one in the call though. Opened https://github.com/elastic/apm-agent-dotnet/pull/1773 to address.
