### ISSUE TITLE
[META 604] Implement `trace_continuation_strategy `

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-dotnet#1637]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F604)](https://github.com/elastic/apm/issues/604)

Spec issue: https://github.com/elastic/apm/issues/596

**Comment by gregkalapos** [comment]
Implemented in https://github.com/elastic/apm-agent-dotnet/pull/1739
