### ISSUE TITLE
Test failures in the CI 

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-dotnet#1644]
I've seen some test failures in the CI, I'm raising the issue for awareness.

<img width="2179" alt="image" src="https://user-images.githubusercontent.com/2871786/157011180-044dffec-c2f0-4781-9816-6356ad93f669.png">

https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/main/lastCompletedBuild/testReport/history/

Please let me know if you need some help.

Thanks

**Comment by cachedout** [comment]
Just an FYI that we are continuing to detect large number of failures in the main branch:

https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/main/lastCompletedBuild/testReport/

Please let us (@elastic/observablt-robots ) know if we can be of any assistance. Thanks!

**Comment by gregkalapos** [comment]
Green now - closing.
