### ISSUE TITLE
[BUG] Missing Retry after failing APM Requests

### ISSUE THREAD

**Issue by fuzolan** [elastic/apm-agent-dotnet#1652]
### APM Agent version
1.14.1

### Environment

.Net 6 on IIS 2019
Elastic Cloud APM Server 8.1 and with 7.17.1

### Describe the bug
There is a highly chance that after the APM Server went down (Maintenance or Plan change) the apm client is completely lost.
To repair this, the Apppool has to be recycled. After one failing transaction, there is no further errors in log to find. After multiple hours there is no further log entry (log level warning). 

Service with an old client 1.8.1 was right back on when the apm was ready again.

**Comment by gregkalapos** [comment]
Hi @fuzolan,

in `1.14.1` there is a [fix related to APM Server timeouts](https://github.com/elastic/apm-agent-dotnet/pull/1634) - that may be related to your issue. Now, `1.14.1` went out just a few hours ago - are you sure you are already on that version?

If so, could you maybe attach agent logs from the problem when this happens?

**Comment by fuzolan** [comment]
Thank you.  Had the wrong version.
