### ISSUE TITLE
Group by Route

### ISSUE THREAD

**Issue by bladefist** [elastic/apm-agent-dotnet#166]
We're using the pre-release and seeing that every request is being logged uniquely by it's route parameters, for example:

/user/profile/32
/user/profile/456

Where it would be more interesting to group these by:
/user/profile/{userid}

Is there anyway to do this currently, or is this something that just have to wait for a newer release?

Thanks!

**Comment by gregkalapos** [comment]
Hi @bladefist,

great to see you already use the preview! 

Unfortunately currently there is no way to do this. This is a missing feature. We already have an issue for it: https://github.com/elastic/apm-agent-dotnet/issues/84.

I think that covers exactly what you'd like to have - and we'll do it, we just haven't had a chance to implement it yet. 

Could you please verify that https://github.com/elastic/apm-agent-dotnet/issues/84 covers all what you need?

Thanks!

**Comment by bladefist** [comment]
@gregkalapos thanks for the response.  #84 looks like the same issue, I'll go subscribe to that. Thanks for all the hard work on this!
