### ISSUE TITLE
MysqlConnector Support

### ISSUE THREAD

**Issue by kg6zgj** [elastic/apm-agent-dotnet#1661]
Is your feature request related to a problem? Please describe.
All mysql queries are not being captured at the moment because my team is using MySqlConnector to connect to our database.

Describe the solution you'd like
Support for capturing spans in https://github.com/mysql-net/MySqlConnector

Describe alternatives you've considered
I started looking at what I could do to create a PR and I am still in the process of reading source to determine where to start.

Additional context
If I could get some general guidance over a zoom call perhaps I can assist in this effort.
[dotnet Agent]

**Comment by gregkalapos** [comment]
@kg6zgj have you looked at the profiler based agent? Docs [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-auto-instrumentation.html).

That may capture the underlaying database calls.
