### ISSUE TITLE
[META 621] Improve Granularity for SQL Databases

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#1664]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F621)](https://github.com/elastic/apm/issues/621)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F622)](https://github.com/elastic/apm/issues/622)

There are two parts to improving the granularity for SQL Databases:
- adding new fields to agent-server protocol, for now it's mostly to future-proof the captured data as we have to keep existing fields for compatibility with UI.
- capture values for those new fields on SQL Databases, which is actually providing better granularity to the end-user.

Each step can be completed independently, but this task will be considered complete when both parts are completed.

**First step : add new service fields**

  - Add and capture values for `span.context.service.target.type` and `span.context.service.target.name` for exit spans.
  - Infer from those new fields the value of `span.destination.service.resource` and keep sending it.
  - Add `service_target_*` fields to dropped spans metrics:  add `service_target_type` and `service_target_name` next to `destination_service_resource` in `transaction.dropped_spans_stats` array, the related metrics documents should include `span.service.target.type` and `span.service.target.name` fields.
  - Handle span compression with new fields (stop relying on `resource` internally)

**Second step : capture values for new fields**

**Comment by gregkalapos** [comment]
Implemented in https://github.com/elastic/apm-agent-dotnet/pull/1765
