### ISSUE TITLE
Kubernetes attachment

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-dotnet#1665]
- [x] Publish a docker image that contains the agent distribution, similar to what the Java agent is already doing (see [build](https://github.com/elastic/apm-agent-java/blob/3187b4fbbf349041f95080e49b194848b1c33098/.ci/release/Jenkinsfile#L245-L257) and the [observability/apm-agent-java](https://container-library.elastic.co/r/observability/apm-agent-java) image in our Docker registry)
- [x] Integrate with the webhook in APM Server (https://github.com/elastic/apm-server/issues/7386) to copy the agent from the image to a volume via an init container and add environment variables to attach the agent.

**Comment by gregkalapos** [comment]
Done - this was implemented in multiple PRs - all linked above.
