### ISSUE TITLE
apm-agent-dotnet unbale to see full trace

### ISSUE THREAD

**Issue by gsantosh-clgx** [elastic/apm-agent-dotnet#1669]
Am using aspnetfullframework packag and am unable to see entire services calls are not flown to APM. Am able to see only first service layer call is being recorded. These are the settings that i have used in start up

var agentComponents = ElasticApmModule.CreateAgentComponents();
            Agent.Setup(agentComponents);

and only following gets recorded

![image](https://user-images.githubusercontent.com/49071398/160653848-2a2fa36d-ddea-4333-ad0b-d7ec06e9b725.png)

I dont see next level of calls being recorded . Please help me

**Comment by gregkalapos** [comment]
Hi @gsantosh-clgx,

I think [this entry on discuss](https://discuss.elastic.co/t/net-apm-method-profiling/259015) is similar to your situation, that explains more on this.

**Comment by gsantosh-clgx** [comment]
Hello **Gergely Kalapos**,

Thank you so much for the quick response. What i understand is "The .NET Agent does not have a feature similar to what is described for Java under the [sampling-based profiler 13](https://www.elastic.co/guide/en/apm/agent/java/current/java-method-monitoring.html#_sampling_based_profiler)". 

This post is dated for Jan-2021, may i know is this still the same case for .NET agent (or) its still under implementation?
