### ISSUE TITLE
[BUG] .Net 6 Worker does not exit when no transaction occurred

### ISSUE THREAD

**Issue by chwebdude** [elastic/apm-agent-dotnet#1672]
### APM Agent version
1.14.1

### Environment

**Operating system and version:**

Windows 10, 20H2, Build 19042.1586

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100):

.Net 6.0.1

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net6.0

### Describe the bug

The application does does not exit correctly when no transaction occured. When typing `Ctrl+C` send the shutdown signal the application keeps running. According to the Elastic APM log it is trying to cancel the `PayloadSenderV2`. See the 
[Full Log.txt](https://github.com/elastic/apm-agent-dotnet/files/8397151/Full.Log.txt). When the application is emitting any transactions the application stops correctly.

### To Reproduce

1. Simply implement a worker like this:

```csharp
using Elastic.Apm.Api;
using Elastic.Apm.Extensions.Hosting;

IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .UseElasticApm()
    .Build();

await host.RunAsync();


public class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            //var t = Elastic.Apm.Agent.Tracer.StartTransaction("Test", ApiConstants.ActionExec); // Uncomment to make it work
            _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            await Task.Delay(1000, stoppingToken);
            //t.End(); // Uncomment to make it work
        }
    }
}
```

2. Start the application
3. Type `Ctrl+C` to send the shutdown signal

When the two lines for the manual transaction are uncommented, the application would stop correctly.

#### Expected behavior

The application should exit with code `0` since nothing has been done. It should only collect metrics.

#### Actual behavior

The process is stuck. When typing `Ctrl+C` again the process is killed with return code `-1073741510`.
When running as a Windows Service I even discovered cases where the service stops, but the application keeps running and the CPU usuage bumps up to 50-80%. But i have not investigated there if there is also a correlation with the transaction.

**Comment by gregkalapos** [comment]
Thanks for reporting!

I opened https://github.com/elastic/apm-agent-dotnet/pull/1703 which fixes this.
