### ISSUE TITLE
[BUG] BreakdownMetricsProvider hits internal limit of 1000 items with more than 1000 transaction within [MetricsInterval] seconds

### ISSUE THREAD

**Issue by fschoening** [elastic/apm-agent-dotnet#1678]
### APM Agent version
1.13.0

### Environment

**Operating system and version:**
Windows 10 Enterprise, v21H2

**.NET Framework/Core name and version**
.NET 4.6.1, NET Core 3.1.100

**Application Target Framework(s)**
net461, netcoreapp3.1

### Describe the bug
Exception _The limit of 1000 metricsets has been reached, no new metricsets will be created until the current set is sent to APM Server._ is thrown frequently when transactions end, even with few distinct `SpanTimerKey` combinations in internal Spans.

Looking at class `Elastic.Apm.Metrics.MetricsCollector` metrics are collected on a fixed interval configured by setting [`MetricsInterval`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-metrics-interval) (defaults to 30s). In this case it does so by calling `Elastic.Apm.Metrics.MetricsProvider.BreakdownMetricsProvider.GetSamples()` that returns the value of field `List<MetricSet> _itemsToSend`.

Span timings on the transaction are aggregated on the field of class `Elastic.Apm.Model.Transaction`:

```internal readonly ConcurrentDictionary<SpanTimerKey, SpanTimer> SpanTimings = new();```

In the course of a transaction, spans are thus aggregated from the `Elastic.Apm.Model.Span` with the dictionary key composed by span + span type:

```
if (_enclosingTransaction.SpanTimings.ContainsKey(new SpanTimerKey(Type, Subtype)))
  _enclosingTransaction.SpanTimings[new SpanTimerKey(Type, Subtype)].IncrementTimer(SelfDuration);
else
  _enclosingTransaction.SpanTimings.TryAdd(new SpanTimerKey(Type, Subtype), new SpanTimer(SelfDuration));
```

When the transaction ends, `_breakdownMetricsProvider?.CaptureTransaction(this);` is called, that iterates the span timings in the following manner (`Elastic.Apm.Metrics.MetricsProvider.BreakdownMetricsProvider.CaptureTransaction(...)`):

```
foreach (var item in transaction.SpanTimings)
{
  var metricSet =
    new MetricSet(timestampNow,
      new List<MetricSample>
      {
        new(SpanSelfTimeCount, item.Value.Count),
        new(SpanSelfTimeSumUs, item.Value.TotalDuration * 1000)
      })
    {
      Span = new SpanInfo { Type = item.Key.Type, SubType = item.Key.SubType },
      Transaction = new TransactionInfo { Name = transaction.Name, Type = transaction.Type }
    };

  if (_itemsToSend.Count < MetricLimit)
    _itemsToSend.Add(metricSet);
  else
  {
    if (_loggedWarning) continue;

    _logger.Warning()
      ?.Log(
        "The limit of {MetricLimit} metricsets has been reached, no new metricsets will be created until "
        + "the current set is sent to APM Server.",
        MetricLimit);
    _loggedWarning = true;
  }
}
```

From this it should follow that the `_itemsToSend` buffer can fill up very quickly since all SpanTimings are now added to the same list (no grouping, just a growing list). I suspect this is not intended, but rather that the hardcoded limit of 1000 metricsets was meant to limit *groups* of metric sets and not individual ones.

I managed to produce this screenshot that shows 2 MetricSets with the same "SpanTimerKey" which should illustrate that exception would be thrown even just completing 1000 transactions with 1 span each in the time frame (or even 1000 transactions with each 0 spans since the transaction itself also has an internal self-timer with key "app,null").

![image](https://user-images.githubusercontent.com/79154/162769772-40e81c5f-b676-4ce8-af4d-575b7fb07db0.png)

Or am I on the wrong track?
Thanks.

/Frederik

**Comment by gregkalapos** [comment]
Thanks for reporting this! 

https://github.com/elastic/apm-agent-dotnet/pull/1816 is merged and fixes the problem. That PR adds grouping and handles the descibed scenario ("completing 1000 transactions with 1 span each in the time frame") with 2 `MetricSet` - one for the transaction and one for the span, each grouping the transactions/spans with the same key.

I'm closing this now - the fix will be included in the next release.

Ps: sorry that this took so long.
