### ISSUE TITLE
[BUG] Middleware usage throws NullReferenceException 

### ISSUE THREAD

**Issue by hrai** [elastic/apm-agent-dotnet#1681]
### APM Agent version
1.14.1

### Environment

**Operating system and version:** Windows 10

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) : .NET Core 6

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1): net6.0

### Describe the bug
I have the following setup:

- Custom middleware 
- .NET Core MVC without Areas (only controller and action)

When the code calls `_next(context)` in the middleware's Invoke(), the application throws `NullReferenceException`

![image](https://user-images.githubusercontent.com/4055444/163920363-20d7fb35-fa4a-4e09-ac54-1491732bd084.png)

### To Reproduce

Here's the test that I wrote that shows exactly where the bug is.

```
        [Fact]
        public void Test()
        {
            var data = new Dictionary<string, object>() {
                {"controller", "Home" },
                {"area",null },
                {"action","Index" }
            };

            Should.NotThrow(() =>
            {
                GetNameFromRouteContext(data);
            });
        }
```

#### Expected behavior
The code should not throw exception.

#### Actual behavior
The code throws exception.

**Comment by gregkalapos** [comment]
Thans for reporting @hrai.

I opened https://github.com/elastic/apm-agent-dotnet/pull/1683 to fix it.

Also thanks for the nice reproducer.

**Comment by gregkalapos** [comment]
Fixed in https://github.com/elastic/apm-agent-dotnet/pull/1683 - fix will be included in the next release.
