### ISSUE TITLE
CaptureBody "errors" and 401 for Kerberos handshake

### ISSUE THREAD

**Issue by rmsryu** [elastic/apm-agent-dotnet#1717]
**Describe the bug**

Current middleware treats all status code response greater or equal than 400 equally as an error.

https://github.com/elastic/apm-agent-dotnet/blob/20fea7888fd3a044e13fb34c3e657d26502a6911/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L52

This is correct definition however when it comes to trace secured application in this case using Kerberos authentication, the initial client  handshake it always return 401 regardless of the result of the request.

Below is an example of the handshake process:
```
Fri May 27 14:24:08 IST 2022: DEBUG: http-outgoing >> 
GET /mysecure/api HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Length: 0
Host: myserver
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.2 (Java/16.0.1)


Fri May 27 14:24:08 IST 2022: DEBUG: http-incoming << 
HTTP/1.1 401 Unauthorized
Content-Length: 0
Date: Fri, 27 May 2022 13:24:08 GMT
Server: Kestrel
Www-Authenticate: Negotiate
```

We would like to set `CaptureBody` to monitor only errors, but excluding the 401's.  Is there any alternative / option to allow this? Alternatively consider a configuration setting to allow filter the Status codes similar to `CaptureBodyContentTypes` configuration option.

**Comment by gregkalapos** [comment]
The agent offers an API to register filters. Docs [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#filter-api). I think that could be utilized here, with something like this (you need to tweak the if block):

```
Agent.AddFilter((ITransaction transaction) =>
{
	// If the request marches the Kerberos authentication URL, we remove the request body.
	if (transaction.Context.Request.Url.Full == "[Kerberos authentication URL]" && transaction.Context.Response.StatusCode == 401)
		transaction.Context.Request.Body = null;
	return transaction;
});
```

Within the filter you can change events before they get sent to APM Server - in this example we remove the request body. Unfortunately you still pay the overhead of capturing it, but at least it won't be sent to APM Server and it won't reach Elasticsearch, so you save storage.

If you return `null` in the filter, it'll completely drop the event.

**Comment by rmsryu** [comment]
Thanks @gregkalapos, I'll test this option. We still want to log the event in APM, but keeping the body as [REDACTED] instead of sending it.

We are only interested in the body content for server errors 5XX and validation problems 400. 

On 401 and 403 response we don't really care about the body and it should be kept as [REDACTED]. The rationale for this is that we can only store PII data in APM if there is a justification for that, such us troubleshooting.

Best

**Comment by rmsryu** [comment]
@gregkalapos thank you very much for pointing us in the right direction. We can achieve what we want using the Agent.Filter.

Regards
