### ISSUE TITLE
MissingMethodException after upgrading to 1.16.1

### ISSUE THREAD

**Issue by Matiszak** [elastic/apm-agent-dotnet#1741]
My AspNetCore project is compiled against ElasticApm 1.14.1. One of the dependent libraries uses 1.16.1 so the resulting executable uses highest version - 1.16.1 by default.

Unfortunately this causes exception which fails every request.

This breaking change show never happen when minor version is upgraded. Every non-major upgrade should retain every previous signature of methods (from consumer perspective) to avoid such error.

I expect previous definition of `StartTransactionAsync` to be put back (while keeping the current updated signature). This is changed line which I think caused this issue: https://github.com/gregkalapos/apm-agent-dotnet/blame/7076a72cad0a17a42cdbb78de7faa8228115a026/src/Elastic.Apm/Api/ITracer.cs#L275

```
2022-06-22 Error|Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ReportApplicationError|Connection id "XXXXXXX", Request id "XXXXXXX:00000002": An unhandled exception was thrown by the application.|System.MissingMethodException: Method not found: 'Elastic.Apm.Api.ITransaction Elastic.Apm.Api.ITracer.StartTransaction(System.String, System.String, Elastic.Apm.Api.DistributedTracingData, Boolean)'.
23
   at Elastic.Apm.AspNetCore.WebRequestTransactionCreator.StartTransactionAsync(HttpContext context, IApmLogger logger, ITracer tracer, IConfiguration configuration)
22
   at Elastic.Apm.AspNetCore.ApmMiddleware.InvokeAsync(HttpContext context)
21
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by gregkalapos** [comment]
Right now, the only solution will be to have the packages on the same version.

I opened https://github.com/elastic/apm-agent-dotnet/issues/1744 to discuss this issue in general.

**Comment by nagarciah** [comment]
Same problem here: we have a CI/CD pipeline to do automated upgrades, therefore we rely on semantic versioning and we upgrade (unattended) only minor and patch versions to avoid breaking changes (by semver's definition, minor and patch versions support backward compatibility), however after upgrading from 1.15.0 to 1.16.1 (minor and patch) we got this same problem. Is your versioning schema not following semantic versioning or is it just a bug? 
I would like to know how you interpret semver, so I can avoid breaking upgrades form this library. Thanks

**Comment by tinonetic** [comment]
> Same problem here: we have a CI/CD pipeline to do automated upgrades, therefore we rely on semantic versioning and we upgrade (unattended) only minor and patch versions to avoid breaking changes (by semver's definition, minor and patch versions support backward compatibility), however after upgrading from 1.15.0 to 1.16.1 (minor and patch) we got this same problem. Is your versioning schema not following semantic versioning or is it just a bug? I would like to know how you interpret semver, so I can avoid breaking upgrades form this library. Thanks

Fully agree. From convention it should be a non-breaking change if it's not a major version change.

We upgraded with that general convention in mind
