### ISSUE TITLE
[BUG] Can't parse container ID when running on AWS ECS/Fargate

### ISSUE THREAD

**Issue by fruffin** [elastic/apm-agent-dotnet#1779]
### APM Agent version
Elastic.Apm.NetCoreAll 1.16.1

### Environment

**Operating system and version:**
Debian 11 on AWS ECS/Fargate

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) :
ASP.Net 6

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1):
net6.0

### Describe the bug
When running on a linux container on Amazon ECS/Fargate, APM fails to parse the container ID correctly due to AWS very specific cgroup format.

When querying `/proc/self/cgroup` on ECS/Fargate containers, each line looks something like this:
`1:name=systemd:/ecs/03752a671e744971a862edcee6195646/03752a671e744971a862edcee6195646-4015103728`

The container ID is whatever is after the last forward slash but doesn't match the Regex expected by the `SystemInfoHelper` class of `Elastic.Apm`. This causes the library to think it is not running in a container, causing issues gathering CPU/memory metrics, which then cause errors in Kibana: `search_phase_execution_exception: [script_exception] Reason: runtime error (500)
URL`

### To Reproduce

1. Create a new asp.net core application
2. Add Elastic AP
3. Run on AWS ECS/Fargate

#### Expected behavior
The container ID should be correctly parsed so that metrics can be collected.

#### Actual behavior
This causes the library to think it is not running in a container, causing issues gathering CPU/memory metrics, which then cause errors in Kibana: `search_phase_execution_exception: [script_exception] Reason: runtime error (500)
URL`

Pull request to fix this issue coming shortly.

**Comment by fruffin** [comment]
@gregkalapos, I've just noticed this has been flagged as `good first issue` and just wanted to point out I already have a pending pull request for this. The only reason it is failing verification right now is that I don't have permission to run CI (which is fair enough).
So, as far as I know, it is good to go.

Thanks

**Comment by fruffin** [comment]
After upgrading my Elastic Cloud deployment to 8.4, I can confirm that the error I was seeing in Kibana is no longer occurring, but the change I made in #1780 is still required for it to work correctly.
Please advise on the next steps, as I would rather not have to fork this repository to maintain this fix as we go to production with Elastic.
Thanks

**Comment by z1c0** [comment]
Fixed with #1780
