### ISSUE TITLE
[BUG] DefaultValues.ExitSpanMinDurationInMilliseconds has incorrect value

### ISSUE THREAD

**Issue by octocat-mona** [elastic/apm-agent-dotnet#1789]
### APM Agent version
1.16.1

### Environment
N/A

### Describe the bug
According to the [documentation](https://www.elastic.co/guide/en/apm/agent/dotnet/master/config-core.html#config-exit-span-min-duration) `ExitSpanMinDuration` has a default value of `1ms`.

However the constant `DefaultValues.ExitSpanMinDurationInMilliseconds` has a value of `1000` instead of `1`: https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Config/ConfigConsts.cs#L30-L31

**Comment by z1c0** [comment]
According to the [specification](https://github.com/elastic/apm-agent-java/blob/198cfac574fcbaae2d9a374702637bbcf44c46f8/apm-agent-core/src/main/java/co/elastic/apm/agent/configuration/SpanConfiguration.java#L68) neither `1` nor `1000` is correct. The actual default value is supposed to be `0ms`.
So both the code and the documentation need to be fixed here.
