### ISSUE TITLE
Instrument implementations of base ADO.NET interfaces

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1791]
Currently we have instrumentation for specific database [libraries](https://github.com/elastic/apm-agent-dotnet/tree/main/src/Elastic.Apm.Profiler.Managed/Integrations/AdoNet).

All these instrumentation target specific types and methods. In case a user uses a database library which is not in the list above, the agent won't instrument it, therefore those calls aren't captured.

A common way these database libraries work is that they implement the base [ADO.NET interfaces](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/). If we'd target these base classes and interfaces (or the implementations of it) for instrumentation we could have support for all database libraries which are based on ADO.NET, including (somewhat) popular libraries, but custom, in-house implementations as well.

Things to do:
- [ ] Discuss if we want to do this
- [ ] Implement instrumentation for all implementations of the specific ADO.NET types/methods.

**Comment by siying-soo** [comment]
Hi @gregkalapos do we still plan to do this? The customer met with Ash last month and this issue was brought up. We're sending a bi-weekly update to Ash about progress of the case documented in https://github.com/elastic/sdh-apm/issues/695

**Comment by stevejgordon** [comment]
Closing as not planned
