### ISSUE TITLE
Log reason for transaction to end unsampled

### ISSUE THREAD

**Issue by ornic** [elastic/apm-agent-dotnet#1794]
It would be much help to separate transactions dropped from sampling for different reasons.

**Is your feature request related to a problem? Please describe.**
Yes. We have an instance of Framework 4,8.2 app that connected to company kibana server.

And all requests from our outsource partners marked as unsampled, we got tons of `{Transaction} Dropping unsampled transaction - unsampled transactions won't be sent on APM Server v8+. TransactionId: ...` messages in logs. And in APM there is not a single transaction, but stable statistics for time spent in spans.

But when I try to make those same requests from my browser / insomnia - they all appear perfectly as transactions in kibana with pretty spans of internal api / db requests (the single peak in the picture after service redeploy).

![image](https://user-images.githubusercontent.com/3350070/185641230-f5e75309-cbb7-467a-a31b-8acd2f4db580.png)

**Describe the solution you'd like**
Option in settings to produce Trace level logs: transaction with id=... was dropped from sampling due to head-based sampling rate settings. 
Option in settings to produce Debug level logs: transaction with id=... was dropped from sampling due to `some other reason`.

**Describe alternatives you've considered**
Gooooooogling. Got me nothing, unfortunately

**Comment by ornic** [comment]
In our case the reason for unsampling was incoming net5 W3C header, that we [started to ignore](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-supportability.html#config-trace-context-ignore-sampled-false).

**Comment by gregkalapos** [comment]
Thanks for reporting this @ornic.

I think I understand the overall issue and the suggestion here, but I'd have one question to think this through completely: where do you expect to see the reason for not sampling a transaction?

In Kibana you don't see it, but you'll see it in the agent logs. [Here we log this info](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Model/Transaction.cs#L307-L323) when the transaction is created. But for that you'll need to look into the agent logs.

Changing logs in the agent is fairly easy and if that could be improved, we can definitely do it quickly. On the other hand, having a reason for not sampling a transaction in Kibana would require more work (that involves APM Server and Kibana as well, not only the agent).

**Comment by ornic** [comment]
> where do you expect to see the reason for not sampling a transaction?

Ideally: inside the log entry about dropping unsampled transaction that is logged on agent side.

> Currently, in Kibana you don't see it, but you'll see it in the agent logs. [Here we log this info](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Model/Transaction.cs#L307-L323) when the transaction is created.

Am I understanding this right: https://www.w3.org/TR/trace-context/#sampled-flag is logged now in the `isSamplingFromDistributedTracingData` branch in the source above?

**Comment by gregkalapos** [comment]
> > where do you expect to see the reason for not sampling a transaction?
> 
> Ideally: inside the log entry about dropping unsampled transaction that is logged on agent side.

That's already the case, but we only print it on trace level. Now that I think about it a bit, maybe it'd be better to print it on info level - the default is error, so either way, you'll need to increase the log level in order to see it. Docs on log level: https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-supportability.html#config-log-level 
 
> > Currently, in Kibana you don't see it, but you'll see it in the agent logs. [Here we log this info](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Model/Transaction.cs#L307-L323) when the transaction is created.
> 
> Am I understanding this right: https://www.w3.org/TR/trace-context/#sampled-flag is logged now in the `isSamplingFromDistributedTracingData` branch in the source above?

Correct - it'll print the whole traceparent header and the tracestate header. The traceparent header is printed in a parsed form. That code [can be seen here](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm/Api/DistributedTracingData.cs#L57-L63).

**Comment by ornic** [comment]
Thank you! :) I suppose I gave up too early in my quest for the answer.

**Comment by gregkalapos** [comment]
Thanks for your answers @ornic.

In this case I think we are good here and the logging in the agent should be sufficient. I close this issue now - if there is anything left, feel free to reopen.
