### ISSUE TITLE
Agent.Setup is never called in non ASP.NET Core scenarios

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#180]
E.g. when only the public API is used `Agent.Setup()` is never called.

Until this method is not called, only a few things are initialized. E.g. the logger won't read the environment variables and the log level is ignored.

We should decide if
- the agent should work with 0 config, so without explicitly calling `Agent.Setup()` we initialize it during the first usage (whatever 'first usage' means) - I personally would prefer this one.
- or we document this and ask people to call it 😞

**Comment by gregkalapos** [comment]
I take this. cc @SergeyKleyman

**Comment by SergeyKleyman** [comment]
I did some refactoring in `AgentComponents` as part of work on #308 and #245 so it might be easier to wait with this one to avoid complicated merges.

**Comment by gregkalapos** [comment]
Ok, I can wait.

Do you maybe have a branch to take a look at it? I'm already thinking about this stuff and I'd be interested.

**Comment by SergeyKleyman** [comment]
NP - I'll make draft PR today.

**Comment by SergeyKleyman** [comment]
https://github.com/elastic/apm-agent-dotnet/pull/391

**Comment by gregkalapos** [comment]
This works now. [Here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Agent.cs#L64) we instantiate a new `AgentComponent` in case the current one is `null`. And [that defaults](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/AgentComponents.cs#L28) to an `EnvironmentConfigurationReader`. 

Tried it, it works.
