### ISSUE TITLE
Report kubernetes system metadata

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-agent-dotnet#181]
per elastic/apm#21

**Comment by axw** [comment]
This logic we should follow is described in https://github.com/elastic/apm/blob/master/docs/agent-development.md#containerkubernetes-metadata

**Comment by gregkalapos** [comment]
`/proc/self/cgroup` is not yet parsed. https://github.com/elastic/apm-agent-dotnet/pull/741#pullrequestreview-402115843

**Comment by gregkalapos** [comment]
_zube 😠_

**Comment by gregkalapos** [comment]
Is this me against @graphaelli and zube? 🤣 

So... this issue is almost done - @vhatsura made big progress on it - we already read and send environment variables. But `/proc/self/cgroup` is not yet parsed - so let's keep it open for that missing part.

**Comment by peterdkdp** [comment]
Hi,

I'm still trying to understand what this and all related issues are about, but does this issue have anything to do with the integration between APM and logs? Or is this a complete different topic?

The issue I'm having is, when a dotnet application runs on kubernetes I see the container.id in the metadata.
When I choose the action "Pod Logs" or "Pod Metrics" it sends the container id to be used with kubernetes.pod.uid, which doesn't work of course.
I tested this with java and nodejs applications in APM and for them it uses the correct kubernetes.pod.uid.

So, I was wondering if this is an elastic/kibana bug or does this have to do with the agent.
For the latter, I can create a new issue of this is off topic of course.

Thanks,
Peter

**Comment by SergeyKleyman** [comment]
I can confirm that indeed `container.id` is sent as `kubernetes.pod.uid` as well (using agent 1.6.1). See https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/PR-935/1/artifact/target/diag-Elastic.Apm.DockerTests.csproj.log:
```
systemInfo.Container.Id: 2227daf62df6694645fee5df53c1f91271546a9560e8600a525690ae252b7f63
systemInfo.Kubernetes.Pod.Uid: 2227daf62df6694645fee5df53c1f91271546a9560e8600a525690ae252b7f63
```

```
systemInfo.Container.Id: 15aa6e53-b09a-40c7-8558-c6c31e36c88a
systemInfo.Kubernetes.Pod.Uid: 15aa6e53-b09a-40c7-8558-c6c31e36c88a
```

**Comment by gregkalapos** [comment]
`cgroup` is not also parsed - this is complete.
