### ISSUE TITLE
windows auth support for agents to use with our reverse proxy

### ISSUE THREAD

**Issue by andrisarkameru** [elastic/apm-agent-dotnet#1825]
We would like to be able to enable APM agent to use the Windows Credentials that the service is running from to be sent to our reverse proxy to centralise authentication with elastic in one place instead of distributing secrets/api keys to every server.

**Is your feature request related to a problem? Please describe.**

We are using windows credential authentication (AD) for requests inside our org for services and users. We would like to use reverse proxy for the apm agent so that the agent would connect with reverse-proxy using windows credentials, and then the reverse proxy would handle connecting to the APM server integration using the API key or the secret. 

**Describe the solution you'd like**
Ideally it would be just a simple config flag next to the ServerCert and ServerToken that would create HttpClientHandler with UseDefaultCredentials  set to true in the BackendComUtils.CreateHttpClientHandler method.

I'd like to contribute but will need some help with all the formalities like doks and proper procedures.

**Describe alternatives you've considered**
Currently we're able to use the API key and secret methods, but that means that we need to distribute the secrets to different servers that we could skip if this issue is resolved.

**Comment by z1c0** [comment]
@andrisarkameru I will bring this up in our next planning meeting and let you know if this is something that might make it into the product.
Should we go forward with this, of course, any contribution and help from your side are highly appreciated. Thanks!

**Comment by gregkalapos** [comment]
There are some related items already in the repo, which'd touch basically the same code. 

Linking here, to potentially think about those as well:
- https://github.com/elastic/apm-agent-dotnet/issues/782
- https://github.com/elastic/apm-agent-dotnet/pull/1629

**Comment by andrisarkameru** [comment]
Thanks for the replies, looking forward for your planning meeting. 

Irregardless on the outcome I've done some changes, I hope that that covers it and hope that your decision will be positive. 

Not sure about that Contributor agreement service - i've signed the agreement (twice already - once before making pull req, second time after the fact) but the bot says I haven't...

**Comment by z1c0** [comment]
Hi @andrisarkameru,

thanks for your PR - we'll have a look soon.

Regarding the CLA problem: perhaps you were using different email addresses for signing the CLA and authoring your PR, is that possible?
What you can quickly do to check this, is adding `.patch` to the URL of one of your commits (e.g. like [this](https://github.com/elastic/apm-agent-dotnet/commit/ae32a209b3ef1e21d94e888bd6d7e66a5da3ae24.patch)). This will reveal the email address used for the commit/PR. Please make sure to use the same email address for signing the CLA.

Thanks!

**Comment by andrisarkameru** [comment]
Thanks, @z1c0. It seems that I was using different email address for the commit. Now I have submitted another CLA with the correct email address. Will the CLA service trigger by itself, or it needs some poking?

**Comment by z1c0** [comment]
Thanks, @andrisarkameru - I triggered your PR build again and expect the CLA check to pass now.
However FYI, we are currently working on an issue in our CI and the PR build will most likely fail for unrelated reasons.

**Comment by z1c0** [comment]
Implemented in #1832 🎉
