### ISSUE TITLE
Replace integration tests (new smoke tests against real APM server)

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1830]
Follow up from: https://github.com/elastic/apm-agent-dotnet/pull/1826 

https://github.com/elastic/apm-agent-dotnet/pull/1826 removed the `integration tests` from the pipeline - that means after that PR there is no test in the .NET APM Agent pipeline to test against a real APM Server.

My overall take on it: https://github.com/elastic/apm-agent-dotnet/pull/1826#issuecomment-1255988572
And great suggestion on how to replace these tests: https://github.com/elastic/apm-agent-dotnet/pull/1826#issuecomment-1256013108

Tasks
- [ ] Discuss how to proceed. It seems not everyone thinks the original integration tests were useful. First let's discuss if we want to replace those at all. If yes, then:
- [ ] Implement new tests based on https://github.com/elastic/apm-agent-dotnet/pull/1826#issuecomment-1256013108

**Comment by stevejgordon** [comment]
Closing as unplanned
