### ISSUE TITLE
Publish a 32bit version of the profiler 

### ISSUE THREAD

**Issue by izmaxxsun** [elastic/apm-agent-dotnet#1866]
**Is your feature request related to a problem? Please describe.**
The .NET Profiler auto instrumentation does not work for a 32-bit application that uses .NET Framework 4.7.2. This was discovered troubleshooting in the Windows Event log which showed the profiler was unable to load with HRESULT: 0x800700c1.

**Describe the solution you'd like**
Provide a 32-bit version of the Elastic profiler

**Describe alternatives you've considered**
Can force the .NET application to run in 64-bit mode and temporarily see the profiler sending APM data, however the .NET application eventually crashes so unable to use this as a workaround.  Don't have access to update the .NET app itself.

**Additional context**
From the Windows Application Log:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/100947826/195163510-ee4e8a40-15c8-4f66-8c64-412b013e4e08.png">

**Comment by Goraff** [comment]
Hello @gregkalapos can you please let me / the SA Team know if there has been any update or progress on this at this time? We have a fairly large opportunity that is at risk because a hard requirement from them is a 32-bit version of Elastic profiler. An update as soon as possible would be greatly appreciated.

**Comment by Goraff** [comment]
Thank you very much for putting that on the agenda. If possible can you please keep me posted? Slack is preferred, but if we need to keep all of our communications in here I'll just leave this open in a tab.

**Comment by Mpdreamz** [comment]
We discussed this and decided to stick to our decision to not support 32bit profiling for now. See #2037. 

Although windows 10 and up dropped 32bit builds of itself too it can still run 32bit applications. 

We expect this to become increasingly rare however and supporting this scenario would open us up to a whole suite of new maintenance tasks (tests/ci environments). 

We'll continue to monitor interest and might re-evaluate this decision in the future. 

Thanks for raising this @izmaxxsun and @Goraff :+1:
