### ISSUE TITLE
SqlClientDiagnosticListener - change how we measure duration

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1869]
[Reported via discuss](https://discuss.elastic.co/t/mssql-span-durations-inaccurate-when-sourced-from-sqlclientdiagnosticlistener/316225)

- Currently we use `Statistics.ExecutionTime` in `SqlClientDiagnosticListener` to get the duration of the given span for a given sql call.
- This value seems to be an aggregated value of multiple statements - I don't fully understand how it's aggregated yet, but as it seems it's not a 1-1 mapping to spans we generate. Maybe this part needs to be researched and understood a little bit better.

Suggestion for the fix:
- Let's just rely on the internal timing of our `Span` type. So instead of getting the duration via the diagnostic source listener, we can just measure it as we do for spans by default.

_If someone picks this up: please also try to add a test for this._

**Comment by bertvan** [comment]
From Discuss:

> Note this doesn't affect the EFCore diagnostics listener, as EFCore libraries are timing each query with a stopwatch internally and do not use the statistics from the sql client. Should we be doing the same in SqlClientDiagnosticListener?

Does this mean only .NET Framework is affected?

**Comment by gregkalapos** [comment]
> From Discuss:
> 
> > Note this doesn't affect the EFCore diagnostics listener, as EFCore libraries are timing each query with a stopwatch internally and do not use the statistics from the sql client. Should we be doing the same in SqlClientDiagnosticListener?
> 
> Does this mean only .NET Framework is affected?

No, I think it's the same regardless of the target framework. What you quoted talks about a different thing: if an app uses MSSql via Entity Framework Core, then we don't have the problem described here, because our EF Core listener measures the duration differently.

But once SqlClient is used directly, then we have the issue, regardless of the framework.

**Comment by bertvan** [comment]
Hi, I'm having a look at the fix this week. 

As to why it's aggregated: https://learn.microsoft.com/en-us/dotnet/framework/data/adonet/sql/provider-statistics-for-sql-server

> Returns the cumulative amount of time (in milliseconds) that the provider has spent processing once statistics have been enabled, including the time spent waiting for replies from the server as well as the time spent executing code in the provider itself.

**Comment by bertvan** [comment]
@gregkalapos as for

> If someone picks this up: please also try to add a test for this.

By checking that no explicit duration was passed to the Span?

**Comment by gregkalapos** [comment]
> @gregkalapos as for
> 
> > If someone picks this up: please also try to add a test for this.
> 
> By checking that no explicit duration was passed to the Span?

I don't have a complete plan about this, but my thinking was this: according to [the linked discuss entry](https://discuss.elastic.co/t/mssql-span-durations-inaccurate-when-sourced-from-sqlclientdiagnosticlistener/316225), you can construct a reproducer where the span duration was very obviously wrong.

The report says:
> For example if I have a 5 queries taking 100ms each, the span durations are 100 + 200 + 300 + 400 + 500 for a total of 1500ms when only 500ms have passed.

and

>  Early in the transaction the span duration of sql queries is correct, but then drifts and becomes inaccurate. At the end we see an update query which we have recorded on the stopwatch taking 4ms, and SqlClientDiagnosticListener has recorded it taking 102ms.

So if I understand this correctly, we could create a test where we run a single sql query a lot (let's say 100 time (not sure 100 is right, we need to check, the point is to make the aggregation of the durations very obvious)) - and then run it once again. We could measure the last call by stopwatch and compare that to the duration of the span which was captured by the agent. Currently the duration will be orders of magnitudes longer than what the stopwatch measures (due to the aggregation) - so we'd define a threshold (to make the test stable) and only accept span duration for the N+1th call within that threshold. This will clearly fail with the current code, and then not fail when the code is fixed.

**Comment by bertvan** [comment]
Ok, I reproduced locally with a query like `SELECT getdate();WAITFOR DELAY '00:00:01.000';` which showed the issue nicely.
I'll setup something along those lines, with a shorter delay.

**Comment by gregkalapos** [comment]
Sounds good.

Tests [live here](https://github.com/elastic/apm-agent-dotnet/tree/main/test/Elastic.Apm.SqlClient.Tests), you can follow those tests. All run against a docker setup - it boots up a real SQLServer and you can run queries against it.
