### ISSUE TITLE
[BUG] Cannot correlate 2 distributed OpenTelemetry activity series into a same APM trace

### ISSUE THREAD

**Issue by kuanpak** [elastic/apm-agent-dotnet#1881]
### APM Agent version
The version of the `Elastic.Apm` nuget package used: 1.18

### Environment

**Operating system and version: Windows 11

**.NET Framework/Core name and version** (e.g. .NET 4.6.1, NET Core 3.1.100) : .NET 6

**Application Target Framework(s)** (e.g. net461, netcoreapp3.1): net6.0

### Describe the bug
Cannot correlate 2 distributed OpenTelemetry activity series into a same APM trace when the first transaction was created via ElasticActivityListenser.

### To Reproduce

1. Use ElasticApm:EnableOpenTelemetryBridge = true
2. Call ActivitySource.StartActivity() to start Activity "s1" and also child activity "s2"
3. Extract "traceparent" value from "s2" and then stop "s2" and "s1" activities
4. Call ActivitySource.StartActivity() with TraceContext from s2 traceparent to start activity "s3"
5. "s3" will be a separated trace shown in Kibana. 

#### Expected behavior
Expect we can see the full trace like "s1" -> "s2" -> "s3" in kibana

#### Actual behavior
2 distributed traces could not be correlated

#### Root cause assumption
Tracer.StartTransactionInternal()'s `traceId` parameter is not passed into Transaction internal constructor, so that the first transaction's TraceId will be different from Activity.TraceId (`s1`), but `s3` parent id is referring to `s1` trace id.
https://github.com/elastic/apm-agent-dotnet/blob/9067636b28bffab9c5aa4d2d1592b1ee26e0a755/src/Elastic.Apm/Api/Tracer.cs#L81-L83

**Comment by z1c0** [comment]
Hi @kuanpak,
thanks for reporting this and even more so for coming up with a fix PR as well!

**Comment by gregkalapos** [comment]
Fixed in https://github.com/elastic/apm-agent-dotnet/pull/1882 by @kuanpak. Thanks for the contribution!
