### ISSUE TITLE
[META 709] Add/simplify ES cluster name capture

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-dotnet#1885]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/709

**Comment by stevejgordon** [comment]
The latest `Elastic.Transport` [ensures we attempt to parse the response headers](https://github.com/elastic/elastic-transport-net/pull/100/files#diff-493703cecda4dacd24c6f5227f7b5fa1d3edb565529f73fa3ff3d5a8df0d610cR208) to capture the cluster name, when possible. This can be marked as done.
