### ISSUE TITLE
Agent should support getting configuration from APM Server (AKA remote/central configuration)

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#190]
.NET Agent implementation issue derived from https://github.com/elastic/apm/issues/76.

See #320 as a prerequisite for this one.

https://github.com/elastic/apm-dev/issues/553 - the name for this feature to use in agent's docs.

**Comment by gregkalapos** [comment]
Closing this in #190 since that is already prioritised.
