### ISSUE TITLE
Support auto instrumentation of `Microsoft.Data.SqlClient` for versions >= 3.0

### ISSUE THREAD

**Issue by z1c0** [elastic/apm-agent-dotnet#1902]
Currently, the max version supported for `Microsoft.Data.SqlClient` is 2.x.
Let's raise the version upper bound to 3.0 (maybe remove the upper bound at all).

**Comment by muralidharanvenkataraman** [comment]
Hi,

any updates on this feature request ?

thanks
Murali

**Comment by z1c0** [comment]
Hi @muralidharanvenkataraman,

thanks for reaching out and following up on this.
Every once in a while we go through a process of prioritization, after which we are focussing on the tasks that are planned for the upcoming [milestone](https://github.com/elastic/apm-agent-dotnet/milestones). The prioritization status is typically reflected through the labels/projects/milestones fields on this issue.
