### ISSUE TITLE
Enable Entity Framework interceptor in the profiler 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1906]
Currently our EF instrumentation is [based on an interceptor](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm.EntityFramework6/Ef6Interceptor.cs), and that's not turned on in the profiler-setup. The result is that database calls through EF6 aren't captured as spans.

### Current status 
The only way to enable EF6 monitoring is to either change the `web.config` file or manually hook it up via code.

### The gaol of this issue
Make sure the `Ef6Interceptor` is turned on with the profiler and DB calls via EF6 are captured without any code (or config file) change.

**Comment by stevejgordon** [comment]
Closing as unplanned
