### ISSUE TITLE
Captured error's context should not change after capture

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#191]
Currently we copy a reference to transaction's context to captured error instance (AKA shallow copy) so error's context changes if transaction's context changes which is incorrect - error's context should not change after capture.

**Comment by SergeyKleyman** [comment]
Add tests to verify that in particular error's context won't have `Response` property.

**Comment by gregkalapos** [comment]
Decision: this is a nice to have, not needed in the next release.

**Comment by gregkalapos** [comment]
Implemented in #982.
