### ISSUE TITLE
[BUG] APM is not properly flushed when a Worker Services app is exiting

### ISSUE THREAD

**Issue by lazar-boradzhiev** [elastic/apm-agent-dotnet#1914]
### APM Agent version
The version of the `Elastic.Apm` nuget package used 1.18.0

### Environment

**Operating system and version:** Windows 10 and Docker with WSL 2

**.NET Framework/Core name and version**: .NET SDK 6/7 (mcr.microsoft.com/dotnet/aspnet:6.0 when on docker)

**Application Target Framework(s)**: net6.0/net7.0

### Describe the bug
When the application ends while APM has not yet flushed all it's buffered messages an exception is thrown.

### To Reproduce

1. Create an empty [Worker service](https://learn.microsoft.com/en-us/dotnet/core/extensions/workers)
2. Install and configure `Elastic.APM.NetCoreAll` 1.18.0
4. In `Program.cs` call `UseAllElasticApm()` on `IHostBuilder`
```
using APMTest;
using Elastic.Apm.NetCoreAll;

IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .UseAllElasticApm()
    .Build();

await host.RunAsync();

```
5. On `ExecuteAsync` terminate the application after a **_short_** delay
```
namespace APMTest
{
    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;
        private readonly IHostApplicationLifetime _hostApplicationLifetime;

        public Worker(ILogger<Worker> logger, IHostApplicationLifetime hostApplicationLifetime)
        {
            _logger = logger;
            _hostApplicationLifetime = hostApplicationLifetime;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            await Task.Delay(5000, stoppingToken);
            _hostApplicationLifetime.StopApplication();
        }

        public override async Task StopAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("Exiting application...");
            await base.StopAsync(cancellationToken);
        }
    }
}

```

#### Expected behavior
Either the application exists gracefully and outputs the messages that were not sent or waits for the APM flush to complete.

Example of what happens when the await duration is longer (e.g. 30-60+ seconds):
```
...
info: APMTest.Worker[0]
      Exiting application...
warn: Elastic.Apm[0]
      {PayloadSenderV2} Cancellation requested. Following events were not transferred successfully to the server (https://.../):
          Elastic.Apm.Metrics.MetricSet,
          Elastic.Apm.Metrics.MetricSet,
          Elastic.Apm.Metrics.MetricSet,
          Elastic.Apm.Metrics.MetricSet,
          Elastic.Apm.Metrics.MetricSet
```
#### Actual behavior
The an error occurs
```
...
info: APMTest.Worker[0]
      Exiting application...
fail: Elastic.Apm[0]
      {BackendCommComponentBase (PayloadSenderV2)} WorkLoop Current thread: `ElasticApmPayloadSenderV2' (managed ID: 10)
      System.InvalidOperationException: The source completed without providing data to receive.
         at System.Threading.Tasks.Dataflow.Internal.Common.InitializeStackTrace(Exception exception)
      --- End of stack trace from previous location ---
         at System.Threading.Tasks.Dataflow.DataflowBlock.Receive[TOutput](ISourceBlock`1 source, TimeSpan timeout, CancellationToken cancellationToken)
         at Elastic.Apm.Report.PayloadSenderV2.ReceiveBatch()
         at Elastic.Apm.Report.PayloadSenderV2.WorkLoopIteration()
         at Elastic.Apm.BackendComm.BackendCommComponentBase.WorkLoop()
```

#### Additional observation
On `Elastic.APM.NetCoreAll` version 1.14.0 the application does not output an error, but rather hangs indefinitely never exiting and utilizes the equivalent of a 1 CPU core.

**Comment by z1c0** [comment]
HI @lazar-boradzhiev,

thanks for reaching out and reporting this.
Note that there is already an [https://github.com/elastic/apm-agent-dotnet/issues/288](issue) for adding a `Flush`API. Is this the functionality you are looking for?

**Comment by lazar-boradzhiev** [comment]
> HI @lazar-boradzhiev,
> 
> thanks for reaching out and reporting this. Note that there is already an issue for adding a `Flush`API (see #288). Is this the functionality you are looking for?

Hi @z1c0, thanks for the reply. Yes, it would most likely technically solve it, but only if you know that you need to use it. I believe the underlying problem is the inconsistency in the behavior when waiting for the app to finish after different time intervals. I have updated the description for further clarification, but in short if I wait say 5 seconds before I exit the app with `_hostApplicationLifetime.StopApplication()` I get the error from the description. However, if I wait longer say 60 seconds instead I get the warning from the description with `Cancellation requested` message and a list of unsent events. My thoughts lead me to believe there is some internal logic that needs some time to complete in order to exit gracefully, which could be handled better without waiting to implement a whole new functionality like the Flush API.

**Comment by z1c0** [comment]
Hi @lazar-boradzhiev,

I understand that the observed behavior might appear inconsistent.
However, this is really agent-internal behavior that's not documented and is subject to change at any time.
There aren't any guarantees from the agent that data will be flushed or sent out before an application shuts down.
It's rather the contrary: the agent must not prevent an application from shutting down or unnecessarily delaying this process.
I know that this is not ideal for short-running applications. As I said, the first step in addressing this scenario will be adding the `Flush` API.

**Comment by lazar-boradzhiev** [comment]
Hey, @z1c0, I tried to dig in and understand if there is some easy way to mitigate the issue here, but to no avail. The error comes from TPL Dataflow library, which unfortunately I have no experience with. I suppose we will stick longer wait duration before exiting until the Flush API is released. Is there any ETA for it?

**Comment by z1c0** [comment]
Hi @lazar-boradzhiev,
sorry, a cannot give you a definite ETA for the `Flush` API, but this definitely something we will be working on soon.
Please keep watching #288.

I will close this issue though as it is not actually a bug but rather unspecified agent behavior. The solution will be the mentioned `Flush` API. I hope you can agree to that approach.
