### ISSUE TITLE
Use Testcontainers v2.2.0 in Elastic.Apm.Elasticsearch.Tests

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1936]
Currently `Elastic.Apm.Elasticsearch.Tests` uses Testcontainers v2.1.0 which has no built-in `ElasticsearchTestcontainer` so we build the container in our code.

Testcontainers v2.2.0 added `ElasticsearchTestcontainer` so most of the building of the Elasticsearch container can be removed and we can just use `ElasticsearchTestcontainer`. This is already done in `Elastic.Clients.Elasticsearch.Tests.csproj` for the new client which was introduced in https://github.com/elastic/apm-agent-dotnet/pull/1935.

**Comment by z1c0** [comment]
This was implemented in #1953.
