### ISSUE TITLE
CaptureError and CaptureException - potential changes

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#194]
2 potential improvements/changes to `IExecutionSegment.CaptureError` and `IExecutionSegment.CaptureException`:

- There is an optional parameter `parentId`, which can make the Error be recorded on another span/transaction. 1) this is not very obvious and can be confusing and we don't know whether this is really useful and 2) there are discussions to also contain span's context in the error (initiated by java, ~issue is to be found~  elastic/apm-agent-java#279) and in this case it'll be not possible to book the error on another span with just the id of the span. In case we keep this parameter there should be tests and sample that utilize it, it's currently unused.

- The public `IError` isn't really used anywhere in the API and it's worth to discuss whether we should return the created Error instance through this interface from the `CaptureError` and `CaptureException` methods - they are currently `void`. It can be useful for logging and checking stuff for users.

**Comment by SergeyKleyman** [comment]
By "initiated by java, issue is to be found" do you refer to https://github.com/elastic/apm-agent-java/issues/279 ?
Also #192 and https://github.com/elastic/apm/issues/62 might be related to this issue.

**Comment by gregkalapos** [comment]
> By "initiated by java, issue is to be found" do you refer to [elastic/apm-agent-java#279]

Yes, updated the text.

**Comment by gregkalapos** [comment]
The 2 issues here became less relevant. Closing now.
