### ISSUE TITLE
Azure Functions: Support dotnet (in-process) runtime

### ISSUE THREAD

**Issue by z1c0** [elastic/apm-agent-dotnet#1952]
In #1642, tracing of `dotnet-isolated` functions (the "out-of-process" runtime) was implemented.
The goal of this issue is to cover the `dotnet` (in-process) runtime as well:

**Note**: due to technical limitations this approach will support HTTP invocations only.

- [x] Implement a `DiagnosticListener` for those invocations.
- [ ] ~Sample application.~
- [x] Unit tests.
- [x] Documentation.

**Comment by Mpdreamz** [comment]
https://github.com/elastic/apm-agent-dotnet/pull/2160
