### ISSUE TITLE
[BUG] Agent 1.19.0  logs constantly :Failed sending event. Events intake API absolute URL  APM Server response: status code: "BadRequest", content: 

### ISSUE THREAD

**Issue by stefannikolei** [elastic/apm-agent-dotnet#1958]
After Updating to 1.19.0 i keep seeing this log entry. It spamms our logs.

```
022-12-06 07:02:04.698 +01:00 [ERR] {PayloadSenderV2} Failed sending event. Events intake API absolute URL: "https://xxx/intake/v2/events". 
APM Server response: status code: "BadRequest", content: 

{
	"accepted": 3,
	"errors": [
		{
			"message": "validation error: span: context: destination: service: 'resource' required",
			"document": "{\"span\":{\"context\":{\"destination\":{\"service\":{\"name\":\"\",\"type\":\"\"}},\"service\":{\"target\":{}}},\"duration\":0.4466,\"id\":\"9da85edfa08762a1\",\"name\":\"DefaultCache.Get\",\"outcome\":\"unknown\",\"parent_id\":\"cd08530b299aec19\",\"links\":[],\"sample_rate\":1.0,\"subtype\":\"internal\",\"timestamp\":1670306524063055,\"trace_id\":\"e087644c12d5f4f78c286720da4db9c9\",\"transaction_id\":\"53b3bafa292e366e\",\"type\":\"app\",\"otel\":{\"spanKind\":\"Internal\"}}}"
		}
	]
}

````

I have not seen this before V1.19.0

**Comment by z1c0** [comment]
Hi @stefannikolei,

thanks for reporting this issue. Could you provide a few more details, please?

* Which version of APM server are you running?
* Are you missing data (transactions, spans) after the update as well?
* Which technologies are you monitoring?
* Are you using the NuGet package, the Profiler or the StartupHooks approach?
* A full agent log on `Trace` level.

Thanks,
Wolfgang

**Comment by stefannikolei** [comment]
Sorry for not giving those infos..

Version APM Server: v8.5.1
Missing data: Have not noticed missing data
Technologies: ASP.NET Core, EF Core, SQLServer, HTTP Client
Using Nuget Package

**Comment by stefannikolei** [comment]
@z1c0 Could you point me to the docs, how to collect the agent log?

**Comment by z1c0** [comment]
> how to collect the agent log?

You can find the instructions here: https://www.elastic.co/guide/en/apm/agent/dotnet/current/troubleshooting.html

> Is there a way to send it to you without posting it here?

Can you use this link, please?
https://upload.elastic.co/u/41327f99-9caf-4199-8992-6f05482120f0

**Comment by z1c0** [comment]
@stefannikolei thanks for providing the log file, we'll have a look into the issue.
Please note that it might take a while until we follow up, given the upcoming holiday season.

**Comment by stefannikolei** [comment]
@z1c0 Ty. Have nice holidays :)

**Comment by kuanpak** [comment]
I have the same issue with OpenTelemetry Bridge when upgraded to 1.19.0

I think it's caused by creating span's Destination with null Resource from ElasticActivityListener below. The `resource` variable might be null when there is no expected matching tags.

https://github.com/elastic/apm-agent-dotnet/blob/7d29a5e77e7548c8da4dac450ab04dbc8eaaeb8d/src/Elastic.Apm/OpenTelemetry/ElasticActivityListener.cs#L324-L325

**Suggest changing to below (create `Destination` only when `resource` is not null)**
``` csharp
if (resource != null) {
    span.Context.Destination ??= new Destination();
    span.Context.Destination.Service = new Destination.DestinationService { Resource = resource };
}
```
