### ISSUE TITLE
Oracle nuget support 3.*.*

### ISSUE THREAD

**Issue by sarabu07** [elastic/apm-agent-dotnet#1967]
The existing oracle auto instrumentation supports Oracle.ManagedDataAccess 2.0.0 - 2.*.*

https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-auto-instrumentation.html

If the auto instrumentation support is expanded to Oracle.ManagedDataAccess.Core 3.*.* that would really help since oracle adding support to .Net 6 and 7 to this new version.  We may lose the auto instrumentation support when oracle drivers are upgarded.

**Comment by z1c0** [comment]
Note the related [discuss question](https://discuss.elastic.co/t/net-oracle-manageddataaccess-core-3-support/322538).

**Comment by sarabu07** [comment]
The microsoft have ended .Net core 3.1 and 5 support. If we upgrade to 6 or 7 then we have to upgrade to Oracle.ManagedDataAccess.Core 3.* version of nuget package. This would make elastic apm integration less valuable without support for auto instrumentation.

**Comment by sarabu07** [comment]
Any update when we will get the support in elastic APM for latest oracle nuget packages?

**Comment by z1c0** [comment]
Hi @sarabu07,
we are still working on it. Thanks for the patience.

**Comment by sarabu07** [comment]
@z1c0  Could you provide a timeframe when this would be available for us? We recently upgraded our api's to .Net core 6 for compliance, and now auto instrumentation is not working.

**Comment by sarabu07** [comment]
@z1c0 Do we have a release date for next version of elastic apm for .NET?

**Comment by z1c0** [comment]
Hi @sarabu07,
sorry, I can't give you a fixed date but expect a release soon.
