### ISSUE TITLE
Baggage support in System.Diagnostics.Activity - summary 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#1971]
Since we are discussing baggage support, I looked at what's present in .NET7 today on `System.Diagnostics.Activity`- I'm summarize  my finding here.

tldr: `Baggage` property exists on `Activity` and it gets propagated, but it does not follow the header name from the [current version of spec](https://www.w3.org/TR/baggage/#header-name) (which is `baggage`) by default. On the other hand, there is a property called `HttpContext.Request.Headers.Baggage` which contains the value of the `baggage` header and even better: if that header is set, the `Activity.Baggage` will contain values from that header, so `Activity.Baggage` parses the header from the spec as well. This means, reading incoming baggage comes for free over `Activity.Baggage` on .NET7+, but propagation of baggage does not follow the header name from the spec.

### Sample app

Caller:

```
using System.Diagnostics;
var l = new ActivityListener()
{
    ShouldListenTo = source => true,
    Sample = (ref ActivityCreationOptions<ActivityContext> options) => ActivitySamplingResult.AllData 
};
ActivitySource.AddActivityListener(l);

using (var activitySource = new ActivitySource("myTestApp"))
{
    using (var activity = activitySource.StartActivity("foo", ActivityKind.Client))
    {
        activity?.AddBaggage("synthetics.monitor.id", "123");
        Console.WriteLine($"{activity.DisplayName}, recorded: {activity.Recorded}");

        var httpClient = new HttpClient();
        await httpClient.GetAsync("http://localhost:5297/Home/Index");
    }
}
```

Callee:

```
public class HomeController : Controller
{
    public IActionResult Index()
    {
        var currentActivity = Activity.Current;
        Console.WriteLine($"Activity name:{currentActivity.DisplayName}, First Baggage: {currentActivity.Baggage.First()}");
        return View();
    }
}
```

Output from Callee:

```
Activity name:Microsoft.AspNetCore.Hosting.HttpRequestIn, First Baggage: [synthetics.monitor.id, 123]
```

Incoming HTTP headers:

```
HttpContext.Request.Headers.ToList()
  {Count = 3}
    [0]: {[Host, localhost:5297]}
    [1]: {[Correlation-Context, synthetics.monitor.id=123]}
    [2]: {[traceparent, 00-639063b892aad282eea271c434442e0f-a9829700601b4fae-00]}
```

As you can see, it uses the header `Correlation-Context` and not `baggage`. This seems to be the default behavior.

### Using only the `baggage` header

I did a test by changing the caller code to this:
```
 using (var activity = activitySource.StartActivity("foo", ActivityKind.Client))
 {
     Console.WriteLine($"{activity.DisplayName}, recorded: {activity.Recorded}");
     var httpClient = new HttpClient();
     httpClient.DefaultRequestHeaders.Add("baggage", "synthetics.monitor.id=123");
     await httpClient.GetAsync("http://localhost:5297/Home/Index");
 }
```

So instead of setting Baggage directly on `Activity`, I set the `baggage` header.

The good news is that this was parsed in the callee side into `Activity.Baggage` properly (same output as before) - that is without sending the `Correlation-Context` header. So the `Correlation-Context` header was NOT sent in this case.

### Summary

It seems, at least on .NET7+ with `HttpClient` we get the parsing of the `baggage` header for free over `Activity` in case of incoming calls. For outgoing calls, I think we don't have this for free - at least currently on .NET7, so in order to pass `baggage` to downstream services on a W3C compatible way, we need to do some further research.

**Comment by AlexanderWert** [comment]
Research completed
