### ISSUE TITLE
How to create a docker image out of this

### ISSUE THREAD

**Issue by amitdixit** [elastic/apm-agent-dotnet#2002]
Team appreciate the great work. Can we have an observability image for dotnet as we have for Java and node. 

I want to use it as  side car in Kubernetes for .net 7 instead of Nuget package.

Or atleast can u guide how to create an image for this.

Request your assistance.

**Comment by stevejgordon** [comment]
@amitdixit We don't support a sidecar install for this agent. However, we do now have a distro of the [OTel SDK for .NET](https://github.com/elastic/elastic-otel-dotnet/tree/main/examples/k8s), which you can check out if this is still a requirement. I'm closing this as unsupported and not something we have on the roadmap.
