### ISSUE TITLE
Sanitise userinfo in URLs

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#202]
Derived from https://github.com/elastic/apm-dev/issues/538

We need to sanitize URLs in

- Incoming requests (`transaction.context`)
- Outgoing requests (`span.context`)

and we need to it for

- Full .NET Framework
- .NET Core

**Comment by gregkalapos** [comment]
I move this into the milestone `7.5`, since we moved #515 into `7.5` during planning, and I think we overlooked this one. This is very related to #515, it's almost like a duplicate.

**Comment by gregkalapos** [comment]
Implemented in https://github.com/elastic/apm-agent-dotnet/pull/568.
