### ISSUE TITLE
[BUG] Failed transaction is registered with 200 status code in APM

### ISSUE THREAD

**Issue by mstrukov** [elastic/apm-agent-dotnet#2028]
### APM Agent version
1.20.0

### Environment

Linux, Kubernetes, .NET 6, Web API

### Describe the bug
If an unhandled exception happens in a controller then .NET will set the response code to 500 but the transaction will be registered with response code 200 in the APM. It seems like a [similar bug](https://discuss.elastic.co/t/java-apm-agent-http-status-codes-not-correctly-identified/149156/2) was reported for java package.

### To Reproduce

1. Create a controller with an action
2. Throw an exception in the controller so that the execution always fails when the action is called
3. Call the action using any tool, curl, postman, swagger, whatever
4. Verify that the response code is 500

#### Expected behavior
The failed transaction is registered with 500 status code. A workaround is to create a custom ExceptionFilterAttribute and set response code to 500 explicitly. 

#### Actual behavior
The failed transaction is registered with 200 status code. It seems like the status code for APM is fetched before .NET sets it to 500.

![image](https://user-images.githubusercontent.com/5313259/222427149-27382c0f-e76a-4166-bc04-2251d7308b02.png)

**Comment by billhong-just** [comment]
Any update on this 👀

**Comment by Mpdreamz** [comment]
Hey All, 

Just a small update that we can reproduce this and are working on a fix. 

The `UseElasticApm()` extension method from `Elastic.Apm.AspNetCore` uses a MiddleWare approach that sadly runs at time when the statuscode on response is not yet changed from `200` to `500`. 

The `UseAllElasticApm()` extension method on `IHostBuilder` from `Elastic.Apm.NetCoreAll` uses an DiagnosticSource approach to getting ASP.NET core lifecycle events which does work. 

I am working on getting rid of our `IMiddleWare` approach and always use the `DiagnosticSource` approach which does end up setting the right status code for the transaction.
