### ISSUE TITLE
[BUG] Elastic.Apm.AspNetFullFramework does not capture SQL operations

### ISSUE THREAD

**Issue by ddgpablo** [elastic/apm-agent-dotnet#2038]
### APM Agent version

APM 8.6

### Environment

.NET Framework 4.7.2

### Describe the bug

Elastic Apm is not able to automatically capture SqlClient operations.

### To Reproduce

To set up elastic APM:

```
            var agentComponents = ElasticApmModule.CreateAgentComponents();
            Agent.Setup(agentComponents);
            Agent.Subscribe(new SqlClientDiagnosticSubscriber());
```

Then when one of the endpoints is hit, we introduced the following code to test if it's able to capture SQL operations automatically:

```
        private void TestSql()
        {
            string queryString = "SELECT Email FROM [dotmailer].[dbo].[UserAccounts]";
            string connectionString = "YOUR_CONECTION_STRING";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand(queryString, connection);
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                try
                {
                    while (reader.Read())
                    {
                        Console.WriteLine(reader["Email"]);// etc
                    }
                }
                finally
                {
                    // Always call Close when done reading.
                    reader.Close();
                }
            }
        }
```

#### Expected behavior
We expect to see a transaction which contains a span for the SQL operation.

#### Actual behavior
We see a transaction without any span.

**Comment by gregkalapos** [comment]
Hi @ddgpablo, thanks for reporting this.

Could you please attach agent logs on `trace` level? Docs on how to collect logs can be found [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/troubleshooting.html#collect-logs-classic).

**Comment by sksk571** [comment]
The important detail is that we use Microsoft.Data.SqlClient library in a .NET Framework project.

The code in [SqlEventListener](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm.SqlClient/SqlEventListener.cs#L31) mentions issue https://github.com/dotnet/SqlClient/issues/436 that has been fixed more than 3 years ago. Should SqlEventListener be updated to use the new event source name for Microsoft.Data.SqlClient?

**Comment by ddgpablo** [comment]
This is the current error I'm getting from `OnEventWritter`:

```
ERROR: Exception in Command Processing for EventSource Microsoft-AdoNet-SystemData: Use of undefined keyword value 0x1 for event EndExecute.
```
