### ISSUE TITLE
Separate CI workflows for Windows/Core and Windows/Full Framework

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#204]
Currently we have 2 CI workflows

- Linux: .NET Core
- Windows: .NET Framework and then .NET Core

Instead we might have 3 workflows

- Linux: .NET Core
- Windows: .NET Core
- Windows: .NET Framework

**Comment by kuisathaverat** [comment]
I only see one stage for the `Windows: .NET Framework` the MSBuild stages, Do we plan to have more?

CC: @v1v

**Comment by SergeyKleyman** [comment]
I am not sure what term “stage” means in this context but the the goal is to have two completely separate build/test flows on Windows: one using only .NET Core tool chain and the other using only full .NET Framework tool chain.
