### ISSUE TITLE
Build/CI/Release Improvements

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-agent-dotnet#2046]
Opening this (incomplete) issue to keep track of all the changes I want to do to the build

Build improvements

- [ ] Refactor our build scripts so they are closer to: https://github.com/elastic/ecs-dotnet/tree/main/build/scripts. Quite a few of the targets now live as dedicated .NET tools: https://github.com/nullean?type=source
- [ ] Introduce local .NET tools including re-introducing `donet-format`
- [ ] Make `build/scripts` the only source of truth.
- [ ] Remove all scripts under `.ci`, something we've done for all our other repositories too.
- [x] Ensure we have one `*.sln` that can be built on all operating systems.
- [x] Split our tests more explicitly under `*.Tests` or `*.IntegrationTests`, this does not have to be perfect from the get go.
- [x] Might move windows integration tests over to `*.WindowsIntegrationTests` (unsure).
- [ ] 

CI improvements

- [ ] Move to Github Actions with explicit goal to fail as fast as possible
- [ ] `format` => `build` => `unit test` => `integration test` (parallel)
- [ ] IIS tests on PR's should only be a smoke tests, only run whole suite (50m) on `main` or if a `tag` is set on the `PR`. 
- [x] Bring inline with https://github.com/elastic/ecs-dotnet for test reporting

Release improvements

- [x] Move to [MinVer](https://github.com/adamralph/minver) for automatic versioning of all assemblies. This will eliminate the need for us to do version bump commits.
- [ ] Move to [release-notes](https://github.com/nullean/release-notes) .NET tool to automatically create labels and release-notes 
- [ ] Move to [release-notes](https://github.com/nullean/release-notes) .NET tool to:
	- [ ] automatically create labels 
	- [ ] release-notes on github and changelog
	- [ ] attach attachments to release automatically
- [x] No need to retest the whole world on `release` if `main` is green we should be able to `release` fast.

**Comment by AlexanderWert** [comment]
Will be continued in https://github.com/elastic/apm-agent-dotnet/issues/2072
