### ISSUE TITLE
AgentComponents should not be used in tests - TestAgentComponents should be used instead

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#205]
AgentComponents should not be used in tests - TestAgentComponents should be used instead because AgentComponents read configuration from environment variables which might be in unknown state and thus cause tests to become flaky.

**Comment by gregkalapos** [comment]
This is done - this become important with metrics because `AgentComponents` uses `MetricsCollector` and subscribing and unsubscribing to ETW and EventSource did not work in a single process multiple times.

Very few tests use it now.
