### ISSUE TITLE
Elastic APM no data logging in .NET 4.6.1 project using Owin

### ISSUE THREAD

**Issue by user-cloudiq** [elastic/apm-agent-dotnet#2052]
I’m working on a .net 4.6.1 framework project which uses owin with a startup.cs file. I have my elastic config code written in a separate file with the server URL, Apikey and the service name defined.
When running the project, I do see the service name appear on the ‘observability’ dash on the elastic site, but I don't see transactions, requests or any sort of data being fed in.
On checking the elastic docs for 4.6.1 framework projects its basically couple of lines of code in the web.config file to include elastic credentials and add to the module section. But I don't have a web.config in my project. Is there a workaround or different setup for .net framework projects using Owin?
Attached the project structure, config code snippet form my config class in common folder and from the settings.xml [file.](http://file.do/) Each of the modules contain a program.cs file, what would be the recommended way to implement auto instrumented elastic setup for my setup.
<img width="776" alt="apm config" src="https://user-images.githubusercontent.com/128178124/225989894-19be6fed-3090-44d8-ac2e-2c42b902d7b9.png">
<img width="305" alt="owin" src="https://user-images.githubusercontent.com/128178124/225989896-50d3a68e-0726-4f59-ac48-32bb6d1a2126.png">
<img width="290" alt="programcs" src="https://user-images.githubusercontent.com/128178124/225989898-4392bc53-23a9-48d8-a578-333dd571f254.png">
<img width="295" alt="project structure" src="https://user-images.githubusercontent.com/128178124/225989900-6a45d8d2-bc0b-4123-a3d6-00675b565454.png">
<img width="775" alt="setting xml" src="https://user-images.githubusercontent.com/128178124/225989903-6a884b99-cd1f-4b93-8ec7-43ea9967b77a.png">

**Comment by gregkalapos** [comment]
Hi @user-cloudiq ,


for OWIN, we don't have any auto-instrumentation. So the only way to make this work is to use the API of the agent and start traces for each incoming request - for that you can e.g. create an OWIN middleware which always starts a transaction. [This part of the doc](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-tracer-api) could be useful for that.
