### ISSUE TITLE
Add unit test collection "DependentOnEnvVars"

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#206]
Add unit test collection "DependentOnEnvVars" to make sure tests dependent on environment variables don't interfere with each other.

**Comment by russcam** [comment]
Closing this issue for now, as it's not something that's been observed as a general problem. An `IEnvironmentVariables` interface was introduced as a seam around `Environment.GetEnvironmentVariables()` for being able to test `CloudMetadataProviderCollection`; its usefulness and usage could be extended to avoid depending directly on `Environment` throughout the agent.
