### ISSUE TITLE
TestAgentConfigurationReader should not use environment variable names

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#207]
TestAgentConfigurationReader should not use environment variable names because it implies that TestAgentConfigurationReader reads configuration from environment variables which is not the case. TestAgentConfigurationReader doesn't read configuration from environment variables which is okay because we don't want TestAgentConfigurationReader to read configuration environment - we just need to remove references to environment variable names from TestAgentConfigurationReader. Instead we can use something like `"<test-config-transaction-sample-rate>"`.

**Comment by stevejgordon** [comment]
This is outdated, therefore closing
