### ISSUE TITLE
Npgsql 7 Support

### ISSUE THREAD

**Issue by ajmal-yazdani** [elastic/apm-agent-dotnet#2070]
As per this article, https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-auto-instrumentation.html, Npgsql is supported only for versions [Npgsql 4.0.0 - 6.*.*].

Question 1. When the support for Npgsql 7 will be available with auto instrumentation ?
Question 2 . Is there any plan to integrate this with Nuget way as well?

**Comment by Mpdreamz** [comment]
I've created a PR to bump us to 7.x, thanks for raising this @ajmal-yazdani !

https://github.com/elastic/apm-agent-dotnet/pull/2103

**Comment by ajmal-yazdani** [comment]
> I've created a PR to bump us to 7.x, thanks for raising this @ajmal-yazdani !
> 
> #2103

Thank you very much.

Will this be available only with auto instrumentation or as a nuget package or both?

**Comment by Mpdreamz** [comment]
Just for the auto instrumentation at the moment

**Comment by sergey-tihon** [comment]
Docs still say that v7 is not supported
https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-auto-instrumentation.html

![image](https://github.com/elastic/apm-agent-dotnet/assets/1197905/7db67a7e-d86a-42f6-ac97-7d27a8f252b4)

**Comment by tomap** [comment]
doc still needs an update :)

**Comment by stevejgordon** [comment]
Thanks @sergey-tihon and @tomap - I've opened #2316 to fix the docs up.
