### ISSUE TITLE
My iis8 version is 2012 r2.

### ISSUE THREAD

**Issue by sysnetadmin2** [elastic/apm-agent-dotnet#2071]
Hello I am trying to install elastic apm agent on iis 8 version.

It was confirmed by the log that the iis server is communicating from the apm-server.

However, even when I access the site configured with iis, the data is not visible in elastic apm.

The agent tries to use elastic_apm_profiler.

Elastic version is 8.7.1 .

Please help me.

![image](https://github.com/elastic/apm-agent-dotnet/assets/100679747/38500b56-b2f4-4179-aadb-10ef4fe7d4ea)

**Comment by stevejgordon** [comment]
@sysnetadmin2, sorry for missing this question. Are you still facing this issue? If so, please try the latest release first. If the issue persists, please share all the steps you have taken to register the profiler.

**Comment by stevejgordon** [comment]
Closing as outdated
