### ISSUE TITLE
Elastic.Apm.EntityFrameworkCore has no Microsoft.EntityFrameworkCore.Relational dependency in nuget

### ISSUE THREAD

**Issue by raman-kazhadub** [elastic/apm-agent-dotnet#2115]
### APM Agent version
Elastic.Apm.EntityFrameworkCore 1.22.0

### Environment

**Application Target Framework(s)** net6.0:

### Describe the bug
Elastic.Apm.EntityFrameworkCore has no dependency in nuget, but it has in project:
![image](https://github.com/elastic/apm-agent-dotnet/assets/26599309/0064fd92-a246-4b8d-afa8-d18a7e56a678)

https://github.com/elastic/apm-agent-dotnet/blob/main/src/instrumentations/Elastic.Apm.EntityFrameworkCore/Elastic.Apm.EntityFrameworkCore.csproj

#### Expected behavior
The nuget must have Microsoft.EntityFrameworkCore.Relational dependency 

#### Actual behavior
There is no dependency in nuget

**Comment by stevejgordon** [comment]
@raman-kazhadub, our implementation doesn't require one at runtime. We have a `PackageReference` using `PrivateAssets` to get the constants required to listen to known events. Do you see an actual bug or issue that needs addressing?
