### ISSUE TITLE
[BUG] The Elastic Agent APM .NET Framework does not present the database in dependency applications.

### ISSUE THREAD

**Issue by tornis** [elastic/apm-agent-dotnet#2117]
**Apm Agent version**
Elastic.Apm.1.22.0 

**Environment**
Application Target Framework(s) .NET 4.8.0 Framework:

**Describe the bug**

The Elastic Agent APM .NET Framework does not present the database in dependency applications.

After configuring the agent, the dependency screen does not display the database,.

Database operations (SQLite) is not displayed in transaction traces

When an error occurs in a transaction, it is not displayed on the transaction detail screen, making it difficult to analyze the root cause and error association in relation to the transaction, however it appears on the service screen.

**Comment by tornis** [comment]
![evidence3](https://github.com/elastic/apm-agent-dotnet/assets/1698811/e52dfb63-e52a-4988-b12d-45b9936c1e1c)
![evidence1](https://github.com/elastic/apm-agent-dotnet/assets/1698811/1f921736-aafa-4121-925e-aaac8b04ea9c)
![evidence2](https://github.com/elastic/apm-agent-dotnet/assets/1698811/429c03cf-0da9-42e0-9f21-d520c034cf63)
![evidence5](https://github.com/elastic/apm-agent-dotnet/assets/1698811/1f6e4d43-4dff-48b9-86c3-4d132e1ddbcb)
![evidence6](https://github.com/elastic/apm-agent-dotnet/assets/1698811/9b3b1004-4b25-4b40-84ac-81787958b3ed)

**Comment by stevejgordon** [comment]
Hi, @tornis. Firstly, apologies for the long delay in getting back to you. Is this still an issue for you using the latest release? How are you configuring the agent?

**Comment by stevejgordon** [comment]
Closing as outdated
