### ISSUE TITLE
Capture the rest of transaction.context.request.url properties

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#212]
According to spec https://github.com/elastic/apm-server/blob/master/docs/spec/request.json we don't capture the following transaction.context.request.url properties: 

- `port`
- `pathname`
- `search`
- `hash`

We need to extend:

- Public API
- Core implementation
- Full Framework implementation

**Comment by gregkalapos** [comment]
`search` is done, rest will deferred from 1.1

**Comment by gregkalapos** [comment]
From  #285:  `env` on `transaction.context.request` should be also added.

**Comment by stevejgordon** [comment]
Closing as out of date. We now capture these on `Destination`
