### ISSUE TITLE
Make sure CPU metrics are cgroup aware

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-dotnet#2122]

**Comment by AlexanderWert** [comment]
Check whether this is already the case for .NET

**Comment by stevejgordon** [comment]
This has been researched internally, and our metrics are consistent with `dotnet counters` for CPU usage inside containers. Some CPU cgroup limits are soft limits, and it is difficult to report them from the container perspective. We will do further research to confirm if the metrics align with those reported by other tools, such as Beats.

**Comment by stevejgordon** [comment]
We have agreed to close this for now as our metrics align with those reported through `dotnet counters`, and there appears not consistent/reliable way to take all CPU cgroup options into account.
