### ISSUE TITLE
[META 814] Normalize metrics reported based on cgroup in all APM agents

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-dotnet#2125]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/814
- Spec issue: https://github.com/elastic/apm/issues/815

**Comment by gregkalapos** [comment]
Dupl of https://github.com/elastic/apm-agent-dotnet/issues/2123

**Comment by stevejgordon** [comment]
1. Having reviewed this for .NET in #2122, we don't feel there is anything further we can do to adjust the CPU metrics for CGroups and doing so would diverge from Microsoft metrics. 
2. We already do not send the magic string `9223372036854771712` for `system.process.cgroup.memory.mem.limit.bytes`. I need to check further to see if we fall back to `system.memory.total`
