### ISSUE TITLE
Integration with .gitattributes for line endings.

### ISSUE THREAD

**Issue by dazinator** [elastic/apm-agent-dotnet#2129]
When checking line endings, if a .gitattributes file is present or specified, allow that to override the .editorconfig.

**Is your feature request related to a problem? Please describe.**

When runing dotnet format on our windows machines, dotnet format doesn't find any issues.
Our linux build server however, discovers that all line endings in `.cs` files are wron and need converting from `LF`.

Our `.editorconfig` has line endings set to `CRLF` windows style line endings.
  - Note: editorconfig seemingly does not support the ability to specify that line endings should be `native` see https://github.com/editorconfig/editorconfig/issues/226
Our `.gitattributes` file has `auto` which means files get checked out with `CRLF` on windows (hence dotnet format runs fine) and `LF` on linux - hence dotnet format sees the discrepency between editor config rule, and the files themselves.

Due to above issue with editor config, we can't make the editor config flexible enough to have one rule for linux checkouts (LF) and another for windows checkouts (CRLF) i.e by specifying something like `native` as the rule as that isn't available.

However many repos use `.gitattributes` and the settings I have provided are largely the default ones, which will lead people into this issue.

If editorconfig is unlikely to get support for `native` line endings,  then perhaps dotnet format should add the capability to detect `.gitattributes` files and allow the rules to override editor config for line endings. Such that `auto` in gitattributes would always mean check foor platform specific line endings, irrespective of the setting in editor config.

```
# Auto detect text files and perform LF normalization
# https://www.davidlaing.com/2012/09/19/customise-your-gitattributes-to-become-a-git-ninja/
*    text=auto

*.cs text diff=csharp
###############################################################################
# Set default behavior to automatically normalize line endings.
###############################################################################
*            text=auto
* 
```

**Describe the solution you'd like**
As above, include `.gitattributes` into the equation when caclulating which line ending rule to use.

**Describe alternatives you've considered**
- Looked for support in `editorconfig` for a `native` line endings rule. Looks like this won't be added: https://github.com/editorconfig/editorconfig/issues/226

**Additional context**

**Comment by dazinator** [comment]
also raised this question here: https://github.com/editorconfig/editorconfig/issues/489

**Comment by Mpdreamz** [comment]
I think this might might have needed to be reported on https://github.com/editorconfig/editorconfig-core-net

Seeing as the linked issue is resolved, closing this one too.
