### ISSUE TITLE
Capture request body in ASP.NET Core 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#213]
Trigger by [this](https://github.com/elastic/apm-agent-dotnet/issues/117#issuecomment-486407571) comment.

In elastic/apm-agent-dotnet#134 we added the `Request.Body` field, but that is only utilized by API tests, so the only way to use it is to manually set the request body.

Other agents have a setting for this. E.g. see [here](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-body).

We should add this config setting and extend our ASP.NET Core instrumentation to behave accordingly.

**Comment by SergeyKleyman** [comment]
@gregkalapos Should we open a separate issue for .NET Framework?

**Comment by gregkalapos** [comment]
> @gregkalapos Should we open a separate issue for .NET Framework?

Yeah, we can do that. I don't see it super important at this point though.

**Comment by katzdan** [comment]
I'll start working on this and report here.

**Comment by gregkalapos** [comment]
Implemented by @katzdan in #402
