### ISSUE TITLE
Tests in Elastic.Apm.Tests should be executed on both .NET Core and full .NET Framework

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#214]
Currently unit tests in Elastic.Apm.Tests are executed only on .NET Core even though code under test is used in production on full .NET Framework as well. So we should have unit tests for the code in Elastic.Apm to run on all the environments for which the code is used in production.

This issue is related to #200   but the difference is that this issue is about unit tests while elastic/apm-agent-dotnet#200 is about integration tests.

**Comment by gregkalapos** [comment]
Cleaning up milestone 1.1 - this is not merged yet due to some discussion, but I leave it on 1.1, since most of the work is already done and no prod code is affected.
