### ISSUE TITLE
[Redis] Elastic.Apm.StackExchange.Redis High Memory Usage.

### ISSUE THREAD

**Issue by solomon-okolie** [elastic/apm-agent-dotnet#2145]
In a windows service using Elastic.Apm.StackExchange.Redis, `HttpDiagnosticsSubscriber` and `SqlClientDiagnosticSubscriber` we noticed very unusual high memory usage (~ 4GB) after a few days.

Redis connection is a singleton created as below.
` var redisConnection = ConnectionMultiplexer.Connect(...);
  redisConnection.UseElasticApm();
`

`Http` and `SqlClient` Diagnostic subscribers are added as below
`
  IHostBuilderInstance.UseElasticApm(new HttpDiagnosticsSubscriber(), new SqlClientDiagnosticSubscriber());
`

The trace is captured manually as below
`
 Agent.Tracer.CaptureTransaction("TestProcessor", "Console", () =>
                            {
                               // code that calls http, sql, redis
                            });
`

When we remove `Elastic.Apm.StackExchange.Redis` the memory usage after days is stable as expected ~200MB

Taking a closer look, we noticed lots `ProfilingSession` instance still being used.

ElasticApm nuget versions: 1.22
Framework: .NET 6
Deployment: self contained win10-x64

![Perfview](https://github.com/elastic/apm-agent-dotnet/assets/17110967/2a303242-9125-4e47-951c-00be8f9c4419)

![Dot Memory](https://github.com/elastic/apm-agent-dotnet/assets/17110967/169518ef-bc10-47eb-9fb2-91f45e347030)

**Comment by Mpdreamz** [comment]
Oof this is not great! 

Just adding a small note that we are now aware and that I've started digging into this.
