### ISSUE TITLE
[BUG] OpenTelemetry Bridge Documentation: wrong Config Name

### ISSUE THREAD

**Issue by warappa** [elastic/apm-agent-dotnet#2164]
When the PR https://github.com/elastic/apm-agent-dotnet/pull/1966 was merged, the configuration option for the OpenTelemetry Bridge was changed from `EnableOpenTelemetryBridge` to `OpentelemetryBridgeEnabled`.

Unfortunately, this is not reflected in the documentation - and all the samples continue to use the old name.
Please update it and maybe also include a hint that it changed.

- Current 1.x: https://www.elastic.co/guide/en/apm/agent/dotnet/1.x/opentelemetry-bridge.html
- Master: https://www.elastic.co/guide/en/apm/agent/dotnet/master/opentelemetry-bridge.html

![image](https://github.com/elastic/apm-agent-dotnet/assets/886232/dbc601ca-07e7-46de-844d-8633270c267d)

**Comment by Mpdreamz** [comment]
Thanks for opening this!, should should be covered by this open PR already:

https://github.com/elastic/apm-agent-dotnet/pull/2140/files
