### ISSUE TITLE
3. preview release

### ISSUE THREAD

**Issue by lafriks** [elastic/apm-agent-dotnet#222]
Now that distributed tracing support has been added it would be great that 3rd preview release could be released

**Comment by gregkalapos** [comment]
Hey @lafriks 

We are preparing the agent for beta (currently it's in alpha), so we don't really plan a 3. alpha release.

We would like to also implement metrics #154 - once that feature lands we will be close to "beta ready".

No strict time plan here, but we are not far away from that.
