### ISSUE TITLE
[BUG] Azure Function Middleware does not assign Service.Environment

### ISSUE THREAD

**Issue by mmodolo** [elastic/apm-agent-dotnet#2246]
Currently it has no way to pass the service environment to apm. It could be easily added somewhere around the line below reading from "DOTNET_ENVIRONMENT" environment variable for example.

Does it have any appetite on adding it? Thanks!

https://github.com/elastic/apm-agent-dotnet/blob/038ece7d09fc18aa3c17d3f4667f7a889d5505bb/src/azure/Elastic.Apm.Azure.Functions/AzureFunctionsContext.cs#L48

**Comment by rfavreau** [comment]
Hello @mmodolo,

To pass the environment to apm, add the environment variable "ELASTIC_APM_ENVIRONMENT". This variable can be set by the [application settings in the Azure Portal](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-use-azure-function-app-settings?tabs=portal#settings).

You can also set this setting during the startup of the Azure Function:
```c#
new HostBuilder()
        .ConfigureFunctionsWorkerDefaults((context, builder) =>
        {
            Environment.SetEnvironmentVariable("ELASTIC_APM_ENVIRONMENT", context.HostingEnvironment.EnvironmentName);
            builder.UseMiddleware<ApmMiddleware>();
        })
        .Build()
        .Run();
```

> With Azure Function, you must use `AZURE_FUNCTIONS_ENVIRONMENT` to set the environment and not `DOTNET_ENVIRONMENT` or `ASPNETCORE_ENVIRONMENT`.

**Comment by stevejgordon** [comment]
I'm going to close this as answered. I've opened #2507 to include more details in the docs.
