### ISSUE TITLE
Implement stack_trace_limit setting

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#225]
This is currently missing in the .NET agent. 

See [here](https://www.elastic.co/guide/en/apm/agent/java/current/config-stacktrace.html#config-stack-trace-limit).

**Comment by SergeyKleyman** [comment]
https://github.com/elastic/apm/issues/89 seems to be relevant to this feature.

**Comment by gregkalapos** [comment]
Implemented in #374.

Also covered by #307.

Once there is a decision on https://github.com/elastic/apm/issues/89 we can also implement that.
