### ISSUE TITLE
Cleanup package reference in Elastic.Apm.AspNetCore for net 6 TFM

### ISSUE THREAD

**Issue by thompson-tomo** [elastic/apm-agent-dotnet#2266]
**Is your feature request related to a problem? Please describe.**
I would like Elastic.Apm.AspNetCore to make full usage of the Framework reference by allowing removal of the packages provided by the framework.

**Describe the solution you'd like**
I would like the below dependencies removed from the project when targeting net 6 as the provided by the framework:

- Microsoft.Extensions.Configuration.Abstractions
- Microsoft.Extensions.Logging.Abstractions
- Microsoft.Extensions.Hosting.Abstractions

**Describe alternatives you've considered**
Leave the dependencies as they are

**Additional context**
N/A

**Comment by Mpdreamz** [comment]
Merged #2267
