### ISSUE TITLE
Integration with .Net Core logging infrastructure

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#228]
**Is your feature request related to a problem? Please describe.**
Current logging implementation inside Elastic.Apm for ASP.Net Core has some limitations.
1. Limited support of logging providers. At the moment, only Console is supported.
2. Unable to modify format of log messages which causes some issues in case of hosting in k8s. in k8s we're writing log messages directly into console in json format. Then such messages are fetched by filebeats and shipped to logstash via kafka. In case of enabling apm, our filebeats generate a huge amount of errors during parsing messages, which are produced by `ConsoleLogger`. It doesn't broke out logging infrastructure, however, it would be nice to have logs from apm into our logging storage.

**Describe the solution you'd like**
It would be nice for `Elastic.Apm.AspNetCore` project to add support of .Net Core logging infrastructure (Microsoft.Extensions.Logging). For compatibility with `IApmLogger` it can be written adapter which accepts `ILogger` as dependency and implement `IApmLogger` interface. In such case will be added eability to support various logging providers ([built-in providers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2#built-in-logging-providers)) with richer configuration capabilities.

**Describe alternatives you've considered**
1. We can implement custom implementation of `IApmLogger` interface, however we cannot override usage of default console logger
https://github.com/elastic/apm-agent-dotnet/blob/2447ecb7212d3659dcae91bf9d3e39370040f59b/src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs#L32-L41
2. `LogLevel` can be set to `None` to not produce log messages from APM, however, we lost all messages from apm agent

**Comment by gregkalapos** [comment]
Thanks for opening this @vhatsura, we definitely plan to do more work in this area; `ConsoleLogger` won't be the only logger long term.

**Comment by vhatsura** [comment]
@gregkalapos, thanks for reply.
Do you have in plans to have integration with `Microsoft.Extensions.Logging` in `Elastic.Apm.AspNetCore`?

**Comment by gregkalapos** [comment]
@vhatsura Yes. 

I don't have a final action plan, but what I can think of is that we implement this in `Elastic.Apm.AspNetCore` in a way that you can pass the logger to it and from that point the agent will log through it as any other component (like ASP.NET Core, or EFCore).

**Comment by vhatsura** [comment]
@gregkalapos, what do you mind if I try to implement this?

**Comment by gregkalapos** [comment]
@vhatsura we are very happy to take contributions. In case you start working on it, I think it'd be best to keep us involved early... you can e.g. open a draft pull request or just open issues in case you have questions. This way we can agree on things early, without needing to make huge changes. Thanks!

**Comment by gregkalapos** [comment]
Implemented by @vhatsura in #249 - thanks for the great work! 👍
