### ISSUE TITLE
General support for custom DiagnosticSource

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#229]
From [discuss](https://discuss.elastic.co/t/support-for-custom-diagnosticsource-in-apm-net-agent/180834).

Currently we only collect specific DiagnosticSource events. Maybe it would make sense to have a general way of collecting custom DiagnosticSource events and create spans automatically.

OpenTracing [has this feature](https://github.com/opentracing-contrib/csharp-netcore/blob/master/src/OpenTracing.Contrib.NetCore/CoreFx/GenericDiagnostics.cs).

Scope: 
- [ ] Discuss and decide if it makes sense (probably it does I think)
- [ ] Define high level how it works
- [ ] Open a follow up issue to implement

**Comment by SergeyKleyman** [comment]
As we discussed, additional points to consider:
- How should agent set `span.type` and `span.subtype` based on data in DiagnosticSource events? (See [`span` spec](https://github.com/elastic/apm-server/blob/master/docs/spec/spans/span.json)
- Should agent support setting parts of `span.context` based on data in DiagnosticSource events? For example, we can start with `span.context.tags` and get to more advanced use cases such as `span.context.http` if the need arises.

**Comment by lreuven** [comment]
pushing for the future
