### ISSUE TITLE
Removal of polyfil packages

### ISSUE THREAD

**Issue by thompson-tomo** [elastic/apm-agent-dotnet#2305]
**Is your feature request related to a problem? Please describe.**
I want that the packages which i am adding to my projects only has dependencies on those packages which it needs & can not obtain via Framework.

**Describe the solution you'd like**
I would like that for the net 6 TFM polyfil packages such as those listed below are not included so that dependencies are kept to a minimum in the case of Elastic.APM the dependencies will be reduced by 80%.
- System.Diagnostics.DiagnosticSource
- System.Reflection.Metadata
- System.Threading.Tasks.Dataflow
- System.Threading.Tasks.Extensions

**Describe alternatives you've considered**
Accept that the polyfil packages are included

**Additional context**
Continuation of #2266

**Comment by thompson-tomo** [comment]
Note happy to submit a PR for the changes

**Comment by stevejgordon** [comment]
@thompson-tomo This sounds reasonable, and we'd very much welcome a PR for this.

**Comment by thompson-tomo** [comment]
Great I will aim to do PR in the next week or so.

**Comment by thompson-tomo** [comment]
@stevejgordon pr is all done with the tweaked conditions to reduce dependencies.
