### ISSUE TITLE
Mark Deprecated packages as such on nuget

### ISSUE THREAD

**Issue by thompson-tomo** [elastic/apm-agent-dotnet#2306]
**Is your feature request related to a problem? Please describe.**
Users are not aware that package is depreciated see #2284

**Describe the solution you'd like**
I want https://www.nuget.org/packages/Elastic.Apm.SqlClient to show as depreciated in Nuget. Telling users it is now part of base package. Downloads should be transferred to Elastic.APM

**Describe alternatives you've considered**
N/a

**Additional context**
Deprecation is mentioned #2284 & #2226

**Comment by stevejgordon** [comment]
@thompson-tomo, thanks for catching this. Sorry for the delay. I have updated the package on NuGet.org to reflect this.

**Comment by thompson-tomo** [comment]
thanks @stevejgordon 👍
