### ISSUE TITLE
[BUG] Request Body not correctly parsed, also redacted

### ISSUE THREAD

**Issue by patently** [elastic/apm-agent-dotnet#2334]
### APM Agent version
1.26.0

### Environment
.NET 4.7.2, Web API

### Describe the bug

**http.request.body.original** is split and also being REDACTED despite having added 

<add key="ElasticApm:CaptureBody" value="all" />

to the web.config

### To Reproduce

Any calls to the API

#### Expected behavior

**http.request.body.original** contains the json passed when calling the action

#### Actual behavior

**http.request.body.original** is split and [REDACTED] is shown

![image](https://github.com/elastic/apm-agent-dotnet/assets/133217423/3d6400f1-677f-426a-8cfd-12a92fbc0082)

**Comment by stevejgordon** [comment]
Unable to reproduce and original GitHub account has been deleted.
