### ISSUE TITLE
[BUG] DOTNET_STARTUP_HOOKS not work

### ISSUE THREAD

**Issue by fidoooooowang** [elastic/apm-agent-dotnet#2335]
### APM Agent version
1.26.0.0

### Environment
.net core 3.1

### Describe the bug
I want to use the method of configuring DOTNET_STARTUP_HOOKS to inject es-apm non-invasively. But it will report an error that the file cannot be found.

document：https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-dotnet-net-core.html#zero-code-change-setup
here is my path and error:
DOTNET_STARTUP_HOOKS=/app/dotnet-es-apm/ElasticApmAgentStartupHook.dll

<img width="898" alt="image" src="https://github.com/elastic/apm-agent-dotnet/assets/137022700/f5811fc3-d0e9-4d5c-8d72-dfbe45a66bf7">

<img width="1491" alt="image" src="https://github.com/elastic/apm-agent-dotnet/assets/137022700/4a4684a7-3606-4a81-97c6-520b9fbe65af">

**Comment by stevejgordon** [comment]
Thanks for raising this, @fidoooooowang. Your app likely references System.Diagnostics.DiagnosticsSource 5.x, and I can see the problem in our build process. I will fix it so the next release zip contains the expected DLLs.

**Comment by fidoooooowang** [comment]
> @fidoooooowang, Can you try the 1.27 release to ensure our fix closed this issue?

yes, version 1.27.0  works！Thank you very much !
