### ISSUE TITLE
Rename UseElasticApm extension methods

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#234]
From elastic/apm-agent-dotnet#230 

Currently we have 2 `UseElasticApm` methods and this is very confusing. There seems to be an agreement to rename those to better reflect their purposes.

This [comment describes](https://github.com/elastic/apm-agent-dotnet/issues/230#issuecomment-493554507) what those do.

Suggestions (from @SergeyKleyman 's [comment](https://github.com/elastic/apm-agent-dotnet/issues/230#issuecomment-494722757))
- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseElasticApmBase`
- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticApm `

**Comment by gregkalapos** [comment]
By looking at this I think the 2. one is a good name, but the first one (`Elastic.Apm.AspNetCore.UseElasticApmBase`) isn't really telling the truth (which was i guess my suggestion 😅 ) - That actually only registers the ASP.NET Core middleware. 

How about:
- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseElasticAspNetCoreMiddleware`
- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticApm`

@SergeyKleyman?

**Comment by gregkalapos** [comment]
Maybe not using the word `Middleware` in the method name would be better, because that is an implementation detail, and it can be changed (e.g. all we do with the middleware, also can be done with DiagnosticSource), and also we in fact register 1 diagnostic source listener for error capturing. 

So alternative:
- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseElasticAspNetCore` (or `Elastic.Apm.AspNetCore.UseElasticAspNetCoreMonitoring`
- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticApm`

**Comment by SergeyKleyman** [comment]
I would go with the following to stress that it's about ASP.NET Core APM and the difference is the set of features enabled (Basic vs All):

- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseBasicElasticAspNetCoreApm`
- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticAspNetCoreApm`

**Comment by SergeyKleyman** [comment]
Or since `Elastic.Apm.AspNetCore.UseElasticApm` is customizable (it receives `IDiagnosticsSubscriber[]`):
- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseCustomElasticAspNetCoreApm`
- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticAspNetCoreApm`

**Comment by gregkalapos** [comment]
But isn't having `AspNetCore` in the `Elastic.Apm.All` misleading? `AspNetCore` is just 1 part of it, it also starts monitoring EFCore and HttpClient. I would prefer not to have `AspNetCore` in that method name.

**Comment by SergeyKleyman** [comment]
We can change it to:
- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseCustomElasticApm`
- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticApm`

In documentation to both we can clarify that capturing start/end of ASP.NET Core transactions is always enabled.

**Comment by gregkalapos** [comment]
I think this one is good:

- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticApm`

I'm not sure about the other one, proposal is:
`Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseCustomElasticApm`

Is the word `Custom` adding value here? Maybe it just makes people wonder what they should customize with it. How about not renaming it? So we'd have `UseElasticApm` in `Elastic.Apm.AspNetCore` with xml docs making clear that it's ASP.NET Core monitoring only and 
`UseAllElasticApm`. 

@SergeyKleyman ?

**Comment by SergeyKleyman** [comment]
Sounds good.

**Comment by gregkalapos** [comment]
Graat, so decision:

- `Elastic.Apm.All.UseElasticApm` -> `Elastic.Apm.All.UseAllElasticApm` (plus in https://github.com/elastic/apm-agent-dotnet/issues/243 we rename `All` to `NetCoreAll`, so actually `Elastic.Apm.NetCoreAll.UseAllElasticApm`)
- `Elastic.Apm.AspNetCore.UseElasticApm` -> `Elastic.Apm.AspNetCore.UseElasticApm` (no change)

**Comment by gregkalapos** [comment]
Implemented in #371.
