### ISSUE TITLE
Bump System.Diagnostics.PerformanceCounter to 8.0

### ISSUE THREAD

**Issue by tomap** [elastic/apm-agent-dotnet#2357]
In the last version of Elastic.Apm, you are using System.Diagnostics.PerformanceCounter version 6.0.1

If you were to bump it to version 8.0.0, you'd also bump System.Configuration.ConfigurationManager
which has one less dependency: it does not include a reference to System.Security.Permissions
see:
https://www.nuget.org/packages/System.Configuration.ConfigurationManager/7.0.0#dependencies-body-tab
vs
https://www.nuget.org/packages/System.Configuration.ConfigurationManager/#dependencies-body-tab

It would make Elastic.Apm lighter

Thank you

**Comment by thompson-tomo** [comment]
@tomap i have already gone and implemented a nicer solution via https://github.com/elastic/apm-agent-dotnet/pull/2308/files which will be in the next release. That MR has eliminated the need for a number of dependencies on the newer TFM'S.

**Comment by tomap** [comment]
Awesome! Thank you
