### ISSUE TITLE
[BUG]  TC_CLOUD_TOKEN environment variable is no longer bootstrapped

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/apm-agent-dotnet#2360]
See e.g: https://github.com/elastic/apm-agent-dotnet/actions/runs/9074899164/job/24934471062?pr=2350

**Comment by v1v** [comment]
I've just regenerated the token and updated the GH secrets, then I [ran](https://github.com/elastic/apm-agent-dotnet/actions/runs/9074899164?pr=2350)

Let's see how it goes

**Comment by v1v** [comment]
and it works now

**Comment by Mpdreamz** [comment]
Reopening because sadly it still happens although I no longer believe this is due to an expired TC_CLOUD_TO

**Comment by v1v** [comment]
> Reopening because sadly it still happens although I no longer believe this is due to an expired TC_CLOUD_TOKEN.

Uhm... if you rerun it, does it work?

**Comment by Mpdreamz** [comment]
Yeah that was the rerun, still see it fail sporadically.

Will use this ticket to collect cases when I see it fail due to a timeout.

**Comment by Mpdreamz** [comment]
Another case: https://github.com/elastic/apm-agent-dotnet/actions/runs/9211903537/job/25342919830#step:3:1

On a new PR.

**Comment by Mpdreamz** [comment]
It still happens but this clearly not secret config problem. 

It sporadically still times out when the actions sets up and tests the agent. 

Will create a PR updating the GitHub action it looks like they more clearly separated these two phases now.

**Comment by v1v** [comment]
I see, thanks Martijn for the update 🙏

**Comment by Mpdreamz** [comment]
Closing for now since it seems to have stabilised on its own
