### ISSUE TITLE
Send container.id in system.

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#238]
Preparing a talk and ran into this. This is very little work for a very useful feature:

Once we send this, users can jump from infrastructure/container to APM data.

This is the missing part: https://github.com/elastic/apm-server/blob/master/docs/spec/system.json#L23

**Comment by gregkalapos** [comment]
Also worth noting: this must be the full container id.

Something like this would be I think a good start: 

```
using (var sr = new StreamReader("/proc/self/cgroup"))
{
	var line = sr.ReadLine();
	var parts = line?.Split('/');
	if (parts != null)
	{
		var lastpart = parts.Last();
		_system.Container = new Container { Id = lastpart };
	}
}
```

**Comment by axw** [comment]
> We should also come up with something for Windows containers.

@gregkalapos If you do come up for something for Windows containers, please create an issue on elastic/apm. I guess it'll be significantly more common for .NET, but still would be useful to have this documented somewhere central.

**Comment by gregkalapos** [comment]
Since the linux support is fairly simple, I implemented it in #238, I think that's a good start, I don't have data, but I feel Linux containers are still more popular among .NET devs than Windows containers - you can also run those on a Windows host, so there is no giant real need for windows containers - and I think people prefer windows containers.

If #238 gets merged I'll close this, open another one just for Windows, once we come up with a solution for that, I'll document it in elastic/apm.

**Comment by axw** [comment]
By the way, in case you haven't seen it: there's a description of how we should go about extracting k8s and container info in https://github.com/elastic/apm/issues/21#issuecomment-444035232, as well as some test cases. You don't have to do the k8s bit straight away, but it might be useful to run through the test cases to make sure the container ID is extracted correctly.

**Comment by gregkalapos** [comment]
> By the way, in case you haven't seen it: there's a description of how we should go about extracting k8s and container info in [elastic/apm#21 (comment)](https://github.com/elastic/apm/issues/21#issuecomment-444035232), as well as some test cases. You don't have to do the k8s bit straight away, but it might be useful to run through the test cases to make sure the container ID is extracted correctly.

👍I added a unit test to test through all the values from the referenced comment - the algorithm itself is a copy-paste from Java with some C#-ification. We only capture the `containerId`, we cover all those k8s cases as well - but don't capture k8s specific things, just the container id.
