### ISSUE TITLE
Use proper fileName function for stacktrace

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#239]
Hi,
Currently, when error occur we can see a stack trace like that : 
![image](https://user-images.githubusercontent.com/3065048/58433618-b6c5c000-80c0-11e9-84d8-9acd7957469a.png)

The problem here that value which we capture is not a real file name, it`s more like a namespace where that file exists. 
Another problem is that the function name is invalid (MoveNext) it`s because the function is async.

My suggestion is to capture real fileName and functionName. I made some test and here is a working example

I made some research and here are my results : 
![image](https://user-images.githubusercontent.com/3065048/58434645-7288ee80-80c5-11e9-95cf-5a6f34fbb97c.png)

I will create a pull request with those changes for the review.

**Comment by gregkalapos** [comment]
Addressed and discussed in #240.
