### ISSUE TITLE
Extend Request by Id (or maybe even more from ECS)

### ISSUE THREAD

**Issue by monty241** [elastic/apm-agent-dotnet#2397]
See https://discuss.elastic.co/t/integration-elastic-common-scheme-with-elastic-apm-events-intake-api/363124

The src/Elastic.Apm/Api/Request.cs class does not allow correlation with trace identifier from asp.net core by default.

Suggestion is to extend it by this and maybe more features from https://www.elastic.co/guide/en/ecs/current/ecs-http.html

**Comment by stevejgordon** [comment]
Hi, @monty241. The transaction spec is generalised to suit all languages. I don't expect any changes such as the one proposed here. It's unclear to me why this is necessary. ECS .NET [logs should correlate](https://www.elastic.co/guide/en/apm/agent/dotnet/current/logs.html) with APM traces automatically. Is that not working in your scenario? The ASP.NET Core request ID is particular to that platform. Correlation is achieved using standardised W3C trace identifiers. 

You can also enrich transactions and spans with additional labels to be indexed so you can expand the data you capture if required. Does that help?

```c#
_tracer.CurrentTransaction.SetLabel("aspnetcore_traceidentifier", HttpContext.TraceIdentifier);
```

**Comment by monty241** [comment]
Thanks for response. I don't recall the background exactly; we have already moved on by replacing the logic to better fit our needs using as depicted labels and other mechanisms. I will close.
