### ISSUE TITLE
[BUG] SqlRoleProvider won't work with AspNet Identity 2

### ISSUE THREAD

**Issue by allen-hsu-rs** [elastic/apm-agent-dotnet#2415]
### APM Agent version
The version of the `Elastic.Apm` nuget package used
1.28.1

### Environment

**Operating system and version:**
windows 11

**.NET Framework/Core name and version** (e.g. .NET 4.6.2, NET Core 3.1.100) :
.NET 4.7.2

**Application Target Framework(s)** (e.g. net462, netcoreapp3.1):
net472

### Describe the bug
Please see the link here - https://github.com/elastic/apm-agent-dotnet/pull/2377#discussion_r1716299209

### To Reproduce

1. Create an empty MVC project targeting net472
2. use this template - https://www.nuget.org/packages/Microsoft.AspNet.Identity.Samples/#readme-body-tab
3. In Startup.cs - copy and paste following
```
using Owin;
using System.Linq;

namespace IdentitySample
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            try {
			    var providers = System.Web.Security.Roles.Providers;
			    var sqlRoleProvider = System.Web.Security.Roles.Providers.Cast<object>().Any(provider => provider.GetType().Name == "SqlRoleProvider");
            }catch(System.Exception e){
                System.Diagnostics.Debug.WriteLine(e.Message);
            }
            ConfigureAuth(app);
        }
    }
}
```

#### Expected behavior
`System.Web.Security.Roles.Providers` will throw exception in Startup.cs, which will do the same and break SDK as mentioned here - https://github.com/elastic/apm-agent-dotnet/pull/2377#discussion_r1716299209

#### Actual behavior
https://github.com/elastic/apm-agent-dotnet/pull/2377#discussion_r1716299209

**Comment by Mpdreamz** [comment]
Thank you for bringing this to our attention @allen-hsu-rs !

Opened https://github.com/elastic/apm-agent-dotnet/pull/2417 to address it.
