### ISSUE TITLE
[BUG] Outdated MongoDB.Driver.Core dependency in Elastic.Apm.MongoDb

### ISSUE THREAD

**Issue by th3ragex** [elastic/apm-agent-dotnet#2416]
The lastest MongoDB Diagnostic listener has a dependency to `"MongoDB.Driver.Core" Version="2.19.0"` 
https://github.com/elastic/apm-agent-dotnet/blob/2d1a0db5ce437cc6042868f9247f2ce62af711b2/src/instrumentations/Elastic.Apm.MongoDb/Elastic.Apm.MongoDb.csproj#L29

I have compile issues in a project with a dependency to `MongoDB.Driver Version 2.28.0` with `"MongoDB.Driver.Core" Version="2.28.0"` as transient dependency and `"Elastic.Apm.MongoDb" Version="1.28.1"`.

```
error CS0012: The type 'IEventSubscriber' is defined in an assembly that is not referenced. You must add a reference to assembly 'MongoDB.Driver.Core, Version=2.19.0.0, Culture=neutral, PublicKeyToken=null'.
error CS1503: Argument 1: cannot convert from 'Elastic.Apm.MongoDb.MongoDbEventSubscriber' to 'MongoDB.Driver.Core.Events.IEventSubscriber'
```
in:

```c#
var clientSettings = MongoClientSettings.FromConnectionString(settings.ConnectionString);

// https://www.elastic.co/guide/en/apm/agent/dotnet/1.x/setup-mongo-db.html
clientSettings.ClusterConfigurator = builder => builder.Subscribe(new MongoDbEventSubscriber());
```

The last update was done on year ago: https://github.com/elastic/apm-agent-dotnet/pull/2030

1) Did the dependabot / renovatebot break?
2) Please update the `MongoDB.Driver.Core` dependency.

**Comment by Mpdreamz** [comment]
I'm all for updating deps in general,

Need to dive in and understand what the breaking change between `2.19.0` and `2.28.0` is though.

**Comment by Mpdreamz** [comment]
Oh yeah thanks for bringing this to our attention @th3ragex! 😸

**Comment by aciobaniteia** [comment]
Hi @Mpdreamz 

We are facing the same issue and another one: 
```CS0012	The type 'IMongoClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'MongoDB.Driver, Version=2.22.0.0, Culture=neutral, PublicKeyToken=null'
```
```C#
    services.AddMongoDb(
        MongoClientSettings.FromUrl(mongoUrl),
        name: "MongoDBHealthCheck",
        timeout: options.HealthcheckTimeout);
```

The behaviour is very weird. We've got the same error as @th3ragex  when we we're having the version to 2.22.0, but when we are trying to update to 2.28.0 the issues appears

**Comment by Mpdreamz** [comment]
Looks like MongoDB 1.28.0 introduced a breaking change: 

https://www.mongodb.com/docs/drivers/csharp/current/upgrade/#std-label-csharp-breaking-changes-2.28.0

**Comment by Mpdreamz** [comment]
Opened #2419 to address this

**Comment by callumgoodridge2** [comment]
There's a similar issue occurring now when updating the MongoDB.Driver package to v3.0.0. Looks like Elastic.Apm.MongoDb will require this update from v2.28.0 to v3.0.0

> Opened [#2419](https://github.com/elastic/apm-agent-dotnet/pull/2419) to address this
