### ISSUE TITLE
Integration with log libraries to be able to tag log messages with trace/transaction IDs (AKA log correlation)

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#244]
Derived from https://github.com/elastic/apm-dev/issues/279
It seems that the approach taken by the other agents is as follows:
1. Implement support for automatically adding trace/transaction IDs for the most popular logging framework(s).
2. Document how user can do it manually for a logging framework that is not among the supported ones.

It's probably makes sense to put this feature behind a configuration flag (enabled by default?)

**Comment by SergeyKleyman** [comment]
Also see https://github.com/elastic/apm/issues/111

**Comment by chrisvanderpennen** [comment]
I'm experimenting with creating a Serilog integration for a collection of asp.net core services, and I'm running into a startup ordering issue.

Log messages emitted during asp.net core startup are routed via the Serilog enrichment component I've created, which reads from `Agent.Tracer.CurrentTransaction?.TraceId`.  This triggers APM to bootstrap with its default configuration, and then the call to `UseAllElasticApm()` in `Startup.Configure()` crashes the service with:
```
Application startup exception: System.Exception: The singleton APM agent has already been instantiated and can no longer be configured
   at Elastic.Apm.Agent.Setup(AgentComponents agentComponents)
   at Elastic.Apm.AspNetCore.ApmMiddlewareExtension.UseElasticApm(IApplicationBuilder builder, IConfiguration configuration, IDiagnosticsSubscriber[] subscribers)
   at Hosting.Web.ElasticApmStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app) in C:\path\to\ElasticApmStartupFilter.cs:line 13
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

I can code around it by setting a static flag on the serilog component immediately after calling `UseAllElasticApm`, but it would be simpler if the agent could expose a property signalling that it has been configured and the tracer is now safe to access.

**Comment by gregkalapos** [comment]
> I can code around it by setting a static flag on the serilog component immediately after calling UseAllElasticApm, but it would be simpler if the agent could expose a property signalling that it has been configured and the tracer is now safe to access.

@chrisvanderpennen In the [`1.2.0` release](https://github.com/elastic/apm-agent-dotnet/releases/tag/1.2.0) a new property was added to the `Agent` type to query if the agent was already configured: `Agent.IsConfigured`. 

I think that solves your problem.

**Comment by chrisvanderpennen** [comment]
@gregkalapos Awesome, thanks for letting me know it was ready, I've been following the conversation on #596.  I'll see if I can get approval to open source our Serilog integration once I've got it updated to respect the IsConfigured flag.

**Comment by gregkalapos** [comment]
> @gregkalapos Awesome, thanks for letting me know it was ready, I've been following the conversation on #596. I'll see if I can get approval to open source our Serilog integration once I've got it updated to respect the IsConfigured flag.

Sounds good - one goal we have as part of this issue is to add trace and transaction id to every log, so we can correlate logs and traces. Some ideas are already [here](https://github.com/gregkalapos/apm-agent-dotnet/blob/LogCorrelation/src/Elastic.Apm.SerilogEnricher/ElasticApmEnricher.cs).

**Comment by gregkalapos** [comment]
Closing this.

Serilog integration - already merged: https://github.com/elastic/ecs-dotnet/tree/master/src/Elastic.Apm.SerilogEnricher

NLog: PR open: https://github.com/elastic/ecs-dotnet/pull/22

Docs: https://github.com/elastic/apm-agent-dotnet/blob/master/docs/log-correlation.asciidoc

Release is TBD - I'll raise that in the next .NET sync.
