### ISSUE TITLE
Notable increase in memory usage from 1.25.x to 1.30.x

### ISSUE THREAD

**Issue by ArminShoeibi** [elastic/apm-agent-dotnet#2500]
Hi there,

Initial Update and Issue Discovery On November 24, 2024, at 1:26:34 AM GMT+3:30, I updated our gateway to: 

- .NET 9 from 8
- Yarp 2.2 from 2.1
- Elastic.Apm.AspNetCore 1.30.1 from 1.23.0

Approximately 120,000 TPM (Transactions Per Minute)
Observed Issue: Notable Memory Usage Increase Following the update, a significant rise in memory usage was detected. For reference, our service's memory usage pattern is illustrated below on the morning of discovery. Fortunately, our 4GB RAM per pod capacity temporarily mitigated the immediate impact.

![Image](https://github.com/user-attachments/assets/2ed9ae78-1a50-4e07-bdba-10e2ee451eef)

Troubleshooting Steps:

Rollback and Partial Update: I rolled back the changes and only updated Yarp and dThe outcome is shown below.
![Image](https://github.com/user-attachments/assets/c1a7b00c-1808-44cd-ba69-14cee0549360)

Testing Elastic.Apm.AspNetCore Versions:

Version 1.25: Although this version exhibited errors (detailed below), memory usage was more efficient compared to version 1.23.
![Image](https://github.com/user-attachments/assets/783fa7a3-fb16-4266-8cbb-2489409e9a4a)
But Kibana was empty in this duration

Version 1.29.0 (Current): Memory usage increases at a gentler rate. However, version 1.25 was preferable in terms of memory efficiency, despite its error profile and the absence of data in Kibana.
![Image](https://github.com/user-attachments/assets/b6843b9e-2c8b-408a-be43-d3de943feb26)

Empty APM with version 1.25
![Image](https://github.com/user-attachments/assets/43ac6b04-53a6-455e-b10c-b1c1a8a0e010)

Additional Metrics:

Ratio: 0.1
Throughput: Illustrated below for context.
![Image](https://github.com/user-attachments/assets/fb20e426-4c64-4e49-ad60-4234c5588998)

**Comment by ArminShoeibi** [comment]
This is 1.29 right now

![Image](https://github.com/user-attachments/assets/49803646-85e0-4a07-82c9-796e42611303)

Kibana and APM are okay, we don't have much errors (headers) but the memory is rising.

**Comment by ArminShoeibi** [comment]
> Thanks for reporting [@ArminShoeibi](https://github.com/ArminShoeibi). I'll need to schedule some time to hopefully reproduce this so I can analyse the memory usage.

Happy to help speed up the process! Can you let me know which .NET tool to add to our Docker image first, and what kind of dump/output would be most helpful for you

@stevejgordon

**Comment by stevejgordon** [comment]
Ah, you're running on Linux? I'm less familiar with analysing memory on Linux, but I believe [dotnet-dump](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) tool will be sufficient to get a managed memory dump that could be analyse.

**Comment by ArminShoeibi** [comment]
> Ah, you're running on Linux? I'm less familiar with analysing memory on Linux, but I believe [dotnet-dump](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) tool will be sufficient to get a managed memory dump that could be analysed.

Yeah, we are using K8s and my base images are

1. mcr.microsoft.com/dotnet/sdk:9.0.100-bookworm-slim-amd64
2. mcr.microsoft.com/dotnet/aspnet:9.0.0-bookworm-slim-amd64

okay, I will get a dotnet-dump with version 1.29 and will send it here to check it with the available tools.

**Comment by ArminShoeibi** [comment]
This picture is better

![Image](https://github.com/user-attachments/assets/5e5e9c84-6797-4d49-a764-ccf6ae691cbe)

by the way, we have a lot of endpoints.

![Image](https://github.com/user-attachments/assets/e446a2d1-8f68-465f-bd38-f8c7ef94290b)
![Image](https://github.com/user-attachments/assets/850afbdc-7ca0-466d-bee7-b9fa14b81835)

**Comment by ArminShoeibi** [comment]
this is my first gc-dump after a redeploy
![Image](https://github.com/user-attachments/assets/3510669e-9d9e-4c97-b728-a5780da92236)

I will upload a complete one in 12 hours with the file itself. but right now it lives on top of others I mean the APM

**Comment by stevejgordon** [comment]
Thanks @ArminShoeibi. That high volume of `LogValuesFormatter` looks suspicious. What configuration are you using for the agent? Specifically, what log level have you enabled?

**Comment by ArminShoeibi** [comment]
> Thanks [@ArminShoeibi](https://github.com/ArminShoeibi). That high volume of `LogValuesFormatter` looks suspicious. What configuration are you using for the agent? Specifically, what log level have you enabled?

That was just the baseline, here is a pod after working about 8~hrs

![Image](https://github.com/user-attachments/assets/6b0093e3-0027-4312-a5a2-a9afdf0f22e7)


all the Unknowns are related to Elastic.Apm

![Image](https://github.com/user-attachments/assets/4c7b15ec-2714-4b13-8758-c706c991183e)


The Log level is error, we don't log anything in the gateway.
and our configuration is real simple

```
  "ElasticApm": {
    "Environment": "Production",
    "Enabled": true,
    "ServerUrl": "http://apm-server-***.***:4000/",
    "TransactionSampleRate": 0.1
  }
```

**Comment by ArminShoeibi** [comment]
I need to downgrade to version 1.23 to stay under the company's radar. I'll provide the corresponding dumps for version 1.23 within the next 6-7 hours

**Comment by ArminShoeibi** [comment]
1.23 Dump (Baseline)

Installed packages:
![Image](https://github.com/user-attachments/assets/352facdf-f6a5-4336-ba68-78c47024b754)

Memory usage after a Redeploy in favor of doing a clean dump.

![Image](https://github.com/user-attachments/assets/c340560c-823e-4738-9b78-bdb16a34cf28)


Flamegraph:
![Image](https://github.com/user-attachments/assets/740d1541-54a2-45a8-ad45-9b3fec778656)

Details:
![Image](https://github.com/user-attachments/assets/6d20cc3d-0525-4017-aa7f-5a854dd12454)

![Image](https://github.com/user-attachments/assets/5837eba3-21c2-48b5-b83b-4695eff1d08b)

**Comment by stevejgordon** [comment]
Thanks for the thorough investigation so far, @ArminShoeibi. I appreciate you taking the time to provide these screenshots. I spent some time reviewing our logging code and profiling locally this morning. I can see the causes for the allocations. There's no apparent leak, per se, but as some undue allocations are `ConditionalWeakTable`, those have a finaliser penalty, too, which impacts how quickly those are recovered. I have several obvious quick wins I'm going to focus on as soon as possible.

**Comment by stevejgordon** [comment]
@ArminShoeibi 1.31.0 was released today and should hopefully have a significantly better footprint.

**Comment by ArminShoeibi** [comment]
> [@ArminShoeibi](https://github.com/ArminShoeibi) 1.31.0 was released today and should hopefully have a significantly better footprint.

Thanks @stevejgordon, I will test it and inform you.

here is the 1.23.0 for the last 7 days.
![Image](https://github.com/user-attachments/assets/956611b5-70e5-43d5-bcfd-45a258395a11)
