### ISSUE TITLE
Run Elastic.Apm.DockerTests in Docker

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#251]
elastic/apm-agent-dotnet#252 implements reading container id and also adds a test covering that - this test is in the `test/Elastic.Apm.DockerTests/Elastic.Apm.DockerTests` project. We need to run this project in docker in order for it to work (if it's not running inside docker the test just skips all the asserts, so the PR is ok for merge).

Happy to create `Dockerfile` or get involved with this, but I'll need help from @elastic/observablt-robots. Let me know if there are any steps I can prepare.

**Comment by kuisathaverat** [comment]
I am testing a solution in this PR https://github.com/elastic/apm-agent-dotnet/pull/256

**Comment by kuisathaverat** [comment]
in review
