### ISSUE TITLE
Transaction.Name is overridden

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#257]
Transaction.Name is always overridden, so it`s impossible to change it.

Root case - https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L93

cc @SergeyKleyman

**Comment by skynet2** [comment]
Proposed solution - https://github.com/elastic/apm-agent-dotnet/pull/258

**Comment by gregkalapos** [comment]
That was I think originally my code 👼 

Great fix, looked at the PR, I looks good to me.
