### ISSUE TITLE
Code coverage should be submitted for each CI pipeline

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#274]
After elastic/apm-agent-dotnet#204 we have 3 CI pipelines:
1. Linux: .NET Core
2. Windows: .NET Core
3. Windows: .NET Framework

But only the first pipeline (Linux: .NET Core) submits code coverage metrics. Now that we have some tests running only in the context of other pipelines (for example Windows: .NET Framework) we need to submit code coverage metrics from all the pipelines. **We need to make sure that code coverage tool, that we use, can properly combine them.**

**Comment by gregkalapos** [comment]
We now have coverage report for each CI pipeline.
