### ISSUE TITLE
Release support for ASP.NET Full Framework

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#276]
We need to investigate if we can release as NuGet package since it's IIS HTTP module or if releasing it as NuGet package is the best option.

Issues to do before starting this one:
- We decided to exclude #343 from the first release of support for ASP.NET Full Framework ~~[ ] Investigate if support IIS ElasticApmModule can be used as standalone module to monitor all applications elastic/apm-agent-dotnet#343~~
- [ ] Document agent's support of ASP.NET Full Framework #346

**Comment by SergeyKleyman** [comment]
Child issue of #83

**Comment by maverix** [comment]
Should the Http Module be available from the Elastic.Apm nuget package?

**Comment by SergeyKleyman** [comment]
Hi Andrew,

If the investigation shows that NuGet is the best option to release support for ASP.NET Full Framework (which is very likely) then it will be released as a separate nuget package (something like `Elastic.Apm.AspNet` or `Elastic.Apm.AspNetFullFramework`) not as part of `Elastic.Apm` nuget package. It's the same approach as we already take with `Elastic.Apm.AspNetCore` and `Elastic.Apm.EntityFrameworkCore` nuget packages. The reason for having separate packages is to allow users flexibility in choosing their dependencies.

**Comment by SergeyKleyman** [comment]
This is an umbrella issue with only two child issues: #343 and #346. We decided to include #346 in the first release of support for ASP.NET Full Framework and #343 can be tracked by itself so we can close issue.
