### ISSUE TITLE
system.cpu.total.norm.pct x-plat implementation

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#278]
#248 ended up adding total system CPU metric on Linux and Windows. That PR initially also contained an x-plat implementation, but during the review we decided that it's better to not include that. 

[This is the commit](https://github.com/elastic/apm-agent-dotnet/pull/248/commits/85aaa20205d5b7e6a03bec0e6cacc87e26b486fb) that removed this x-plat implementation.

This code needs another iteration, which we should do at some point.

Discussion about the issues we should think about: https://github.com/elastic/apm-agent-dotnet/pull/248#discussion_r290911724.

This is not high prio.

**Comment by lreuven** [comment]
lower priority

**Comment by gregkalapos** [comment]
Closing now - we had 1 question about it regarding macOS, but even in that case it was more like a "nice to have" since macOS was only dev environment, in prod (if I remember correctly Linux) we report this.
