### ISSUE TITLE
Implement mechanism to record and report agent's internal errors

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#280]
In the agent's code we have cases where we encountered errors but we are not sure how to handle them - sometimes we are not sure if those errors can actually occur and if so under which circumstances. For example, getting the same request instance as argument to `HttpDiagnosticListenerImplBase.ProcessStartEvent`.  Just logging it might be risky because when the event does occur it might occur very frequently and thus overflow the logs. Also if we would like to attach some context to each event occurrence (for example host name from the request URL and thread ID) and we can aggregate statistics about the event based on the properties of the context attached - it might helps in the future investigation.

We can extend this mechanism to record other events that might be of interest when investigating support cases, etc. For example:
- **[Update:** Most of this particular issue might not be relevant anymore since we are about to switch to stack approach for tracking current transaction/span. But we have to place an upper bound on stack size so it would be nice to report stats on transactions/spans that tried to go over that limit.**]**
We have a concept of current-transaction (and current-span to be added in #308) but we don't enforce  that those transactions/spans don't overlap (in which the later transaction/span will just overwrite the earlier one). Users might cause overlap by incorrectly using agent's public API (for example forgetting to call `End()`) or we might cause overlap with automatically generated transactions/spans in which case we should consider it a bug and fix it. In both cases we would like to know if it happens - we could just log it but it happens very frequently it might overflow the logs. The best approach would be to log it on high enough level (error?) but with throttling to prevent logs overflow and record stats on this event. For example in addition to just a counter on how many times it happen (in the last day, hour, 5 minutes, etc.) it would be interesting to see which transaction type+sub-type was overwritten and did the overwriting.  
    - Another potential issues with keeping stack of the current of transactions/spans 
        - Transactions/spans can be ended in the order contradicting their nesting (it can detected by comparing the transaction/span being ended with the one at the top of the stack. This can be caused by a user incorrectly invoking agent's public API.
        - `Pop` can be called on an empty stack - it doesn't seem that user can cause it by invoking agent's public API (TBD: make sure) so if it happens it means a bug in the agent's code
- Another event about which we might want to gather statistics for supportability is the effect of `VERIFY_SERVER_CERT` configuration option (how frequently it overridden certificate validation errors). See https://github.com/elastic/apm-agent-dotnet/pull/465#discussion_r319816303

**Comment by russcam** [comment]
I'm going to close this for now. We can look to revisit in future if needed
