### ISSUE TITLE
Add tests to verify `transaction.context.user.username` on Full Framework

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#292]
At the moment the code to capture the required information and fill `transaction.context.user.username` for .NET Full Framework exists but there are no tests for it. We need to 

- [ ] Implement additions to sample application `sample\AspNetFullFrameworkSampleApp`
- [ ] and additional tests in `test\Elastic.Apm.AspNetFullFramework.Tests`.

Derived from #273.

**Comment by tomashyam** [comment]
I would like to work on this issue.  @SergeyKleyman  is there a way I can contact you for further questions?

**Comment by SergeyKleyman** [comment]
@tomashyam I would recommend you to contact @gregkalapos and @russcam.

**Comment by gregkalapos** [comment]
This was implemented by @russcam in https://github.com/elastic/apm-agent-dotnet/pull/978. It also includes tests with a sample application.
