### ISSUE TITLE
Add tests for spans for HTTP client calls that fail because of timeout or server forcibly closing connection (on .NET Core)

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#293]
At the moment we only have tests for HTTP call that fails because host name is nonexistent, i.e., DNS resolution failure - we also need to cover cases when HTTP call fails because it's timed out and/or server forcibly closed connection.

#291 is the issue to implement the same kind of tests for .NET Full Framework.

**Comment by stevejgordon** [comment]
Closing as something we don't plan to add currently
