### ISSUE TITLE
Include agent's production code invoked by Full Framework tests in code coverage

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#295]
Derived from #273.
At the moment agent's production code invoked by Full Framework tests will not be included in code coverage. We would like to fix that to have more accurate picture of agent's production code covered by all the tests - both unit tests and component/integration tests since Full Framework tests are essentially component and not unit tests.

**Comment by gregkalapos** [comment]
Subset of https://github.com/elastic/apm-agent-dotnet/issues/274 -  closing now.
