### ISSUE TITLE
Prepare beta release

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#298]
Tasks:

- [x] create packages - Make sure to do it on Windows! 
- [x] upload packages to nuget.org
- [x] create release on GitHub
- [ ] create blogpost

**Comment by gregkalapos** [comment]
Version number will be `1.0.0-beta1`

**Comment by SergeyKleyman** [comment]
It's also worth adding a Git tag for it in case we would need to create a branch for fixes.

**Comment by gregkalapos** [comment]
> It's also worth adding a Git tag for it in case we would need to create a branch for fixes.

👍  Added it as a separate task. Once we create a new release here, it'll get it's own tag: https://github.com/elastic/apm-agent-dotnet/tags

**Comment by gregkalapos** [comment]
Packages are online, [release also created here on GitHub](https://github.com/elastic/apm-agent-dotnet/releases/tag/1.0.0-beta1).

**Comment by gregkalapos** [comment]
Done, we released. Blogpost is tracked in a separate issue.
