### ISSUE TITLE
Add Entity Framework Core telemetry through DiagnosticSource

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#3]
Subscribe to "Microsoft.EntityFrameworkCore" events and create spans based on those events.

**Comment by SergeyKleyman** [comment]
@gregkalapos Isn't this already implemented?

**Comment by gregkalapos** [comment]
Yes, it's technically implemented, I just did not feel confident to close it, since the test coverage is not that great.

I'd like to spend some time on this before GA and make sure it's properly covered - (e.g. having tests with some more db providers, not only SQLite). Assigned it to myself and moved it to milestone GA - probably doesn't need much more effort to close this.

**Comment by gregkalapos** [comment]
Done, we are good here.
