### ISSUE TITLE
Sanitize potential security sensitive info in HTTP headers, cookies and POST form fields

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#300]
Sanitize (sanitise, scrub, redact, remove) potential security sensitive info in HTTP headers, cookies and POST form fields.

Implementations by other Elastic APM agents:

| Agent  | Configuration setting |
|---------|-------------------------|
| Java     | [`sanitize_field_names`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-sanitize-field-names)  |
| Go       | [`sanitize_field_names`](https://www.elastic.co/guide/en/apm/agent/go/current/configuration.html#config-sanitize-field-names) |
| node.js | [`filterHttpHeaders`](https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#filter-http-headers) |
| Ruby    | [`custom_key_filters`](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-custom-key-filters) |

**Comment by gregkalapos** [comment]
In 1.0GA we don't implement it, since it can be turned off. We move this after 1.0GA.

**Comment by gregkalapos** [comment]
Feedback and response, related to this: https://github.com/elastic/apm-agent-dotnet/issues/379#issuecomment-515235602

**Comment by gregkalapos** [comment]
Implemented in #549.
