### ISSUE TITLE
Automatically created spans for HTTP calls on .NET Full Framework - transaction is null inside the ProcessExceptionEvent method

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#302]
Based on https://github.com/elastic/apm-agent-dotnet/issues/291#issuecomment-503369728

**Comment by SergeyKleyman** [comment]
@maverix I was not sure if your comments

> Also found in my testing that the transaction is null inside the ProcessExceptionEvent method

and

> The DiagnosticListener seems to assume that ProcessExceptionEvent is always an exception.
This isn't really the case when the response is a status code (400 bad request etc)

are related. I assumed that they are and I've added a test for this scenario (https://github.com/elastic/apm-agent-dotnet/pull/273/commits/938af6f1b867bcdd4783dfc367fb6aacfb9ff5b0). It works as expected - it captures a span for HTTP call that has 400 (Bad Request) as its result. Please note that this is not the same scenario as the one in #291. If server returns an error HTTP status it doesn't cause an exception to be thrown from `await new HttpClient().GetAsync(...)` unlike the scenario in #291 where `await new HttpClient().GetAsync("http://dsfklgjdfgkdfg.mmmm")` throws `WebException: The remote name could not be resolved: 'dsfklgjdfgkdfg.mmmm'`. In server responding with 400 (Bad Request) scenario `IDiagnosticListener` receives the same type of event as it would have received if server returned success HTTP status so `ProcessExceptionEvent` is not called which is as expected.

Also regarding

> Also found in my testing that the transaction is null inside the ProcessExceptionEvent method

In the agent log I see that during sample application (sample\AspNetFullFrameworkSampleApp) startup there's an HTTP call that doesn't have a transaction

> [2019-06-19 11:00:43][Trace] - {HttpDiagnosticListenerImplBase} Processing start event... Request URL: http://169.254.169.254/metadata/instance/compute?format=json&api-version=2017-12-01
[2019-06-19 11:00:43][Debug] - {HttpDiagnosticListenerImplBase} No active transaction, skip creating span for outgoing HTTP request

But this is because this HTTP call is not made in context of processing of a request to the application. Judging by [this doc](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service) and IP address 169.254.169.254 this HTTP call probably comes from one of Microsoft's telemetry packages that tries to connect to Azure. The package got included in the sample application by default by Visual Studio when the sample application was generated.

In case I misunderstood your scenario, could you please provide a little bit more details about it - I would like to reproduce it and fix it.

**Comment by maverix** [comment]
I will try and get a repro together tomorrow.

**Comment by SergeyKleyman** [comment]
@maverix I closed this issue because it seems not to be relevant anymore based on your comment - https://github.com/elastic/apm-agent-dotnet/issues/291#issuecomment-506572402. Please re-open this issue if the problem reproduces.
