### ISSUE TITLE
Improve development experience on non Windows OS with .NET Full Framework targeting projects

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#306]
We have a few projects that can build only Windows + .NET Full Framework and so those projects fail to build on Linux and MacOS or even Windows without .NET Full Framework development tools installed.

We would like to find a way to improve this aspect of development experience on non Windows OS.

CI pipeline handles this issue by removing those projects but this is not a convenient solution for development environment.

Derived from https://github.com/elastic/apm-agent-dotnet/pull/273#discussion_r295224433

**Comment by SergeyKleyman** [comment]
A possible approach to consider would be to create a separate solution (something like `ElasticApmAgentXPlat.sln`) that will contain references to a subset of projects that can be built on any OS. Developers on non Windows OS can use this solution instead of the one referencing all the projects.

We can also change CI pipelines to use `ElasticApmAgentXPlat.sln` and thus getting rid of `dotnet sln remove` hack. Of course Windows + .NET Full Framework CI pipeline will continue using the solution referencing all the projects.

**Comment by gregkalapos** [comment]
Alternatively this is a very promising project: https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies
