### ISSUE TITLE
Add API method/property to get current span

### ISSUE THREAD

**Issue by lafriks** [elastic/apm-agent-dotnet#308]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to get current span only current transaction

**Describe the solution you'd like**
Add option to get current span like it is possible to get `CurrentTransaction` a new getter should probably be added `CurrentSpan`. 

**Additional context**
Something like it is possible in Java API - https://www.elastic.co/guide/en/apm/agent/java/master/public-api.html#api-current-span

This could probably be requirement to fix elastic/apm-agent-dotnet#245

**Comment by gregkalapos** [comment]
Thanks for opening! 

> This could probably be requirement to fix #245

Yes, those are related. 

I think both this and #245 are good candidates to implement before GA...  cc @SergeyKleyman
