### ISSUE TITLE
Revise target frameworks of test projects to avoid netcoreapp2.1

### ISSUE THREAD

**Issue by NeoXtreem** [elastic/apm-agent-dotnet#315]
The Full Framework unit tests project that was recently added as part of [this commit](https://github.com/elastic/apm-agent-dotnet/commit/7fac5489b99bd5bd73db6139219350e52ac7a23a) and [this PR](https://github.com/elastic/apm-agent-dotnet/pull/273) along with the `MockApmServer` project is structured incorrectly in terms of target frameworks.

It appears that the test project targets .NET Core because of its dependencies when it should of course target .NET Framework.  This is causing build issues under certain configurations that would be resolved by splitting the dependencies properly and targeting the correct frameworks concordantly.

To start with, `Elastic.Apm.AspNetFullFramework.Tests` should target `net461` as `Elastic.Apm.AspNetFullFramework` targets this framework.  `Elastic.Apm.Tests`, `Elastic.Apm.PerfTests` and `Elastic.Apm.DockerTests` should target `netstandard2.0` or `netstandard2.0;net461` (conditionally) as `Elastic.Apm` targets this framework.

Any references to types in `Elastic.Apm.Tests.MockApmServer` should be split out to a new project that targets `netstandard2.0` so there is no need to reference `Elastic.Apm.Tests.MockApmServer` directly and therefore no need to target `netcoreapp2.1` in the test projects, especially the Full Framework one!

**Comment by gregkalapos** [comment]
Thanks for the input. I think this is addressed by #306 (which also leads to some comments in the referenced PR).

@NeoXtreem Do you feel this is a duplicate? Maybe we could just add you comment to #306.

**Comment by NeoXtreem** [comment]
@gregkalapos No, I don't think that's the same issue. That issue is to do with SDK installations on different OSs and therefore having a new VS solution to remove a hack. The issue I've raised is about the target frameworks in relation to the unit test projects.

But I strongly recommend approving [my PR](https://github.com/elastic/apm-agent-dotnet/pull/309) soon so that the unit test projects are cleaner and therefore easier to work with in this respect. I [cleanly merged](https://github.com/elastic/apm-agent-dotnet/pull/309/commits/88bb014f2e15a9d34209f80a74d88f96acbd97fb) all the Full Framework test code into the fork recently, but I think delaying it much longer may result in further issues like this as the test code is not currently lean or clean to work with, and my PR resolves that.

**Comment by gregkalapos** [comment]
Ok let's keep this open. 

1 discussion on this: https://github.com/elastic/apm-agent-dotnet/pull/273#discussion_r295224433

**Comment by russcam** [comment]
`Elastic.Apm.AspNetFullFramework.Tests` now targets net5.0 with dependencies on two projects that target net461, that are referenced only on Windows

- Elastic.Apm.AspNetFullFramework

  This is to test extracting of SOAP actions only and is referenced with `<SetTargetFramework>TargetFramework=net461</SetTargetFramework>`

- AspNetFullFrameworkSampleApp

  This is to pull in constants defined for MVC routes in the application, which could arguably be moved to the test project.

Neither has really been an issue with running tests locally or in CI so I'm closing this issue as unlikely to implement.
