### ISSUE TITLE
Add support for Elasticsearch.Net

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#316]
See https://github.com/elastic/elasticsearch-net/blob/7.x/src/Tests/Tests/ClientConcepts/Troubleshooting/DiagnosticSource.doc.cs#L22

**Comment by lafriks** [comment]
It should be taken into account that elastic calls are already captured by http client listener

**Comment by gregkalapos** [comment]
Work in progress in https://github.com/elastic/apm-agent-dotnet/pull/329

**Comment by gregkalapos** [comment]
Done by @Mpdreamz  in #329.
