### ISSUE TITLE
Revisit "what to capture as service.runtime.{name and version}" question

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#317]
A follow up on discussion started at https://github.com/elastic/apm-agent-dotnet/pull/314#issuecomment-505430010

**Comment by SergeyKleyman** [comment]
It was suggested to keep `service.runtime.name version` as `.NET Framework 4.8.3801.0` ( `.NET Core 2.2.5`) as it's implemented in #314 and add `CLR 2.0` (`CoreCLR 3.0`) as additional fields (TBD what are these additional fields exactly).

**Comment by gregkalapos** [comment]
This is out already since a couple of versions and no complains so far, so I'd say let's keep it as it is.
