### ISSUE TITLE
Agent should allow directing its logs to logging backend used by the application

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#318]
As experience directing agent's log to NLog as part of `AspNetFullFrameworkSampleApp` has shown there is room for improvement:
- It required changes to public API
- It's hard fully integrate with target logging library because current agent API doesn't provide enough support for it. For example `scope` (other libraries call it `category`, `source-context`, etc.) which we use to implement `logger-per-class` pattern is mixed with the message.

I think we should separate logging to front-end and back-end. Agent will own the front-end part whose API the rest of agent's code will call to emit logging events. A back-end is an interface that functions as a sink for front-end. If I want to direct agent's logs to a logging library of my choice I would need to implement back-end interface and register an instance of it via agent's public API. We can implement a few of these "bridges" for most popular logging libraries (each in its package to minimize dependencies) so it's not more than a one line to apply.

Directly related to #228. While #228 is dealing only with supporting .NET Core logging, in this issue we should go broader and while keeping .NET Core logging support we should provide easy way to direct agents logs to a couple other popular logging libraries. For example: 

- [Serilog](https://serilog.net/)
- [NLog](https://nlog-project.org/)
- [log4net](https://logging.apache.org/log4net/)

**Comment by stevejgordon** [comment]
Closing as out of date
