### ISSUE TITLE
EntityFrameworkCore DiagnosticListener throws null ref 

### ISSUE THREAD

**Issue by josiahpeters** [elastic/apm-agent-dotnet#32]
We use IdentityServer4 for our Authentication provider. It is currently configured to use EntityFrameworkCore with SqlServer. A piece of functionality that comes out of the box with IdentityServer4 and EFCore as the backing store is a periodic task that runs in the background that deletes expired tokens from the database.

When this background task runs it triggers the OnNext method of the EfCoreDiagnosticListener. However because this task is not executed within the context of an HttpRequest, no transaction is created. Therefore when the background task executes a null reference exception is thrown because the TransactionContainer.Transactions.Value is null.

**Comment by gregkalapos** [comment]
Thanks! This is indeed a bug.

Once [your PR](https://github.com/elastic/apm-agent-dotnet/pull/33) which fixes this gets merged, this can be closed.

**Comment by gregkalapos** [comment]
Fixed by https://github.com/elastic/apm-agent-dotnet/pull/33 

Thanks!
