### ISSUE TITLE
Verify ProcessTotalCpuTimeProvider works correctly for edge cases

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#333]
Derived from https://github.com/elastic/apm/issues/103

Even though .NET agent implementation does not parse `/proc/self/stat` it uses 
an API provided by .NET runtime and it seems that this API's implementation on Linux does parse `/proc/self/stat`. So it might be worth verifying that it handles all the edge cases mentioned at https://github.com/elastic/apm/issues/103 correctly.

Links to API implementation mentioned so far:
- Here is what happens on Linux:
This is where the managed call ends up:
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs#L361

- And here is how they parse the stat file:
https://github.com/dotnet/corefx/blob/1b6f45ca261467baea62ef577f8b8a7c6cf3b96c/src/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.cs#L219

- The key thing in corefx to notice is the use of `TicksToTimeSpan` which is defined here: https://github.com/dotnet/corefx/blob/007571b90c3cc555cd30f3b467b87c22f9f665e0/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L754-L764

**Comment by gregkalapos** [comment]
I think we are good here. This is covered [here](https://github.com/dotnet/corefx/blob/d3911035f2ba3eb5c44310342cc1d654e42aa316/src/Common/src/System/IO/StringParser.cs#L101)
