### ISSUE TITLE
Investigate how to monitor Entity Framework 6 (EF6) calls with “library-only” approach

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#335]
We agreed that for initial implementation of monitoring Full Framework (#83) we should try to find a way to monitor Entity Framework 6 (EF6) instead ADO.NET (#114).

**Comment by gregkalapos** [comment]
Plan: for release 1.1 we aim to have a simple solution (not covering edge cases)

**Comment by NikoMix** [comment]
I'd like to propose adding Elastic.Apm.EntityFramework Project with a IDbCommandInterceptor which can be individually added via web.-/app.config via 
`<entityFramework>
    <interceptors>
        <interceptor type="Elastic.Apm.EntityFramework.ElasticApmInterceptor, Elastic.Apm.EntityFramework">
        </interceptor>
    </interceptors>
</entityFramework>` 

or via code by using:
`DbInterception.Add(new ElasticApmInterceptor());`

If accepted and no one else is working on this, I can work on a pull-request for it.

**Comment by SergeyKleyman** [comment]
@NikoMix I'm currently working on it and it should be ready in a few days.
