### ISSUE TITLE
Create an umbrella package - Elastic.Apm.NetFrameworkAll

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#336]
After completing support for monitoring Entity Framework 6 (#335) create an umbrella package - `Elastic.Apm.NetFrameworkAll` to bring together `Elastic.Apm.AspNetFullFramework` and `Elastic.Apm.EntityFramework6`.

**Comment by gregkalapos** [comment]
We talked about this in the last planning - since we heard no need from customers&users about it so far, we close it for now.
