### ISSUE TITLE
Make logger less error prone

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#337]
We should find a better solution for #209 - instead of waiting for logger to throw at runtime and still loosing information in the malformed logging statement (but at least with the solution in #209 not crashing the application) we should find a way to prevent creating malformed logging statements to begin with.

For example, we can consider using advanced string interpolation as described here - https://www.meziantou.net/interpolated-strings-advanced-usages.htm

**Comment by stevejgordon** [comment]
Closing as we have no plans to make any changes in the near future
