### ISSUE TITLE
Support dotnet core 2.0.0 versioned dependencies

### ISSUE THREAD

**Issue by josiahpeters** [elastic/apm-agent-dotnet#34]
While trying to pull in packages for ElasticApm that I built locally into a project I ran into some dependency issues. 

Currently the libraries reference these versions:
`Microsoft.AspNetCore.Http.Abstractions` Version `2.1.1`
`Microsoft.Extensions.Configuration.Abstractions` Version `2.0.2`

Our IdentityServer4 impelementation currently references these dependency versions:
`Microsoft.AspNetCore.Http.Abstractions` Version `2.0.0`
`Microsoft.Extensions.Configuration.Abstractions` Version `2.0.0`

We created our project right after 2.0.0 came out and haven't gotten around to updating. (We can and should update.) I was able to tweak the version numbers manually and build a new package and get the application running. However, it made me wonder if it would be worth targeting those dependency versions as a decision to try and support 2.0.0 outright.

I'll submit a PR with the change and let you decide if it makes sense.

**Comment by gregkalapos** [comment]
Fixed by @josiahpeters in https://github.com/elastic/apm-agent-dotnet/pull/35. 

Thank you!
