### ISSUE TITLE
Go over other agents documentation to see if .NET agent documentation is missing anything that is applicable to it at the current state

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#341]
Documentation related items that other agents have and we should consider adding to .NET agent documentation:
- Troubleshooting section (for example [Java agent's](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html)) - Opened https://github.com/elastic/apm-agent-dotnet/issues/483 to follow up
    - https://github.com/elastic/apm-dev/issues/425#issuecomment-490757036
- Frequently Asked Questions section (for example [Java agent's](https://www.elastic.co/guide/en/apm/agent/java/current/faq.html)) - Opened https://github.com/elastic/apm-agent-dotnet/issues/484 to follow up

**Comment by SergeyKleyman** [comment]
@gregkalapos i went over documentation of the other agents and I listed the items I've found. Do you think there is anything else?

**Comment by gregkalapos** [comment]
It looks ok to me.

Ping @bmorelli25 - I think we have a spreadsheet about this topic.

**Comment by bmorelli25** [comment]
Looking at https://github.com/elastic/apm-dev/issues/425, I think you'll be good to go with the two additions @SergeyKleyman recommended.

**Comment by SergeyKleyman** [comment]
Opened https://github.com/elastic/apm-agent-dotnet/issues/483 and https://github.com/elastic/apm-agent-dotnet/issues/484 to follow up.
