### ISSUE TITLE
Investigate if IIS ElasticApmModule can be used as standalone module to monitor all applications

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#343]
Investigate if `ElasticApmModule` IIS HTTP module we implemented to support Full Framework ASP.NET can be used in as a standalone module (configured at the machine level instead of per application) to monitor all applications without requiring to modify each application's configuration.
- If this use case can be supported without significant effort we should document how to deploy `ElasticApmModule` module for this use case.
- If this use case cannot be supported without significant effort we should document this fact (as a limitation?).

**Comment by bmorelli25** [comment]
👋 Sorry to dredge this up from the depths, but I wanted to see if there's anything I can help with on this issue? I'm going through very old doc issues and this one is near the top. Let me know!

**Comment by stevejgordon** [comment]
Closing as something we don't plan to pursue at the present time.
