### ISSUE TITLE
Add source analyzer to verify that the class used to create logger is correct

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#344]
At the moment when creating a logger name/type of the current class is provided: 
```
_logger = loggerArg.Scoped(nameof(MyClass));
```
or in the upcoming proposal for logger improvements (#345):
```
_logger = loggerFactory.GetLogger<MyClass>();
```
An error can be easily introduced when copying & pasting this code between classes.

One approach to solve this problem is to introduce a mechanism similar to [NLog's GetCurrentClassLogger()](https://github.com/nlog/nlog/wiki/Tutorial#Writing-log-messages) but it's a brittle solution relying on JIT settings of the code creating the logger (for example see https://github.com/NLog/NLog/issues/2900).
 
Another approach to consider is similar to the one suggested at https://github.com/elastic/apm-agent-dotnet/issues/208#issuecomment-507786174 - implement source analyzer (for example using Roslyn) that will verify that the class used to create logger is correct. The analyzer can be invoked as a unit test and fail the build if the verification fails.

**Comment by gregkalapos** [comment]
This is not high prio at this point - closing for now.
