### ISSUE TITLE
Implement remote (AKA central) configuration

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#352]

**Comment by SergeyKleyman** [comment]
Do we already have an issue for this - https://github.com/elastic/apm-agent-dotnet/issues/190 ?

**Comment by gregkalapos** [comment]
From #190:

> .NET Agent implementation issue derived from [elastic/apm#76](https://github.com/elastic/apm/issues/76).
> 
> See #320 as a prerequisite for this one.
> 
> [elastic/apm-dev#553](https://github.com/elastic/apm-dev/issues/553) - the name for this feature to use in agent's docs.

**Comment by gregkalapos** [comment]
Overlooked  #190 👼  - closing it, since we already prioritised this one.

**Comment by SergeyKleyman** [comment]
https://github.com/elastic/apm-server/pull/2407#issuecomment-509680789 is related.

**Comment by bmorelli25** [comment]
I'll be on vacation when you implement this feature. Here's some boilerplate documentation you can hopefully adapt to match your config style: https://github.com/elastic/apm/issues/86. Also, don't forget to mention precedence.

**Comment by SergeyKleyman** [comment]
A relevant change - https://github.com/elastic/apm/pull/118

It is worth reading through https://github.com/elastic/apm/blob/master/docs/agent-development.md#apm-agent-configuration-via-kibana before implementation.

**Comment by SergeyKleyman** [comment]
Configuration option to enable/disable agent's polling for central configuration - https://github.com/elastic/apm/issues/76#issuecomment-509379996

**Comment by SergeyKleyman** [comment]
Configuration option to enable/disable agent's polling APM server for configuration - https://github.com/elastic/apm/pull/119, https://github.com/elastic/apm/issues/76#issuecomment-509379996

**Comment by SergeyKleyman** [comment]
https://www.elastic.co/guide/en/kibana/7.3/agent-configuration.html
