### ISSUE TITLE
Sanitize tag keys ie. "de-dotting"

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#353]
From https://github.com/elastic/apm/issues/14

**Comment by SergeyKleyman** [comment]
Is it just "de-dotting" or do tag keys have more constrained charset?
The reason I'm asking is because we currently do "de-dotting" on `service.name` while allowed charset for `service.name` is more constrained than that - https://github.com/elastic/apm-agent-dotnet/issues/340

**Comment by gregkalapos** [comment]
This was only about de-dotting. Done in https://github.com/elastic/apm-agent-dotnet/pull/591.
