### ISSUE TITLE
Rename Tags to Labels

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-dotnet#355]
See https://github.com/elastic/apm/issues/42

**Comment by gregkalapos** [comment]
We should have done that before the beta release 🤦‍♂ 

Anyway... we missed that opportunity. 

Next question: do we wanna do this before we GA? (hint: #breakingchange)

**Comment by SergeyKleyman** [comment]
@gregkalapos Just to make sure it doesn't fall off the radar - we want to make this change in 1.0, right?

**Comment by gregkalapos** [comment]
Yes, I think it's still our best option.

It's just a rename and making sure the docs is ok.

**Comment by gregkalapos** [comment]
Hmm.. or since we are overbooked - should we wait? 

I just thought it's an API breaking change, so let's get this behind us as early as possible - on the other hand we are already overbooked.

**Comment by SergeyKleyman** [comment]
We can give it low priority.

**Comment by gregkalapos** [comment]
> We can give it low priority.

Sounds good!

**Comment by gregkalapos** [comment]
@katzdan - maybe this is a good first issue.

We have this [`IExecutionSegment.Tags`](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Api/IExecutionSegment.cs#L40) - usually forwarded this [this field](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Api/Context.cs#L33). 

To be aligned with the ECS (Elastic Common Schema) we decided to rename this field. We also have [some documentation to adapt](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/public-api.asciidoc).

**Comment by SergeyKleyman** [comment]
@gregkalapos there is `good first issue` label you can use to mark issues.
