### ISSUE TITLE
Agent's public API should allow user to register filters similar to those of node.js agent

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#361]
[Documentation for node.js agent filters feature](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-add-filter)

We should consider invoking registered filter(s) earlier than "just before sending to APM server" and with more context the just event object that we captured (span, transaction, etc.). For example in order to support solution proposed at https://github.com/elastic/apm-agent-dotnet/issues/360#issuecomment-508797877 filter will have to receive both DB span instance (to which `Context` the filter will add custom tag/label) but also filter needs to receive instance of `Microsoft.EntityFrameworkCore.Diagnostics.CommandExecutedEventData` because the filter needs the value of `CommandExecutedEventData.Result` property to set the value for the above mentioned custom tag/label.

**Comment by gregkalapos** [comment]
Done in #792.
