### ISSUE TITLE
Update diagram at https://www.elastic.co/solutions/apm to include .NET

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#368]
At the moment the diagram at https://www.elastic.co/solutions/apm looks as follows:

![image](https://user-images.githubusercontent.com/7782093/60766615-c9b2b380-a0b4-11e9-8a3a-50611a9a4b9c.png)

**Comment by gregkalapos** [comment]
I think this can be closed - there is no diagram on the new site. 

On the other hand there is an `Instrument your X app` section with installation instructions, maybe .NET should be on that list. @jamiesmith who should we talk to abut that? I guess an issue in this repo won't have enough visibility for that.

**Comment by jamiesmith** [comment]
That's what we were chatting about yesterday.  The .NET instruction module should go out with 7.3

**Comment by gregkalapos** [comment]
> That's what we were chatting about yesterday. The .NET instruction module should go out with 7.3

Oh, I see, that's awesome! Did not realize that it's for the website :) Great, thx!
