### ISSUE TITLE
Fix flaky test - Elastic.Apm.Tests.MetricsTests.MetricsWithRealAgent

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#378]
For example it failed when testing changes from [PR #375](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/PR-375/3/pipeline/#step-160-log-531) and [PR #380](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/PR-380/2/pipeline/143/#step-185-log-490) even though those PRs did not change anything related to the test.

Currently the test instructs agent to collect metrics every second and wait 2.2 seconds for the agent to collect metrics at least once. It seems that agent doesn't get an opportunity to collect metrics even during 2.2 seconds. We can either investigate why it happens (Does the timer even starts during 2.2 seconds? If it does then why it cannot complete in time?) or we can just increase wait time (let's say to 10 instead of 2.2 seconds) and see if it helps.

**Comment by gregkalapos** [comment]
I opened #385 to address this.

It's very strange. I `XunitOutputLogger`, probably the logs will help. 

> or we can just increase wait time 
I think it's also worth doing it - did also that in the PR.

**Comment by gregkalapos** [comment]
I think this is ok to close since #385 is merged. I'd just close this and if the test fails again we can reopen this. I think it's better than leaving it open and "wait" for failing again.

Anything against that?

**Comment by SergeyKleyman** [comment]
I agree - we can close it.
