### ISSUE TITLE
Capture request body in ASP.NET Full Framework

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#379]
Derived from #213,

**Comment by katzdan** [comment]
I can start working on this one. I might need some guidance though. 
I'm assuming that the implementation should be identical to what's written in the docs (https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-body).

**Comment by SergeyKleyman** [comment]
Here are the links to all other Elastic APM agents that already have this feature implemented (I've taken them from [Elastic APM Backend Agent Config Comparison spreadsheet](https://docs.google.com/spreadsheets/d/1JJjZotapacA3FkHc2sv_0wiChILi3uKnkwLTjtBmxwU/))
- Java - https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-capture-body
- Node.js - https://www.elastic.co/guide/en/apm/agent/nodejs/current/configuration.html#capture-body
- Ruby - https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-capture-body
- Python - https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-capture-body

I would recommend to start with the requirements for this feature by going over other agents' documentation for this feature to make sure requirements for .NET agent align with the other agents.

**Comment by gregkalapos** [comment]
@katzdan it's totally fine if you start with this, just some thoughts:

Our ASP.NET Core part is more advanced, and the ASP.NET Full Framework project is not yet released. So #213 is maybe a better candidate to make it into production sooner - also writing tests is I think simpler for that case - although for Full Framework we already also have a nice setup, but it maybe needs more learning, the ASP.NET Core tests are simpler in-process tests.

**Comment by katzdan** [comment]
I'll start with #213 then. Thanks.

**Comment by andrewharry** [comment]
Can you consider including redacting requirement?  I often have business requirements to ensure sensitive data such as credit cards are not accidentally logged.

This could be as simple as some kind of regex replacement...

**Comment by gregkalapos** [comment]
> Can you consider including redacting requirement? I often have business requirements to ensure sensitive data such as credit cards are not accidentally logged.
> 
> This could be as simple as some kind of regex replacement...

@andrewharry thanks for the input. 

That'd be covered by https://github.com/elastic/apm-agent-dotnet/issues/300. We already have an [ongoing PR](https://github.com/elastic/apm-agent-dotnet/pull/402) by @katzdan. I'd say in the first round we won't do it - just to reduce the scope and make sure that at least some part of the feature lands soon. In #300 we'll come back to it.

**Comment by Sarabjit-Tatra** [comment]
@gregkalapos - I would like to work on this so want to understand if someone has already submitted their work for it or not ?
If no one has yet submitted their work on this than based on code review it seems we have Elastic.Apm.AspNetFullFramework project which is created for ASP.Net Full framework application's instrumentation and ElasticApmModule.cs is having code related to monitoring of ProcessBeginRequest which seems to right point to investigate it further, so let me know if I am in right direction for this ?

**Comment by gregkalapos** [comment]
>  I would like to work on this so want to understand if someone has already submitted their work for it or not ?

Awesome! So far there is no PR for this, so feel free to work on it.

> based on code review it seems we have Elastic.Apm.AspNetFullFramework project which is created for ASP.Net Full framework application's instrumentation and ElasticApmModule.cs is having code related to monitoring of ProcessBeginRequest which seems to right point to investigate it further, so let me know if I am in right direction for this ?

Yes, that's all correct - so `ElasticApmModule.cs` is a good entry point for this feature. `ElasticApmModule.cs` is basically an IIS module we use for capturing requests for ASP.NET Classic.

The same feature (capturing request body) already exists for ASP.NET Core. [Here](https://github.com/elastic/apm-agent-dotnet/blob/main/src/Elastic.Apm.AspNetCore/WebRequestTransactionCreator.cs#L116) you can see how it works in that case. There are 2 configs related to this feature - docs [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-capture-body) and [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-http.html#config-capture-body-content-types).

Just ping me if you have any question.
