### ISSUE TITLE
Agent should not have unlimited size collections to prevent unbounded memory consumption

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#387]
At the moment we have the following collections that don't have any limit on their size:
- `Elastic.Apm.DiagnosticListeners.HttpDiagnosticListenerImplBase.ProcessingRequests`
- `Elastic.Apm.EntityFrameworkCore.EfCoreDiagnosticListener._spans`
- `Elastic.Apm.CurrentExecutionSegmentsTracker.TrackerStack._stack`
- `SingleThreadTaskScheduler._taskQueue`

We should define an upper bound on the size of of each collection and implement an eviction strategy to ensure that size stays under the upper bound.

**Comment by stevejgordon** [comment]
We have no plans to implement this and no reported issues that incline us to prioritise it.
