### ISSUE TITLE
Source analyzer to improve agent's implementation quality

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#392]
- `nameof` usages that can be checked automatically by source analyzer
    - Add source analyzer to verify that the class used to create logger is correct #344
    - `Elastic.Apm.Helpers.ToStringBuilder`
    - `Elastic.Apm.Helpers.ContractExtensions.ThrowIfArgumentNull`
    - Find other usage of `nameof` that can be checked automatically by a source code analyzer

**Comment by stevejgordon** [comment]
Closing as no plans to implement this currently.
