### ISSUE TITLE
Source code analyzers to detect and fix code using agent's public API

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#395]
Consider publishing NuGet package with source code analyzers (based on Roslyn?) to detect and fix user code using agent's public API.

Potential code issues to detect and propose fix:
- Using `CurrentTransaction`/`CurrentSpan` without checking for `null`

References:
- [Analyzer NuGet formats](https://docs.microsoft.com/en-us/nuget/reference/analyzers-conventions)
- [Overview of .NET Compiler Platform analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019)
- [How to package analyzers? #26222](https://github.com/dotnet/roslyn/issues/26222)
- [xUnit Roslyn analyzers](https://davidpine.net/blog/xunit-powered-by-roslyn/)
- [JetBrains Rider - Using .NET Compiler Platform (Roslyn) Analyzers](https://www.jetbrains.com/help/rider/Using_NET_Compiler_Analyzers.html)

**Comment by stevejgordon** [comment]
Closing as no plans to implement this currently.
