### ISSUE TITLE
What is the best way to create integration with different ORMs?

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#396]
Does such integrations should be located at this repository or should be situated as self-repository?
E.g., `Serilog` uses strategy of various repositories, `AppMetrics` uses strategy of mono repository.

**Comment by gregkalapos** [comment]
The current approach is to create a new project under the [`src` folder](https://github.com/elastic/apm-agent-dotnet/tree/master/src) in this repository. From each project we generate a separate NuGet package. That seem to work for us well atm.

For which ORM would you like to build support? Is there anything that would cause trouble there?

**Comment by vhatsura** [comment]
I want to add support for mongodb C# driver, however, driver isn't used [`DiagnosticSource` approach](https://jira.mongodb.org/browse/CSHARP-1639).

**Comment by gregkalapos** [comment]
> I want to add support for mongodb C# driver, however, driver isn't used [`DiagnosticSource` approach](https://jira.mongodb.org/browse/CSHARP-1639).

Nice that you plan to do this! ...and sad they don't use DiagnosticSource yet. If I remember some version has a diagnostic API, or am I mistaken? - I'm not totally sure, I searched quickly but haven't found it. 

If I understand correctly [MiniProfiler wraps it](https://github.com/MiniProfiler/dotnet/tree/master/src/MiniProfiler.Providers.MongoDB) - that's a less nice approach, but maybe it's worth looking at it for ideas.

Back to your original question: we are discussing internally where these packages should go - I think as for now starting in this repo is fine - maybe we'll suggest to move it out, but currently I think the easiest would be to start here.

**Comment by vhatsura** [comment]
Got it, thanks. Will start work.

As for getting diagnostic data from mongodb client, it isn't a problem: mongodb c# client have ability to [subscribe for events](https://www.mattburkedev.com/logging-queries-from-mongodb-c-number-driver/)

**Comment by gregkalapos** [comment]
Awesome! 🎉 

> The last question: do I need to create a separate issue for this?

Yeah, let's create an issue specifically for mongodb, just for better visibility. Also feel free to create a draft pull request and ping us in case you need any help.

Thanks for all your great effort! 

I'm closing this now, I guess this question is answered.
