### ISSUE TITLE
Should trim strings read from environment

### ISSUE THREAD

**Issue by rickardp** [elastic/apm-agent-dotnet#407]
**Describe the bug**
It is quite common for strings read from environment to contain whitespaces. A typical example is when they are populated from Kubernetes secrets.

**To Reproduce**
1. Append newline to end of ELASTIC_APM_SERVER_URLS
2. Start APM
4. Error: Failed parsing server URL from environment: ELASTIC_APM_SERVER_URLS, value: ...

**Expected behavior**
While possible to work around, it is an annoyance that could easily be mitigated by trimming whitespace. Expected behavior is then that above string should be parsed successfully.

**Comment by gregkalapos** [comment]
Yeah, let's fix this!

Already ongoing on https://github.com/elastic/apm-agent-dotnet/pull/408. 

Thanks @rickardp!

**Comment by gregkalapos** [comment]
Merged #408 which fixes this - thanks @rickardp.
