### ISSUE TITLE
service.name should be limited to 1024 characters

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#412]
According to elastic apm server specification, service name should be limited to 1024 characters
https://github.com/elastic/apm-server/blob/7b716ad540a68d0f95060340651d4ec5dbfdc017/docs/spec/service.json#L55

**Comment by gregkalapos** [comment]
Yeah, missing `[JsonConverter(typeof(TrimmedStringJsonConverter))]` [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Api/Service.cs#L17). 

Thanks for reporting!
