### ISSUE TITLE
filter resource file request

### ISSUE THREAD

**Issue by hiwjcn** [elastic/apm-agent-dotnet#418]
> drop those

![](https://github.com/hiwjcn/file-store/raw/master/TIM%E6%88%AA%E5%9B%BE20190730160502.png)

**Comment by gregkalapos** [comment]
You don't want the agent to capture those, right?

Some options we can do here:
- Add a config to disable capturing those (e.g. based on extension)
- Not capturing those et all (probably not the way to go)
- Do something on the UI/APM Server 

I'm also asking on other channels what other agents do.

**Comment by gregkalapos** [comment]
Here is what the Java agent does: https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-ignore-urls

**Comment by SergeyKleyman** [comment]
@hiwjcn Could you add a little bit more about your use case? I have a feeling that you might be using `ElasticApmModule` from `Elastic.Apm.AspNetFullFramework` - is it correct? If so please take a look at https://github.com/elastic/apm-agent-dotnet/issues/346 - by adding [`managedHandler` to modules `precondition`](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/modules/add) monitoring can be limited to dynamic pages (URLs handled by ASP.NET) excluding static content.

**Comment by hiwjcn** [comment]
@SergeyKleyman hey bro,im using asp.net core

``` c#
Elastic.Apm.All, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ae7400d2c189cf22

app.UseElasticApm(config);
```
and configuration like this:
``` json
  "ElasticApm": {
    "LogLevel": "Debug",
    "ServerUrls": "http://3h.elk.hiwj.cn:8200",
    "TransactionSampleRate": 1.0
  }
```

**Comment by hiwjcn** [comment]
@SergeyKleyman @gregkalapos is there any api like this:
``` c#
app.UseElasticApm(config,option=>
{
option.filter.add(url=>!url.endwith(".css"));
option.filter.add(url=>!url.endwith(".js"));
option.filter.add(url=>regex.match(url));
});
```

**Comment by gregkalapos** [comment]
> @SergeyKleyman @gregkalapos is there any api like this:
> 
> ```cs
> app.UseElasticApm(config,option=>
> {
> option.filter.add(url=>!url.endwith(".css"));
> option.filter.add(url=>!url.endwith(".js"));
> option.filter.add(url=>regex.match(url));
> });
> ```

No, we don't have it in .NET. We know other agent have similar filters. We already had some initial discussion about this, no final decision if we add it to .NET or not - probably it'd make sense to add it.

**Comment by gregkalapos** [comment]
Also related: https://discuss.elastic.co/t/how-to-exclude-signalr-requests-from-collected-transactions/203848

**Comment by gregkalapos** [comment]
Some update on this:
In #792 we introduced a filter API - with that you'll be able to filter out specific requests. This feature will be out with the next release.
