### ISSUE TITLE
Add support for Custom fields

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#419]
Can not reopen original issue https://github.com/elastic/apm-agent-dotnet/issues/116 

Per last conversation on APM discussion https://github.com/elastic/apm/issues/7 it was decided to stay with custom. 
It will good to have that in APM agent.

Thanks,
Stas

**Comment by SergeyKleyman** [comment]
@skynet2 Could you please give an example as to why you would like to use `custom` part of the `context` and not `labels`?

**Comment by SergeyKleyman** [comment]
@skynet2 I see that you already gave an example at https://github.com/elastic/apm-agent-dotnet/pull/118#issuecomment-466071721

>  the reason why i decided to use custom is that it can save big objects, for example, requests and response.

**Comment by SergeyKleyman** [comment]
BTW I see that Java agent 1.7.0 added support for custom context. Other agents support custom context as well:
- [Java](https://www.elastic.co/guide/en/apm/agent/java/current/public-api.html#api-transaction-add-custom-context)
- [Node.js](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-set-custom-context)
- [Python](https://www.elastic.co/guide/en/apm/agent/python/current/api.html#api-set-custom-context)
- [Ruby](https://www.elastic.co/guide/en/apm/agent/ruby/current/api.html#api-agent-set-custom-context)
- [Go](https://www.elastic.co/guide/en/apm/agent/go/current/api.html#context-api) (it's not clear if Go agent supports custom context)

@axw Does Go agent support custom context?

**Comment by skynet2** [comment]
Hi @SergeyKleyman , 
Yep, go agent has support for that https://github.com/elastic/apm-agent-go/issues/594#issuecomment-513615134

**Comment by alexandre-sampaio** [comment]
Hi! is anyone working on it?
I need this to save the body from response, maybe there is another way, but i didn't find it.

**Comment by skynet2** [comment]
@alexandre-sampaio for as a temporary solution use Request.Body. According to APM specification it can be both, string or object., so for me its simple key-value pairs.

**Comment by gregkalapos** [comment]
Implemented in #585 - will be included in the next minor release.
