### ISSUE TITLE
Verify agent's payload against APM server's Intake API spec

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#421]
For example it would have helped us
- To avoid introducing this bug - https://github.com/elastic/apm-agent-dotnet/issues/420
- When we introduce a new property that has a constraint (for example max length) and forget to enforce the constraint

We can place verification of agent's payload against APM server's Intake API spec at:
- Elastic.Apm.Tests.MockApmServer
- Maybe somewhere in `Elastic.Apm.Tests.SerializationTests`?

Or maybe we can have dedicated tests (static source code analysis or runtime fuzz testing) that verify that agent's output is compliant with API spec and not just based on data generated by other tests?

**Comment by SergeyKleyman** [comment]
To continue discussion from https://github.com/elastic/apm-agent-dotnet/pull/413#discussion_r315548965:

>Hm, I believe we can have two options:

> 1. Analyzer which will analyze conformity according to the spec. However, it's expensive and only needed in this repo.
> 2. Unit test which will check conformity according to the spec through reflection. However, the main point which we want to cover is maxLength. In such case we can check only presence of `JsonConverter` attribute with proper converter. However, as I see, `maxLength` is set not for all string properties in the spec.

> I believe the 2nd option is more realistic. The only once question is do we need parse spec or we can specify certain classes which will be tested. WDYT? 

So if I understand you correctly the options you propose are
1. Static analysis of the source code (that is what you mean by "analyzer", did I understand you correctly?)
2. Runtime verification by instantiating a model, setting the model properties to the values that don't satisfy the constraints (somewhat similar to fuzz testing), serializing to JSON and asserting expected output.

I agree that the 2nd option is easier to implement (I assume that is what you mean by "more realistic", right?) and its additional advantage is that we will also make sure agent serializes invalid values correctly although at the moment there's low chance of a bug in that area since the implementation is just adding an attribute so it is very declarative.

I'm not sure I understand what exactly you mean by
>  do we need parse spec or we can specify certain classes which will be tested

If we don't get constraints automatically by parsing the spec and instead manually add them won't we be back to the original problem where we frequently forget to set the constraint on a new property so it's very likely we will forget adding a test for those constrains as well. WDYT?

**Comment by gregkalapos** [comment]
@russcam in https://github.com/elastic/apm-agent-dotnet/pull/984 you did a lot of work that mostly covers this.

I think this can be closed - if you agree feel free to hit "Close" on this.
