### ISSUE TITLE
APM server docs still refer to .NET Labels as Tags 

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#423]
See https://www.elastic.co/guide/en/apm/get-started/7.3/metadata.html#labels-fields

**Comment by gregkalapos** [comment]
Opened https://github.com/elastic/apm-server/pull/2671, I think there is nothing more to do in this repo - unless there is something against it, I'd close this.

**Comment by gregkalapos** [comment]
Fixed in https://github.com/elastic/apm-server/pull/2671 - already merged.
