### ISSUE TITLE
Null pointer in PayloadSenderV2

### ISSUE THREAD

**Issue by skynet2** [elastic/apm-agent-dotnet#428]
Having that error on remote server, but can not reproduce on local
```
Aug  3 01:22:24 server1 integration[4834]: [2019-08-02 11:22:24][Debug] - {Tracer} Starting Transaction{Id: 8525f9f45ad1798f, TraceId: 1b20305c5f76358cb3424438c407522f, ParentId: null, Name: POST /api/xx/deposit, Type: request, IsSampled: True}
```
Then there is a bunch of spans from entity framework 

And last lines are : 
```
Aug  3 01:22:26 server1 integration[4834]: [2019-08-02 11:22:26][Debug] - {PayloadSenderV2} Transaction added to the queue, Transaction{Id: 8525f9f45ad1798f, TraceId: 1b20305c5f76358cb3424438c407522f, ParentId: null, Name: POST Xx/Deposit, Type: request, IsSampled: True}
Aug  3 01:22:26 server1 integration[4834]: [2019-08-02 11:22:26][Debug] - {Transaction} Ending Transaction{Id: 8525f9f45ad1798f, TraceId: 1b20305c5f76358cb3424438c407522f, ParentId: null, Name: POST Xx/Deposit, Type: request, IsSampled: True}
Aug  3 01:22:26 server1 integration[4834]: [2019-08-02 11:22:26][Warning] - {PayloadSenderV2} Failed sending events. Following events were not transferred successfully to the server:
Aug  3 01:22:26 server1 integration[4834]: Span{Id: 8bb96752463c20a8, TransactionId: 8525f9f45ad1798f, ParentId: 8525f9f45ad1798f, TraceId: 1b20305c5f76358cb3424438c407522f, Name: SELECT x.id, x.extra, x.game_id, x."order", x.partner_aggregator_id, x.product_type, x.status, "x.Game".id, "x.Game".device_type, "x.Game".external_id, "x.Game".extra, "x.Game".has_demo, "x.Game".image_url, "x.Game".provider_id, "x.Game".recalled_at, "x.Game".released_at, "x.Game".status, "x.Game".token
Aug  3 01:22:26 server1 integration[4834]: FROM common.partner_games_new AS x
Aug  3 01:22:26 server1 integration[4834]: INNER JOIN common.partner_aggregators AS "x.PartnerAggregator" ON x.partner_aggregator_id = "x.PartnerAggregator".id
Aug  3 01:22:26 server1 integration[4834]: INNER JOIN common.games AS "x.Game" ON x.game_id = "x.Game".id
Aug  3 01:22:26 server1 integration[4834]: WHERE (("x.Game".external_id = @__gameExtId_0) AND EXISTS (
Aug  3 01:22:26 server1 integration[4834]:     SELECT 1
Aug  3 01:22:26 server1 integration[4834]:     FROM common.aggregator_games AS y
Aug  3 01:22:26 server1 integration[4834]:     INNER JOIN common.aggregators AS "y.Aggregator" ON y.aggregator_id = "y.Aggregator".id
Aug  3 01:22:26 server1 integration[4834]:     WHERE "y.Aggregator".type IN (9) AND ("x.Game".id = y.game_id))) AND "x.PartnerAggregator".partner_id IN (4)
Aug  3 01:22:26 server1 integration[4834]: LIMIT 1, Type: db, IsSampled: True},
Aug  3 01:22:26 server1 integration[4834]: Span{Id: 9c0999c76d9d3327, TransactionId: 8525f9f45ad1798f, ParentId: 8525f9f45ad1798f, TraceId: 1b20305c5f76358cb3424438c407522f, Name: UPDATE xx.rounds SET is_finished = @p0
Aug  3 01:22:26 server1 integration[4834]: WHERE id = @p1;
Aug  3 01:22:26 server1 integration[4834]: INSERT INTO xx.transactions (amount, client_id, created_at, currency, external_id, game_external_id, partner_game_id, round_id, status, token, type)
Aug  3 01:22:26 server1 integration[4834]: VALUES (@p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12)
Aug  3 01:22:26 server1 integration[4834]: RETURNING id;
Aug  3 01:22:26 server1 integration[4834]: , Type: db, IsSampled: True},
Aug  3 01:22:26 server1 integration[4834]: Transaction{Id: 8525f9f45ad1798f, TraceId: 1b20305c5f76358cb3424438c407522f, ParentId: null, Name: POST Xx/Deposit, Type: request, IsSampled: True}
Aug  3 01:22:26 server1 integration[4834]: Exception: System.NullReferenceException, Message: Object reference not set to an instance of an object.
```
Any ideas about Exception: System.NullReferenceException, Message: Object reference not set to an instance of an object. ?

**Comment by SergeyKleyman** [comment]
Could you include the stack trace for the exception, please?

**Comment by skynet2** [comment]
Hi @SergeyKleyman ,

It`s not logged, i gave a full output which I can find...

**Comment by SergeyKleyman** [comment]
Are you sure you are using 1.0.0 (https://www.nuget.org/packages/Elastic.Apm/1.0.0) because there is only one logging statement with the phrase "Following events were not transferred successfully to the server"  but it looks different in 1.0.0 source code - https://github.com/elastic/apm-agent-dotnet/blob/1.0.0/src/Elastic.Apm/Report/PayloadSenderV2.cs#L176

**Comment by skynet2** [comment]
Yes, you are right @SergeyKleyman im using     
```<PackageReference Include="Elastic.Apm.All" Version="1.0.0-beta1" />```
Strange, looks like it was removed from nuget.

**Comment by gregkalapos** [comment]
> Yes, you are right @SergeyKleyman im using
> `<PackageReference Include="Elastic.Apm.All" Version="1.0.0-beta1" />`
> Strange, looks like it was removed from nuget.
> 
> Ill try to update to latest version tomorrow and ping you with the results, thanks :)

We renamed that package. It's now called [Elastic.Apm.NetCoreAll](https://www.nuget.org/packages/Elastic.Apm.NetCoreAll/).

More about it in https://github.com/elastic/apm-agent-dotnet/pull/371 

Sorry for the confusion. On the release we listed some of our breaking changes: https://github.com/elastic/apm-agent-dotnet/releases/tag/1.0.0

**Comment by skynet2** [comment]
Ok thanks @SergeyKleyman and @gregkalapos 

Just a small question, on test env I have latest apm 7.2 on another env i have 6.6 
I can see that in 1.0.0 version you are using Labels instead of tags, so my question is if 1.0.0 is compatible with APM Server 6.x ?

Thanks,
Stas

**Comment by SergeyKleyman** [comment]
`Tags` to `Labels` change is just for .NET agent's public API - .NET agent still sends `Labels` as `tags` to APM Server Intake API.

**Comment by gregkalapos** [comment]
> Ok thanks @SergeyKleyman and @gregkalapos
> 
> Just a small question, on test env I have latest apm 7.2 on another env i have 6.6
> I can see that in 1.0.0 version you are using Labels instead of tags, so my question is if 1.0.0 is compatible with APM Server 6.x ?
> 
> Thanks,
> Stas

Yes, 6.6. should be ok. Specifically to that change: the JSON we send is still uses `tags`, so it only changed on the API.

**Comment by skynet2** [comment]
Good news, i was able to reproduce it locally with 1.0.0. 
cc @gregkalapos @SergeyKleyman 
```qa0 gaming-integration[32530]: Connection id "0HLONL5STNQTH" disconnecting.
Aug  2 19:28:30 srv gaming-integration[32530]: #033[40m#033[1m#033[33mwarn#033[39m#033[22m#033[49m: Elastic.Apm[0]
Aug  2 19:28:30 srv gaming-integration[32530]: {PayloadSenderV2} Failed sending events. Following events were not transferred successfully to the server (http://logs:8200/):
Aug  2 19:28:30 srv gaming-integration[32530]: Transaction{Id: 6eae9ea3b9459483, TraceId: 71e10d4cf7516fa9645c075707ae57b8, ParentId: null, Name: POST Xx/Withdraw, Type: request, IsSampled: True}
Aug  2 19:28:30 srv gaming-integration[32530]: System.ArgumentNullException: Value cannot be null.
Aug  2 19:28:30 srv gaming-integration[32530]: Parameter name: input
Aug  2 19:28:30 srv gaming-integration[32530]: at Elastic.Apm.Helpers.ContractExtensions.ThrowIfArgumentNull[T](T arg, String argName)
Aug  2 19:28:30 srv gaming-integration[32530]: at Elastic.Apm.Report.Serialization.LabelsJsonConverter.WriteJson(JsonWriter writer, Dictionary`2 labels, JsonSerializer serializer)
Aug  2 19:28:30 srv gaming-integration[32530]: at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
Aug  2 19:28:30 srv gaming-integration[32530]: at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Aug  2 19:28:30 srv gaming-integration[32530]: at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
Aug  2 19:28:30 srv gaming-integration[32530]: at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
Aug  2 19:28:30 srv  gaming-integration[32530]: at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
Aug  2 19:28:30 srv gaming-integration[32530]: at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
Aug  2 19:28:30 srv gaming-integration[32530]: at Elastic.Apm.Report.PayloadSenderV2.ProcessQueueItems(Object[] queueItems)
```

**Comment by SergeyKleyman** [comment]
I agree - the agent should handle `null` values (it's even [allowed by Intake API spec](https://github.com/elastic/apm-server/blob/6.5/docs/spec/tags.json#L8)) and the agent should definitely not crash the application.

**Comment by skynet2** [comment]
It doesn't crash the application, the app is ok, but there is no transaction in APM.
Thanks

**Comment by SergeyKleyman** [comment]
Yes, you right - in this case exceptions are not propagated out of `Elastic.Apm.Report.PayloadSenderV2.ProcessQueueItems`.

**Comment by SergeyKleyman** [comment]
@skynet2 I think we are on the same page regarding how agent should handle `null` passed as label value but what do you think should be the way agent should handle `null` passed as label **key**? Should the agent throw `ArgumentNullException` (might crash the application) or should the agent just log an error and not add the label?

**Comment by skynet2** [comment]
Hi @SergeyKleyman , 
I think throwing an exception is not good, coz the main idea is that user should be able to see data in the APM.
I think it's better to log an error (or warning), but transaction should be sent to APM server

Thanks,
Stas

**Comment by gregkalapos** [comment]
Opened https://github.com/elastic/apm-agent-dotnet/pull/429 

I'm not sure that we should handle `null` as key.. Problem is, we expose the `Dictionary<string,string>` directly. So `Agent.Tracer.CurrentTransaction.Labels` is the `Dictionary` itself. 

Once you write `Agent.Tracer.CurrentTransaction.Labels[null] = "foo"`, the `Dictionary` already throws. And I think that is good - that's what the `Dictionary` API does, so I think it makes sense to follow that.

**Comment by SergeyKleyman** [comment]
@gregkalapos Yes, you are correct - the approach is already decided for us by the interface :)
I think it's worth adding a code comment for `Labels` drawing user's attention to the fact that `null`  value is completely okay but `null` key will throw `ArgumentNullException`.

**Comment by gregkalapos** [comment]
#429 merged to master, so the fix will be in the next release.

Thanks for reporting Stas! 

Anyone against closing this?
