### ISSUE TITLE
Add ITracer in ASP.NET Core as a service

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#431]
From https://github.com/elastic/apm-agent-dotnet/issues/77#issuecomment-518141703

Back when we designed the API we wanted to make the `ITracer` injectable in ASP.NET Core.

E.g.:

```
public static void ConfigureServices(IServiceCollection services)
{
   services.AddSingleton(n => Agent.Tracer);
   //..
}
```

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
   app.UseElasticApm(...);
   //...
}
```

```
public class HomeController : Controller
{
   private readonly ITracer _tracer;

   public HomeController(ITracer tracer)
   {
      tracer = tracer;
   }
//...
}
```

Problem is in `ConfigureServices` the `services.AddSingleton(n => Agent.Tracer);` already triggers initialization, therefore in ` app.UseElasticApm(...);` we throw an exception.

I think we should fix this. My intention was to support this use case, because I think this is a very nice integration with ASP.NET Core. Furthermore based on the discussion in #77 (issue itself is only indirectly related, that's why I'm opening this as a follow-up) I think we already have need for this.

**Comment by yhvicey** [comment]
In fact registering IApmAgent/ITracer instance using above approach won't trigger initialization - It will only be triggered when `provider.GetService<ITracer>()` is called - I used this approach as a workaround before and it actually works

**Comment by gregkalapos** [comment]
> In fact registering IApmAgent/ITracer instance using above approach won't trigger initialization - It will only be triggered when `provider.GetService<ITracer>()` is called - I used this approach as a workaround before and it actually works

You are right. I messed up my sample and freaked out too quickly. 

This use case is indeed supported, and works as intended.

So.. please ignore ;)
