### ISSUE TITLE
 Failed sending event. {"error":"Content-Type header [application/x-ndjson; charset=utf-8]

### ISSUE THREAD

**Issue by gabrieldocarmosantana** [elastic/apm-agent-dotnet#436]
Hi, i try integrate APM in aspnetcore project with AWS, using APM 6.7, but when i start app and acess enpoints i get this error in console:

Failed sending event. {"error":"Content-Type header [application/x-ndjson; charset=utf-8] is not supported","status":406}

I tried downgrade for 5.6 but i get other error ""Malformed content, found extra data after parsing: START_OBJECT"} asp net

Any suggestions for resolution?

Thanks!

**Comment by SergeyKleyman** [comment]
Hi @gabrieldocarmosantana.
First of all thank you for trying out the agent.

What version of Elasticsearch did you use when the following error was printed by .NET agent?
> Failed sending event. {"error":"Content-Type header [application/x-ndjson; charset=utf-8] is not supported","status":406}

Regarding
> I tried downgrade for 5.6 but i get other error ""Malformed content, found extra data after parsing: START_OBJECT"} asp net

Indeed as documented [here](https://www.elastic.co/guide/en/apm/get-started/current/agent-server-compatibility.html#dotnet-compatibility) .NET agent is compatible with APM Server version >= 6.5

BTW which version of .NET agent do you use?

**Comment by alfhv** [comment]
I'm having exactly same issue.
I'm running in internal network, not cloud.
Elasticsearch and APM agent upgraded to latest available version 7.3, running on RH 7.
No extra configuraiton added, just default.
.NET Core application on dotnetcore version 2.2 running on Windows, APM Nuget v1.0.0.

**Comment by SergeyKleyman** [comment]
@alfhv Thank you for reporting the issue - we're working on it with APM Server team.

**Comment by SergeyKleyman** [comment]
@alfhv, @gabrieldocarmosantana 
Is it possible that [`ServerUrls`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html) with which you configured .NET agent (either via environment variables or `IConfiguration`) points directly to Elasticsearch and not to APM Server as it should?

**Comment by alfhv** [comment]
Checked and yes, exactly that! Thanks!

**Comment by SergeyKleyman** [comment]
I've opened https://github.com/elastic/apm-agent-dotnet/issues/437 to make issues like this one easier to diagnose.

**Comment by SergeyKleyman** [comment]
@alfhv Thank you for the feedback - I'm glad we resolved the issue.
Do you think we can improve the documentation to prevent such mistakes?

**Comment by SergeyKleyman** [comment]
@gabrieldocarmosantana I'm going to soft-close this issue - please re-open it if not all the concerns were addressed.
