### ISSUE TITLE
Health check APM Server

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#437]
To make it easier to diagnose issues like https://github.com/elastic/apm-agent-dotnet/issues/436 agent can use [APM Server's information API](https://www.elastic.co/guide/en/apm/server/current/server-info.html) to verify that 
1. `ServerUrls` configuration option value indeed points to APM Server and not some other component (like Elasticsearch, etc.)
2. APM Server version is [compatible](https://www.elastic.co/guide/en/apm/get-started/current/agent-server-compatibility.html#dotnet-compatibility) with the agent.

Also related - https://github.com/elastic/apm-server/issues/2538.

**Comment by gregkalapos** [comment]
Something like this is already implemented - we now query the the APM Server endpoint from the agent.
