### ISSUE TITLE
{PayloadSenderV2} Failed sending event. 404 page not found

### ISSUE THREAD

**Issue by vsbatista** [elastic/apm-agent-dotnet#438]
Hi everyone,
I have created a very minimal asp.net core api and tried to monitor it. However, while running that, I noted no information is being sent to my APM server. Looking at app logs, I found the following

```
fail: Elastic.Apm[0]
      {PayloadSenderV2} Failed sending event. 404 page not found
      
Elastic.Apm:Error: {PayloadSenderV2} Failed sending event. 404 page not found

fail: Elastic.Apm[0]
      {PayloadSenderV2} Failed sending event. 404 page not found
      
Elastic.Apm:Error: {PayloadSenderV2} Failed sending event. 404 page not found
```
E/S version: 6.4.0
APM server version: 6.4.0
I have tested the APM/ES config by creating a simple python API and data flows as expected.

appsettings.json config(APM server is running locally):
```
{
	"Logging": {
		"LogLevel": {
			"Default": "Debug",
			"System": "Information",
			"Microsoft": "Information",
			"Elastic.Apm":  "Debug"
		}
	},
	"AllowedHosts": "*",
	"ElasticApm": {
		"ServerUrls": "http://localhost:8200",
		"TransactionSampleRate": 1.0
	}
}
```

Appreciate any help. 
Thanks in advance, Vinicius

**Comment by SergeyKleyman** [comment]
Hi @vsbatista,
First of all thank you for trying out the agent.

Second - a small administrative issue. As mentioned in [README](https://github.com/elastic/apm-agent-dotnet/blob/master/README.md) we recommend using [the forum](https://discuss.elastic.co/tags/c/apm/dotnet) for questions and GitHub issues for confirmed bugs and enhancement requests. The forum allows other users to learn from the questions and answers and the number of people that can answer a question at the forum is much larger than at the Github repo which is mostly for developers of the agent.

Regarding your question - as documented [here](https://www.elastic.co/guide/en/apm/get-started/current/agent-server-compatibility.html#dotnet-compatibility) .NET agent is compatible with APM Server version >= 6.5.

Please let us know if the above answers your question and if the issue can be closed.

**Comment by vsbatista** [comment]
Hi @SergeyKleyman ,
thanks for the quick response. 
I apologize for not paying attention to README as expected. The next ones, I'll be using the proper channels. 
Concerning the issue, thanks for pointing out the compatibility matrix. I'd setup an environment with newest 6.X version and it works like a charm.
Have a nice week!
Vinicius
