### ISSUE TITLE
Print where the agent reads configs from

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#445]
I chatted with one of our SAs and for non .NET devs it's not very intuitive that in case you activate the agent with 

```
app.UseAllElasticApm()
```

the agent will read configs from environment variables, while when configuring with 

```
app.UseAllElasticApm(Configuration);
```

the agent will read configs from `IConfiguration`. In this instance the `IConfiguration` was not passed and that took some time to figure out why the configs from `appsettings.json` are ignored.

We kind of print things like: 

```
WebApplication1> dbug: Elastic.Apm[0]
WebApplication1>       {EnvironmentConfigurationReader} Using default ServerUrl: http://localhost:8200/
WebApplication1> info: Elastic.Apm[0]
```

And `EnvironmentConfigurationReader` tells me this info, but I think during the startup an an explicit line would be nice saying something like 

```
Reading configs from only Environment variables
```

and 

```
Reading configs from IConfiguration
```

**Comment by stevejgordon** [comment]
Superseded by latest config changes which implement this in general
