### ISSUE TITLE
Document CAPTURE_BODY and CAPTURE_BODY_CONTENT_TYPES configuration options

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#452]
The feature was implemented in https://github.com/elastic/apm-agent-dotnet/pull/402 but we also need to document it. 
[Here is the link to the corresponding section of Java agent docs](https://www.elastic.co/guide/en/apm/agent/java/current/config-http.html#config-capture-body).

**Comment by gregkalapos** [comment]
cc @bmorelli25 in case you wanna go for it.
