### ISSUE TITLE
Unable to use ScopedLogger in extrernal listeners for Elastic.Apm

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#461]
**Is your feature request related to a problem? Please describe.**
As @gregkalapos mentioned in https://github.com/elastic/apm-agent-dotnet/pull/390#issuecomment-518041244 some of external listeners should be placed out of main repo and I'm totally agree with it. However, in such case, we as developers of external listeners are limited in interaction with Elastic.Apm internals.
The first and major limitation is logging. Most of developers prefer to have log records in the consistent way and structure across one component (`Elastic.Apm` in our case). As you know, in case of `Elastic.Apm` consistency is achieved through the use of `ScopedLogger`  in listeners. However, it cannot be used in external listeners due to `ScopedLogger` and `LoggingExtensions` are mark as internal.

**Describe the solution you'd like**
Mark `LoggingExtensions` class as public with logging infrastructure refactoring. Without refactoring it will be needed to also expose `ScopedLogger` and `MaybeLogger` as public.

**Describe alternatives you've considered**
Implement own version of `ScopedLogger` in each external listener. But it will increase effort for external developers

**Comment by vhatsura** [comment]
@SergeyKleyman. @gregkalapos, it would be nice to hear your thoughts about it. It will allow to move into right direction with necessary changes.

**Comment by SergeyKleyman** [comment]
@vhatsura We have plans (https://github.com/elastic/apm-agent-dotnet/issues/345) to revamp agent's internal logger - I've added your request to make logger API public for use in external extensions to the agent.

If you don't object I would to prefer to close this issue and follow up on this request in https://github.com/elastic/apm-agent-dotnet/issues/345
