### ISSUE TITLE
Clarify in docs how to configure HTTPS communication between .NET agent and APM Server

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#464]
it seems to be unclear to the users how to configure HTTPS communication between .NET agent and APM Server - there are already two support cases: https://github.com/elastic/support-dev-help/issues/7878 and https://github.com/elastic/support-dev-help/issues/7953

@bmorelli25: Do you know if any of the agents/APM server documentation has anything related? Should we cover it by introducing "Troubleshooting" in .NET agent documentation?

**Comment by bmorelli25** [comment]
We have a small section in the APM Server documentation without much information. There's a long open issue about improving this documentation in APM Server. It might make sense to prioritize it at this point.

* [Link](https://www.elastic.co/guide/en/apm/server/current/securing-apm-server.html) to current docs.
* Issue: https://github.com/elastic/apm-server/issues/1579.

**Comment by gregkalapos** [comment]
Done in https://github.com/elastic/apm-server/pull/3538.
