### ISSUE TITLE
Add support for auto capturing DB spans for LINQ to SQL queries

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#469]
This feature was requested at https://discuss.elastic.co/t/how-to-use-distributed-tracing-in-with-elastic-apm-in-non-net-core-application/197356/3

**Possible implementation approaches**
1. Use [`DataContext.Log` roperty](https://docs.microsoft.com/en-us/dotnet/api/system.data.linq.datacontext.log?view=netframework-4.8) to capture textual as described [here](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/how-to-display-generated-sql). There are two problems with this approach:
    1. Log entries are emitted before the query/command is executed so it's not clear we can get duration and result.
    2. Log entries are textual so it will require parsing which can brittle and/or differ between different versions/implementation.
2. [Extend an IQueryable by wrapping it](https://blogs.msdn.microsoft.com/alexj/2010/03/01/tip-55-how-to-extend-an-iqueryable-by-wrapping-it/) although it requires more research to determine what are the pros/cons of this approach.

**Comment by gregkalapos** [comment]
I think this will be covered in https://github.com/elastic/apm-agent-dotnet/pull/592 - that adds `SqlClient` support and I believe LINQ to SQL also uses that. If not we can revisit if there is need.
