### ISSUE TITLE
Use Microsoft.NETFramework.ReferenceAssemblies

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#470]
Followup from #444

Currently in case we build the solution on a non-Windows OS we don't generate `net461` targets.

The `Microsoft.NETFramework.ReferenceAssemblies` would solve this: https://github.com/dotnet/designs/pull/33#issuecomment-489264196

**Comment by SergeyKleyman** [comment]
Is this really a problem we need to solve considering that we do have Windows machines?

**Comment by gregkalapos** [comment]
Given that [this](https://discuss.elastic.co/t/issue-while-adding-elastic-apm-to-net-project/196125) could have been prevented by using something like `Microsoft.NETFramework.ReferenceAssemblies`, I'd say it'd be nice to address this. Not super urgent, but the current solution with this [`condition`](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Elastic.Apm.csproj#L5) is dangerous (e.g. see the issue referenced above).

Also `Microsoft.NETFramework.ReferenceAssemblies` is exactly for our use-case. 

So not super urgent, but given we already had 1 I'd say fairly major problem due to this (#444) - I'd say relaying on having Windows machines is not enough.

**Comment by SergeyKleyman** [comment]
If I understand correctly if we use Windows machine to build then there's no problem so I don't follow why isn't it good enough?

It's not like we have a safe and easy to implement alternative at the moment. Wouldn't our effort better spent for example implementing automated package creation and have CI always run it on Windows thus killing two birds with one stone?

**Comment by gregkalapos** [comment]
> If I understand correctly if we use Windows machine to build then there's no problem so I don't follow why isn't it good enough?

Because currently packages are generated manually - in an ideal world this would not be the case, but fact is: that's how it is today. Additionally, the condition in the `.csproj` file is a hack, and the `Microsoft.NETFramework.ReferenceAssemblies` addresses exactly that. Why not use it, if there is an out of the box solution for it? Even if we'd have a working solution for this in CI, I'd still prefer not to have [this hack](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Elastic.Apm.csproj#L5).

> Wouldn't our effort better spent for example implementing automated package creation and have CI always run it on Windows thus killing two birds with one stone?

We are talking about a 6 lines of code change (see #471). The effort is minimal (I already spent more on answering here than on the whole thing otherwise). Yes, having automated package creation on Windows would be better, we should have it, we in fact already have something [here](https://github.com/elastic/apm-agent-dotnet/blob/master/Jenkinsfile#L296) - it's currently running on Linux. We never tested that in real, and also I'd say as a fallback it's nice to have the option to generate a release package not only in CI, but everywhere.

I really don't know why this is bad - there was already a problem due to having [this](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Elastic.Apm.csproj#L5),  having package generation on Windows won't make that case irrelevant - it can still happen that accidentally we create package on Linux - Microsoft addresses exactly that with the `Microsoft.NETFramework.ReferenceAssemblies` package. Why shouldn't we use it? It takes 6 lines to enable it.

**Comment by SergeyKleyman** [comment]
IIUC 6 lines of code change in #471) rely on feature that is not a GA so do we really want to take risk using it in agent production release which in turn agent users might use in their production applications?

**Comment by gregkalapos** [comment]
> IIUC 6 lines of code change in #471) rely on feature that is not a GA so do we really want to take risk using it in agent production release which in turn agent users might use in their production applications?

Have you seen my comment on the PR? 

> are we confident using this to generate our production packages? - given that this feature is still preview.

**Comment by SergeyKleyman** [comment]
Yes, I'v seen your comment and that is why I'm bringing up here that we should consider other alternatives. For example we can construct a test to verify if nuget package has the issue we encountered before. I assume that it should be really simple to construct an application reproducing issue encountered by the user at https://discuss.elastic.co/t/issue-while-adding-elastic-apm-to-net-project/196125 and just remember to manually run the test before releasing the packages.

**Comment by gregkalapos** [comment]
> Yes, I saw your comment and that is why I'm bringing up here that we should consider other alternatives. For example we can construct a test to verify if nuget package has the issue we encountered before. I assume that it should be really simple to construct an application reproducing issue encountered by the user at https://discuss.elastic.co/t/issue-while-adding-elastic-apm-to-net-project/196125 and just remember to manually run the test before releasing the packages.

Then why did you not start by stating this? Maybe directly on the PR.

**Comment by gregkalapos** [comment]
All right, decided - we wait until `Microsoft.NETFramework.ReferenceAssemblies` becomes GA. We  don't want to risk generating our packages based on a preview package. If nothing happens for a very long time with `Microsoft.NETFramework.ReferenceAssemblies` and it remains preview too long we may look for another solution. 

We leave this open for now.

**Comment by gregkalapos** [comment]
Done in https://github.com/elastic/apm-agent-dotnet/pull/426 - closing this now.
