### ISSUE TITLE
Add support for providing additional labels in CaptureError and CaptureException agent's public API

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#473]
Currently [`CaptureError`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-span-capture-error) and [`CaptureException`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-span-capture-exception) .NET agent 's public API inherit `Context`, which in particular includes labels, from the corresponding transaction and there's no way to provide additional labels specific to the error and not to the whole transaction. For example, [Node.js](https://www.elastic.co/guide/en/apm/agent/nodejs/current/agent-api.html#apm-capture-error) and [Python](https://www.elastic.co/guide/en/apm/agent/python/current/api.html#client-api-capture-exception) agents do support providing additional labels in their capture-error public API.

Requested at https://discuss.elastic.co/t/how-to-use-distributed-tracing-in-with-elastic-apm-in-non-net-core-application/197356/5

**Comment by gregkalapos** [comment]
Implemented in #982.
