### ISSUE TITLE
Performance improvement: Agent should not auto capture spans that will be discarded

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#474]
Current implementation auto captures spans (HTTP calls and DB operation for EF Core) even if those spans will be later discarded because the transaction is not sampled or it reached "transaction max spans" (assuming we already implemented the latter - see https://github.com/elastic/apm-agent-dotnet/issues/178, https://github.com/elastic/apm-agent-dotnet/pull/472)

*Note:* we might need to still capture some information for "to be discarded" spans in order to include it in breakdown metrics (https://github.com/elastic/apm-agent-dotnet/issues/227) but we can still improve performance by not doing anything is not necessary for breakdown metrics. For example we can omit parsing DB statement, etc.

**Comment by russcam** [comment]
This issue may have less relevance now, with the dropped span stats implementation: https://github.com/elastic/apm-agent-dotnet/pull/1511.

@gregkalapos I suggest we close this for now, and can reopen or open a new issue when looking at this in detail.

**Comment by gregkalapos** [comment]
Agreed.
