### ISSUE TITLE
support grpc? 

### ISSUE THREAD

**Issue by sunchao809** [elastic/apm-agent-dotnet#478]
Please use the [discuss forum](https://discuss.elastic.co/c/apm) to ask questions.
.net Core  
Whether grpc is currently supported?

**Comment by gregkalapos** [comment]
Hi @sunchao809,

Currently gRPC is not supported out of the box by auto instrumentation. Mid/Long term this is definitely something we'll look into, but at the moment there is no auto instrumentation for it.

One option is to use the [Public Agent API](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html) and place manual instrumentation to the gRPC specific methods.

**Comment by gregkalapos** [comment]
Done in #969.
