### ISSUE TITLE
Add Troubleshooting section to the docs

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#483]
For example [Java agent's Troubleshooting section](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html))

Also see https://github.com/elastic/apm-dev/issues/425#issuecomment-490757036

Derived from #341

Candidates to be included in Troubleshooting section:
- [SystemTotalCpuProvider fails with InvalidOperationException: Category does not exist #501](https://github.com/elastic/apm-agent-dotnet/issues/501#issuecomment-534193901)

**Comment by gregkalapos** [comment]
@bmorelli25 is this something we still want to have? If not, I'd suggest that we close this.

**Comment by bmorelli25** [comment]
All other agents (except Go) have a troubleshooting section. I think we should still plan on adding one to the .NET agent docs. Are there any other common questions you can think of that might be good additions?

**Comment by gregkalapos** [comment]
Ok, sure - makes sense, let's keep this issue.

Logging is definitely 1 topic we could add.

**Comment by bmorelli25** [comment]
Great. Once we get the Troubleshooting section up, you can do what other agent devs do:
1. Notice that the same question has been asked in discuss/github/support multiple times
2. Open an issue with links to the discuss/github/support cases
3. I'll turn your responses into a documentation PR
4. No one asks that question any more 😄

**Comment by gregkalapos** [comment]
Merged #814 - closing this now and we'll roll with the suggestion above in the future :)
