### ISSUE TITLE
Add Frequently Asked Questions (FAQ) section to the docs

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#484]
For example [Java agent's Frequently Asked Questions (FAQ) section](https://www.elastic.co/guide/en/apm/agent/java/current/faq.html)

Derived from #341

**Comment by gregkalapos** [comment]
@bmorelli25 is this something we still want to have? If not, I'd suggest that we close this.

**Comment by bmorelli25** [comment]
I like to avoid FAQs whenever possible. Eventually, they always end up becoming a dumping point for documentation that "doesn't fit elsewhere" and they turn into an unnavigable sea of unrelated topics. I think we should close this issue. If it becomes absolutely necessary in the future, we can reassess.
