### ISSUE TITLE
Make ISpan, IExecutionSegment etc. disposable

### ISSUE THREAD

**Issue by busybruce11** [elastic/apm-agent-dotnet#488]
**Is your feature request related to a problem? Please describe.**

Ends span with out exception capturing is not unusual, but the instance declared one by one which make readability lower。

```c#
    var trans = Agent.Tracer.CurrentTransaction;
    var spanForMethod1 = trans.StartSpan(nameof(Main), nameof(Method1));
    Method1();
    spanForMethod1.End();

    var spanForMethod2 = trans.StartSpan(nameof(Main), nameof(Method2));
    Method2();
    spanForMethod2.End();
```

**Describe the solution you'd like**

Make `IExecutionSegment` inherit from `IDisposable` is the suggestion, the `End()` method is implicitly called when the instance disposed.

Sample usage as bellow:

```c#
    var trans = Agent.Tracer.CurrentTransaction;
    using (trans.StartSpan(nameof(Main), nameof(Method1))) {
        Method1();
    }

    using (trans.StartSpan(nameof(Main), nameof(Method2))) {
        Method2();
    }
```

**Describe alternatives you've considered**

**Additional context**

The delegate version has not yet been considered, Thanks.

**Comment by gregkalapos** [comment]
Related discussion: https://github.com/elastic/apm-agent-dotnet/issues/38 

In case you feel it's a dup, I think probably it'd be better to reopen #38

**Comment by busybruce11** [comment]
@gregkalapos oops, searching via 'using', 'dispose' found nothing, quite agree with you on this point.

**Comment by gregkalapos** [comment]
> @gregkalapos oops, searching via 'using', 'dispose' found nothing, quite agree with you on this point.

No problem @busybruce11 👍 

I reopened #38 - in case you have more input feel free to comment there - there are some "cons" listed there, having more input on those could help us to make a better decision.

Closing this over #38. - Nevertheless thanks for bringing this up, this is definitely a topic where we need more input from users.
