### ISSUE TITLE
ASP.NET Core - UseAllElasticApm after other middlewares are already registered

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#489]
From [discuss](https://discuss.elastic.co/t/net-core-agent-not-showing-transactions/199129/4)

In that discuss entry `UseAllElasticApm` (or `UseElasticApm`) was added NOT as the 1. line in the `Configure` method and according to the description the agent did not create transactions. 

In case the agent is not registered as the 1. middleware the timing of the transactions won't be correct, but other than that the agent should works. 

Tasks:
- Figure out if the agent works in that case or not (aka reproduce), and if not, why?
- Figure out if we can print some warning, or something like that.

**Comment by chrisvanderpennen** [comment]
Requests that are routed to an MVC controller don't invoke any subsequent middleware stages, so the APM middleware never gets a chance to create a transaction.  This `Configure` body should reproduce the scenario without needing all of the MVC stuff:

```csharp
app.Use(next => req => req.Response.WriteAsync($"{Agent.Tracer.CurrentTransaction?.Id ?? "<null>"}"));
app.UseAllElasticApm();
```

We implemented an [IStartupFilter](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#extend-startup-with-startup-filters) that ensures `UseAllElasticApm` is called before `Startup.Configure` is, and add it to the service collection from an extension method on `WebHostBuilder` we created to handle startup boilerplate for several services.  Hopefully this is helpful info for you.

**Comment by gregkalapos** [comment]
> Requests that are routed to an MVC controller don't invoke any subsequent middleware stages, so the APM middleware never gets a chance to create a transaction. This `Configure` body should reproduce the scenario without needing all of the MVC stuff:
> 
> ```cs
> app.Use(next => req => req.Response.WriteAsync($"{Agent.Tracer.CurrentTransaction?.Id ?? "<null>"}"));
> app.UseAllElasticApm();
> ```
> 
> We implemented an [IStartupFilter](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/startup?view=aspnetcore-2.1#extend-startup-with-startup-filters) that ensures `UseAllElasticApm` is called before `Startup.Configure` is, and add it to the service collection from an extension method on `WebHostBuilder` we created to handle startup boilerplate for several services. Hopefully this is helpful info for you.

Thanks for the input @chrisvanderpennen. Yeah it totally makes sense, if a middleware terminates a the pipeline then our middleware won't have the chance to capture the transaction. 

In fact, the sample code was pasted to the [referenced discussion](https://discuss.elastic.co/t/net-core-agent-not-showing-transactions/199129/9) and this was exactly the case. I'm not sure we can do anything to prevent this, other than covering this in the docs. Closing this, since probably does not worth the effort to spend more time on this.
