### ISSUE TITLE
Transaction and span created in new task are not accessible

### ISSUE THREAD

**Issue by wsz34** [elastic/apm-agent-dotnet#490]
**Describe the bug**
When span or transaction created in task, they are not accessible in outer scope. Does not look to me as intended behavior.

**To Reproduce**
1. Run this code
```
        class Program
	{
		static async Task Main()
		{
			int test = 0;
			await Task.Run(() =>
			{
				Agent.Tracer.StartTransaction("test", "test");
				Agent.Tracer.CurrentTransaction.StartSpan("test", "test");

				test = 5;
			});

			var c = new Counter();
			c.TestEvent += TestEvent;

			await Task.Run(() => TestEvent(null, new EventArgs()));

			// test is 5 here
			test++;

			// CurrentTransaction is null
			Agent.Tracer.CurrentTransaction.End();
		}

		static void TestEvent(object sender, EventArgs e)
		{
			// CurrentSpan is null
			Agent.Tracer.CurrentSpan.End();
		}
	}

	internal class Counter
	{
		public event EventHandler<EventArgs> TestEvent;
	}
```

**Expected behavior**
test variable has value 5 in Main method after Task while CurrentTransaction and CurrentSpan are nulls. Expected behavior would be to reach created transaction and span outside the task it was created.

**Comment by gregkalapos** [comment]
@wsz34 I hope the explanation above makes sense. In case there is a use case where this model breaks I'm happy to look into this in more detail, otherwise I'd close this issue soon.

Thanks

**Comment by wsz34** [comment]
Yes, it makes sense. Thank you. My goal was to have similar to EFCore query performance tracer for MongoDB. In my opinion the best solution was to subscribe to start and end events. Both events are needed because command succeeded event is missing query and started command is missing duration. So my code was looking like this

```
                        var mongoClientSettings = MongoClientSettings.FromConnectionString(config.GetConnectionString());

			mongoClientSettings.ClusterConfigurator = cb =>
			{
				cb.Subscribe<CommandStartedEvent>(e =>
				{
					performanceMonitor.StartMongoQuery(e, config.Database);
				});
				cb.Subscribe<CommandSucceededEvent>(e =>
				{
					performanceMonitor.EndMongoQuery(e);
				});
			};
```

But apparently those two events work as separate tasks. So I ended up capturing span in repository decorator.

**Comment by vhatsura** [comment]
Hey, @wsz34!
You can use [Elastic.Apm.Mongo](https://github.com/vhatsura/elastic-apm-mongo) package to track MongoDB queries.

**Comment by gregkalapos** [comment]
@wsz34 great, nice to see that you found a solution. 

I already wanted to ping you @vhatsura  :) Yeah, so Vadim worked on MongoDB monitoring... maybe we should make it "official" at some point. 

Closing this now, since the original problem is explained. https://github.com/elastic/apm-agent-dotnet/issues/401 is a good place to continue MongoDB related discussions in this repo.

Thanks everyone!
