### ISSUE TITLE
Automated tests for Central Configuration feature

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#496]
PR (#497) for central configuration implementation doesn't include automated tests - this issue is to add automated tests for central configuration feature.

- [ ] Unit tests using `MockCentralConfigFetcher` to simulate dynamic changes in configuration and verify that relevant features of the Agent (at the moment only transaction sampling) reacts to the configuration changes as expected
- [ ] Tests that run on both Full .NET Framework and .NET Core (and use `MockApmServer`?)
   - **Note:** If we want to use `MockApmServer` we won't be able to place the tests into `Elastic.Apm.Tests` because dependecies go into the opposite direction -  `Elastic.Apm.Tests.MockApmServer` depends on `Elastic.Apm.Tests`.
      - One possible approach is to create a new test project (for example `Elastic.Apm.ComponentTests`) that will depend on `Elastic.Apm.Tests.MockApmServer` and include tests that use only via Agent public API and data Agent sends to APM Server.
An advantage of this approach is that we don't need to allow `Elastic.Apm.ComponentTests` access to implementation `internal`-s thus reducing the chance of deviating from real world use cases.
- [ ] Tests for `Elastic.Apm.AspNetFullFramework.Tests` to verify that implementation works correctly when running in context of classic ASP.NET application on top of IIS.
   - It would be nice to re-use the same logic of (scenario, expected outcome) used in the tests from the previous item.

**Comment by stevejgordon** [comment]
Closing as this an old issue and we have no plans to implement specific further testing
