### ISSUE TITLE
Central configuration doesn't work if environment name contains characters that have to be URL encoded

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#513]
For example if user configures:
```
"ElasticApm": {
    ...
    "Environment": "my env amp:(&) plus:(+) ang:(<>) eq:(=) qm:(?)"
    ...
}
```
Kibana does display environment name correctly and user can create configuration for the corresponding service and environment but that agent will not receive the created configuration,

The root cause is the fact that agent doesn't URL encode service and environment names when sending them to APM Server's get-central-config API (`config/v1/agents`) so in the example above agents sends:
```
http://.../config/v1/agents?service.name=...&service.environment=my%20env%20amp:(&)%20plus:(+)%20ang:(%3C%3E)%20eq:(=)%20qm:(?)
```
while the correct URL should be
```
http://.../config/v1/agents?service.name=...&service.environment=my+env+amp%3A%28%26%29+plus%3A%28%2B%29+ang%3A%28%3C%3E%29+eq%3A%28%3D%29+qm%3A%28%3F%29
```

**Comment by lreuven** [comment]
why not add validation in the UI?

**Comment by SergeyKleyman** [comment]
> why not add validation in the UI?

There are two issues with that approach:
1. At the moment those special characters (that should be URL encoded) are allowed in environment name.  For example user can name the environment using non-Latin alphabet. If we want to disallow that it will be a breaking change.
2. The second issue is that service name and environment name are used by APM backend to select which central configuration goes to which agent so moving service name and environment name to UI will create the chicken and the egg problem.
