### ISSUE TITLE
How does this SDK montor HttpClient calls

### ISSUE THREAD

**Issue by markdemich** [elastic/apm-agent-dotnet#538]
I have a .Net Framework app where I included the AspNetFullFramework module.  I downloaded the source and have successfully stepped into the code for that and the core stuff.  I'm testing out my application against the APM and it's not capturing my HttpClient calls and I'm not sure why.  I looked at how it's instrumented, but I can't figure out what supposed to make it capture the HttpClient calls.  Can anyone give me some insight on how this is supposed to work so I can further debug why it's not working.

Thanks,
Mark

**Comment by axw** [comment]
@markdemich please create a forum post at https://discuss.elastic.co/c/apm for questions. GitHub issues should be used for reporting bugs. Thanks!
