### ISSUE TITLE
UserID is Empty on Full Framework

### ISSUE THREAD

**Issue by insanity13** [elastic/apm-agent-dotnet#540]
**Describe the bug**
UserID is N/A on the APM dashboard.

**To Reproduce**
1. Add APM Full Framework to Asp.Net application
2. Go to cloud APM Dashboard
![image](https://user-images.githubusercontent.com/1174911/66452206-a9f2a900-ea70-11e9-9c0d-a48e64cf831d.png)

**Expected behavior**
UserID is not empty.

**Comment by gregkalapos** [comment]
Thanks for reporting this @insanity13.


The way we report the user is that we use the `HttpContext.User?.Identity` property. If that is `null` or `HttpContext.User?.Identity.IsAuthenticated` returns `false`, we won't be able to report the user id.

How is authentication implemented in the given application? Could you maybe figure out if the properties above return the expected data in your case?

**Comment by insanity13** [comment]
We got ClaimsPrincipal
![image](https://user-images.githubusercontent.com/1174911/66489749-27dea080-eac1-11e9-9eb2-ef7d9b585528.png)

Username is totally fine but it shows only in Metadata:
![image](https://user-images.githubusercontent.com/1174911/66489917-6a07e200-eac1-11e9-91e9-3cba00216c0c.png)

**Comment by gregkalapos** [comment]
Oh, yes, know I got it.

So, yes, we do set the username, but we actually don't set the user id, because there was nothing on `HttpContext.Current.User` that would be something like an id.

But as you point out, the id is on a fairly prominent place in the UI. One option would be to also put the user name into the id field. Another option would be to look further and see if maybe there is a way to get the real user id.

**Comment by axw** [comment]
@gregkalapos I think we probably could get the additional information by looking in the claims:

 - `"sub"` claim -> `user.id`
 - `"email"` claim -> `user.email`

https://www.iana.org/assignments/jwt/jwt.xhtml#claims

**Comment by jlchmura** [comment]
Is there a workaround for this? I tried setting `Context.User` on the current transaction in `Application_PostAuthenticateRequest` but it seems to get overwritten.
