### ISSUE TITLE
Full request path logged instead of route name (asp.net core 3.0)

### ISSUE THREAD

**Issue by cbo100** [elastic/apm-agent-dotnet#541]
**Describe the bug**
When using `UseRouting` in asp.net core 3.0 the transaction names logged to APM are not parameterised using the route names

`GET /WeatherForecast/1234`
`GET /WeatherForecast/5678`

instead of (roughly)

`GET WeatherForecast/ByPostCode`

**To Reproduce**
1. `dotnet new webapi`
2. `dotnet add package Elastic.Apm.NetCoreAll`
3. Add `app.UseAllElasticApm(Configuration)` in `Startup.cs`

**Expected behavior**
The transaction names with routes should be logged with parameter names instead of being specific to each request (as per .net core 2.2 and below)

**Comment by cbo100** [comment]
On my own testing I found changing:

https://github.com/elastic/apm-agent-dotnet/blob/9d0949a5c7dd38c7f7fdc1f060df220a4eca9562/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L124

To `context.GetRouteData()` resolves the issue and works across 2.2 and 3.0 at least, but that was just a quick test. Not sure of all the scenarios that need to be covered in testing this.

**Comment by cookbr** [comment]
In case anyone else is hampered by this, I've been using the following workaround ...
```c#
/// <remarks>
/// TODO Remove this filter when <see cref="https://github.com/elastic/apm-agent-dotnet/issues/541">Issue 541</see> has been resolved.
/// </remarks>
/// <see cref="https://github.com/elastic/apm-agent-dotnet/issues/541"/>
public class ElasticApmActionFilter : ActionFilterAttribute
{
	/// <summary>
	/// A regular expression for matching route constraints, excluding the regex constraint.
	/// </summary>
	/// <see cref="https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing#route-constraint-reference"/>
	private static readonly Regex routeConstraintRegex = new Regex(@":[\w(),:]+(?=})");
	private readonly ITracer tracer;

	public ElasticApmActionFilter(ITracer tracer)
	{
		this.tracer = tracer ?? throw new ArgumentNullException(nameof(tracer));
	}

	public override void OnActionExecuting(ActionExecutingContext context)
	{
		var transaction = tracer.CurrentTransaction;
		if (transaction == null)
			return;

		var method = context.HttpContext.Request.Method;
		var template = context.ActionDescriptor.AttributeRouteInfo?.Template;

		if (string.IsNullOrEmpty(method) || string.IsNullOrEmpty(template))
			return;

		template = routeConstraintRegex.Replace(template, string.Empty);
		transaction.Name = $"{method.ToUpper()} {template.ToLower()}";
	}
}
```
```c#
public class ConfigureElasticApmActionFilter : IConfigureOptions<MvcOptions>
{
	public void Configure(MvcOptions options)
	{
		options.Filters.Add(typeof(ElasticApmActionFilter));
	}
}
```
```c#
public static class ElasticApmServiceCollectionExtensions
{
	public static IServiceCollection AddElasticApmActionFilter(this IServiceCollection services, IConfiguration configuration)
	{
		return services
			.AddSingleton(_ => Agent.Tracer)
			.ConfigureOptions<ConfigureElasticApmActionFilter>();
	}
}
```

**Comment by yantang-msft** [comment]
This is also breaking how ApplicationInsights reports the operation name and thus break our dashboard: https://github.com/microsoft/ApplicationInsights-aspnetcore/blob/a135f1f7d9da7beb11f9bcf20a30f7e779b739f2/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/DiagnosticListeners/Implementation/HostingDiagnosticListener.cs#L872

**Comment by gregkalapos** [comment]
I believe this was fixed in https://github.com/elastic/apm-agent-dotnet/issues/628.

Feel free to reopen if the issue still happens.
