### ISSUE TITLE
Move to .NET Core 3.0

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#546]
- Both tooling and CI - especially for local tools mentioned [here](https://github.com/elastic/apm-agent-dotnet/pull/532#pullrequestreview-299706201)
- Also we should have sample apps exercising the agent on .NET Core 3.0. and also with ASP.NET Core 3.0

**Comment by vhatsura** [comment]
Hey, @gregkalapos. Do we have any updates on it? .Net Core 3.0 will allow using C# 8.0 to simplify code in some places.

**Comment by gregkalapos** [comment]
@vhatsura no update yet, we did not do any work yet.

**Comment by vhatsura** [comment]
> @vhatsura no update yet, we did not do any work yet.

Do you have smth we, as a community, can do it to help your team?

**Comment by gregkalapos** [comment]
> > @vhatsura no update yet, we did not do any work yet.
> 
> Do you have smth we, as a community, can do it to help your team?

@vhatsura I think a good first step would be to make sure we have test coverage for 3.0 - if we'd make both the `Elastic.Apm.Tests` and the `Elastic.Apm.AspNetCore.Tests` run both on `2.1` and `3.0` (actually `2.2` would be also nice) that would be already a good first step. 

I guess `Elastic.Apm.Tests` can be done by multitargeting, `Elastic.Apm.AspNetCore.Tests`  is more challenging, since that depends on the ASP.NET Core version.

If we would have that, we would already discover things like #604.

**Comment by gregkalapos** [comment]
Let's start working on this! 

I see @vhatsura already opened some PRs, which is awesome.

I think there will be multiple steps needed.

1.
First we have to make sure CI is able to build 3.x - I started working on it in #638. 

2. 
Then we can update the projects to target netcoreapp3.x - that is done in #622 (thanks for that!)

3.
And then once that's done we need to fix all the tests and fix some bugs (we already know about #632 - and I think I also saw that on 3.x the default service name detection does not work either, and maybe there are other things. 

Now, until step 3. is not done we won't have a green build, so I'd propose doing this work on a separate branch and once that's green we can merge the whole thing to `master`. I created a branch [`NetCore3`](https://github.com/elastic/apm-agent-dotnet/tree/NetCore3) - let's direct all 3.x related PRs to that branch. With that it's fine to merge things that are not green into that branch - everything that moves us to get closer to have 3.x is fine to merge. Please only do PRs that are about targeting 3.x - no refactorings, logical changes, etc - those can be done against master later if needed.

Another suggestion is that we go with the 3.1 SDK version which came out a couple of days ago. It's the LTS version (3.0 is not LTS), and it is basically 3.0 plus some minor fixes, so if 3.0 works I assume 3.1 will be just an additional target.

**Comment by gregkalapos** [comment]
Current status:

I moved a bunch of things to the `NetCore3` branch. 

CI: 
- Linux: fails - The linux stage runs in docker, my idea is to use the 3.1 base image and additionally install the 2.1 sdk into it - I spent some time on it with no success. I'll ping the automation team, they know jenkins better.
- Windows - .NET Framework: fails, the current MSBuild version is too old for .NET Core SDK 3.1 - added to https://github.com/elastic/observability-dev/issues/389. 
- Windows .NET Core: build green, but tests fail - the log output is strange - it does not reveal any info. More details: https://github.com/elastic/apm-agent-dotnet/pull/644#issuecomment-562967206 

 Targetframeworks:
`netcoreapp3.1` is missing, I'll add it. 

Tests:
All green locally on my machine. 

Next step: 
Tomorrow I'll talk to the automation team about the CI - I think we can make the Linux and  Windows .NET Core stages green fast.

**Comment by vhatsura** [comment]
> Targetframeworks:
> netcoreapp3.1 is missing, I'll add it.

Thanks for your update. I share my thoughts about an additional for `netcoreapp3.1` in https://github.com/elastic/apm-agent-dotnet/pull/622#discussion_r355208948.
It would be nice to hear your feedback about it

**Comment by gregkalapos** [comment]
Update: 

In #646 @v1v prepared CI for all the new targetframeworks. 

#647 is getting close to being ready to review and merge.

**Comment by gregkalapos** [comment]
Done in #647.
