### ISSUE TITLE
Not enough information about Exceptions.

### ISSUE THREAD

**Issue by insanity13** [elastic/apm-agent-dotnet#552]
![image](https://user-images.githubusercontent.com/1174911/66748026-23d2ca00-ee97-11e9-9579-4505cb19e030.png)
![image](https://user-images.githubusercontent.com/1174911/66748038-2b926e80-ee97-11e9-8efb-017ec112c4fc.png)

I think that information about Aggregateexception will shows the same way.
In this case, it’s more useful to see InnerException then StackTrace.

**Comment by gregkalapos** [comment]
Hey @insanity13 , 

we have https://github.com/elastic/apm-agent-dotnet/issues/358 - which points to a more general issue. I think that would also cover `AggregateException`s. Does this issue sound like a duplicate (or a subset) of https://github.com/elastic/apm-agent-dotnet/issues/358?

**Comment by insanity13** [comment]
@gregkalapos yes, thanks!
