### ISSUE TITLE
Full Net Framework: Support self hosted applications

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#557]
It would be nice to add support for self hosted .Net Framework applications. It can be achieved by implementing custom `DelegatingHandler`, which can be used as message handler in http self host configuration.

Are you interesting to have support for such applications?

**Comment by SergeyKleyman** [comment]
@vhatsura Could you please provide a simple example of such application?

**Comment by vhatsura** [comment]
> @vhatsura Could you please provide a simple example of such application?

Yeap, sure. Will provide an example

**Comment by stevejgordon** [comment]
Closing as stale
