### ISSUE TITLE
How to remove duplicate spans 

### ISSUE THREAD

**Issue by soumithx** [elastic/apm-agent-dotnet#569]
Capturing Span's leads to duplicate spans, how to remove ?

**Comment by SergeyKleyman** [comment]
@soumithx 
Could you please provide more information on the issue? Namely:
> Capturing Span's

How exactly do you capture spans? Do you use agent's public API or rely on automatic instrumentation? If you use agent's public API which methods do you use and how?

> duplicate spans

What exactly do you mean? Is it something you see in Kibana's APM UI? Could you provide a screenshot?

If you can reduce your issue to a minimal reproducible example that you can share it will allow us to investigate it much more quickly.

**Comment by soumithx** [comment]
Yes, i am using Public agent , i use like below,
1. Get Current Transaction
2.Calling Start span method to the transaction
3.Adding label to that span

after executing the code ,  i see the UI with started span , with duplicates

**Comment by soumithx** [comment]
@SergeyKleyman   ?

**Comment by SergeyKleyman** [comment]
@soumithx 
We definitely have tests covering this use case. That means that there is some substantial difference between how those tests use agent's public API and how your application uses it. We need to find out what that difference is. I recommend you to reduce your issue to a minimal reproducible example that you can post here.
