### ISSUE TITLE
How to add a xml label to the span ? 

### ISSUE THREAD

**Issue by soumithx** [elastic/apm-agent-dotnet#571]
i am using  apm for .Net API Calls , i want to add label for a xml string , if it converted to string , displaying on UI with truncted text ? is there any way to get Full XML

**Comment by SergeyKleyman** [comment]
Hi @soumithx,

Labels are indeed limited to 1024 characters and if a label is longer it is truncated.

APM has a mechanism to attach pieces of data longer than 1024 characters and that mechanism is [custom context](https://github.com/elastic/apm-server/blob/6.5/docs/spec/context.json#L7). But it's not implemented by .NET agent yet (https://github.com/elastic/apm-agent-dotnet/issues/419) and when custom context will be supported by .NET agent it will be available only for transactions and errors (for example it will not be available for spans). Will custom context work for your use case?

In addition a small administrative issue. As mentioned in [README](https://github.com/elastic/apm-agent-dotnet/blob/master/README.md) we recommend using [the forum](https://discuss.elastic.co/tags/c/apm/dotnet) for questions and GitHub issues for confirmed bugs and enhancement requests. The forum allows other users to learn from the questions and answers and the number of people that can answer a question at the forum is much larger than at the Github repo which is mostly for developers of the agent.

**Comment by soumithx** [comment]
ok thanks @SergeyKleyman 👍
