### ISSUE TITLE
Capture stack traces improvements (Async, etc.)

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#6]
***Scope***
Send stack traces for Spans.

***Issues***

1. 
In case of async calls the stack trace is very hard to read. In .NET Core 2.1 this was improved, but only for exceptions (at least this is what I see...). Capturing a stack with System.Diagnostics.StackTrace().GetFrames() still returns the "real", hard-to-read stack trace and I did not find any .NET Standard 2.0 API which would demystify those stack traces.

I tried using [Ben.Demystifier](https://github.com/benaadams/Ben.Demystifier), but within the DiagnosticSource OnNext() method it threw an exception - so it'd be an additional dependency + it does not work for this use case out of the box. 

2. 
Another problem related to .NET is that we seem to show this format on the UI:
[FileName] in [Function] at [Lineno]. 

<img width="1597" alt="screenshot 2018-11-20 at 09 54 39" src="https://user-images.githubusercontent.com/1091853/48762432-525a1c00-ecab-11e8-8548-76dd334f398d.png">

Currently the agent sends the assembly name as filename and since the [stacktrace_frame definition](https://github.com/elastic/apm-server/blob/master/docs/spec/stacktrace_frame.json) doesn't have a "class" or "type" field I send the type name in the "module" field, but that is not shown on the UI.
So we end up showing [AssemblyName] in [Function (aka method)] at [lineno].
For .NET a better format would be something like this:
[Module (aka .NET type name)] in [Function (aka method)] at [Lineno]. A workaround would be to send the Typename in the filename field, but to me that does not sound correct.

3. 
We don't always have lineno, this topic is currently discussed [here](https://github.com/elastic/apm/issues/18).

***Current status***
In case of outgoing HTTP calls I already send callstacks, we just need to discuss how/what fields I need to fill.

**Comment by Mpdreamz** [comment]
> I tried using Ben.Demystifier, but within the DiagnosticSource OnNext() method it threw an exception - so it'd be an additional dependency + it does not work for this use case out of the box.

Might be worthwhile opening an issue @gregkalapos. The additional dep can be shaded and merged if it's a problem (we do this with json.net in the .net client).

**Comment by gregkalapos** [comment]
Done in #847
