### ISSUE TITLE
Current transaction is null for ASP.NET Web API

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#602]
Mentioned for the first time - https://github.com/elastic/apm-agent-dotnet/issues/83#issuecomment-516472934.
[Brought up by another user at discuss](https://discuss.elastic.co/t/current-transaction-is-empty-aspnetfullframework/206812).

**Comment by kodigo35** [comment]
Hello, i have this issue with WCF support on 1.2 release.

CurrentTransaction is null when calling in WCF services, due to AsyncLocal

i fixed it temporarly using httpcontext.current to store CurrentTransaction and CurrentSpan.

Is there a workaround for this issue ?

**Comment by SergeyKleyman** [comment]
> i fixed it temporarly using httpcontext.current to store CurrentTransaction and CurrentSpan.
> 
> Is there a workaround for this issue ?

It sounds like you have a workaround (using `HttpContext.Current`) or did I misunderstand what you meant by "i fixed it temporarly"?

Unfortunately, at the moment (as of agent version 1.2) there is no fix for this issue available out of the box. We accept community PRs if you would like to give it a try.

BTW I have (albeit not 100% verified) understanding why `CurrentTransaction` using `AsyncLocal` doesn't work for WCF but are you sure `CurrentSpan` doesn't work neither?

**Comment by kodigo35** [comment]
thx for your reply

i have a workaround for WCF but i am not sure it is convenient for .net api calls.

i have to make more tests on basic http api calls using async tasks.

i guess asynclocal use has been made for a particular reason

**Comment by sluebbert** [comment]
@kodigo35,

Is your work around a short one that can be shared here as a snippet or is it lengthy? We are bumping up against this too for our WCF services. I'm suspicious this is also causing auto wrapping of outgoing HTTP calls to not be collected in these services as well.

Thanks!

**Comment by kodigo35** [comment]
@sluebbert sorry for delay, my workaround is pretty simple.

on which branch do you want me to PR ?

**Comment by sluebbert** [comment]
@kodigo35 thanks for following up. I think we would rather live with the issue for now if it involves a patch to this repo vs making a work around outside of it within our code.  We are trying to stick with the official releases.

**Comment by kodigo35** [comment]
ok no prb, here's what i did if you want to integrate it later
CurrentExecutionSegmentsContainer.cs
```
               public Span CurrentSpan
		{
			get
			{
				if (HttpContext.Current.Items["Elastic.Apm.CurrentSpan"] != null)
				{
					return HttpContext.Current.Items["Elastic.Apm.CurrentSpan"] as Span;
				}

				return null;
			}

			set => HttpContext.Current.Items["Elastic.Apm.CurrentSpan"] = value;
		}

		public Transaction CurrentTransaction
		{
			get
			{
				if (HttpContext.Current.Items["Elastic.Apm.CurrentTransaction"] != null)
				{
					return HttpContext.Current.Items["Elastic.Apm.CurrentTransaction"] as Transaction;
				}

				return null;
			}

			set => HttpContext.Current.Items["Elastic.Apm.CurrentTransaction"] = value;
		}
```

**Comment by russcam** [comment]
@sluebbert, @kodigo35 

#992 introduced an `ICurrentExecutionSegmentsContainer` implementation that uses both `HttpContext` and `AsyncLocal<T>` to get/set the current transaction/span. This is in version [1.7.0](https://www.nuget.org/packages/Elastic.Apm/1.7.0) onwards. If you're running Web API or WCF in IIS and using the `ElasticApmModule`, this will address the issue.

Closing this as I believe this is now addressed.
