### ISSUE TITLE
Documentation for CaptureBodyContentTypes is not fit with implementation

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#603]
In documentation for `CaptureBodyContentTypes` configuration parameter mentioned that default value is [`application/x-www-form-urlencoded*, text/*, application/json*, application/xml*`](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/configuration.asciidoc#capturebodycontenttypes-performance-added101), however, it isn't aligned with implementation:

https://github.com/elastic/apm-agent-dotnet/blob/a73b10f0f6d61de45786f10501120644b9a82ff7/src/Elastic.Apm/Config/AbstractConfigurationReader.cs#L658-L660

**Comment by gregkalapos** [comment]
In #577 (not merged yet) this will be probably fixed - see [here](https://github.com/elastic/apm-agent-dotnet/pull/577/files#diff-e74fe9fba394b4822dd5cd6256fb737eR658) - at least as the code looks now I think this will be covered there.

**Comment by vhatsura** [comment]
Closes the issue due to #577 was merged
