### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#61]
Currently the logging interface is very simple. It's basically 1 method, with it's string parameter (which contains the log level, all the parameters, etc). Users have access to the log, and they can redirect it wherever they want by doing this:

```
Agent.Config.Logger = new CustomLogCollector();

class CustomLogCollector : AbstractLogger
{
	protected override void PrintLogline(string logline)
	{
		//send the logline or process it...
	}
}
```

@SeanFarrow suggested [here](https://github.com/elastic/apm-agent-dotnet/issues/31#issuecomment-452500948) that: 

> Even if I derive from AbstractLogger to send the log somewhere else, I’m stuck with a string and would have to use something else to extract data using regex or an alternative input such as LogStash.

Let's discuss if we could make this a nicer interface! I'm totally open to provide an interface with more details.

@SeanFarrow feel free to suggest a specific interface if you have something in mind. 

Thanks

**Comment by SeanFarrow** [comment]
Should we be logging any exceptions, or do they not apply?

**Comment by Mpdreamz** [comment]
`TState` could very well be an `Exception`. `Microsoft.Extensions.Logging.ILogging.Log` has these separated not sure we need too.

**Comment by SeanFarrow** [comment]
Makes sense.
