### ISSUE TITLE
Revert addition of volatile backing field to Agent.IsConfigured

### ISSUE THREAD

**Issue by NeoXtreem** [elastic/apm-agent-dotnet#623]
The changes in #621 to add a `volatile` backing field to `Agent.IsConfigured` (on the basis of the two assignments in `Agent.Setup` being reordered by hardware optimisation) are likely unnecessary.

As stated [here](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2#c-memory-model-implementation-on-the-x86-x64):

> The x86-x64 processor will not reorder two writes

As for the JIT compiler, ordering is guaranteed on the x86-x64 processor as also mentioned in the aforementioned link:

> the JIT compiler doesn’t need to use any special instructions on the x86-x64 to achieve volatile semantics

I suggest to simply revert the changes in [this PR](https://github.com/elastic/apm-agent-dotnet/pull/621).

**Comment by SergeyKleyman** [comment]
[The article's "Example: Lazy Initialization" section](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2#example-lazy-initialization) explains why various implementations without `volatile` are incorrect and provides a correct implementation using `volatile`.

**Comment by NeoXtreem** [comment]
> [The article's "Example: Lazy Initialization" section](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2#example-lazy-initialization) explains why various implementations without `volatile` are incorrect and provides a correct implementation using `volatile`.

@SergeyKleyman The 'correct' implementation is for lazy initialisation which involves a mixture of reads and writes in the same function.  We're not talking about lazy initialisation for `IsConfigured`.  The 'correct' implementation is just for demonstration and even states:

> Note that even though the code sample is correct, in practice it’s still preferable to use the Lazy<T> or the LazyInitializer type.

Using `Lazy<T>` or `LazyInitializer` does not apply to `IsConfigured` because it's not a "lazy" use case.

Even the 'incorrect' implementations are not relevant as all implementations (both 'correct' and 'incorrect') in this section relate to lazy initialisation.  However, the first 'incorrect' initialisation (figure 5 does clarify below it that _"this code will behave correctly (that is, always return 42) on all architectures in the .NET Framework versions 4 and 4.5"_, and then goes on to explain why for each architecture, namely:

> - x86-x64:
>   - Writes and reads will not be reordered. There is no store-load pattern in the code, and also no reason the compiler would cache values in registers.
> - Itanium:
>   - Writes will not be reordered because they are ST.REL.
>   - Reads will not be reordered due to data dependency.
> - ARM:
>   - Writes will not be reordered because DMB is emitted before “_boxedInt = b.”
>   - Reads will not be reordered due to data dependency.

So it appears that the change in #621 will do nothing additional to what is already guaranteed by the .NET Framework version and architectures. And I accept that because this seems like it would break multithreaded applications everywhere otherwise, because `volatile` is not typically used to protect two interdependent publicly-accessible variables from optimisation reordering.

**Comment by SergeyKleyman** [comment]
The relation between `Agent._components` and `Agent._isConfigured` in the way they used in `Agent.Setup()` and callers of `Agent.Instance` is the same as `LazyExample._value` and `LazyExample._initialized ` in Incorrect Implementation No. 2 and 3 so the article's conclusions apply. The fact that in our case writes are done in `Agent.Setup()` while reads are done by another methods doesn't matter for the purposes of this discussion.

Regarding the quote you have provided above - the quote is from Incorrect Implementation No. 1 while our use case is the same Incorrect Implementation No. 2 and 3 and not No.1, But even if we put that aside, the article itself explicitly discourages from relying on the quote you provided above with the sentence that follows it:
> Of course, you should use this information only to try to understand the behavior of existing code. Do not use this pattern when writing new code.

**Comment by NeoXtreem** [comment]
@SergeyKleyman I can see that the second 'incorrect' implementation is similar to our situation, _"but that behavior doesn’t seem to happen in the .NET Framework 4.5."_ (quote from the article).

Regarding where it says _"Do not use this pattern when writing new code"_, then this implies to use the 'correct' implementation above (in the article) which states _"that even though the code sample is correct, in practice it’s still preferable to use the Lazy<T> or the LazyInitializer type"_. So, based on what you're saying in relation to the article, we should wrap `IsConfigured` in `Lazy<T>`. This is why I said early, this is not a matter of lazy initialisation, so I think the fact that this won't happen on .NET Framework 4.5 (onwards) according to the article, or indeed x86-x64 at all (this is inferred by the article where it says _"this version may fail and return 0 on ARM and Itanium in practice"_) is an argument against using `volatile`.

**Comment by SergeyKleyman** [comment]
Regarding

> so I think the fact that this won't happen on .NET Framework 4.5 (onwards)

The article says absolute opposite:

> This behavior isn’t guaranteed by the ECMA C# spec, and, consequently, might not hold in future versions of the .NET Framework and on future architectures (and, in fact, does not hold in the .NET Framework 4.5 on ARM).

Please note that we claim to support .NET Core which runs on ARM. 

The article clearly discourages relying on implementation details (vs a spec such ECMA C#) of particular .NET runtime implementation (such as .NET Framework 4.5 on  x86-x64):
> rely on the ECMA C# specification guarantees and not on architecture-specific implementation details

I am not sure I understand what is your argument so I would like to ask you [again](https://github.com/elastic/apm-agent-dotnet/pull/621#discussion_r349048474):
 - Are you saying that the problem described in #621 doesn't actually occur so there is no need to fix anything?
- Or do you agree that there's a problem but the fix implemented in #621 is incorrect?

**Comment by NeoXtreem** [comment]
@SergeyKleyman I note you are being selective in quoting excerpts from the article out of context. Note that I am trying to help with Elastic APM code where it doesn't materially affect my own project right now.

My comment that _"I think the fact that this won't happen on .NET Framework 4.5 (onwards)"_ is directly based on the quote from the article that _"that behavior doesn’t seem to happen in the .NET Framework 4.5"_ which is under the second 'incorrect' implementation which is the most similar situation to ours as it specifically refers to the reordering of two reads (and indeed, two writes).

What you are quoting where you say the article says the "absolute opposite" is in the context of Itanium. To put the whole excerpt (with the part you selected **bolded**):

> The reason Itanium is an interesting part of the story is that it was the first architecture with a weak memory model that ran the .NET Framework.
> 
> As a result, in a number of articles about the C# memory model and the volatile keyword and C#, the authors generally had Itanium in mind. After all, until the .NET Framework 4.5, Itanium was the only architecture other than the x86-x64 that ran the .NET Framework.
> 
> Consequently, the author might say something like, “In the .NET 2.0 memory model, all writes are volatile—even those to non-volatile fields.” What the author means is that on Itanium, CLR will emit all writes as ST.REL. **This behavior isn’t guaranteed by the ECMA C# spec, and, consequently, might not hold in future versions of the .NET Framework and on future architectures (and, in fact, does not hold in the .NET Framework 4.5 on ARM).**
> 
> Similarly, _some folks would argue that lazy initialization is correct in the .NET Framework even if the holding field is non-­volatile, while others would say that the field must be volatile_.
> 
> And of course, developers wrote code against these (sometimes contradictory) assumptions. So, _understanding the Itanium part of the story can be helpful when trying to make sense of concurrent code written by someone else, reading older articles or even just talking to other developers_.

I have _italicised_ parts in the last two paragraphs that seem to be where we are disagreeing. I am arguing that the _"initialisation is correct ... even if the holding field is non-­volatile, while [you] say that the field must be volatile."_ Based on the last paragraph of the quoted part above (which is where your quote came from in context), I now _"understand the Itanium part of the story"_ while making sense of the _"code written by [you]"_ which itself seems to be based on an article written almost 7 years ago (_"older articles"_).

In summary, this article that you are relying on to back up your argument predates .NET Core by several years. It is almost 7 years old, and is written based on a version of .NET Framework and C# equally as old.

I think the only definitive way of resolving this discussion, without using quotes out of context and wasting each other's time further, is to refer directly to the [latest ECMA C# spec](https://www.ecma-international.org/publications/standards/Ecma-334.htm) as it currently stands. Since you made the change recently on top of my own recent changes, I would ask you to verify this given that your changes seem only to be loosely aligned with a 7-year-old article that also alludes to those changes being relevant only for Itanium, and not for x86-x64 on .NET Framework 4.5 onwards even when the article was written.

It's reasonable to surmise that this aspect of the specification may have been concreted since then in the specification or otherwise, and my professional and experienced opinion is that such ordering considerations in terms of optimisation are typically not necessary in modern programming (due to WYSIWYG being applied ever increasingly in high-level languages, not least in recent years).

**Comment by SergeyKleyman** [comment]
> Note that I am trying to help with Elastic APM code where it doesn't materially affect my own project right now.

Thank you very much for that and we welcome community contributions.

> refer directly to the latest ECMA C# spec as it currently stands

[ECMA-334 (5th Edition / December 2017)](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf) 8.10 Execution order 
>The execution environment is free to change the order of execution of a C# program, subject to the following constraints:
    - The ordering of side effects is preserved with respect to volatile reads and writes 

Regarding

>  such ordering considerations in terms of optimisation are typically not necessary in modern programming

I think the opposite is the case - it stems from the fact that CPU manufactures cannot improve performance by increasing CPUs frequency anymore and instead modern CPUs scale horizontally (by increasing number of cores). Herb Sutter's [article "The Free Lunch Is Over"](http://www.gotw.ca/publications/concurrency-ddj.htm) gives detailed explanation on that point. This change, just as movement to distributed/microservices architecture, means that some burden is shifted to the application programmer unless you just don't use threads like NodeJS or don't share any data between threads like Rust/Kotlin Native or always use locks to ensure thread safety which, akin to distributed transactions, might introduce a considerable performance overhead.  I also recommend to watch the following presentations by Herb Sutter where he explains how thread safety and runtime environment's memory model are related. It's based on C++ `atomics` which are essentially the same thing as C# `volatile`.

https://www.youtube.com/watch?v=A8eCGOqgvH4
https://www.youtube.com/watch?v=KeLBd2EJLOU

**Comment by SergeyKleyman** [comment]
I hope my last comment didn't address your concerns and we can close this issue.
