### ISSUE TITLE
[Discussion] Make some agent components internal

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#626]
I'd like to open a discussion about our current [`AgentComponents`](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/AgentComponents.cs) and maybe to make some of the things it exposes `internal`. 

Currently exposed through `AgentComponents`:
- `IApmLogger`
- `IConfigurationReader`
- `IPayloadSender`

I know @SergeyKleyman already works on some `IConfigurationReader` refactoring - regardless of that, I'd like to discuss if we maybe would like to make some of those completely internal and not expose it to our users. 

## Why?
Mainly to simplify things.

I think some of these, especially `IConfigurationReader` already caused some challenges to us. Each time we change something on the public API, we make a breaking change. 

Plus, all these interfaces add some complexity on the Public API of the agent - although these are optional parameters when you configure the agent, so technically users can ignore it, still, those are there, and people may wonder what those are. 

I suspect it's hard to understand those, and I'm not sure there is a subset of our user-base that even needs to understand these - unless they'd like to contribute to the agent (but that's a different story).

On the other hand, I'm not sure our users really use those - or even that they should use those. 

### `IConfigurationReader`
(or whatever equivalent we'll have after the refactoring)

This is something that other agents I think do not expose. We already support a couple of ways to configure the agent: 1) environment variables, 2) Microsoft.Extensions.Config, 3) Web.config - if there is more, I think we should just add that and introduce some ways to switch between these configs. Overall I think it's kind of odd that you can configure how you configure the agent 🤯

### `IApmLogger`
This is probably something that should remain public 

### `IPayloadSender`

Once we implement ways to turn off the agent I don't really see any useful reason for this being public either. Furthermore other than a NoOp implementation I think it's very hard to offer a proper implementation of this.

Now, these are some early thoughts on this, nothing is decided - I just wanted to write down my thoughts and maye have some input on these.

**Comment by SergeyKleyman** [comment]
### `IConfigurationReader`
As requested at #553 by a user (unfortunately without further details about the actual use case) I think it's worth allowing users to provide custom configuration as simple `string`  to `string` map (for example we can call it _raw_ configuration). As a concept it fits very well into configuration sub-system design by shifting from inheritance between various `ConfigurationReader`s that we use in the current implementation to composition of just one parser and various raw configuration sources. But I don't have strong opinion one way or the other regarding if we should wait for actual requests from users before making it `public`.

### `IPayloadSender`
I agree that there isn't much value in allowing users to provide custom `IPayloadSender` - at least until we have requests to do so from user with use cases that can benefit from `IPayloadSender` being part of `AgentComponents`.

**Comment by BellBat** [comment]
I am using the public api to implement functionality on an internal framework and would prefer these to stay open. Honestly I would prefer some areas closed now to be open since I have to re-code; ex helpers.

I am currently using the IConfigurationReader to adapt the framework config interface to the agent including utilizing some values that already exist as global config (ex: ServiceName) and creating out of the box experience for our developers.

I am looking at using the payload sender to customize the output of some of the captured data.

**Comment by diablo39** [comment]
Hi,
I agree with @BellBat. With current implementation it's hard to extend solution and introduce new functionalities.
For instance I would like to use kafka as medium for sending traces.

**Comment by gregkalapos** [comment]
Thanks for the responses here - ok I can see those use cases @BellBat  - not taken. The `IConfigurationReader` may changes, since each time we add a new config we technically break your code, which is not ideal - but we can definitely keep it open. 

@diablo39 could you please elaborate?  What new functionalities would you like to implement? Regarding kafka as a medium for sending traces: that's definitely not something we designed for or thought about - we send traces over HTTP. But actually by implementing `IPayloadSender` you could do that - at least off the top of my head I don't see any reason why you couldn't. Let me know, if you need I can point you to some code places on how to do the custom implementation.

**Comment by BellBat** [comment]
@gregkalapos 
Yes it has already changed and we have to add configs as we upgrade to the newest version.
I simply see this as the price we pay.

Since the integrator also need to evaluate new functionality it is not a big deal for this use case.

**Comment by gregkalapos** [comment]
> I simply see this as the price we pay.

I really appreciate the way you think about this :) 


All right, closing this now - no change planned near term. Thanks everyone for the feedback!
