### ISSUE TITLE
Ignore error reporting

### ISSUE THREAD

**Issue by ffMathy** [elastic/apm-agent-dotnet#633]
Can we control that APM should not report errors, or at least control what errors are reported?

I already have error logging in place directly to Elasticsearch, and it is properly configured to filter out specific errors that are out of my control (by other libraries etc).

APM picks up all these errors, which spams my cluster, and makes it unavailable.

**Comment by gregkalapos** [comment]
Hi @ffMathy 

Unfortunately there is nothing in the APM Agent that'd give you this functionality at the moment. Let's keep this issue open and see what we can come up with.

**Comment by gregkalapos** [comment]
#792 added an API to register filters - with that you'll be able to drop all errors that the agent'd send. Will be out with the next agent release. Docs will follow soon, too.
