### ISSUE TITLE
Add Transaction.Type to errors

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#64]
Add support for elastic/apm-server#1781

**Comment by vhatsura** [comment]
@gregkalapos, as I understand transaction type for error is already added: https://github.com/elastic/apm-agent-dotnet/blob/a951cbd9cc0c26e2d8154f54890ee5f10e90ba09/src/Elastic.Apm/Model/Error.cs#L82-L86

Am I right or maybe I look into wrong place?

**Comment by gregkalapos** [comment]
Yes, nice catch - this was added in https://github.com/elastic/apm-agent-dotnet/pull/188. 

Closing.

Thanks!
