### ISSUE TITLE
Create a way to release "ad hoc" Agent builds to users

### ISSUE THREAD

**Issue by SergeyKleyman** [elastic/apm-agent-dotnet#653]
Lately more than once we encountered a situation where it would very useful to release an "ad hoc" build for users with issues that only they can reproduce - either a build with additional logging to investigate the issue and/or with changes to try out a potential fix. To achieve that we should find a way to make those "ad hoc" builds available to external users so they can easily reference them from their applications.

Indirectly related elastic/apm-agent-dotnet#619 in that if we set up automated testing for "about-to-be-released" Agent builds (to verify that NuGet package was built successfully, etc.) we can use that testing in both use case: releasing stable builds (major, minor, patches) and "ad hoc" builds.

**Comment by v1v** [comment]
I'll keep here a list of possible repository services:
- https://artifactory.elstc.co/artifactory

**Comment by gregkalapos** [comment]
I think we already have this - although I have never used it.

First of all we publish to [AppVeyor](https://github.com/elastic/apm-agent-dotnet/blob/master/Jenkinsfile#L348) - bad thing I don't know what URL we push to... @kuisathaverat  @v1v  - could you tell me that? We hide it from the logs. 

Second in CI we always create the nuget packages as artifacts on master - not on custom branches. But if the branch is something we want to publish, we can just quickly adapt the jenkinsfile to create artifacts or push to AppVeyor on a non `master` branch. 

I feel that's good enough. 

Anyone against closing this?

**Comment by kuisathaverat** [comment]
the URL and credential are in the Vault `secret/apm-team/ci/elastic-observability-appveyor`

**Comment by v1v** [comment]
@gregkalapos , I'll close this issue as solved with your abovementioned points :)
