### ISSUE TITLE
Support for Cassandra

### ISSUE THREAD

**Issue by willsilvano** [elastic/apm-agent-dotnet#664]
Hi guys! :)

I have verified that the nodejs agent has support for the Cassandra database: https://www.elastic.co/en/blog/elastic-apm-nodejs-agent-1-10-0-released

There is currently a driver for dotnet connection to Cassandra: https://www.nuget.org/packages/CassandraCSharpDriver/

I am using this driver above, and have set up the APM agent for dotnet, but it is only capturing HTTP requests.

Is there any chance of developing support for Cassandra?

**Comment by lreuven** [comment]
Thanks for the feedback,
I've added it to our backlog, feel free to jump in and contrib

**Comment by gregkalapos** [comment]
I quickly looked at the library - no `DiagnosticSource` unfortunately :(

**Comment by russcam** [comment]
@willsilvano This could be a candidate using the profiler auto instrumentation approach: #1534. I'm not overly familiar with the Cassandra C# driver, but from a cursory look, `session.Execute()` and `session.ExecuteAsync()` look like the methods to instrument.

I don't think Cassandra has come up very often as something we're missing instrumentation for, so this would likely be a low priority at this time.

**Comment by stevejgordon** [comment]
Closing this as unplanned
