### ISSUE TITLE
[Docs] Serilog/NLog links point to 404 pages

### ISSUE THREAD

**Issue by brolaugh** [elastic/apm-agent-dotnet#668]
**Describe the bug**
[This page](https://github.com/elastic/apm-agent-dotnet/blob/master/docs/log-correlation.asciidoc) describes that I can use `Elastic.Apm.SerilogEnricher` and `Elastic.CommonSchema.Serilog`  to enrich my logs etc. however, the links like shown in the quotes below leads 404 page on nuget. It's the same for the link to `Elastic.Apm.NLog`

>### Serilog
> We offer a Serilog Enricher that adds the trace id to every log line that is created during an active trace.
> The enricher lives in the [Elastic.Apm.SerilogEnricher](https://www.nuget.org/packages/Elastic.Apm.SerilogEnricher) NuGet package.

>If you want to send your logs directly to Elasticsearch you can use the [Serilog.Sinks.ElasticSearch](https://www.nuget.org/packages/Serilog.Sinks.Elasticsearch) package. Furthermore, you can pass the `EcsTextFormatter` from the [Elastic.CommonSchema.Serilog](https://www.nuget.org/packages/Elastic.CommonSchema.Serilog) package to the Elasticsearch sink, which formats all your logs according to Elastic Common Schema (ECS) and it makes sure that the trace id ends up in the correct field.

>### NLog
> For NLog, we offer two LayoutRenderers that inject the current trace and transaction id into logs.

> In order to use them, you need to add the [Elastic.Apm.NLog](https://www.nuget.org/packages/Elastic.Apm.NLog) NuGet package to your application and load it in the <extensions> section of your NLog config file:

**Comment by gregkalapos** [comment]
Hi @brolaugh,

this doc was merged yesterday and the packages are not yet released. This was known when I merged the [PR](https://github.com/elastic/apm-agent-dotnet/pull/663).

The official documentation is here: https://www.elastic.co/guide/en/apm/agent/dotnet/current/index.html 

That points to `1.x (current)` which is the latest version. The `master` branch both here in GitHub and on the docs page can contain things that are not yet released - so the "current" docs is the one that documents the latest release, `master` is always under construction.

cc @bmorelli25 - is this something we should maybe change?

**Comment by bmorelli25** [comment]
Sorry about the confusion @brolaugh. As @gregkalapos explained, you're looking at the documentation for an unreleased version.

> cc @bmorelli25 - is this something we should maybe change?

No. The master branch of documentation has a banner at the top for this reason:
<img width="746" alt="Screen Shot 2019-12-20 at 9 44 40 AM" src="https://user-images.githubusercontent.com/5618806/71278791-5f619880-230d-11ea-9752-d92f36ce2088.png">

**Comment by gregkalapos** [comment]
The one small bug that probably broke this experience is that the .NET log correlation docs on GitHub pointed to the Java Agent docs 😇  

Fixed in https://github.com/elastic/apm-agent-dotnet/pull/669 .

**Comment by brolaugh** [comment]
Within my organization we use GitFlow (I believe it's called) were the master branch is always on the latest release which is why I found it odd that you had broken links 😄

**Comment by bmorelli25** [comment]
Ahh, that makes sense!

If you spot anything else that looks amiss, don't hesitate to let us know 😄
