### ISSUE TITLE
Ampserver settings should be loadable from other location than web.config

### ISSUE THREAD

**Issue by kodigo35** [elastic/apm-agent-dotnet#675]
In heavy distributed context, apm settings should be loadable from other service like database or external configuration service.

ElasticApmModule uses FullFrameworkConfigReader class to load settings from web.config file

var agentComponents = new AgentComponents(rootLogger, new **FullFrameworkConfigReader**(rootLogger));

ConfigReader instance could be declared in app start.

**Comment by gregkalapos** [comment]
We work on a feature that will address exactly this. Some settings are already part of this.

You can read about it here: https://www.elastic.co/guide/en/kibana/7.5/agent-configuration.html

I feel that addresses your issue - in general this is the direction we take our config story. 

Closing this, but feel free to reopen if we should discuss something about this.

**Comment by kodigo35** [comment]
Thanks for your feedback
