### ISSUE TITLE
Merge netcore 3.0 and server certificate branch

### ISSUE THREAD

**Issue by KINGGUOKUN** [elastic/apm-agent-dotnet#676]
When does the .netcore 3.0 and server certificate branch merge to master and release the nuget?

**Comment by gregkalapos** [comment]
Do you mean https://github.com/elastic/apm-agent-dotnet/pull/465? 

That is not related to .NET Core 3.0 - https://github.com/elastic/apm-agent-dotnet/issues/546 has more details on our .NET Core 3.x effort - that work is done.

**Comment by KINGGUOKUN** [comment]
OK , thanks .
