### ISSUE TITLE
Use classname in stacktrace 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#677]
From https://github.com/elastic/kibana/issues/49467, implemented in APM Server: https://github.com/elastic/apm-server/pull/3096.

Now we can send `classname` instead of misusing the `filename`.

**Comment by gregkalapos** [comment]
This will also close https://github.com/elastic/apm-agent-dotnet/issues/677

**Comment by russcam** [comment]
Does this need looking at for 7.10, @gregkalapos ?

**Comment by gregkalapos** [comment]
@russcam, yes I'd like to have this in the next release, but it's not really a 7.10 cross agent issue.

It's on my todo list for today - https://github.com/elastic/apm-agent-dotnet/pull/848 is about this, I'd like to finish it today.

**Comment by gregkalapos** [comment]
Implemented in https://github.com/elastic/apm-agent-dotnet/pull/848.
