### ISSUE TITLE
Please add a time component/minimum threshold to the sampling rate

### ISSUE THREAD

**Issue by jderose9** [elastic/apm-agent-dotnet#679]
**Is your feature request related to a problem? Please describe.**
I have drastically fluctuating load. I would like a consistent picture of performance at any point in time. I would like to have a minimum threshold of captures over time before the sampling rate kicks in. If the load is low, I would like to capture most/all traces. If the load is high, I don't want to capture an overwhelming amount of traces

**Describe the solution you'd like**
Ideally I could set some amount of time (ie. 1 second, 100ms, etc) for which at least one trace will be captured, regardless of the TransactionSampleRate. Or alternatively, a minimum number of traces to be captured over a set time period before the TransactionSampleRate is utilized.

**Describe alternatives you've considered**
This is a feature provided in AWS X-Ray and described as the "reservoir".
https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html

By default, the first trace each second will be captured.

**Additional context**

**Comment by gregkalapos** [comment]
Something like this is discussed over here in general for all agents: https://github.com/elastic/apm/issues/201

**Comment by stevejgordon** [comment]
Closing as unplanned
