### ISSUE TITLE
Documentation does not describe how to manually enable individual traces/subscribers

### ISSUE THREAD

**Issue by jderose9** [elastic/apm-agent-dotnet#680]
**Describe the bug**
The documentation states:

>In case you only reference the Elastic.Apm.AspNetCore package, you won’t find the UseAllElasticApm. Instead you need to use the UseElasticApm() method from the Elastic.Apm.AspNetCore namespace. This method turns on ASP.NET Core tracing, and gives you the opportunity to manually turn on other components. By default it will only trace ASP.NET Core requests - No HTTP request tracing, database call tracing or any other tracing component will be turned on.

The problem is that it does not describe how to  "manually turn on other components".

**Expected behavior**
I had to examine the source code to determine how to manually enable individual components, which I believe is:

```
app.UseElasticApm(this.Configuration,
                    new HttpDiagnosticsSubscriber() /* Enable tracing of outgoing HTTP requests */,
                    new EfCoreDiagnosticsSubscriber() /* Enable tracing of database calls */)
```

**Comment by gregkalapos** [comment]
👍 

Opened #687 to extend the docs.

Thanks for opening this.

**Comment by gregkalapos** [comment]
https://github.com/elastic/apm-agent-dotnet/pull/687 merged.
