### ISSUE TITLE
Support for .Net Core 3.1.

### ISSUE THREAD

**Issue by aspramsh** [elastic/apm-agent-dotnet#684]
Hi. I would like to ask, if the package supports .Net Core 3.1?

**Comment by gregkalapos** [comment]
> Hi. I would like to ask, if the package supports .Net Core 3.1?

Hi @aspramsh,

Yes, .NET Core 3.1 is supported - we [also have automated tests](https://github.com/elastic/apm-agent-dotnet/blob/master/test/Elastic.Apm.AspNetCore.Tests/Elastic.Apm.AspNetCore.Tests.csproj#L3) against 3.1.

**Comment by aspramsh** [comment]
Thanks a lot.
