### ISSUE TITLE
APM does not seem to use Asp.Net 3.0+ Tracing Context (W3C Trace Context/Activity)?

### ISSUE THREAD

**Issue by ckarcz** [elastic/apm-agent-dotnet#691]
In Asp.Net Core 3.0, they adopted the [W3C Trace Context standard](https://www.w3.org/TR/trace-context-1/)

https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/

The AspNetCore APM agent does not seem to be using the same tracing context as the framework, which I believe is ```Activity.Current```.

The trace.id logged to ES is not the same TraceId that the framework uses (and logs in a scope).

This means we cannot view logs (in Kibana) of a trace you are viewing in Kibana APM app.

I'm not sure if something is not set up correctly, or the APM agent is not using the same tracing context as the framework.

😿

**Comment by gregkalapos** [comment]
> I'm not sure if something is not set up correctly, or the APM agent is not using the same tracing context as the framework.

I assume your setup correct, we create our own trace id and not use the one that is created by `Activity`. 

The main reason is that when we started (a year ago) the `Acitivty` id wasn't logged anywhere, and I believe that the feature that ASP.NET Core creates a trace id and `HttpClient` puts that into the `traceparent` header was also introduced in 3.0 - plus we also support Full Framework.

Nevertheless I agree that we should think about reusing the id from `Activity`, if there is one. So I leave this issue here, definitely something worth investigating.

Regarding this:

> This means we cannot view logs (in Kibana) of a trace you are viewing in Kibana APM app.

Look at our almost brand new log correlation story [here](https://www.elastic.co/guide/en/apm/agent/dotnet/master/log-correlation.html). That's something we continuously work on and plan to add support for more scenarios.

**Comment by ckarcz** [comment]
thanks for the prompt reply @gregkalapos. that is great to hear. and thanks for linking to that enricher package, as I did not know about it and it should solve my problem of correlating the APM and application logs. 👍

**Comment by gregkalapos** [comment]
We had some progress on this and I feel everything which is possible is already covered. 

- W3C TraceContext support is already released - this means the Elastic agent uses the header format with the same header name as defined in the standard - this is already out
- #800 Makes sure that the trace id of Activity is the same as the trace id of the transactions/spans captured by the Elastic agent - this will be released with the next release.

So `Activity.Current.TraceId` will be the same as the trace id in elastic and you'll be able to find traces based on `Activity.Current.TraceId` within Elastic.

One thing to keep in mind here is that `Activity` itself is still something that is not mapped to any concept within Elastic - so we keep the trace id across `Activity` and Elastic APM in-sync, but `Activity.Id` is still the id of the activity and that is still independent from a transaction or a span within elastic. https://github.com/elastic/apm-agent-dotnet/issues/303 is an issue about maybe mapping `Activity` to something within Elastic, but that's undecided at this point.

Other note I'd like to add here is that `Activity` still supports [hierarchical ids](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activityidformat?view=netcore-3.1) - in case hierarchical ids are used there is no trace id, and we can't do much about that. So we only keep TraceId in-sync with Activity if `ActivityIdFormat.W3C` is the idFormat (that is basically the one that implements TraceContext, the hierarchical id format predates TraceContext).

Closing now, hope this is already some meaningful step.

**Comment by Veikedo** [comment]
@gregkalapos thanks for the update!
Sorry, when do you plan to release the next version of the nuget package with these changes?

**Comment by gregkalapos** [comment]
Hi @viktor-nikolaev,

we try to avoid publicly announcing release dates upfront and to be honest I don't really know about a specific date at this point. Only thing I can say is that for the next 1-2 weeks no release is planned (there are some things in-progress right now), but it's not like you'll need to wait multiple months for the next release either - so something in between.

You can watch the repo for new releases - that way you'll know it immediately.

Sorry that I can't be more specific, but we believe this is still better than communicating a specific date and creating stress internally and ship something that's not ready or fail to deliver.
