### ISSUE TITLE
Elastic.Apm cant find System.Net.Http v4.2.0.0

### ISSUE THREAD

**Issue by adameasten** [elastic/apm-agent-dotnet#695]
Hello, i have a server with .NetFramework 4.6.2 installed on. When i try to start a transaction with a APM Agent the application breaks and it seems like my transaction is swallowing the exception. An assembly redirect of System.Net.Http that points to v4.0.0.0 solves the problem, but i wonder why its needed since the only requirement for Elastic.Apm package is .NetFramework 4.6.1.

**Comment by gregkalapos** [comment]
This is a related discussion: https://discuss.elastic.co/t/error-publishing-app-with-dotnet-fullframework-apm/209303

**Comment by adameasten** [comment]
Well, im distirbuting a metric-configuration nugetpackage that is dependent on Elastic.Apm, so a assembly redirect is kind of a pain in this case. Im just confused how the package that is supposed to only need netframework 4.6.1 doesnt find the right dll's on the server, even though i have 4.6.1 installed :)

**Comment by stevejgordon** [comment]
Binding redirects etc. on .NET Framework are sadly something we generally just have to live with. I don't think we have any changes to make here, so closing this issue.
