### ISSUE TITLE
Attribute for CaptureTransaction/CaptureSpan

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/apm-agent-dotnet#698]
**Is your feature request related to a problem? Please describe.**
I am currently evaluating the .NET agent for APM - I am using the full .net Framework in version 4.6.1 in a standalone application. Everything is working fine so far but I do not like the way I have to create the transactions and spans:
Either I have different methods which do more or less the same:
```
public void transferChanges()
{
    Agent.Tracer.CaptureTransaction("transferChanges", ApiConstants.TypeExternal, transferChanges_internal);
}
public void transferChanges_internal() {
	...
}
```
Or I have a large block of nested code:
```
public void transferChanges()
{
    Agent.Tracer.CaptureTransaction("transferChanges", ApiConstants.TypeExternal, () => {
		...
	});
}
```

**Describe the solution you'd like**
In Java I like the ability to use annotations - maybe this would be possible with .NET attributes too?
[CaptureTransaction("transferChanges",ApiConstants.TypeExternal)]
public void transferChanges()
{
    ...
}

**Describe alternatives you've considered**
An alternative would be to use an injection library and implementing a decorator for the concrete type. this way the APM code would not clutter our implementing classes.

**Comment by gregkalapos** [comment]
@wolframhaussig have you seen the other methods? We also offer `StartTransaction` and `StartSpan`. Details in the [docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-start-transaction) - that does not need any nested code.

Nevertheless, this is definitely a very valid idea. I did not do any major research on this, but I feel that as long as the agent does not do byte code rewriting, having annotations (aka .NET attributes) will be very hard or even impossible to implement.

So, first step would be to create a layer in the agent that changes the byte code.

Also, I'd like to address this part:

> Or I have a large block of nested code:

To be fair, this is 1 level of nesting for a transaction and in case you capture spans there is an additional level - So unless you have lots of inner spans, there should be 1 or 2 level of nesting. 

But I get the point - thanks for the feedback.

**Comment by stevejgordon** [comment]
Closing as answered and not something we plan to change in the near future
