### ISSUE TITLE
culprit always reproted as PublicAPI-CaptureException

### ISSUE THREAD

**Issue by kanadaj** [elastic/apm-agent-dotnet#705]
**Describe the bug**
In the APM Errors UI, all errors have the culprit marked as `PublicAPI-CaptureException`.

![image](https://user-images.githubusercontent.com/3247357/73146034-7633a180-40a8-11ea-9eb2-d80156632111.png)

**To Reproduce**
Using the following versions:

- ASP.NET Core 3.1.1
- Elastic APM 1.2
- ElasticSearch 7.5
- APM server 7.5

**Expected behavior**
The Errors should have the culprit extracted from the Stacktrace. If you still aren't sure about how to identify the right one, why not just simply grab the first trace not starting with `System.` by default and expose a callback for developers to add their own filters to decide whether a line is in their app? Or a simple blacklist/whitelist approach.

**Comment by gregkalapos** [comment]
Done in #740. Thanks @kanadaj 🎉
