### ISSUE TITLE
Ability to register or change IMetricsProvider

### ISSUE THREAD

**Issue by marcoregueira** [elastic/apm-agent-dotnet#708]
**Is your feature request related to a problem? Please describe.**

The current metrics retrieved by the application are quite scarce. I need to monitor a desktop application in classic .Net Framework for Windows installed in a number of desktop PCs. In this scenario is not possible to deploy additional Filebeat, metricbeat, packetbeat or any other components along with the application. Monitoring only needs to happen when the application is working.

**Describe the solution you'd like**

I need to be able to add new classes implementing IMetricsProvider and add them to the MetricsCollector. At this moment I have my own collector for network traffic using WMI. 

It would be great adding it without needing to build my own version of the APM agent to allow visibility of the internal interfaces. 

It would be great for me to add other metrics from [this list at will](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-system.html), or any other metrics of my own.

**Describe alternatives you've considered**
The only option is to send that metric info using transactions, but... it is not the same. It appears, the apm agent sends events in packets of 20 (or something similar) but transactions are sent when finished. Transaction rate would be a problem too, I suppose.

**Comment by gregkalapos** [comment]
Thanks @marcoregueira for opening. 

I feel https://github.com/elastic/apm-agent-dotnet/issues/322 covers this. Is this ok for you to close this and reference from #322?

**Comment by marcoregueira** [comment]
Request forwarded to #322
