### ISSUE TITLE
Load agent without code change

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#71]
By implementing `IHostingStartup` and using the following two environment variables we could load the agent into an ASP.NET Core app without any code change or even recompilation:
- `DOTNET_ADDITIONAL_DEPS`
- `ASPNETCORE_HOSTINGSTARTUPASSEMBLIES`

I blogged about this feature [here](https://kalapos.net/Blog/ShowPost/IHostingStartupInAspNetCore20).

**Comment by NeilCross** [comment]
Oh snap!

**Comment by Mpdreamz** [comment]
That's a really cool feature! Would this provide us a hook to register `PayloadSender` as `IHostedService` rather than it starting a background thread?

**Comment by gregkalapos** [comment]
> Would this provide us a hook to register PayloadSender as IHostedService rather than it starting a background thread?

Not directly. This feature basically enables the application to pick up a dll and register a middleware by code from that dll. And all that without changing the application's code. 

Independently we can still think about registering the `PayloadSender` as a `IHostedService`, but for that I think we don't really need this feature.

**Comment by gregkalapos** [comment]
Another question about this in discuss: https://discuss.elastic.co/t/instrument-any-net-core-application/207680

**Comment by gregkalapos** [comment]
> Another question about this in discuss: https://discuss.elastic.co/t/instrument-any-net-core-application/207680

**Comment by gregkalapos** [comment]
Implemented in #828.
