### ISSUE TITLE
Agent doesn't send body to APM Server

### ISSUE THREAD

**Issue by vhatsura** [elastic/apm-agent-dotnet#710]
**Describe the bug**
The captured request body is reported to the APM server as empty string.

**To Reproduce**
It's reproducible in #661 
1. Run `SampleHttpSelfHostApp` project
2. Execute the following command:
```
curl --location --request POST 'http://localhost:12345/api/values/' \
--header 'Content-Type: application/json' \
--data-raw '{
	"id": 1,
	"name": "sample"
}'
```
3. To APM server the `{\n\t"id": 1,\n\t"name": "sample"\n}` body needs to be reported, however, I got the following from logs:
```
[2020-01-30 00:01:45.536 +03:00][Trace] - {PayloadSenderV2} Serialized item to send: Transaction{Id: a157529ca7a9c0d7, TraceId: aebc002e58df3557b1bd85090ae02957, ParentId: null, Name: POST /api/values/, Type: request, IsSampled: True} as {"context":{"request":{"body":"","headers":{"Postman-Token":"[REDACTED]","Cache-Control":"no-cache","Connectio
n":"keep-alive","Accept":"*/*","Accept-Encoding":"gzip, deflate, br","Host":"localhost:12345","User-Agent":"PostmanRuntime/7.22.0"},"http_version":"1.1","method":"POST","socket":{"encrypted":false},"url":{"full":"http://localhost:12345/api/values/","hostname":"localhost","pathname":"/api/values/","protocol":"http","raw":"http://localhost:12345/ap
i/values/","search":""}},"response":{"finished":true,"headers":{},"status_code":200}},"duration":653.856,"id":"a157529ca7a9c0d7","sampled":true,"name":"POST /api/values/","result":"http 2xx","span_count":{"dropped":0,"started":0},"timestamp":1580331686757135,"trace_id":"aebc002e58df3557b1bd85090ae02957","type":"request"}
```

It seems that the issue in
https://github.com/elastic/apm-agent-dotnet/blob/59b527ed12a97e5ef6eef2ed8470b4c637039ad2/src/Elastic.Apm/Report/Serialization/BodyStringSanitizerConverter.cs#L55-L79
The possible fix is to change `return true` at the end of the method to `return i != 0`, however, what if we will have smth like `{ "Data": "x=1&y=2" }` in the POST body? So, in this case, it would be nice to have an additional technical field inside `Context` class, which will point to the original `Content-Type` of the request body.

**Expected behavior**
`{\n\t"id": 1,\n\t"name": "sample"\n}` needs to be reported as body.

/cc @gregkalapos

**Comment by gregkalapos** [comment]
Oh yeah, this is a known thing and not that trivial to solve. 

Some thoughts here: https://github.com/elastic/apm-agent-dotnet/issues/656#issuecomment-565543923

And one PR that tries to address it - but I'm still not 100% happy with it - is here: https://github.com/elastic/apm-agent-dotnet/pull/617

>  So, in this case, it would be nice to have an additional technical field inside Context class, which will point to the original Content-Type of the request body.

That is indeed an option - the only potential issue here is that the `Body` is exposed through the public API, so it's possible that someone sets the `Body`, but not the `Content-Type` - and in that case we still have the same problem - alternatively we could say that if the `Content-Type` is not set, we don't sanitize anything.

**Comment by gregkalapos** [comment]
Addressed in https://github.com/elastic/apm-agent-dotnet/pull/712.
