### ISSUE TITLE
Capture SystemTotalCpuProvider without PerfCounters on Windows 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#715]
We have many problems with perfcounters on windows. It'd be nice to get rid of those and capture total CPU usage with something different. 

[discuss](https://discuss.elastic.co/t/systemtotalcpuprovider-failed-instantiating-performancecounter/217811) discussion.

**Comment by stevejgordon** [comment]
Closing as we have no plans to refine this currently
