### ISSUE TITLE
"Time spent by span type" chart is not coming up in .Net core application

### ISSUE THREAD

**Issue by ghodasarakartik** [elastic/apm-agent-dotnet#718]
**Describe the bug**
We have set elastic APM configuration and using .net core NuGet package, but we are not getting "Time spent by span type" chart, everything else is working fine.

**To Reproduce**
In my Startup, I've used UseAllElasticApm middle ware in StartUp.cs

![image](https://user-images.githubusercontent.com/6263711/73817510-18722880-4811-11ea-9b28-31865e279320.png)

but "Time spent by span type chart is always blank.

![image](https://user-images.githubusercontent.com/6263711/73908526-086d4e00-48d0-11ea-9cf8-7ef09445f571.png)

Please suggest if I am missing anything.

**Comment by gregkalapos** [comment]
Hi @ghodasarakartik,

this is unfortunately a missing feature in .NET - we already work on it. This is the issue to follow: https://github.com/elastic/apm-agent-dotnet/issues/227 It's currently in progress.
