### ISSUE TITLE
Setup instructions in Kibana

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#719]
The setup instructions in Kibana could be extended - it covers ASP.NET Core very well, but does not cover:

- ASP.NET (Classic)
- General .NET Application, in case you only use the public agent API 

Inspired by https://github.com/elastic/apm-agent-dotnet/pull/714#issuecomment-582853599

**Comment by stevejgordon** [comment]
Closing as outdated
