### ISSUE TITLE
HttpClient calls from .NET Framework not always auto wrapped

### ISSUE THREAD

**Issue by sluebbert** [elastic/apm-agent-dotnet#721]
**Describe the bug**
.NET Framework calls made using HttpClient are not automatically wrapped in a span within a ASP.NET Web API web app.

**To Reproduce**
1. Clone this repo
2. Add a ASP.NET Web Application (.NET Framework) project to the sample folder (.NET 4.6.1). Select Web API template, uncheck configure for HTTPS.
3. Add the following existing projects as references: Elastic.AP, Elastic.Apm.AspNetFullFramework
4. Add to the `<system.webserver>` section in the Web.config:
  ```xml
<modules>
      <add name="ElasticApmModule" type="Elastic.Apm.AspNetFullFramework.ElasticApmModule, Elastic.Apm.AspNetFullFramework"/>
    </modules>
```
5. Edit Web.config to have a ElasticApm:ServerUrls appSetting pointing at your instance of APM server.
6. Edit ValuesController.Get() to contain:
  ```cs
// GET api/values
public IEnumerable<string> Get()
{
	var client = new HttpClient();
	var x = client.GetAsync("http://www.google.com").Result.Content.ReadAsStringAsync().Result;
	return new [] { $"Length: {x.Length}" };
}
```
6. Run service and send a request: `GET /api/values`

**Expected behavior**
When the /api/values transaction is logged to the APM server, it should contain a span from the HttpClient call to google. A transaction for /api/values is logged just fine, it just has no spans.

I have only seen this work out of the box with the AspNetFullFrameworkSampleApp and haven't been able to get it to work in any of my existing .Net framework services by just adding the module reference in the web.configs (in addition to installing the nuget packages).  There is so much extra going on in AspNetFullFrameworkSampleApp that it is hard for me to compare what might be causing the issue.

I have put breakpoints on various methods in HttpDiagnosticListenerImplBase like OnNext, ProcessStartEvent, etc, with none getting hit.

The following breakpoints are hit while testing:
- ElasticApmModule.InitOnceForAllInstancesUnderLock (line 312)
- HttpDiagnosticListener.New (line 23)

I'm guessing I'm missing something simple. Please advise.

Thanks!

**Comment by gregkalapos** [comment]
Hi @sluebbert, 

Just one quick idea (without looking into this deeper yet): Could you please check the version of the `System.Net.Http` dll? 

The one thing I can imagine is that the `HttpClient` version in that setup is too old and it does not have the `DiagnosticSource` events that the agent uses in order to create the span. 

I remember that `HttpClient` was part of the framework installation for a long time, but at some point Microsoft decided to move it to a NuGet pacakge, so they can update it without updating the whole framework. 

If my theory is true, then by replacing `System.Net.Http.dll` by [this NuGet package](https://www.nuget.org/packages/System.Net.Http/), it should work. 

If my theory turns out to be true, then of course this is something we should and will document - I expect this to only effect older versions.

If my theory is wrong, I'll dig deeper.

**Comment by sluebbert** [comment]
Replacing with the most recent version of `System.Net.Http.dll` didn't do it. I should be using the same version of that DLL as AspNetFullFrameworkSampleApp since that app doesn't pull in the nuget package either.

DiagnosticSource events may be the next thing I can start poking though. I'll keep trying to compare my test app with the provided one too.

Thanks

**Comment by sluebbert** [comment]
So you were right about version issues, but for me it was the `System.Diagnostics.DiagnosticSource` dll.

If I added `System.Memory.dll`, added binding redirects into my web.config for `System.memory` and `System.Diagnostics.DiagnosticSource`, and then swapped out the version of `System.Diagnostics.DiagnosticSource` from AspNetFullFrameworkSampleApp to my test app after building, it works!

I just need to figure out how to gracefully do that without my hackory.

**Comment by gregkalapos** [comment]
Oh, great, thanks for the info. I'll also try to repro this and understand the details - this should be at least documented or based on the version we could also print a warning in the logs.

**Comment by sluebbert** [comment]
I added the nuget package System.Diagnostics.DiagnosticSource version 4.6.0 to one of my other existing services and that fixed it right up. System.Memory got added automatically as a dependency.
So that alone seems to have cleared it up for me.

4.7.0 seemed to break things again.

Thanks for the help!

**Comment by vhatsura** [comment]
@gregkalapos, I also faced this issue in #661. In my case, referencing `System.Diagnostics.DiagnosticSource` of `4.4.0` version solved the problem. This is the lowest version that works.

https://github.com/elastic/apm-agent-dotnet/blob/ae1658a613c9faacc214a728fe7e0e80db0edfb4/sample/SampleHttpOwinSelfHostApp/SampleHttpOwinSelfHostApp.csproj#L10-L11

 I believe we need to up the version to `4.4.0` in
https://github.com/elastic/apm-agent-dotnet/blob/76620ef36befe55e8f127f139d7a654e51b88107/src/Elastic.Apm/Elastic.Apm.csproj#L19

**Comment by vhatsura** [comment]
@gregkalapos, what do you think about increasing version of `System.Diagnostics.DiagnosticSource`? I know, it looks like breaking change, however, it seems we need it to correct instrumentation in some cases.

**Comment by vhatsura** [comment]
@gregkalapos, did you have a chance to look into my previous comments?

**Comment by Belorus** [comment]
Updating lib to 4.4.0 as Vadim suggested helped. 

.NET 4.6.1

**Comment by gregkalapos** [comment]
@vhatsura sounds good - we can consider updating to `4.4.0`. 

Maybe 1 idea: If I understand correctly, this only affects Full Framework. Maybe we can consider keeping it `4.0.0` for `netstandard2.0` and only use `4.4.0` for the `net461` target. Or is the `netstandard2.0` assembly picked up in scenarios where this caused problem?

**Comment by vhatsura** [comment]
@gregkalapos, I did fast check, and yes it seems `System.Diagnostics.DiagnosticSource` of `4.0.0` version is enough for `netstandard2.0` for getting event from `HttpClient`.
