### ISSUE TITLE
Add test to cover server certificate verification 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#722]
From https://github.com/elastic/apm-agent-dotnet/pull/465 

The config `VerifyServerCert` is implemented, but the test coverage could be improved. 

We should have 1 test that starts up a (mock) APM Server with a self signed cert, or with any other cert that'd fail the verification process, set `VerifyServerCert` to false and make sure the HTTPS requests are still ok. 

Some good thought here: https://github.com/elastic/apm-agent-dotnet/pull/465#issuecomment-584972995

**Comment by russcam** [comment]
Server certificate tests for `VerifyServerCert` and `ServerCert` are implemented in 

https://github.com/elastic/apm-agent-dotnet/blob/bab776194d91a8e65be077d3ad1f5db3f38f81b4/test/Elastic.Apm.Tests/ServerCertificateTests.cs#L46-L95
