### ISSUE TITLE
[apm-ci] release automation fails with 404

### ISSUE THREAD

**Issue by v1v** [elastic/apm-agent-dotnet#726]
1.3.0 release failed with 404 when pushing to the nuget

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/1.3.0/1/

## Actions
- Debug what's going on
- Document how to debug this
- Archive artifacts for future usage even if it fails

**Comment by gregkalapos** [comment]
This is not secret info, so commenting here 

We push with `dotnet nuget push ${nupkg} -k ${1} -s ${2}` 

The `${2}` parameter should be `https://api.nuget.org/v3/index.json` - is that what we pass there? 🤔

**Comment by gregkalapos** [comment]
@v1v this one is fixed and can be closed, right?

**Comment by gregkalapos** [comment]
Release script was used for the `1.4.0` release and we don't have this issue anymore.
