### ISSUE TITLE
Nuisance console write line when trace data exists

### ISSUE THREAD

**Issue by cbo100** [elastic/apm-agent-dotnet#737]
**Describe the bug**
When "TraceParent" header is on the incoming request, this line containing the "TraceState" is written to the console.

https://github.com/elastic/apm-agent-dotnet/blob/c8650abfdac498659fa42d7310677ab350010a17/src/Elastic.Apm/DistributedTracing/TraceContext.cs#L40

**To Reproduce**
1. Configure application with ElasticApm
2. Make a test request including "TraceParent" header
3. Observe the console log will contain this message.

**Expected behavior**
This log message should be sent to the standard logging stack so that it can be filtered etc.

**Comment by cbo100** [comment]
I would PR, but I'm not sure of the intention here. 

Maybe a simple "#if DEBUG" is fine, maybe it should be written to the proper logging system?

**Comment by gregkalapos** [comment]
> I would PR, but I'm not sure of the intention here.
> 
> Maybe a simple "#if DEBUG" is fine, maybe it should be written to the proper logging system?

Thanks for reporting. We can simply remove that - it should not be there. Happy to take a PR :)

**Comment by gregkalapos** [comment]
Fixed in #738.

Thanks @cbo100! 👏
