### ISSUE TITLE
Elastic.Apm 1.3 ParsePortValue bug

### ISSUE THREAD

**Issue by CrazyJson** [elastic/apm-agent-dotnet#746]
**Describe the bug**

https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm/Helpers/DbConnectionStringParser.cs

In Elastic.Apm 1.3 DbConnectionStringParser. Cs parsing oracle connection string port to abnormal

oracle  connection string example:
DATA SOURCE=192.168.0.151:1521/ORCL;PASSWORD=xxx;PERSIST SECURITY INFO=True;USER ID=xxx

`private static void ParsePortValue(string valueToParse, Destination destination)
		{
			if (string.IsNullOrWhiteSpace(valueToParse))
				throw new FormatException($"Port part of server value is white space only/empty string. valueToParse: `{valueToParse}'.");

			if (! int.TryParse(valueToParse, NumberStyles.Integer, CultureInfo.InvariantCulture, out var port))
				throw new FormatException($"Failed to parse port part of server value. valueToParse: `{valueToParse}'.");

			if (port < 0)
				throw new FormatException($"Port part of server value is a negative integer. port: {port}. valueToParse: `{valueToParse}'.");

			destination.Port = port;
		}`
valueToParse = "1521/ORCL";

**Comment by gregkalapos** [comment]
Hi @CrazyJson

thanks for reporting this. This got fixed in #749 - the fix will be included in the next release.
