### ISSUE TITLE
Make stack trace public on span

### ISSUE THREAD

**Issue by BellBat** [elastic/apm-agent-dotnet#758]
**Is your feature request related to a problem? Please describe.**
Implementing elastic apm tracing on internal framework. We use an event pattern and this ends up adding framework frames to the trace. I would like to trim them prior to sending them on. Plan to use a decorator on the payload sender.

**Describe the solution you'd like**
Expose a way to manipuate the stacktrace captured on the span.

**Describe alternatives you've considered**
I have not found / thought any others.

**Additional context**

**Comment by gregkalapos** [comment]
We can definitely make `StackTrace` public. The main reason it's not public yet is that there was some change in the API between the APM Server and the agent. This is related: https://github.com/elastic/apm-agent-dotnet/issues/677 

But I'm not sore if that'd be enough here - in order change the stacktrace something like a filter that other agents have would be useful.

**Comment by gregkalapos** [comment]
This is implemented now. In #847 I made stack trace public - this will be released in the next version. Additionally in [Version 1.5](https://github.com/elastic/apm-agent-dotnet/releases/tag/1.5.0) we already shipped filters (more details on it in the [docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#filter-api)).

So in the next release in combination with filters this will be possible.
