### ISSUE TITLE
Public vs Internal - Make sure we limit the things that are public initially

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#77]
By looking at the code-base I'd say there are too many things that are public. 

E.g. on `ITransaction` there is a public `Spans` array, and this is an example why this can be a problem in user code:
```
class MySpan : ISpan
{
  //...all the ISpan stuff
}
		
public static void MyMethod()
{
   Agent.Tracer.CurrentTransaction.Spans[0] = new MySpan { Id = -1 , Duration = -10};
  //leave everything else empty, and send id -1 and everything else as empty values...
}
```
The server won't like this...And there are many other examples.

I'd say generally for the first release we should make sure we only make things public that 100% should be public. Adding things later won't break, so if there is something missing we can add it later easily. On the other hand removing things would break.

Therefore: I'll go on and make sure that we only have things in public that will very-very likely remain public forever, and make things that are questionable internal, just to be on the safe side.

**Comment by gregkalapos** [comment]
Fixed by #78

**Comment by yhvicey** [comment]
Should `MicrosoftExtensionsConfig` and `EnvironmentConfigurationReader` be made public again? Users can only implement their own `IConfigurationReader` or use `EnvironmentConfigurationReader` by passing `null` into the agent constructor.

**Comment by gregkalapos** [comment]
> Should `MicrosoftExtensionsConfig` and `EnvironmentConfigurationReader` be made public again? Users can only implement their own `IConfigurationReader` or use `EnvironmentConfigurationReader` by passing `null` into the agent constructor.

I think this is how it should be. By default we always use `EnvironmentConfigurationReader`, and in case you pass an `IConfiguration` instance to the Agent in ASP.NET Core we switch to `EnvironmentConfigurationReader`. I don't really see any need for users to know about this, or know the internals of those two - of course no secret there, I just don't see the need to add additional complexity.

Do you have any use-case where this does not work well?

**Comment by yhvicey** [comment]
We'd like to split our integration with ElasticApm into different pieces - One for general console app, one for AspNetCore, and one for EFCore. Besides, we'll have a uber one for AspNetCore apps with EFCore. Basically we are doing the same thing you did in this packages, but we want to leave some space for OpenTracing/OpenTelemetry and design some generic pattern for future integration/switching. I guess my best option is to implement my own `IConfigurationReader` here.

**Comment by gregkalapos** [comment]
> We'd like to split our integration with ElasticApm into different pieces - One for general console app, one for AspNetCore, and one for EFCore. Besides, we'll have a uber one for AspNetCore apps with EFCore. Basically we are doing the same thing you did in this packages, but we want to leave some space for OpenTracing/OpenTelemetry and design some generic pattern for future integration/switching. I guess my best option is to implement my own `IConfigurationReader` here.

I see.. And in some cases you'll have `IConfiguration`, but won't use the `UseAllElasticApm()` method, and you'd like to configure the application through this `IConfiguration` including the agent, right?

Currently the `MicrosoftExtensionsConfig` lives in our `Elastic.Apm.AspNetCore` package, so that is a restriction, but probably that class isn't strictly related to ASP.NET Core. Would it help you if we'd add an overload to the `Setup()` method to take an `IConfiguration` instance and in case you add that the agent would switch to `MicrosoftExtensionsConfig`? ...same as with the `UseAllElasticApm()` method.

**Comment by yhvicey** [comment]
Basically my plan is, use `Elastic.Apm` package to get agent object, and it's suitable for general console application; then, use `Elastic.Apm.AspNetCore` to create middleware for AspNet Core, using the `UseElasticApm` override which takes `IApmAgent` as the parameter; last, use `Elastic.Apm.EFCore` to provide a EFCore subscriber to built agent. In this way, those three packages suits for each case and won't introduce unneeded dependencies. So, all we have to do is to create the agent, then use it in different packages.

As agent's functionality can be achieved with `Microsoft.Extensions.*` stack, I guess it might be a good idea to integrate the agent with `Microsoft.Extensions.*` stack first (as it can be used anywhere, not only AspNetCore) using `IServiceCollection/IServiceProvider`, then integrated with `Microsoft.AspNetCore.*` stack using `IApplicationBuilder`.

**Comment by gregkalapos** [comment]
> Basically my plan is, use Elastic.Apm package to get agent object, and it's suitable for general console application; then, use Elastic.Apm.AspNetCore to create middleware for AspNet Core, using the UseElasticApm override which takes IApmAgent as the parameter

Is this even possible?  The [`UseElasticApm` overload that takes an `ApmAgent` is internal](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs#L59).

**Comment by yhvicey** [comment]
> > Basically my plan is, use Elastic.Apm package to get agent object, and it's suitable for general console application; then, use Elastic.Apm.AspNetCore to create middleware for AspNet Core, using the UseElasticApm override which takes IApmAgent as the parameter
> 
> Is this even possible? The [`UseElasticApm` overload that takes an `ApmAgent` is internal](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddlewareExtension.cs#L59).

Oh, I just noticed that. I was thinking `UseElasticApm(this IApplicationBuilder, ApmAgent, IApmLogger, IDiagnosticsSubscriber[])` is public. My bad.

**Comment by gregkalapos** [comment]
No problem. 

So, yeah. The idea is 1 agent instance per process. So as long as your packages run in a single process you need to enable the agent sometimes at the "beginning" of the process.

In case you run those in multiple processes you'll need an agent in each process.

**Comment by yhvicey** [comment]
The pain point for now is, if I want to have a package with only dependency to `Elastic.Apm`, the ideal way to achieve this is to use `IApmAgent`; However, if I want to setup a package using `Elastic.Apm.AspNetCore` on top of previous package, it's hard to use the middleware directly - as it will call `Agent.Setup(AgentComponents)`, which will either trigger re-initialize exception, or create another agent. Is there any possibility to expose the override which takes the `ApmAgent` as the parameter to public?

**Comment by gregkalapos** [comment]
> The pain point for now is, if I want to have a package with only dependency to `Elastic.Apm`, the ideal way to achieve this is to use `IApmAgent`; However, if I want to setup a package using `Elastic.Apm.AspNetCore` on top of previous package, it's hard to use the middleware directly - as it will call `Agent.Setup(AgentComponents)`, which will either trigger re-initialize exception, or create another agent. Is there any possibility to expose the override which takes the `ApmAgent` as the parameter to public?

I'm not sure this is really an issue, or maybe I don't see where this fails in your case.

So, in case you have a library you can use the constant `Agent` type - no `Agent.Setup` call is needed in the library. 

So let's say, this is your library and you want to have a span for a specific method:

```
public class MyLibraryClass
{
    public int MyMethod()
    {
        var currentTransaction = Agent.Tracer.CurrentTransaction;
        var span = currentTransaction?.StartSpan("MyMethod", "CustomSpan");
        try
        {
            //Any other app code
        }
        catch (Exception e)
        {
            span?.CaptureException(e);
            throw;
        }
        finally
        {
            span?.End();
        }
        return 42;
    }
}
```

Then in an ASP.NET Core application you just initalize the agent normally in `startup.cs`:

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseAllElasticApm(Configuration);
    //...more app code
```

And in let's say one of your controllers (or somewhere else) you use your library with the agent:

```
public class HomeController : Controller
{
    public IActionResult Index()
    {
        var c = new MyLibraryClass();
        c.MyMethod();
        return View();
    }
 }
```

With `app.UseAllElasticApm(Configuration);` the agent gets initialized, so the `Agent` in `MyLibraryClass` is already initalized.

Now if you use `MyLibraryClass` in a non ASP.NET Core app (like a console app), then `Agent` will get initalized the first time you use it - in case you want to customize something in it, then you can call the `Agent.Setup(AgentComponents)` method. Typically you would do this in the beginning of the `Main` of your console application. Similarly to ASP.NET Core, in this case the `Agent` will be already initalized in `MyLibraryClass`.

Does this make sense? Is there anything I miss here where this does not work in your scenario? I'm happy to take a closer look if you can show me some code.

**Comment by yhvicey** [comment]
Let me try to explain:

First, our primary goal is to integrate tracing with `IServiceProvider`, and split dependencies into different packages, E.g. one for console apps, one for AspNetCore, one for EFCore without AspNetCore and all those packages can be added in below way:

```cs
// Take some AspNetCore + EFCore project as an example
public void ConfigureServices(IServiceCollection services)
{
    services.AddTracing(builder =>
    {
        builder.AddHttpTracing(); // Inject tracing services for HttpRequest
        builder.AddEFTracing(); // Inject tracing services for EFCore
    });
}
```

A proper approach to achieve this with ElasticAPM is to initialize an `IApmAgent` object first, then insert each `IDiagnosticsSubscriber` in each `builder.AddXXXTracing` call. To achieve this, we will need a tracing builder like this:

```cs
public class TracingBuilder
{
    public IApmAgent Agent { get; }
    public TracingBuilder(IApmAgent agent) => Agent = agent;
}

public class TracingServiceCollectionExtensions
{
    public static IServiceCollection AddTracing(this IServiceCollection services, Action<TracingBuilder> configure)
    {
        IApmAgent agent = ...;
        configure?.Invoke(new TracingBuilder(agent));
        services.AddSingleton(agent);
    }
}
```

Then, we can 'hook' other customization into this tracing builder, meanwhile split them into different pieces:

```cs
// In HTTP module (dll)
public static class TracingHttpExtensions
{
    public static TracingBuilder AddHttpTracing(this TracingBuilder builder)
    {
        builder.Subscribe(new HttpDiagnosticsSubscriber());
    }
}

// In EFCore module (dll)
public static class TracingEFExtensions
{
    public static TracingBuilder AddEFTracing(this TracingBuilder builder)
    {
        builder.Subscribe(new EFCoreDiagnosticsSubscriber());
    }
}
```

Then we achieved our primary goal: Integrate tracing with `IServiceProvider`, and split dependencies into different packages. And, if we can use `IApplicationBuilder UseElasticApm(IApplicationBuilder, ApmAgent, IApmLogger,IDiagnosticsSubscriber[])`, we can use middleware inside `ElasticApm.AspNetCore` directly.

However, there're some issues if we wanna do so:

- This method isn't public
- The public version used `Agent.Instance`, but we cannot assign an existing agent into that property
- If we inject this static instance into the service provider, it will lead to its initialize process (it's a lasy object and will be created when we access it)
- Then we can't use `UseElasticApm` anymore (it will call `Agent.Setup()` and inside it will check if `Agent.Instance.IsValueCreated` is true, if so it will throw an exception, and the value already been created when we inject this global instance into DI container).
- If we inject manually created agent into DI container, then another agent object will be created & used in `UseElasticApm` call.

Not sure if there's a better way to achieve our goal using existing APIs, I'll try to figure it out.

**Comment by gregkalapos** [comment]
Thanks for the explanation @yhvicey.

I think I understand your intention. So… yes, we don’t really integrate currently with `IServiceProvider` in a way you suggest doing it - or well… we do for Tracing (more about it later).

But still I think you should be able to achieve what you want with the current API.


So, in to your AspNetCore + EFCore sample:

```
// Take some AspNetCore + EFCore project as an example
public void ConfigureServices(IServiceCollection services)
{
    services.AddTracing(builder =>
    {
        builder.AddHttpTracing(); // Inject tracing services for HttpRequest
        builder.AddEFTracing(); // Inject tracing services for EFCore
    });
}
```

My first question to this is: why do you add these tracing things to the `IServiceCollection`? The way the agent works is that we try to add auto instrumentation for every popular technology. This means you don’t really need to interact with those components, they do the job for you. You just turn them on, and from that point the agent will create Transactions and Spans for you. So these components are not services in a sense that you should interact with them in e.g. your Controllers or in any other class in your app - so it’s not like let’s say a logger, which you use in your code and interact with an instance of it. They just do the job without you doing anything with then after you turned those on.

Specifically to your scenario: in case you want to manually enable let’s say only incoming HTTP requests in ASP.NET Core and EFCore monitoring (and nothing else, so you don’t use our `Elastic.Apm.NetCoreAll` package that turns on everything), then you can add the `Elastic.Apm.AspNetCore` and the `Elastic.Apm.EfCore` packages to your package (the `Elastic.Apm` will be pulled in through the other 2 packages) and in the `Configure` method you can just write this:

```
app.UseElasticApm(subscribers: new EfCoreDiagnosticsSubscriber());
```

The UseElasticApm activates ASP.NET Core auto instrumentation and the EfCoreDiagnosticsSubscriber does the same for EF Core - there is no need to access those things further in the code - there is 1 scenario where you do, which is the public Agent API, but more on that later. Maybe 1 additional comment, since this is a little bit of an unfortunate scenario: for most things we have these `DiagnosticsSubscribers`, but ASP.NET Core is a little bit different, for that we have a middleware, and that follows this `UseXXX()` convention.


Now let’s say you have a console application and you only want to activate outgoing HTTP monitoring and EF Core monitoring (no incoming HTTP request with ASP.NET Core) in a console application.

In this case you add the `Elastic.Apm` and the `Elastic.Apm.EfCore` packages and you write this line in the “beginning” of the app:


```
Agent.Subscribe(new HttpDiagnosticsSubscriber(), new EfCoreDiagnosticsSubscriber());
```

The `HttpDiagnosticsSubscriber` will capture outgoing HTTP request that you do with `HttpClient` and the `EfCoreDiagnosticsSubscriber` will capture EF Core calls.

So non of these tracing components are things that you can interact with in your code.

Now, there is 1 thing when you need to interact with the agent, and this is the public Agent API. There are some technologies for which we currently don’t offer auto instrumentation, and in those cases if you want to trace your code you need to do it manually.

This is done by the `Agent.Tracer.StartTransaction()` , `Agent.Tracer.CaptureTransaction()`, `CaptureSpan`, etc methods. Details of the API is in the [docs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html).


Now, I can imagine that in this case you don’t want to use the static `Agent` type, instead you would like to treat it as a “service”. So let’s say you have a component that you want to manually trace - e.g. my `MyLibraryClass` example from above - I totally see that e.g. you wish to receive an `ITracer` in the `MyLibraryClass` `.ctor` and use that, and e.g. pass that from an ASP.NET Core controller. 

You can do this with the current API:

``` 
public class MyLibraryClass
{
	private readonly ITracer _tracer;
	public MyLibraryClass(ITracer tracer) => _tracer = tracer;
	public int MyMethod()
	{
		var currentTransaction = _tracer.CurrentTransaction;
		var span = currentTransaction?.StartSpan("MyMethod", "CustomSpan");
		try
		{
			//Any other app code
		}
		catch (Exception e)
		{
			span?.CaptureException(e);
			throw;
		}
		finally
		{
			span?.End();
		}
		return 42;
	}
}

```

ASP.NET Core `Startup.cs`:

```
public static void ConfigureServicesExceptMvc(IServiceCollection services)
{
	services.AddSingleton(n => Agent.Tracer);

```

So the point above with `services.AddSingleton(n => Agent.Tracer);` is that the `Tracer` is the only thing in the agent that you should interact with, and you can treat that as a service - that is our current “integration” with `IServiceProvider`.

Usage:

```
public class HomeController : Controller
{
	private readonly ITracer _tracer;

	public HomeController(ITracer tracer) => _tracer = tracer;

	public IActionResult MyAction()
	{
		var myInstance = new MyLibraryClass(_tracer);
		myInstance.MyMethod();
	}
}
``` 

So, overall I think with this you already can achieve what you want, even if we would add the `TracingBuilder` to have a nicer syntax to interact with `IServiceProvider`, that would be basically just the equivalent of `app.UseElasticApm(subscribers: new EfCoreDiagnosticsSubscriber());` and things like that; and you won’t use those auto instrumentation components as real services. The only thing you use is the `ITracer` for the Public API.

Does this make sense? Does this help you? I’d be happy to talk about more examples. Let me know if you think a call would be more useful and we’ll figure that out - I'm happy to jump on skype or zoom if that'd help.

**Comment by gregkalapos** [comment]
🤦‍♂ 

Yeah, cool story from me above, but similarly with `services.AddSingleton(n => Agent.Tracer);` we already have the double initialization, you talk about.

So we kind of prepared for this, but the current implementation does not help with that. I'll open an issue for that. 

Nevertheless what I said above should work and I'll try to fix that. In case that worked, would that already help you?

**Comment by gregkalapos** [comment]
Opened #431 to address specifically this problem.

**Comment by yhvicey** [comment]
In fact what we actually wanna do is to use `OpenTelemetry` APIs only (ISpan, ITracer, etc.) in our code, and will have glue libs for other vendor libs, like ElasticApm. To have a common 'base' glue lib, I think our best way to do so is to use `IServiceProvider` - `IHost` is hard to integrate, `IApplicationBuilder` is for AspNetCore only. So, what we wanna have is like below:

1. A basic lib providing `ILoggingBuilder`-like pattern for other libs to hook (`TracingBuilder` above), it also contains `OpenTelemetry` APIs;
1. Some glue libs hooking to `TracingBuilder` to add vendor implementations for `OpenTelemetry` interfaces into the service provider;
    1. Enable libs' auto instrumentation in those libs if possible
1. Base on above glue lib, provide integration libs for different stack (console app, aspnet core, ef core, etc.) to help avoid unneeded dependencies (like EFCore for non-EFCore AspNetCore applications).
    1. Enable libs' auto instrumentation in those libs if above step is not able to achieve this, like middleware for AspNetCore

Back to ElasticApm case, with `Agent.Instance` and `IServiceProvider`, we can achieve step 2 *partialy* - and that's why we call `AddTracing` explicity - we want this integration can be achieved with `IServiceProvider` only.

However, that's not enough for step 3 - We don't have middlewares. I guess this design (having an additional step 3 to avoid unwanted dependencies) is kind of over-designed, I'm still wondering if it's worthy to do this.

**Comment by yhvicey** [comment]
My explaining seems confusing, in fact I'm not sure if I expressed my thoughts correctly 🤣 in general, what we want is:

1. Interact with `OpenTelemetry` APIs only (Like `ILogger`)
1. Suitable for most cases (`IServiceProvider`)
1. Create different glue libs for different stacks, and those initialization processes should be able to be merged in service initialization (E.g. `Microsoft.Extensions.Logger.Console`, `Microsoft.Extensions.Logger.Debug`, etc.)

So we want to have is an `ILogger`-like lib - `IServiceProvider` only, easy for other vendor to integrated with, users use some facade APIs when needed.

**Comment by gregkalapos** [comment]
> My explaining seems confusing, in fact I'm not sure if I expressed my thoughts correctly 🤣 in general, what we want is:
> 
> 1. Interact with `OpenTelemetry` APIs only (Like `ILogger`)
> 2. Suitable for most cases (`IServiceProvider`)
> 3. Create different glue libs for different stacks, and those initialization processes should be able to be merged in service initialization (E.g. `Microsoft.Extensions.Logger.Console`, `Microsoft.Extensions.Logger.Debug`, etc.)
> 
> So what we want to have is an `ILogger`-like lib - `IServiceProvider` only, easy for other vendor to integrated with, users use some facade APIs when needed.

Not sure if it's related, but recently I started prototyping an OpenTelemetry exporter. I guess that'd be the ultimate solution for you, right?

[Here is the branch with the code](https://github.com/gregkalapos/apm-agent-dotnet/tree/OpenTelemetryExporter ).

In [this file](https://github.com/gregkalapos/apm-agent-dotnet/blob/OpenTelemetryExporter/sample/OpenTelemetry/TestApp.AspNetCore.2.0/Startup.cs) you can see how it's configured for ASP.NET Core. Only this part is ElasticApm related:

```
services.AddSingleton<ElasticApmExporter>((p) =>
{
   var exportComponent = p.GetService<ISpanExporter>();
   return new ElasticApmExporter(exportComponent);
});
```

Everything else is just OpenTelemetry.

[Here](https://github.com/gregkalapos/apm-agent-dotnet/blob/OpenTelemetryExporter/sample/OpenTelemetry/OpenTelemetrySample/TestElastic.cs) is another sample, that's a simple console app. Similarly, only [this part](https://github.com/gregkalapos/apm-agent-dotnet/blob/OpenTelemetryExporter/sample/OpenTelemetry/OpenTelemetrySample/TestElastic.cs#L14) is ElasticApm related, all the tracing stuff is independent from it, and just by replacing that line you can export to any other APM backend that supports OpenTelemetry. [Here is](https://twitter.com/gregkalapos/status/1160192144985997313?s=20) how the prototype looks in Kibana. 

How does this look? This is not something we planned for, it's more like me exploring new things while vacationing, so no promises or timeline here, but if it's something that helps people I'm sure we'll consider putting more effort into it.

**Comment by yhvicey** [comment]
Cool! I guess that's exact the ultimate solution we're looking for, thanks for your work! I'll keep watching your repo and all Telemetry/ElasticApm related works, wish you a good vacation!
