### ISSUE TITLE
Extend SDK for adding labels to allow adding numbers and bools

### ISSUE THREAD

**Issue by alex-fedotyev** [elastic/apm-agent-dotnet#788]
Java SDK allows adding labels which could be string, number or bool type.
https://www.elastic.co/guide/en/apm/agent/java/master/public-api.html#api-transaction-add-tag

Currently .NET SDK is limited to adding string only.
https://www.elastic.co/guide/en/apm/agent/dotnet/current/public-api.html#api-transaction-tags

It would be great to update .NET SDK to match java capabilities.
This functionality would be useful to enable exposing application KPI's programmatically.

**Comment by gregkalapos** [comment]
Implemented in #982.
