### ISSUE TITLE
Custom transactions

### ISSUE THREAD

**Issue by ffMathy** [elastic/apm-agent-dotnet#789]
Can I add more details here?

As in - can I programmatically provide new sub-timelines under this operation, that show how much each operation took to finish?

I guess that's what you call transactions in RUM, right?

![image](https://user-images.githubusercontent.com/2824010/77544742-bb5a3100-6ea9-11ea-9f42-c73efb24db2a.png)

**Comment by gregkalapos** [comment]
Yes, you can create custom spans on the transaction, you can do something like this:

```
// this gets you the currently active transaction - e.g. in a controller method it'll give you the
// transaction that captures the HTTP request:
var currentTransaction = Agent.Tracer.CurrentTransaction;
if (currentTransaction != null)
{
        // start a custom span on the transaction:
	var span1 = currentTransaction.StartSpan("Operation1", "CustomSpan");
	try
	{
		// execute operation 1... the execution time of this will be measured automatically
	}
	catch (Exception e)
	{
                // capture the error on the span
		span1.CaptureException(e);
		throw;
	}
	finally
	{
                 //end the custom span:
		span1.End();
	}
	
        // Here we create a 2. span
	var span2 = currentTransaction.StartSpan("Operation2", "CustomSpan");
	try
	{
		// execute operation 2
	}
	catch (Exception e)
	{
		span2.CaptureException(e);
		throw;
	}
	finally
	{
		span2.End();
	}
}
```

The code above is a bit noise, but calling `End()` manually gives you flexibility - it'll also capture you exceptions and end the transaction and measure the duration. 

If you want to capture something in a method and you are 100% sure the current transaction is not `null` you can use this shorter form:

```
Agent.Tracer.CurrentTransaction?.CaptureSpan("Operation3", "CustomSpan", () =>
{
	// execute operation you want to capture as a span
        // Keep in mind: only runs when Agent.Tracer.CurrentTransaction is not null!
});
```

**Comment by gregkalapos** [comment]
Also to this part:

> I guess that's what you call transactions in RUM, right?

Not really, the 1. one is always a transaction and within the transactions we have spans. [This](https://www.elastic.co/guide/en/apm/get-started/current/transactions.html) documentation explains it.

**Comment by ffMathy** [comment]
Thank you for this! This is amazing!

**Comment by gregkalapos** [comment]
Great - happy to see it helps.
