### ISSUE TITLE
New central config options: CaptureHeaders, LogLevel, SpanFramesMinDuration, StackTraceLimit

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#794]
These 4 configs are not yet supported by .NET, but they are already [added in Kibana](https://github.com/elastic/kibana/blob/master/x-pack/plugins/apm/common/agent_configuration/setting_definitions/index.test.ts#L128-L138).

Given we already have the infrastructure, let's add these 4 and make them also runtime changeable.

```
capture_headers
log_level
span_frames_min_duration
stack_trace_limit
```

**Comment by gregkalapos** [comment]
Note to future self: Don't forget to update the docs ;)

**Comment by gregkalapos** [comment]
Big progress was made on this by @vhatsura in #820 👏 

Missing part to close this:
`LogLevel` does not work yet.
- We should make sure our loggers read the value that we fetch from central config
- We should also think about how this integrates with .NET Core logging (e.g. do we really want to override the log level defined in `appsettings.json` or elsewhere, etc.)

**Comment by vhatsura** [comment]
@gregkalapos,
(I've tried to resolve it, at least, for console logger, but it instantiates before remote configuration and used by central config fetcher itself. Looks like we need to add a new method on `IApmLogger` interface, smth like `SetLogLevel`. WDYT?
As for
> We should also think about how this integrates with .NET Core logging

I'd say, we don't need to do it, due to log level is defined on common logging configuration.

**Comment by gregkalapos** [comment]
> @gregkalapos,
> (I've tried to resolve it, at least, for console logger, but it instantiates before remote configuration and used by central config fetcher itself. Looks like we need to add a new method on `IApmLogger` interface, smth like `SetLogLevel`. WDYT?
> As for
> 
> > We should also think about how this integrates with .NET Core logging
> 
> I'd say, we don't need to do it, due to log level is defined on common logging configuration.


>  Looks like we need to add a new method on `IApmLogger` interface, smth like `SetLogLevel`. WDYT?

Well, it'd be really nice to avoid it - otherwise all implementors need to implement it - and I know for our IIS module it's common that people redirect logs by implementing `IApmLogger` - for them this would mean a build error. This would be especially less nice if all the benefit would be that our Console Logger uses it, but e.g. in ASP.NET Core we ignore this.

**Comment by gregkalapos** [comment]
With https://github.com/elastic/apm-agent-dotnet/pull/1096 this is done.
