### ISSUE TITLE
When Elastic.Apm.SqlClient Nuget will be available on nuget.org

### ISSUE THREAD

**Issue by axelabikzer** [elastic/apm-agent-dotnet#801]
Hi,
Since few weeks, Elastic.Apm.SqlClient Nuget is not available on nuget.org.
Do you have an idea when it will be back please?

Thanks.

**Comment by gregkalapos** [comment]
Hi @axelabikzer,

that package was not yet released - it's not 100% finished yet. Or to be precise: we did not release it, so if you saw it somewhere it was not from us. We plan to ship it with our next release. I can't tell you an exact that, but it's definitely one of the goal for the next release.

**Comment by axelabikzer** [comment]
Thanks @gregkalapos 👍
