### ISSUE TITLE
Can I set up some API interfaces that don't do apm tracing

### ISSUE THREAD

**Issue by CrazyJson** [elastic/apm-agent-dotnet#818]
There are some interfaces that are invoked very frequently. If apm logs to es, it needs a large amount of storage space. Can you support marking on the interface so as not to log

**Comment by gregkalapos** [comment]
There are some settings that you can use here to reduce the data that is sent and stored in elasticsearch. 

You can for example [reduce the sample rate](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-transaction-sample-rate). This will affect all transactions, so maybe not 100% what you want, nevertheless maybe it's worth trying this setting.

Now, I'm not totally sure I get the full context for your question - can you give me an example oof this situation? Like, what kind of interface is this? And does the agent automatically capture traces for that code or do you use the public agent API and capture things manually? Also to make sure I fully get your question: this is about APM traces and not about logs from the agent right? In case this is about agent logs, then just set the loglevel to `Error` and the agent won't log anything if everything is good.

Also, recently merged a PR which will enable you to register filters: https://github.com/elastic/apm-agent-dotnet/pull/792 With that you can basically control what the agent sends to the APM Server with a little bit of a code. This will be out with the next release.

**Comment by CrazyJson** [comment]
For example, my program provides an API to the outside world, which is called about 20 million times a day.The invocation trace of this interface can be kept unrecorded, otherwise it will take up too much storage

**Comment by gregkalapos** [comment]
Is that a web API called through HTTP? Have you looked at #792? I think with that you will be able to exclude the transaction that causes the trouble - again, this will be included in the next release.

**Comment by gregkalapos** [comment]
Closing now - feel free to reopen if further discussion is needed.
