### ISSUE TITLE
Run benchmarks in CI

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#822]
Follow up on #28.  https://github.com/elastic/apm-agent-dotnet/pull/821 is a prerequisite - that PR will contains the benchmarks.

Things to do:

- Make sure we have the proper environment (e.g. Hetzner machine) - also elasticsearch to receive the data
- Run commands that generate the results (will update the issue with the commands)
- A dashboard is already created - it'd be nice to import those

Ping me for a short sync if you feel I could help.

**Comment by gregkalapos** [comment]
Also if it helps - let me know when you start with this and I can show how I run the benchmarks locally.

**Comment by v1v** [comment]
Then we need to update our obs11 docs that are related to the benchmarks :)

**Comment by gregkalapos** [comment]
Doone in https://github.com/elastic/apm-agent-dotnet/pull/821
