### ISSUE TITLE
ASP.NET Core transaction name with double / 

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#827]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/1091853/80007168-3113e580-84c6-11ea-9e35-b53f70233b58.png">

Like `GET //`

Problem is probably [here](https://github.com/elastic/apm-agent-dotnet/blob/master/src/Elastic.Apm.AspNetCore/ApmMiddleware.cs#L286)

**Comment by vhatsura** [comment]
@gregkalapos, I'm curious how did you get such behavior? It would be nice to get the environment details to fix it.

I've checked raw endpoint routing, but in such case, route data is empty and mentioned code isn't executed. In addition, the issue can be in a different place due to, as I understand, neither controller name or action name can contain `/` character. 
Looking forward to details from you.

**Comment by gregkalapos** [comment]
@vhatsura this was in our integration testing environment running [this sample app](https://github.com/elastic/opbeans-dotnet).

**Comment by vhatsura** [comment]
I dug a little bit into sample app. It seems the issue in the external calling code. I got the following result:
![image](https://user-images.githubusercontent.com/10338692/80877128-ec592d00-8cc3-11ea-827c-5e92cff449df.png)
The last transaction was gotten by calling `https://localhost:5001//api/types` URL.

**Comment by gregkalapos** [comment]
Thanks for looking into this @vhatsura. 

I also looked into our test environment and as it seems we have 2 had where we had a few hundred requests to those URLs, but then the requests went away.

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/1091853/81431886-362d9180-9162-11ea-8636-2bef9b6864e0.png">

More details on the transaction (see `url.full`)
<img width="894" alt="image" src="https://user-images.githubusercontent.com/1091853/81432018-6ffe9800-9162-11ea-98af-7c59e22acc78.png">


When I type this, all is good with the sample app and none of these requests showed up in the last week. Which makes me think that:
- The code in the agent is ok - it seems that the request indeed went into a url with `//`. We could check for this in the transaction name generation and fix-up transaction names with `//`, but I feel it'd be unnecessary overhead and these transaction names are technically correct.
- The test app is also ok - for more than a week, no sign if these calls.
- Probably something started generating those requests, but that went away. I don't know what it was, but probably not the frontend. 


I'll close this now - I feel no action is needed on this. 

cc @alex-fedotyev
