### ISSUE TITLE
Cannot get HttpDiagnosticsSubscriber to work on AspNetFramework

### ISSUE THREAD

**Issue by sorenhl** [elastic/apm-agent-dotnet#835]
Hi,
I have a solution that runs CMS in Framework and an API layer as .NET Core. The .NET Core works as intended, but cannot get HttpDiagnosticsSubscriber to work with AspNetFramework.
I have tried applying it to Application_Start, which seems to give a bug as it was not started by the module. I also tried to start it with Application_BeginRequest with "Agent.Subscribe(new HttpDiagnosticsSubscriber());" once. It does not complain,but this did not yield any http span either.

Does anyone have a working example that uses AspNetFramework and the HttpDiagnosticsSubscriber?

/Søren

**Comment by gregkalapos** [comment]
Hi Søren, 

You use the IIS module, right? - like described [here](https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup.html#setup-asp-net)

We ran into this an issue recently [here](https://discuss.elastic.co/t/distributed-tracing-on-net-fullframework/228663/2?u=gregkalapos). Could you maybe check if it's the same?

**Comment by sorenhl** [comment]
Hi gregkalapos,

Thank you for the fast response.

Yes, i am using the IIS module. I tried what you said, and upgraded System.Diagnostics.DiagnosticsSource from version 4.0.0 to 4.7.0 and this resolved the issue. I can also confirm that it is turned on by default, so i removed the Agent.Subscribe(..).
