### ISSUE TITLE
Query: Asking for release of new build to nugget 

### ISSUE THREAD

**Issue by thapakazi** [elastic/apm-agent-dotnet#836]
**Query: when are you guys planning to publish the new release to the nugget.** 

**Problem definition**
Currently we are waiting for the changes from this https://github.com/elastic/apm-agent-dotnet/pull/792
which allows us to filters.

**Workaround**
Desperate times, desperate measure, I have published the build from https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/master/lastSuccessfulBuild/artifact/
April 29 to nugget as: https://www.nuget.org/packages/IT.Elastic.Apm/1.4.0

Looking forward to new version. Please redirect me if you guys have any shared timeline for it.
Thanks :neckbeard:

**Comment by gregkalapos** [comment]
Hi @thapakazi,

we don't publicly announce release dates upfront but the release should happen in the near future. 

I'll ping you on this issue.

**Comment by gregkalapos** [comment]
The release with the Filter API is out: https://github.com/elastic/apm-agent-dotnet/releases/tag/1.5.0
