### ISSUE TITLE
Add nuspec files and define the process on how to release

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#85]
Currently we have 4 projects under the `src` folder and each should be released as a nuget package referencing each other.

So we should have nuspec files doing this. Additionally the release process should be also defined.

**Comment by Mpdreamz** [comment]
`dotnet pack` also works with `csproj` files and most nuget metadata can be persisted there. Nice part is that you can centralize most metadata and include them as `*.build.props` files.

**Comment by gregkalapos** [comment]
Thx @Mpdreamz! Will try to do this in `csproj` then.

**Comment by gregkalapos** [comment]
Just for future reference - useful doc on this topic: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets

**Comment by gregkalapos** [comment]
Done. Managed to do everything in the .csproj file. There will be a follow-up to automate generating the nuget, assembly, and file versions.
