### ISSUE TITLE
Request body is not buffered when it is form content type

### ISSUE THREAD

**Issue by yuft** [elastic/apm-agent-dotnet#854]
https://github.com/elastic/apm-agent-dotnet/blob/2182be81af478390111061e3edee280c4cafa3b9/src/Elastic.Apm.AspNetCore/Extensions/RequestExtentions.cs#L33

Here we don't pass any FormOptions, the default option is false according to https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.formoptions.bufferbody?view=aspnetcore-3.1#Microsoft_AspNetCore_Http_Features_FormOptions_BufferBody

It becomes a problem if we have body capture set to all on components like Proxy/Gateway built with dotnet core.

**Comment by gregkalapos** [comment]
Will be fixed by https://github.com/elastic/apm-agent-dotnet/pull/855 once CLA is signed. 

Thanks @yuft! 👏

**Comment by gregkalapos** [comment]
#855 merged.
