### ISSUE TITLE
Code drill-down support for Elastic APM .NET agent

### ISSUE THREAD

**Issue by QuintenScheppermans** [elastic/apm-agent-dotnet#861]
Just like the NodeJS agent, it would be really nice to have automatic code drill-down support in the .NET agent. [Greg Kapalos confirmed to me that this isn't included, or on the roadmap](https://stackoverflow.com/questions/61524132/code-snippets-from-net-agent-not-showing-in-elastic-apm). 

![image](https://user-images.githubusercontent.com/64773513/82922134-7e79eb80-9f79-11ea-9d18-bbdc129d7b3c.png)

**Comment by stevejgordon** [comment]
We have no plans to implement this currently, so closing this for now.
