### ISSUE TITLE
How to track outgoing HTTP requests in Asp.Net

### ISSUE THREAD

**Issue by insanity13** [elastic/apm-agent-dotnet#863]
I'm using an apm-agent in ASP.NET application.
It configured in web.config
`<add name="ElasticApmModule" type="Elastic.Apm.AspNetFullFramework.ElasticApmModule" preCondition="managedHandler" />`
and added interceptor for EF
`    <interceptors>
      <interceptor type="Elastic.Apm.EntityFramework6.Ef6Interceptor, Elastic.Apm.EntityFramework6" />
    </interceptors>`

Everything is ok except one thing, we don't get HTTP-requests inside transactions (our request to the external APIs via WebRequest, SOAP, etc.). 
As I see it should work for .netCore trough HttpDiagnosticsSubscriber. 
Is there a way to catch all outgoing requests inside the parent request to our API?

Versions:
![image](https://user-images.githubusercontent.com/1174911/82999649-61e1c000-a01a-11ea-9928-2a714d88021f.png)
APM Server the latest in ElasticCloud.

**Comment by gregkalapos** [comment]
It seems we overlooked this one - sorry about that.

`WebRequest` is not supported at this point, we only support `HttpClient` for outgoing web requests. Feel free to reopen if you use `HttpClient` and it still doesn't work.
