### ISSUE TITLE
Disable APM completely (or simply not enable by default)

### ISSUE THREAD

**Issue by freeranger** [elastic/apm-agent-dotnet#865]
Our use case is that we have common libraries used by multiple consuming projects
We are collecting APM data in the libraries, but the consumers either might not want APM at all or might want to disable it specifically (e.g. investigating performance).

Currently if no server URL is provided then APM will assume there is a server running on localhost so we get a bunch of errors logged such as
```
{{{Scope}}} Failed sending events. Following events were not transferred successfully to the server ({ApmServerUrl}):
{SerializedItems}
```
because there is no server there.
Could we either have the option to disable Apm completely, explicitly, or the default behaviour if no server url is supplied would be for it to be disabled and not assume a server is running on local host.
I do appreciate we could filter out the logs, but that isn't quite the same as Apm is still doing work which it doesn't need to do.

**Comment by gregkalapos** [comment]
Hi @freeranger, 

this is on our roadmap: https://github.com/elastic/apm-agent-dotnet/issues/122 

Definitely something we want to address. If you don't mind I'll close this one and link it from #122.

**Comment by lafriks** [comment]
You can check `Agent.IsConfigured` in libraries and only start transactions/spans if that property is true. This way it would not start connecting to APM server. Of course it is workaround while #122 is not implemented.

**Comment by freeranger** [comment]
@gregkalapos Sure no problem - I didn't see that issue.
@lafriks The problem there is littering the code with Agent.IsConfigured statements, but thanks for the suggestion.
