### ISSUE TITLE
SqlClientDiagnosticSubscriber dosent work in ASPNetFullFramework app.

### ISSUE THREAD

**Issue by anujsethi06** [elastic/apm-agent-dotnet#871]
**Describe the bug**
i am trying to setup SQL dependency tracing in an ASP.Net (.net framework 4.8 ) app. Which is using "ElasticApmModule". The problem comes when i try to setup SqlClientDiagnosticSubscriber in global.cs, Agent.IsConfigured is always false, i think agent is initialized in ElasticApmModule module when module gets invoked for first time. where as, global.asax.cs gets called in app start before any request comes in. 

also, if i add "SqlClientDiagnosticSubscriber" without the "Agent.IsConfigured" check then it initializes a bare minimum agent already. So when it comes to module to initialize it(Agent), it throws exception which dosent get logged in custom APMLogger instance as it needs scoped logger only, and starts disposing everything loosing any and all logs. 
**To Reproduce**
1. Use basic setup suggested for ASPNet Full framework app
2. Then open global.asax.cs and add             if (Agent.IsConfigured) Agent.Subscribe(new SqlClientDiagnosticSubscriber());
3. Then run the app and notice Agent.Isconfigures will be always false.

**Expected behavior**
This is like a dependency that i want to pass to APM and hence it shouldn't matter whether we pass it before initialization or after. 
May be it can have a initialization facilitated by AgentDependencies class like it does for IAPMLogger. and then Module can take care of setting the subscriber as needed during its init. 
Also, All logs should be passed to IAPMLogger if its populated so that the client app gets notified of error and can log accordingly.

**Comment by jaketigbd** [comment]
I had the same problem. `Agent.IsConfigured` was always false in `Application_Start()`

overriding MVCApplication.Init()  instead seems to solve the issue

`Global.asax.cs`
```
public override void Init()
{
      if (Agent.IsConfigured) Agent.Subscribe(new SqlClientDiagnosticSubscriber());
      base.Init();
}
```

**Comment by poserdonut** [comment]
I have tried doing it both in Application_Start and Init, and altugh it seems to be firing in the Init method, there is still no tracing for the SQL calls.

**Comment by russcam** [comment]
The following configuration should work

```c#
public class MyApplication : HttpApplication
{
    protected void Application_Start()
    {
        // other application startup e.g. RouteConfig, etc.

        // set up agent with components
        var agentComponents = ElasticApmModule.CreateAgentComponents();
        Agent.Setup(agentComponents);

        // add capturing of SQL client calls
        Agent.Subscribe(new SqlClientDiagnosticSubscriber());
    }
}
```

A few notes:

- `ElasticApmModule.CreateAgentComponents();` was introduced to be able to configure the agent with ASP.NET Full Framework specific components. Specifically, the ASP.NET pipeline is not async aware, so transactions and spans that async flow using `AsyncLocal<T>` do not flow in the ASP.NET pipeline. The agent components for ASP.NET Full Framework also use `HttpContext` to flow transactions and spans.

  Documentation was added for this from version 1.8 onwards: https://www.elastic.co/guide/en/apm/agent/dotnet/current/setup-asp-dot-net.html#setup-asp-dot-net

- `Agent.Subscribe(...)` has the unfortunate consequence of instantiating the singleton agent instance. In version 1.9.0 onwards, as part of https://github.com/elastic/apm-agent-dotnet/pull/1161, the agent no longer throws an exception when  an agent instance is already instantiated, and the ElasticApmModule attempts to configure the instance before instantiating it.

  Subscribing `IDiagnosticsSubscriber` to the agent should not eagerly instantiate the agent instance. Similarly, adding filters shouldn't either. This behaviour is unlikely to be changed until a next major version though.

I'm going to close this issue as I believe it is resolved. If this isn't the case, please feel free to reopen to continue the discussion.
