### ISSUE TITLE
Filters: Missing tags for IError and missing filter for metrics 

### ISSUE THREAD

**Issue by marcoregueira** [elastic/apm-agent-dotnet#872]
Hi

I've been using the new filters feature. It works quite well and allowed me to remove some customizations of my own.

I still have an issue with IError. This interface doesn't include the Context attribute in order to set additional data like for transactions and spans, that allow to set up custom labels. But the class Error has a property for that, and it is serialized when sending data to APM server It has an additional "custom data" property that is, also, not reachable.

The original class Error is internal and there is no way I could do a casting in order to access those properties...

And, since we're talking about filters, it seems that there is no filter for Metrics. It would be great to have this feature for metrics too. I can remove spans and transactions and avoid them being sent but there is not an equivalent for metrics, that would allow me to change the ratio they're sent or stop them completely on the fly. It would be great to add some metrics of my own without adding a new metrics provider and messing with the way components are created.

Thank you.

**Comment by marcoregueira** [comment]
One more thing regarding the missing filter for metrics. A possible use case would be the ability to filter the "all green" records and throttle them down, reducing their frequency while being able respond to peaks in values by keeping a good sample rate. Currently I have too much data ingested of little value in detecting anomalies or problems.

I could code the rules of my interest, for instance, threshold values and send, for instance 1 tenth of the measurements when they are nominal. And also being able to add some more custom values to the samples, that is, in fact, the reason I started to dig in the code time ago. For that more opening in the is desiderable. 

I understand the reason for making everything internal or private, but the KeyValue of each metric is, in fact, internal and not accesible, that seems excessive.

I will add a new issue about this.

Thank you

**Comment by gregkalapos** [comment]
Regarding the empty `IError` interface: totally agree, that was clearly not meant as the final shape of that interface and something is already prepare for the next release.

https://github.com/elastic/apm-agent-dotnet/pull/847 is already merged to `master` which makes things public - @marcoregueira maybe you could take a look and verify that all fields you need were made indeed public - now is still a good time to make changes around this interface. This will be included in the next release.

Regarding metrics: I also think that offering filters to metrics would be ok, but first we need to make our metrics API public. For that we wanna see what'd be the best story for it. https://github.com/elastic/apm-agent-dotnet/issues/322 is about that.

**Comment by gregkalapos** [comment]
Closing new - #847 fixes it for errors, for metrics we'll first need to make things public.
