### ISSUE TITLE
Any plan to add CaptureBody for responses

### ISSUE THREAD

**Issue by brezaie** [elastic/apm-agent-dotnet#881]
Hi pals,

Is there any plan to monitor the response body in very close future?

**Comment by gregkalapos** [comment]
Hi @brezaie, 

this was discussed within the team a couple of times and we don't plan to do this.

### Explanation 

Main reason for this is that this isn't really an APM or an Observability use case. We capture request body and it's already very hard to implement it and it can add very significant performance overhead. So capturing a response body is something that is not very suited for a production monitoring tool - and it would also increase our support load where we'd need to assist with such issues. This would also open up new security questions.

### Alternative approach

One thing you could do is that you could manually capture the response body and index it manually into Elasticsearch - you could also add the current trace id to it, which you can capture by something like `var traceId = Agent.Tracer.CurrentTransaction?.TraceId;`. With that you'll be able to correlate the manually captured response body with APM traces - of course there won't be a UI for this within APM in Kibana, but you can still quickly manually query the request body index and filter based on trace id. So with a little bit of a code you can do this, but at this point we think this is not something which should be a built-in feature of the APM Agent.
