### ISSUE TITLE
An netcore 3.1 or classlibrary 2.1 project referencing Elastic.Apm.EntityFrameworkCore does not compile if using IAsyncEnumerable

### ISSUE THREAD

**Issue by L3Z4** [elastic/apm-agent-dotnet#884]
**Describe the bug**
An netcore 3.1 or classlibrary 2.1 referencing Elastic.Apm.EntityFrameworkCore does not compile if using IAsyncEnumerable.

**To Reproduce**
1. Create a new application 3.1 or a new class library netstandard2.1
2. Create a class 
`using System;
using System.Collections.Generic;

namespace ClassLibrary1
{
	public class Class1
	{
		private IAsyncEnumerable<object> TestCompilation() => throw new Exception();
	}
}
`
3. Compile -> It works 😄 
4. Reference the nuget or the project Elastic.Apm.EntityFrameworkCore 
5. Compile -> Compilation error 😞 

**Solution**
This is due to a bug on the version 2.0.0 of Microsoft.EntityFrameworkCore. This is solved with the version 3.1.5 (I did not test it with other version to define the lower required increment)

**Comment by gregkalapos** [comment]
Thanks for reporting @L3Z4. 

#895 should solve it.
