### ISSUE TITLE
Transaction.name generation: missing {templates}

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#890]
This was found in opbeans-dotnet: 
![image](https://user-images.githubusercontent.com/1091853/86011969-aa2b3e00-ba1d-11ea-9e43-542602fab222.png)

**Comment by gregkalapos** [comment]
I looked into this and this is very likely caused by an old agent version. 

The latest version is `1.5.1` - with that, the agent groups these transactions properly (`GET Customers/Get {id}`). 

In the opbeans-dotnet repo, the [sample app uses agent version `1.4.0`](https://github.com/elastic/opbeans-dotnet/blob/master/opbeans-dotnet/opbeans-dotnet.csproj#L11) - that's a fairly old version which indeed has this problem (no transaction grouping), I reproduced this issue with 1.4.0.

**Comment by gregkalapos** [comment]
@v1v fixed this - also the agent version is already bumped in opbeans-dotnet. 

@dgieselaar it should be fixed after the next deployment - could you maybe please verify it for us? Thanks.

**Comment by dgieselaar** [comment]
awesome, thanks @gregkalapos and @v1v

**Comment by gregkalapos** [comment]
We needed another iteration, but it's good now, fixed by @v1v  - verified in the `dev-next...` environment.
