### ISSUE TITLE
.Net Core support for Elastic.Apm.EntityFramework6

### ISSUE THREAD

**Issue by chris-sung** [elastic/apm-agent-dotnet#902]
**Is your feature request related to a problem? Please describe.**
EntityFramework6 supports .Net core target. 
but Elastic.Apm.EntityFramework6 is not.

**Describe the solution you'd like**
Elastic.Apm.EntityFramework6 also should target .Net Core

**Additional context**
There were a lot of missing features in EntityFrameworkCore, so there are still many users using EntityFramework6.

This is important for other EntityFramework users and me, as EntityFramework6 was in .Net Framework ecosystem for a long time, and were blocker for migrating to .net Core.
Many of those enthusiasts migrated to .net core when they EntityFramework team targetted .net Core.

**Comment by gregkalapos** [comment]
Thanks for opening @chris-sung. 

> Many of those enthusiasts migrated to .net core when they EntityFramework team targetted .net Core.

That is a really good point! 

I opened a PR (#913) to also offer .NET Core support for EF6.

**Comment by gregkalapos** [comment]
Implemented in #913 - will be included in the next release.
