### ISSUE TITLE
Allow alternative field names for trace correlation to support EventSource

### ISSUE THREAD

**Issue by WhitWaldo** [elastic/apm-agent-dotnet#905]
**Is your feature request related to a problem? Please describe.**
I currently use `System.Diagnostics.Tracing.EventSource` for all my structured logging in my .NET Core applications. The documentation [here](https://www.elastic.co/guide/en/apm/agent/dotnet/1.x/log-correlation-manual.html) indicates that I'd need to add "trace.id" and "transaction.id" to my logs in order to correlate the logs with traces, but EventSource does not permit this. Given that the field names are derived from the variable named passed as arguments into the logging methods, and .NET does not support periods within those property names, there's no way to emit these particular values in any of the EventSource logging that I'm aware of.

As such, I've got to augment all the logging to use the unstructured approach, but as your docs point out, this leaves a bit more post-processing to do later on.

**Describe the solution you'd like**
Ideally, I'd like to see alternative fields available to use instead of "trace.id" and "transaction.id" that match the [identifier naming rules](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/identifier-names) available for properties in C#. Specifically, allowing fields like "trace_id" and "transaction_id" as an alternative valid field would be optimal.

**Describe alternatives you've considered**
I've looked at the cost of switching to a supported logging framework like Serilog, but our logging is too comprehensive to justify the switch at this time.

**Additional context**
No additional context.

**Comment by russcam** [comment]
@WhitWaldo the field names `"trace.id"` and `"transaction.id"` refer to the names of the fields that must be used on a document indexed into Elasticsearch that represents a log event / log line, to allow Kibana to correlate the logs to an APM trace. [These field names are part of Elastic Common Schema and are fixed.](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html)

Do the logs that you capture with EventSource get indexed into Elasticsearch?

**Comment by WhitWaldo** [comment]
We can go ahead and close this as we moved onto other logging approaches, but thanks for the response!

**Comment by russcam** [comment]
Thanks for getting back, @WhitWaldo
