### ISSUE TITLE
Elastic.Apm.Extensions.Hosting in UseElasticApm doesn't set up Agent.Setup

### ISSUE THREAD

**Issue by Belorus** [elastic/apm-agent-dotnet#923]
**Describe the bug**
Due to the subject libraries that use static Agent.Tracer always get default configuration. 

Following code doesn't work in that case. Agent.Tracer.CurrentTransaction is always null
https://github.com/gregkalapos/apm-agent-dotnet/blob/83075d3fd6200a191701590f220917ca34a688d9/src/Elastic.Apm.SerilogEnricher/ElasticApmEnricher.cs#L11

CC @vhatsura :)

**Comment by gregkalapos** [comment]
😱 

Thanks for reporting @Belorus. 

I opened https://github.com/elastic/apm-agent-dotnet/pull/924 - that should fix this.
