### ISSUE TITLE
Span name is same as statement and not as in elastic java

### ISSUE THREAD

**Issue by sharanraj124** [elastic/apm-agent-dotnet#926]
We are having two applications - one in Java and one in .NET. They both access in certain cases the same database. We see that the span.name is not common between the elastic apm java and dotnet agents.

For e.g., we have a database sequence and in Java we get the following:
```mysql
span.name -    SELECT FROM sequence
span.statement - select val as id from sequence
```
However, the same database being accessed from .NET we get the following:
```mysql
span.name - SELECT `val` FROM sequence
span.statement - SELECT `val` FROM sequence
```
The span.name and statement are identical in .NET. Instead, we were expecting the span.name to be just `SELECT FROM sequence`.

Could you please let me know whether there is a configuration to do that or is it something in your TODO to do this.

**Comment by gregkalapos** [comment]
> Could you please let me know whether there is a configuration to do that or is it something in your TODO to do this.

This is a missing feature and it's on our TODO lost, [here](https://github.com/elastic/apm-agent-dotnet/issues/242) is the issue for it. Unfortunately at this point there is no way to configure or change this. The plan is to just align with the behaviour from the Java agent in the linked issue.
