### ISSUE TITLE
Allow transaction sample rate to bias towards higher latency requests

### ISSUE THREAD

**Issue by kanadaj** [elastic/apm-agent-dotnet#927]
**Is your feature request related to a problem? Please describe.**
When receiving an order of magnitude more fast requests to an endpoint with sampling enabled, it's hard to see why the slower requests are slow exactly.

**Describe the solution you'd like**
On a larger application, increasing the sample rate would generate a lot of unwanted data; it would be better for these use cases if it was possible to tell the APM to weigh the request duration in during the sampling process to ensure that the slower requests have a higher chance to be sent to the APM.

**Describe alternatives you've considered**
Other than weighed random, percentile based filtering could work too with a sliding window function. Alternatively, a minimum request time for sampling elligibility would also be helpful here.

**Comment by gregkalapos** [comment]
[This is](https://github.com/elastic/apm-agent-dotnet/issues/679) a very similar discussion, which links to a general APM issue that discusses even more things.

Definitely a valid idea, but if we do something like this, it'll be probably the same for all agents (so it won't be .NET only) given this is something that is the same across all agents.

We have already lots of issues in this repo, so I'd prefer to have sampling related ideas under 1 issue. I'd link this from https://github.com/elastic/apm-agent-dotnet/issues/679 and close this one if it's fine. @kanadaj also feel free to comment on the other issues.

**Comment by kanadaj** [comment]
@gregkalapos Well to be fair, #679 isn't quite the same issue, since he has fluctuating workload so he needs a sliding window for the sample rate, whereas I simply have too many requests with outliers, so rather than variable sampling rate over time, in this instance I'd need weighed/percentile based sampling based on response times instead.
