### ISSUE TITLE
Make HostName overridable by config

### ISSUE THREAD

**Issue by Tasmanien** [elastic/apm-agent-dotnet#932]
Hi,

I'm currently using APM agent on different setup, and the hostname of the servers are not really meaningful, like DESKTOP-JOKELGE, or DATA01.

Like for Metricbeat and Filebeat, would it be possible to make the host.name overridable by apm-agent with something in the config, instead of only relying on Dns.GetHostName() ?

Thanks!

**Comment by gregkalapos** [comment]
Hi @Tasmanien  

the is the [`ServiceNodeName`](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-service-node-name) which may help. 

Having said that - the Java agent [has this setting](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-hostname), so we could also implement the same for .NET.

**Comment by Tasmanien** [comment]
Hi @gregkalapos 
We currently use ServiceNodeName for other purpose so having the hostname like in the java agent would be ideal, it would also allow the use of the built-in host filter from Kibana

![image](https://user-images.githubusercontent.com/6470492/93862110-df17fb80-fcc1-11ea-82b8-4187619ebe2f.png)
