### ISSUE TITLE
Agent.Tracer.CurrentTransaction is null inside IDispatchMessageInspector 

### ISSUE THREAD

**Issue by no1ross** [elastic/apm-agent-dotnet#934]
**Describe the bug**
The transaction created by the HttpModule is not carried to the IDispatchMessageInspector in a WCF service.  I do see the Agent.Tracer.CurrentTransaction in the Application_BeginRequest:

		protected void Application_BeginRequest(object sender, EventArgs e)
		{
			//this is testing that we can get the current transaction
			var transaction = Agent.Tracer.CurrentTransaction;
			if (transaction != null)
			{
				HttpContext.Current.Items.Add("CurrentTransaction", transaction);
			}
		}

But when we get to the AfterReceiveRequest in a IDispatchMessageInspector the Agent.Tracer.CurrentTransaction is null and i'm forced  to grab it from the HttpContext i created in the BeginRequest:

		public object AfterReceiveRequest(ref Message request, IClientChannel channel, InstanceContext instanceContext)
		{
			if (request.IsEmpty)
				throw new ArgumentNullException(nameof(request));
			try
			{
				if (HttpContext.Current != null)
				{
					var currentTransaction = (ITransaction)HttpContext.Current.Items["CurrentTransaction"];
					//var currentTransaction1 = Agent.Tracer.CurrentTransaction;  always null!!!
					if (currentTransaction != null)
					{
						_currentSpan = currentTransaction.StartSpan(_apmName,
							"SoapRequest", serviceInstance.GetType().Name, operationName);
						_isNewSpan = true;
					}
				}
			}
			catch (Exception exception)
			{
				throw;
			}

			return null;
		}
Which does create a new span, but Agent.Tracer.CurrentTransaction is still null and Agent.Tracer.CurrentSpan has the span i just created.

I have attached a sample WCF application that demonstrates this issue.

**To Reproduce**
1. Use this config '...'
Use the sample app i supplied and debug at the break points
Global.asax.cs line: 48
WcfEndpointBehavior.cs line 40
2. Then call '....'
use WcfTestClient and call GetData(), watch the break points
3. Then do '....'
see that the transaction is not persisted
No error, just no data...

**Expected behavior**
The Agent.Tracer.CurrentTransaction should be available in the IDispatchMessageInspector, so we can add Spans.

[WcfService4.zip](https://github.com/elastic/apm-agent-dotnet/files/5113479/WcfService4.zip)

**Comment by gregkalapos** [comment]
`Agent.Tracer.CurrentTransaction` uses async local storage, so very likely the `AfterReceiveRequest` method runs on a different context compared to where we start the transaction.

I'm not sure about the ultimate solution, but as you do in the sample, storing `CurrentTransaction` on the `HttpContext` would be something we could think about for these legacy applications. We could have a version of `ICurrentExecutionSegmentsContainer` which uses the `HttpContext` instead of async local. That'd be one option I can came up with.

**Comment by salem84** [comment]
Hi, I'm developing a similar solution however using OwinMiddleware and libraries with .NET Standard 2.0 and I have similar issues.
I have tried in different ways, and each one has different drawbacks; using `HttpContext `works for Owin/WCF in controller/methods calls, but it doesn't work with async calls.
Using standard `ICurrentExecutionSegmentsContainer` with `AsyncLocal` works with async methods but not inside Owin/WCF pipeline.

**Comment by russcam** [comment]
> Using standard ICurrentExecutionSegmentsContainer with AsyncLocal works with async methods but not inside Owin/WCF pipeline, needed to insert configuration and DI directly inside code.

I think a composite `ICurrentExecutionSegmentsContainer` implementation might be an approach here, one that is able to get/set the current transaction/span in multiple `ICurrentExecutionSegmentsContainer`, one that uses async local and another that uses `HttpContext`
