### ISSUE TITLE
Test against IIS Classic Pipeline Mode

### ISSUE THREAD

**Issue by b-deam** [elastic/apm-agent-dotnet#942]
**Is your feature request related to a problem? Please describe.**
Currently we do not test against IIS' Classic Pipeline mode, meaning that some users report not seeing transactions, errors with missing stack traces etc.

**Describe the solution you'd like**
Test the .NET agent against running IIS in Classic Pipeline mode to verify that functionality around transactions, errors, stack traces, and metrics function as they do with IIS Integrated Pipeline. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gregkalapos** [comment]
I did a quick test and I think IIS Classic does not work at this point.

Simple test with an agent throws:

```
Exception Details: System.PlatformNotSupportedException: This operation requires IIS integrated pipeline mode.
```

```
An unhandled exception was generated during the execution of the current  web request. Information regarding the origin and location of the  exception can be identified using the exception stack trace below.
--
```

```
[PlatformNotSupportedException: This operation requires IIS integrated pipeline mode.]    System.Web.HttpResponse.AddOnSendingHeaders(Action`1 callback) +216    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +220    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +94
--
```


At the first look this seems like adding a header causes the problem, probably that's when we'd add our `traceparent` header.

**Comment by stevejgordon** [comment]
Closing as we don't support IIS Classic Pipeline
