### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by wojbuj** [elastic/apm-agent-dotnet#943]
**Describe the bug**
The problem is memory leak .NET when request websservices in Task which is in Task

**To Reproduce**
1.  Settings ```Agent.Subscribe(new Elastic.Apm.DiagnosticSource.HttpDiagnosticsSubscriber());```
without this setting it works correct

```c#
Task<List<Article>> articlesTask= doSomethingTask();
       articlesTask.Wait();
	   
doSomethingTask()
{
           Task<List<Article>> aTask ;
	   for
	   {
	      aTask .Add(_ws.GetArticle(Id));
           }  
           var Result = (await TaskNET.WhenAll(aTask )).SelectMany(s => s.Data);
}
```

then this object ```_ws.GetArticle(Id)``` never memory  clear 

**Expected behavior**
No memory leak

**Comment by gregkalapos** [comment]
@wojbuj is this .NET Framework, or .NET Core? Or both?

**Comment by wojbuj** [comment]
.NET Framework

**Comment by fuzolan** [comment]
I don't know if this is related. I also have a dump with 4gb mem consumed by Elastic.Apm.DiagnosticListeners.HttpDiagnosticListenerFullFrameworkImpl

![image](https://user-images.githubusercontent.com/6806135/94627285-5ef32680-02bd-11eb-81ba-c2af2c14771e.png)

**Comment by russcam** [comment]
@fuzolan are you able to share the dump?

**Comment by russcam** [comment]
@wojbuj The example provided doesn't compile unfortunately. Do you have a complete reproducible example, that would help investigate this more easily?

**Comment by gregkalapos** [comment]
I looked into this and the only way I found where this can happen is when `Activity` uses `W3C` id format. With that I reproduced the problem.

https://github.com/elastic/apm-agent-dotnet/pull/896 was a PR which has info on the original problem - but that PR does not fix the original issue, it only makes sure the agent does not force `Activity` to use `W3C` id format on Full Framework, so we at least try to avoid this. But one reproducer would be something like this:

```
//Here we force Activity to use W3C format, and it's a known bug that on Full Framework the `HttpHandlerDiagnosticListener` does not send the end event and with that we never `.End()` outgoing HTTP spans. More on that in https://github.com/dotnet/corefx/pull/40777
Activity.DefaultIdFormat = ActivityIdFormat.Hierarchical; //that's not the default

await Agent.Tracer.CaptureTransaction("Test", "Test", async () =>
{
	var httpClient = new HttpClient();
	try
	{
		 //In HttpDiagnosticListenerImplBase we start a span for this, but we never call `End` on it, and the ProcessingRequests will always grow.
		 await httpClient.GetAsync(myUrl);

	}
	catch(Exception e)
	{
		//ignore - we don't care about the result
	}

});
```

Good news is that in `System.Diagnostic.DiagnosticSource` version `5.0.0` contains the fix, and once that's referenced we get the end diagnostic source event from `HttpHandlerDiagnosticListener`, so we can close the spans.

https://github.com/elastic/apm-agent-dotnet/pull/1022 bumps the version to `5.0.0` and also contains a test which covers this (basically the same snippet above, which was failing with `System.Diagnostic.DiagnosticSource` versions older than `5.0.0` and is green with `5.0.0` on `net461`).

**Comment by russcam** [comment]
@wojbuj Are you able to upgrade the agent to 1.7.0 and see if the issue is resolved?

**Comment by gregkalapos** [comment]
Closing now for inactivity. I think we fixed this. If not feel free to reopen.
