### ISSUE TITLE
Requests that cause 404 are logged under individual actions, flooding Elastic with paths that don't exist

### ISSUE THREAD

**Issue by kanadaj** [elastic/apm-agent-dotnet#952]
**Is your feature request related to a problem? Please describe.**
When any request is on a path that doesn't exist (even file requests), these requests go all the way to the MVC middleware before returning a 404. Elastic APM logs each of these requests as a different action based on the path.

**Describe the solution you'd like**
404 requests should all all grouped under a path such as `GET NotFound` and `POST NotFound`, unless they were matched against an MVC route. Otherwise the result is something like this:
![image](https://user-images.githubusercontent.com/3247357/92162240-c25a7780-ee29-11ea-9cdc-cee682500306.png)

**Comment by gregkalapos** [comment]
Agreed - it is also what the [spec](https://github.com/elastic/apm/blob/master/specs/agents/tracing-instrumentation-http.md) defines. There is already 1 issue related to this: https://github.com/elastic/apm-agent-dotnet/issues/930. Those 2 can be fixed together.

**Comment by kanadaj** [comment]
See PR at https://github.com/elastic/apm-agent-dotnet/pull/953

**Comment by gregkalapos** [comment]
Fixed in #953. Thanks @kanadaj .
