### ISSUE TITLE
agent lost kubernetes and docker fields

### ISSUE THREAD

**Issue by wajika** [elastic/apm-agent-dotnet#954]
https://discuss.elastic.co/t/apm-agent-lost-kubernetes-and-docker-fields/243963
I have set the kubernetes environment variable, but I haven't found any kubernetes metadata on kibana. Can anyone give me some advice

**Comment by russcam** [comment]
@wajika would you be able to try this with [agent version 1.11.1](https://www.nuget.org/packages/Elastic.Apm/1.11.1)? The issue that you saw I think may have been fixed with https://github.com/elastic/apm-agent-dotnet/pull/1481.

**Comment by wajika** [comment]
I can't verify at the moment, but I can close the issue first
