### ISSUE TITLE
"Buffer limit exceeded" when transferring big files

### ISSUE THREAD

**Issue by MikhailIzvekov** [elastic/apm-agent-dotnet#960]
asp .net core 3.1
elastic apm 1.6.1 (works on 1.4.0 though)

**Describe the bug**
Elastic APM Middleware (specifically HttpRequestExtensions.ExtractRequestBodyAsync, line 33) ignore limits for request size. 

**To Reproduce**
1. Create new asp .net core API from standard template;
2. Add method to controller:
```C#
    [HttpPost]
    [DisableRequestSizeLimit]
    [RequestFormLimits(ValueLengthLimit = int.MaxValue, MultipartBodyLengthLimit = int.MaxValue)]
    public long Post(IFormFile file)
    {
      return file.Length;
    }
```
3. Test it on a large file (~150 mb or so). It works.
4. Install and setup Elastic APM.
5. Test method again. Error: System.IO.IOException: Buffer limit exceeded.

**Expected behavior**
Method still works. OR there is a way to configure limits for apm at least.

**Workaround**
Startup.cs:
```C#
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
      if (Configuration.GetSection("ElasticApm").Exists())
      {
        app.Use(async (ctx, next) =>
        {
          if (ctx.Request.HasFormContentType)
          {
            var features = ctx.Features;
            var formFeature = new FormFeature(ctx.Request,
              new FormOptions { BufferBody = true, BufferBodyLengthLimit = int.MaxValue, MultipartBodyLengthLimit = int.MaxValue});
            features.Set<IFormFeature>(formFeature);
            await ctx.Request.ReadFormAsync();
          }
          await next.Invoke();
        });

        app.UseElasticApm(Configuration);
...
```

**Comment by russcam** [comment]
Hi @MikhailIzvekov, this looks like it may have already been addressed in the master branch: https://github.com/elastic/apm-agent-dotnet/blob/ffe234e5301fe8d6c71e70e06894fce03baf1c65/src/Elastic.Apm.AspNetCore/Extensions/RequestExtentions.cs#L32-L54

As part of https://github.com/elastic/apm-agent-dotnet/commit/ecdf377dc55e28881f58993c0b5066b6aa50a6f0. This should be in the next release.

I'll add an integration test for posting a large file though, as I think it's a good test to have.
