### ISSUE TITLE
[CI] Add .NET 5 support in CI

### ISSUE THREAD

**Issue by gregkalapos** [elastic/apm-agent-dotnet#962]
.NET 5 is already RC - can be found [here](https://dotnet.microsoft.com/download/dotnet/5.0) including the [install scripts](https://dotnet.microsoft.com/download/dotnet-core/scripts).

We should have that in CI. Once that's done I'll add .NET 5 as target for all our tests and sample apps, so all our tests run on the new version.

So the point of this issue: make sure it's installed in CI, once that's done I'll make sure the tests also utilize it.

**Comment by kuisathaverat** [comment]
Do we need to compile with previous versions too? I mean, we will build with 3.5, 4.0, and 5.0 or we only want to build and test with 5.0
It would need a new worker with the new version of Visual Studio 2019 (v16.8, Preview 3), which I see is not a final version is a preview version.

**Comment by gregkalapos** [comment]
> Do we need to compile with previous versions too? I mean, we will build with 3.5, 4.0, and 5.0 or we only want to build and test with 5.0

We definitely need to keep the current versions - most of those are long term supported versions, so we'll have users using those. .NET 5 will be very similar to .NET Core, you can think of it as a new ".NET Core version" - hopefully we'll just be able to add it [here](https://github.com/elastic/apm-agent-dotnet/blob/master/.ci/windows/tools.ps1#L11)

> It would need a new worker with the new version of Visual Studio 2019 (v16.8, Preview 3), which I see is not a final version is a preview version.

I don't think we need Visual Studio for this - there is a .NET CLI tool also in .NET5 (same as on .NET Core) which can run the tests from command line and I'd try using that first because that does not need Visual Studio. [Here](https://github.com/elastic/apm-agent-dotnet/blob/master/.ci/windows/test.bat#L5) is how we run tests on .NET Core. Our test projects are [multi targeted](https://github.com/elastic/apm-agent-dotnet/blob/master/test/Elastic.Apm.Tests/Elastic.Apm.Tests.csproj#L4), my plan is to just add the .NET5 target to it, we install .NET 5 SDK with the CLI and then the `dotnet test` command will just pick it up 🤞 .

**Comment by gregkalapos** [comment]
Oh and btw. yes, this is all in preview right now, but there is a release candidate already out and I expect no major change (MS usually keeps this promise) between rc and the final version. In order to make sure we are ready for .NET 5 release, I'd test with rc now, and once the final is out, hopefully we can just update the scripts that pull the .NET 5 sdk to get the final version instead of rc.

**Comment by v1v** [comment]
For the record, dotnet-sdk versions are installed on the fly with [tools.ps1](https://github.com/elastic/apm-agent-dotnet/blob/master/.ci/windows/tools.ps1). There is no chocolatey package for `dotnet-sdk` version `5`.

As @gregkalapos  mentioned,  [install scripts](https://dotnet.microsoft.com/download/dotnet-core/scripts) might be the one to be used (see [docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script))
