### ISSUE TITLE
Support numeric labels

### ISSUE THREAD

**Issue by devree-bvb** [elastic/apm-agent-dotnet#967]
**Is your feature request related to a problem? Please describe.**
While monitoring our application, we capture information regarding our sql statements, including the numbers of rows affected. Currently we add the number of rows as a label to the span measuring the statement. This data however is sent to the backend as a string, which prevents us from aggregating this data in a numeric way (average, ....)

**Describe the solution you'd like**
Support the feature of numeric labels (https://www.elastic.co/guide/en/apm/get-started/7.2/metadata.html)

**Describe alternatives you've considered**

**Additional context**

**Comment by TomDeVree** [comment]
For this enhancement, would an implemenation like the Java implementation be a possibility? There they have 3 methods to add 3 different kinds of labels, string, numeric and boolean (https://github.com/elastic/apm-agent-java/blob/master/apm-agent-api/src/main/java/co/elastic/apm/api/SpanImpl.java) In C# now there is a dictionary for the labels, so the type is fixed to string.

This of course would be a breaking change in the API, so I would like some feedback before trying a PR

**Comment by gregkalapos** [comment]
> This of course would be a breaking change in the API, so I would like some feedback before trying a PR

I'd try not to break it if possible.

Without looking into this too much: how about keeping the dictionary as it is and then additionally add the `AddLabel` method with different types? The way the dictionary is used can be changed, but let's try to not break the current API surface. That way you don't break current users, but you can add the overloads for new users. Then long term, probably best would be to just deprecate the dictionary.

**Comment by TomDeVree** [comment]
Ok, Thanks for the feedback.

I will keep the existing API.
Problem there is that, because all labels come together in this dictionary that contain string values, and that can be modified, I don't know if the user intended to add a number in string format, or in a number format (for example). The difference is important for serialization to the backend.

I will try to find a solution for this

**Comment by gregkalapos** [comment]
Implemented in #982.
