### ISSUE TITLE
Replace Thread in PayloadSender with LongRunning Task

### ISSUE THREAD

**Issue by kanadaj** [elastic/apm-agent-dotnet#98]
Generally speaking, .NET Tasks set to `LongRunning` have a far superior error handling system and still run on their own dedicated thread, so the core loop inside `PayloadSender`. Threads scheduled on their own can still completely crash the containing application when using async void.

So the recommendation would be to use a Task for this, as outlined in this StackOverflow thread: https://stackoverflow.com/questions/26921191/how-to-pass-longrunning-flag-specifically-to-task-run/26931368#26931368

**Comment by gregkalapos** [comment]
Hi,

Thanks for reporting this. 

I think the problem with that code isn’t its error handling. The main problem is that the dedicated thread just starts the loop, but then the HTTP POSTs to the server can start and end on whatever thread… and that’s not really good, at least it’s not my original intention. But by thinking about this I’m not even sure that we need a dedicated thread for this.

But I got your point.

Just to give you more context: currently this agent uses the intake v1 protocol to send data to the APM server, which will be deprecated in a future version on the server (other agents already use the intake v2 protocol), so the agent-server communication and the `PayloadSender` is a temporary implementation to get things going. 

Very soon we’ll start implementing #13 and that’ll be a point where we will think very hard about how to do this - specifically: should we have a dedicated thread to send data or not, how to batch things, how to reuse tcp connections, etc.

I’ll leave this open until that work is done. If you have more specific ideas feel free to comment here - or send a PR :) 

Thanks again!

**Comment by kanadaj** [comment]
One thing you could consider doing is using .NET Core's `BackgroundService` which is already set up for long-running background tasks, and should be fairly simple to use even in a non-ASP.NET Core context with `StartAsync()` and `StopAsync()`.

Using a Task should also force `PostAsync()` to use the current loop thread as long as you use `await`.

As far as TCP connection use goes, you can just use Dependency Injection for the `HttpClient` and get a `HttpClient` assigned by the `IHttpClientFactory` of ASP.NET Core for the given name, which would avoid wasting connections.

I'd definitely stick to a dedicated thread (via `Task`) at least for ASP.NET Core since you really don't want to bottleneck a website with the APM pipeline :)

And because I like to live dangerously, I must report that v0.1 actually does work in a fairly busy production env (some 3-4k RPM), surprisingly enough, given that batch size is currently set to 1, so not very efficient. :)

**Comment by gregkalapos** [comment]
Addressed in https://github.com/elastic/apm-agent-dotnet/pull/136
